'use client'

import Link from 'next/link'
import { useAuth, useClerk } from '@clerk/nextjs'

function LogoMark() {
  return (
    <svg width="28" height="28" viewBox="0 0 32 32" fill="none" aria-hidden>
      <polygon points="16,2 30,10 30,22 16,30 2,22 2,10" stroke="#D4AF37" strokeWidth="1.5" fill="rgba(212,175,55,0.06)" />
      <polygon points="16,8 24,13 24,19 16,24 8,19 8,13" fill="#D4AF37" opacity="0.5" />
      <circle cx="16" cy="16" r="3" fill="#D4AF37" />
    </svg>
  )
}

function SignOutButton() {
  const { isSignedIn, isLoaded } = useAuth()
  const { signOut } = useClerk()

  if (!isLoaded || !isSignedIn) return null

  return (
    <button
      onClick={() => signOut({ redirectUrl: '/sign-in' })}
      className="relative z-10 mt-4 text-xs text-zinc-500 hover:text-[#D4AF37] transition-colors"
    >
      Signed in with wrong account? Sign out
    </button>
  )
}

export default function AuthLayoutClient({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex" style={{ background: '#050810' }}>
      {/* Left side — branding panel (hidden on mobile) */}
      <div className="hidden lg:flex lg:w-[45%] relative flex-col items-center justify-center px-12 overflow-hidden">
        {/* Background effects */}
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background: 'linear-gradient(135deg, rgba(212,175,55,0.06) 0%, rgba(212,175,55,0.02) 40%, transparent 70%)',
          }}
        />
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background: 'radial-gradient(circle at 30% 50%, rgba(212,175,55,0.08) 0%, transparent 50%)',
          }}
        />
        {/* Subtle grid */}
        <div
          className="absolute inset-0 pointer-events-none opacity-[0.03]"
          style={{
            backgroundImage: 'linear-gradient(#D4AF37 1px, transparent 1px), linear-gradient(90deg, #D4AF37 1px, transparent 1px)',
            backgroundSize: '60px 60px',
          }}
        />

        <div className="relative z-10 max-w-md">
          <Link href="/" className="flex items-center gap-3 select-none group mb-8">
            <LogoMark />
            <span className="text-3xl font-bold tracking-tight transition-opacity duration-150 group-hover:opacity-80">
              <span className="text-white">Forje</span>
              <span style={{ color: '#D4AF37' }}>Games</span>
            </span>
          </Link>

          <h2 className="text-4xl font-bold text-white leading-tight mb-4">
            The only cursor you
            <br />
            ever need for{' '}
            <span style={{ color: '#D4AF37' }}>Roblox</span>
          </h2>

          <p className="text-lg text-zinc-400 leading-relaxed mb-10">
            Build complete games from a single prompt. Terrain, scripts, 3D assets, UI — all generated by AI and synced live to Studio.
          </p>

          <div className="space-y-4">
            {[
              '9 AI agents working together on every build',
              '3D mesh generation from text',
              '13 image styles for any art direction',
              'Live sync to Roblox Studio',
            ].map((feature) => (
              <div key={feature} className="flex items-center gap-3">
                <div className="w-5 h-5 rounded-full bg-[#D4AF37]/15 border border-[#D4AF37]/30 flex items-center justify-center flex-shrink-0">
                  <div className="w-1.5 h-1.5 rounded-full bg-[#D4AF37]" />
                </div>
                <span className="text-sm text-zinc-300">{feature}</span>
              </div>
            ))}
          </div>

          <div className="mt-12 pt-8 border-t border-white/[0.06]">
            <p className="text-sm text-zinc-500 italic">
              &ldquo;Finally, an AI that builds the WHOLE game, not just scripts&rdquo;
            </p>
            <p className="text-xs text-zinc-600 mt-2">— RK, Roblox creator</p>
          </div>
        </div>
      </div>

      {/* Right side — auth form */}
      <div className="flex-1 flex flex-col items-center justify-center px-6 sm:px-10 py-12 relative">
        {/* Ambient glow */}
        <div
          className="pointer-events-none absolute inset-0"
          aria-hidden
          style={{ background: 'radial-gradient(ellipse 600px 500px at 50% 40%, rgba(212,175,55,0.04) 0%, transparent 70%)' }}
        />

        {/* Mobile logo (hidden on desktop since left panel has it) */}
        <div className="lg:hidden relative z-10 mb-10 flex flex-col items-center">
          <Link href="/" className="flex items-center gap-3 select-none group">
            <LogoMark />
            <span className="text-2xl font-bold tracking-tight transition-opacity duration-150 group-hover:opacity-80">
              <span className="text-white">Forje</span>
              <span style={{ color: '#D4AF37' }}>Games</span>
            </span>
          </Link>
          <p className="mt-3 text-base text-zinc-500 text-center">
            The only cursor you ever need for Roblox
          </p>
        </div>

        {/* Auth card */}
        <div
          className="relative z-10 w-full rounded-2xl p-8 sm:p-10"
          style={{
            maxWidth: '28rem',
            background: 'rgba(255,255,255,0.025)',
            backdropFilter: 'blur(24px)',
            WebkitBackdropFilter: 'blur(24px)',
            border: '1px solid rgba(255,255,255,0.07)',
            boxShadow: '0 12px 48px rgba(0,0,0,0.5), 0 0 80px rgba(212,175,55,0.03)',
          }}
        >
          {children}
        </div>

        <SignOutButton />

        <p className="relative z-10 mt-6 text-xs text-zinc-600">
          By continuing you agree to our{' '}
          <Link href="/terms" className="text-zinc-500 hover:text-zinc-400 transition-colors underline underline-offset-2">Terms</Link>
          {' & '}
          <Link href="/privacy" className="text-zinc-500 hover:text-zinc-400 transition-colors underline underline-offset-2">Privacy</Link>
        </p>
      </div>
    </div>
  )
}
