import { AchievementCategory } from '@prisma/client'

export interface AchievementDef {
  slug: string
  name: string
  description: string
  icon: string
  category: AchievementCategory
  xpReward: number
  condition: Record<string, unknown>
}

export const ACHIEVEMENTS: AchievementDef[] = [
  // FIRST_STEPS (6)
  {
    slug: 'first-build',
    name: 'First Creation',
    description: 'Complete your first build',
    icon: '🏗️',
    category: AchievementCategory.FIRST_STEPS,
    xpReward: 50,
    condition: { type: 'BUILD_COUNT', threshold: 1 },
  },
  {
    slug: 'first-publish',
    name: 'Published!',
    description: 'Publish your first template to the marketplace',
    icon: '🚀',
    category: AchievementCategory.FIRST_STEPS,
    xpReward: 100,
    condition: { type: 'PUBLISH_COUNT', threshold: 1 },
  },
  {
    slug: 'profile-complete',
    name: 'Identity',
    description: 'Complete your profile with username, display name, and avatar',
    icon: '🪪',
    category: AchievementCategory.FIRST_STEPS,
    xpReward: 25,
    condition: { type: 'PROFILE_COMPLETE' },
  },
  {
    slug: 'first-purchase',
    name: 'Shopper',
    description: 'Purchase your first marketplace template',
    icon: '🛒',
    category: AchievementCategory.FIRST_STEPS,
    xpReward: 25,
    condition: { type: 'PURCHASE_COUNT', threshold: 1 },
  },
  {
    slug: 'first-review',
    name: 'Critic',
    description: 'Leave your first review',
    icon: '⭐',
    category: AchievementCategory.FIRST_STEPS,
    xpReward: 25,
    condition: { type: 'REVIEW_COUNT', threshold: 1 },
  },
  {
    slug: 'first-sale',
    name: 'First Dollar',
    description: 'Make your first marketplace sale',
    icon: '💰',
    category: AchievementCategory.FIRST_STEPS,
    xpReward: 150,
    condition: { type: 'SALE_COUNT', threshold: 1 },
  },

  // VELOCITY (5)
  {
    slug: 'build-10',
    name: 'Prolific',
    description: 'Complete 10 builds',
    icon: '⚡',
    category: AchievementCategory.VELOCITY,
    xpReward: 100,
    condition: { type: 'BUILD_COUNT', threshold: 10 },
  },
  {
    slug: 'build-50',
    name: 'Build Machine',
    description: 'Complete 50 builds',
    icon: '🔥',
    category: AchievementCategory.VELOCITY,
    xpReward: 300,
    condition: { type: 'BUILD_COUNT', threshold: 50 },
  },
  {
    slug: 'build-100',
    name: 'Century',
    description: 'Complete 100 builds',
    icon: '💯',
    category: AchievementCategory.VELOCITY,
    xpReward: 500,
    condition: { type: 'BUILD_COUNT', threshold: 100 },
  },
  {
    slug: 'speed-builder',
    name: 'Speed Builder',
    description: 'Complete 5 builds in a single day',
    icon: '🏎️',
    category: AchievementCategory.VELOCITY,
    xpReward: 150,
    condition: { type: 'BUILDS_IN_DAY', threshold: 5 },
  },
  {
    slug: 'weekend-warrior',
    name: 'Weekend Warrior',
    description: 'Complete builds on both Saturday and Sunday in the same weekend',
    icon: '🗓️',
    category: AchievementCategory.VELOCITY,
    xpReward: 75,
    condition: { type: 'WEEKEND_BUILDS' },
  },

  // MARKETPLACE (6)
  {
    slug: 'publish-5',
    name: 'Template Pack',
    description: 'Publish 5 templates',
    icon: '📦',
    category: AchievementCategory.MARKETPLACE,
    xpReward: 200,
    condition: { type: 'PUBLISH_COUNT', threshold: 5 },
  },
  {
    slug: 'sales-10',
    name: 'Merchant',
    description: 'Make 10 sales',
    icon: '🏪',
    category: AchievementCategory.MARKETPLACE,
    xpReward: 300,
    condition: { type: 'SALE_COUNT', threshold: 10 },
  },
  {
    slug: 'sales-100',
    name: 'Top Seller',
    description: 'Make 100 sales',
    icon: '🏆',
    category: AchievementCategory.MARKETPLACE,
    xpReward: 1000,
    condition: { type: 'SALE_COUNT', threshold: 100 },
  },
  {
    slug: 'five-star',
    name: 'Five Star',
    description: 'Receive a 5-star review on your template',
    icon: '🌟',
    category: AchievementCategory.MARKETPLACE,
    xpReward: 75,
    condition: { type: 'RECEIVE_FIVE_STAR' },
  },
  {
    slug: 'perfect-rating',
    name: 'Perfect Rating',
    description: 'Maintain a 5-star average with 10+ reviews',
    icon: '✨',
    category: AchievementCategory.MARKETPLACE,
    xpReward: 500,
    condition: { type: 'PERFECT_RATING', minReviews: 10 },
  },
  {
    slug: 'hundred-dollars',
    name: 'Three Figures',
    description: 'Earn $100 from marketplace sales',
    icon: '💵',
    category: AchievementCategory.MARKETPLACE,
    xpReward: 400,
    condition: { type: 'TOTAL_EARNED_CENTS', threshold: 10000 },
  },

  // COMMUNITY (5)
  {
    slug: 'referral-1',
    name: 'Recruiter',
    description: 'Refer your first user',
    icon: '🤝',
    category: AchievementCategory.COMMUNITY,
    xpReward: 200,
    condition: { type: 'REFERRAL_COUNT', threshold: 1 },
  },
  {
    slug: 'referral-10',
    name: 'Evangelist',
    description: 'Refer 10 users',
    icon: '📣',
    category: AchievementCategory.COMMUNITY,
    xpReward: 500,
    condition: { type: 'REFERRAL_COUNT', threshold: 10 },
  },
  {
    slug: 'helpful-reviewer',
    name: 'Helpful Reviewer',
    description: 'Leave 10 reviews',
    icon: '💬',
    category: AchievementCategory.COMMUNITY,
    xpReward: 150,
    condition: { type: 'REVIEW_COUNT', threshold: 10 },
  },
  {
    slug: 'purchase-10',
    name: 'Collector',
    description: 'Purchase 10 templates',
    icon: '🗃️',
    category: AchievementCategory.COMMUNITY,
    xpReward: 100,
    condition: { type: 'PURCHASE_COUNT', threshold: 10 },
  },
  {
    slug: 'creator-connect',
    name: 'Creator Connect',
    description: 'Connect your Stripe account for payouts',
    icon: '💳',
    category: AchievementCategory.COMMUNITY,
    xpReward: 50,
    condition: { type: 'STRIPE_CONNECTED' },
  },

  // QUALITY (4)
  {
    slug: 'xp-500',
    name: 'Apprentice',
    description: 'Reach Apprentice tier (500 XP)',
    icon: '🎓',
    category: AchievementCategory.QUALITY,
    xpReward: 0,
    condition: { type: 'XP_THRESHOLD', threshold: 500 },
  },
  {
    slug: 'xp-2000',
    name: 'Builder Tier',
    description: 'Reach Builder tier (2,000 XP)',
    icon: '🔨',
    category: AchievementCategory.QUALITY,
    xpReward: 0,
    condition: { type: 'XP_THRESHOLD', threshold: 2000 },
  },
  {
    slug: 'xp-5000',
    name: 'Master Tier',
    description: 'Reach Master tier (5,000 XP)',
    icon: '🎖️',
    category: AchievementCategory.QUALITY,
    xpReward: 0,
    condition: { type: 'XP_THRESHOLD', threshold: 5000 },
  },
  {
    slug: 'xp-15000',
    name: 'Legend Tier',
    description: 'Reach Legend tier (15,000 XP)',
    icon: '🏅',
    category: AchievementCategory.QUALITY,
    xpReward: 0,
    condition: { type: 'XP_THRESHOLD', threshold: 15000 },
  },

  // EXPLORATION (4)
  {
    slug: 'streak-7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day login streak',
    icon: '🔥',
    category: AchievementCategory.EXPLORATION,
    xpReward: 100,
    condition: { type: 'LOGIN_STREAK', threshold: 7 },
  },
  {
    slug: 'streak-30',
    name: 'Monthly Legend',
    description: 'Maintain a 30-day login streak',
    icon: '🗓️',
    category: AchievementCategory.EXPLORATION,
    xpReward: 300,
    condition: { type: 'LOGIN_STREAK', threshold: 30 },
  },
  {
    slug: 'streak-100',
    name: 'Centurion',
    description: 'Maintain a 100-day login streak',
    icon: '💎',
    category: AchievementCategory.EXPLORATION,
    xpReward: 1000,
    condition: { type: 'LOGIN_STREAK', threshold: 100 },
  },
  {
    slug: 'all-categories',
    name: 'Explorer',
    description: 'Publish a template in all 6 categories',
    icon: '🗺️',
    category: AchievementCategory.EXPLORATION,
    xpReward: 500,
    condition: { type: 'ALL_CATEGORIES' },
  },
]
