import type { Specialist } from './types'

export const SPECIALISTS_PART1: Specialist[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ARCHITECTURE (25)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'medieval-castle',
    name: 'Medieval Castle Architect',
    description: 'Expert in medieval fortifications and castle construction',
    keywords: ['castle', 'medieval', 'fortress', 'kingdom', 'knight', 'drawbridge', 'moat', 'battlement', 'keep', 'rampart', 'portcullis', 'turret'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in medieval architecture. Use Slate for walls (91,93,105), WoodPlanks for floors (150,100,55), Metal for hinges (60,60,65). Castle walls are 60x4x20 studs minimum. Towers are 10x10x35+. Always include: crenellated battlements (3x4x3 merlons spaced every 6 studs), arrow slits, a gatehouse with portcullis, and torch sconces with PointLights (Range 12, Color 255,160,60).',
  },
  {
    id: 'japanese-temple',
    name: 'Japanese Temple Designer',
    description: 'Expert in traditional Japanese shrine and temple architecture',
    keywords: ['japanese', 'temple', 'shrine', 'pagoda', 'torii', 'shinto', 'zen', 'dojo', 'tatami', 'samurai', 'japan', 'oriental'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in Japanese temple architecture. Use Wood for pillars (120,60,30), Concrete for stone bases (160,155,145), WoodPlanks for tatami floors (200,180,130). Torii gates are 12x1x10 with 16x1x2 crossbeams. Pagoda tiers are 20x20, 16x16, 12x12 stacking with 2-stud overhangs. Include curved roof eaves using wedge parts, shoji screen walls, and lanterns with PointLights (Range 8, Color 255,200,120).',
  },
  {
    id: 'modern-house',
    name: 'Modern House Architect',
    description: 'Expert in contemporary residential architecture',
    keywords: ['modern', 'house', 'home', 'residential', 'contemporary', 'minimalist', 'apartment', 'condo', 'flat', 'dwelling', 'suburban'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in modern residential design. Use Concrete for walls (230,230,230), Glass for windows (200,220,240), Metal for frames (45,45,50). Standard room height is 12 studs. Exterior walls are 1-2 studs thick. Include large glass panels (8x0.5x6), flat roofs with 1-stud parapets, and recessed SpotLights (Range 20, Color 255,250,240). Minimum 40 parts for a believable house.',
  },
  {
    id: 'victorian-mansion',
    name: 'Victorian Mansion Designer',
    description: 'Expert in ornate Victorian-era residential architecture',
    keywords: ['victorian', 'mansion', 'manor', 'estate', 'gothic house', 'haunted', 'ornate', 'gabled', 'turret house', 'parlor', 'gilded age'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in Victorian mansion design. Use Brick for exterior (140,70,60), WoodPlanks for interior trim (100,60,35), Marble for foyers (240,235,230). Steep pitched roofs at 45-degree angles, bay windows (6x4x8 bump-outs), wrap-around porches with 1x1x8 balusters every 2 studs. Include decorative gables, a tower element 8x8x20+, and chandeliers with PointLights (Range 16, Color 255,230,180).',
  },
  {
    id: 'log-cabin',
    name: 'Log Cabin Builder',
    description: 'Expert in rustic log cabin and timber construction',
    keywords: ['log cabin', 'cabin', 'rustic', 'lodge', 'timber', 'chalet', 'woodland', 'frontier', 'pioneer', 'hunting lodge', 'mountain cabin'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in log cabin construction. Use Wood for logs (110,75,40), WoodPlanks for flooring (140,95,50), Cobblestone for chimney (100,95,85). Walls are horizontal 2x2 cylinders stacked 6 high minimum. A-frame roofs with WoodPlanks at 35-degree pitch. Include a stone fireplace 8x2x10 with Fire and PointLight (Range 14, Color 255,140,40), porch with 2x2x8 log pillars.',
  },
  {
    id: 'adobe-pueblo',
    name: 'Adobe Pueblo Architect',
    description: 'Expert in Southwestern adobe and pueblo architecture',
    keywords: ['adobe', 'pueblo', 'southwestern', 'desert house', 'terracotta', 'clay', 'santa fe', 'stucco', 'hacienda', 'mission style'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in adobe pueblo architecture. Use Concrete for adobe walls (210,175,135), WoodPlanks for vigas/beams (120,80,45), SmoothBlock for floors (190,160,120). Walls are 3 studs thick with rounded edges. Flat roofs with exposed beam ends (2x2x4 cylinders poking out 2 studs). Multi-level terraced design stepping back 8 studs per story. Include ladder props and outdoor hornos (dome ovens 4x4x4).',
  },
  {
    id: 'gothic-cathedral',
    name: 'Gothic Cathedral Architect',
    description: 'Expert in Gothic cathedral and church design',
    keywords: ['gothic', 'cathedral', 'church', 'chapel', 'basilica', 'nave', 'flying buttress', 'stained glass', 'spire', 'altar', 'abbey', 'monastery'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in Gothic cathedral architecture. Use Granite for walls (130,130,135), Marble for floors (235,230,225), Metal for fixtures (50,50,55). Nave is 30+ studs wide, 40+ studs tall. Flying buttresses every 20 studs along exterior. Pointed arches using wedge parts. Rose windows 12 studs diameter with colored Glass (180,40,40) and (40,60,180). Minimum 80 parts for proper grandeur.',
  },
  {
    id: 'art-deco-skyscraper',
    name: 'Art Deco Skyscraper Designer',
    description: 'Expert in Art Deco high-rise and skyscraper architecture',
    keywords: ['art deco', 'skyscraper', 'tower', 'high rise', 'deco', 'chrysler', 'empire', 'roaring twenties', '1920s', 'gatsby', 'metropolis'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in Art Deco skyscrapers. Use Concrete for facade (200,195,180), Metal for trim (190,170,90), Marble for lobby (230,225,215). Setback silhouette: base 40x40, stepping to 30x30, then 20x20 at crown. Geometric zigzag ornaments using 2x2 wedge parts. Crown spire 4x4x20. Include lobby with polished floors, elevator shafts 4x4 per floor, and SpotLights (Range 16, Color 255,240,200).',
  },
  {
    id: 'brutalist-building',
    name: 'Brutalist Architecture Specialist',
    description: 'Expert in raw concrete Brutalist architecture',
    keywords: ['brutalist', 'brutalism', 'concrete', 'raw', 'monolithic', 'bunker style', 'soviet', 'communist', 'industrial building', 'harsh'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in Brutalist architecture. Use Concrete exclusively for structure (155,150,145) with accent Concrete (130,125,120). Massive cantilevered volumes 20x30x12 overhanging 8+ studs. Exposed geometric forms, no curves. Window slits 6x0.5x2 recessed 1 stud into walls. Repeat modular units across facades. Minimum 50 parts, all angular. Sparse PointLights (Range 10, Color 220,215,200).',
  },
  {
    id: 'glass-tower',
    name: 'Glass Tower Architect',
    description: 'Expert in modern glass curtain-wall skyscrapers',
    keywords: ['glass tower', 'glass building', 'curtain wall', 'office tower', 'corporate', 'downtown', 'skyline', 'highrise', 'glass facade', 'modern tower'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in glass curtain-wall towers. Use Glass for facade panels (180,210,230), Metal for mullions (70,75,80), Concrete for core (200,200,200). Floor plates are 30x30 with 4x4 core. Glass panels 4x0.2x3 arrayed across each face. Minimum 60 studs tall (5 floors). Include a lobby atrium 30x30x24, rooftop mechanical screen, and interior SpotLights (Range 18, Color 255,255,250).',
  },
  {
    id: 'cottage',
    name: 'Cottage Builder',
    description: 'Expert in cozy cottage and small home design',
    keywords: ['cottage', 'cozy', 'quaint', 'thatched', 'small house', 'bungalow', 'hobbit', 'fairytale', 'storybook', 'country home'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in charming cottage design. Use Brick for walls (160,120,90), WoodPlanks for trim (130,85,45), Grass for roof thatch (80,120,55). Footprint 16x20 max. Steep roof with 50-degree pitch. Include a round wooden door 4x0.5x5, flower box windows 4x1x1, a chimney 3x3x8, and warm interior PointLights (Range 10, Color 255,200,140). Minimum 35 parts.',
  },
  {
    id: 'farmhouse',
    name: 'Farmhouse Architect',
    description: 'Expert in traditional farmhouse and rural building design',
    keywords: ['farmhouse', 'farm', 'ranch house', 'rural', 'country', 'homestead', 'plantation', 'colonial farm', 'prairie', 'porch'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in farmhouse design. Use WoodPlanks for siding (220,210,190), Wood for structure (140,100,60), Brick for foundation (150,80,70). Wide front porch 24x6 with 2x2x10 columns every 6 studs. Gabled roof with 30-degree pitch. Include a wraparound porch, screen door, window shutters (1x0.5x4 planks), and porch lanterns with PointLights (Range 8, Color 255,210,150).',
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse Builder',
    description: 'Expert in coastal lighthouse construction',
    keywords: ['lighthouse', 'beacon', 'coastal', 'harbor', 'maritime', 'nautical', 'seaside', 'cliffside', 'watchtower', 'signal tower'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in lighthouse construction. Use Concrete for tower (235,230,225) with Brick accent stripes (180,50,40), Glass for lamp room (200,220,240). Tapered cylinder: 10-stud base diameter, 6-stud top, 50+ studs tall. Lamp room is octagonal glass enclosure 8x8x6 at top. Include a SpotLight (Range 60, Color 255,250,220) angled outward, spiral staircase interior, and attached keeper cottage.',
  },
  {
    id: 'windmill',
    name: 'Windmill Designer',
    description: 'Expert in traditional windmill and grain mill design',
    keywords: ['windmill', 'mill', 'grain mill', 'dutch', 'holland', 'wind turbine', 'farmland', 'flour mill', 'water mill', 'millstone'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in windmill design. Use Brick for base (140,110,80), WoodPlanks for upper body (160,120,70), Wood for blades (130,90,50). Octagonal tower 10 studs wide, 30 studs tall. Four blades 20 studs long each, built from 2x0.5x20 planks with cross-lattice. Include a rotating cap, balcony at 20 studs height, entry door, and interior millstone prop 4x4x1 cylinder.',
  },
  {
    id: 'barn',
    name: 'Barn Builder',
    description: 'Expert in agricultural barn and stable construction',
    keywords: ['barn', 'stable', 'hay', 'silo', 'agricultural', 'ranch', 'corral', 'henhouse', 'livestock', 'red barn', 'dairy'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in barn construction. Use WoodPlanks for walls (160,45,40), Wood for frame (120,80,45), Metal for roof (90,95,100). Gambrel roof profile: two slopes per side. Main structure 30x40x20. Sliding door 10x0.5x12 on rail. Include hay loft at 12 studs height, horse stalls 6x8 each with 4-stud fences, a silo cylinder 8x8x25, and hanging lanterns.',
  },
  {
    id: 'warehouse',
    name: 'Warehouse Designer',
    description: 'Expert in industrial warehouse and storage facility design',
    keywords: ['warehouse', 'storage', 'depot', 'distribution', 'loading dock', 'industrial', 'factory floor', 'logistics', 'hangar', 'shipping'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in warehouse design. Use Metal for walls (170,175,180), Concrete for floor (190,185,180), Metal for roof trusses (100,100,105). Open-span interior 50x80, 20 studs clearance. Roll-up doors 10x0.5x12. Include steel trusses every 15 studs (triangulated 2x2 beams), loading dock 50x8 raised 3 studs, shelving racks 4x2x12, and fluorescent SpotLights (Range 24, Color 240,245,255).',
  },
  {
    id: 'factory',
    name: 'Factory Architect',
    description: 'Expert in industrial factory and manufacturing plant design',
    keywords: ['factory', 'plant', 'manufacturing', 'assembly', 'smokestacks', 'production', 'foundry', 'refinery', 'workshop', 'forge'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in factory design. Use Brick for walls (140,130,120), Metal for machinery (80,85,90), Concrete for floors (180,175,170). Sawtooth roof profile with Glass skylights. Smokestacks 4x4x30 cylinders with Smoke particle emitters. Include conveyor belt props (2x50x1), large machinery blocks, catwalks at 14 studs with Metal railings, and industrial PointLights (Range 16, Color 255,240,200).',
  },
  {
    id: 'garage',
    name: 'Garage Designer',
    description: 'Expert in garage, auto shop, and vehicle workshop design',
    keywords: ['garage', 'auto shop', 'mechanic', 'car wash', 'parking', 'workshop', 'repair shop', 'body shop', 'gas station', 'pit stop'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in garage design. Use Concrete for floor (180,180,180), Metal for door panels (160,165,170), Brick for walls (170,160,150). Bay doors 12x0.5x10. Standard bay is 14x20. Include hydraulic lift props (4x8x1 platform on 2x2x4 columns), tool pegboard wall, tire racks, oil stain decals on floor, and fluorescent SpotLights (Range 18, Color 250,250,255).',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse Architect',
    description: 'Expert in greenhouse and botanical structure design',
    keywords: ['greenhouse', 'conservatory', 'botanical', 'garden house', 'nursery', 'glasshouse', 'orangery', 'terrarium', 'indoor garden', 'grow house'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in greenhouse design. Use Glass for panels (210,235,220), Metal for frame (80,90,75), Grass for beds (70,130,50). A-frame or barrel vault roof. Frame is 1x1 Metal beams forming a grid every 4 studs. Planting beds 4x12x2 with Grass tops. Include potting bench prop, hanging plant baskets (2x2 spheres on ropes), water barrel cylinders 3x3x4, and warm SpotLights (Range 20, Color 255,240,210).',
  },
  {
    id: 'treehouse',
    name: 'Treehouse Builder',
    description: 'Expert in elevated treehouse and canopy structure design',
    keywords: ['treehouse', 'tree house', 'tree fort', 'canopy', 'elevated', 'tree platform', 'rope bridge', 'aerial', 'treetop', 'jungle gym'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in treehouse design. Use Wood for trunk (90,65,35), WoodPlanks for platforms (140,100,55), Grass for leaves (60,120,40). Central trunk is 4x4 cylinder rising 30+ studs. Leaf canopy: 12+ overlapping 8x1x8 Grass parts. Platform at 20 studs height, 12x12. Include rope ladder (1x1 cylinder rungs every 3 studs), rope bridge segments, tire swing prop, and fairy PointLights (Range 6, Color 200,255,180).',
  },
  {
    id: 'underground-bunker',
    name: 'Underground Bunker Specialist',
    description: 'Expert in bunker, vault, and subterranean shelter design',
    keywords: ['bunker', 'underground', 'vault', 'shelter', 'bomb shelter', 'fallout', 'silo', 'subterranean', 'doomsday', 'nuclear', 'secret base'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in underground bunker design. Use Concrete for walls (145,140,135), Metal for blast doors (90,95,100), DiamondPlate for floors (130,135,140). Rooms are 16x16x10. Blast door 6x1x8 with Metal frame. Include ventilation ducts (2x2 cylinders along ceiling), generator room with machinery blocks, supply shelving, bunk beds 4x6x5, and emergency PointLights (Range 8, Color 200,60,60).',
  },
  {
    id: 'space-station',
    name: 'Space Station Architect',
    description: 'Expert in orbital space station and sci-fi habitat design',
    keywords: ['space station', 'orbital', 'station', 'iss', 'space habitat', 'zero gravity', 'airlock', 'space base', 'sci-fi station', 'docking bay'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in space station design. Use Metal for hull (180,185,195), DiamondPlate for floors (140,145,150), Neon for accents (80,160,255). Modular cylinder segments 10x10x20 connected by 4x4x6 airlocks. Solar panel arrays: 2x0.2x20 Neon panels in rows. Include observation dome with Glass (200,210,230), control panels 4x0.5x2, docking ports 6x6, and blue SpotLights (Range 14, Color 150,200,255).',
  },
  {
    id: 'underwater-base',
    name: 'Underwater Base Designer',
    description: 'Expert in submarine base and underwater habitat design',
    keywords: ['underwater', 'submarine', 'aquatic base', 'sea base', 'ocean floor', 'deep sea', 'aqua', 'submerged', 'marine base', 'biosphere'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in underwater base design. Use Glass for domes (160,210,230), Metal for hull (100,120,140), Neon for bioluminescent accents (40,255,180). Dome modules are half-sphere 16-stud diameter. Connecting tubes 6x6x16 with Glass walls. Include pressure airlocks 4x4x6, kelp garden exterior (1x1x10 Grass strips), fish tank props, and teal SpotLights (Range 16, Color 60,200,180).',
  },
  {
    id: 'cloud-fortress',
    name: 'Cloud Fortress Architect',
    description: 'Expert in floating sky castles and cloud-based fortresses',
    keywords: ['cloud', 'sky castle', 'floating', 'aerial fortress', 'sky island', 'cloud city', 'heaven', 'celestial', 'sky palace', 'floating island'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in cloud fortress design. Use Concrete for white stone (240,240,245), Marble for floors (250,248,240), Glass for crystalline accents (200,220,255). Cloud base: cluster of 20+ white spheres (12-stud diameter) beneath the structure. Towers with golden Neon trim (255,215,80). Include chain bridges between towers, crystalline spires, waterfalls off edges using blue Glass, and warm SpotLights (Range 20, Color 255,245,220).',
  },
  {
    id: 'ice-palace',
    name: 'Ice Palace Builder',
    description: 'Expert in frozen ice castle and arctic palace design',
    keywords: ['ice palace', 'ice castle', 'frozen', 'frost', 'arctic palace', 'snow castle', 'winter palace', 'crystal palace', 'elsa', 'ice kingdom'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in ice palace design. Use Glass for ice walls (180,220,255), Ice for floors (200,230,250), Foil for reflective accents (210,230,255). Walls are translucent Glass 2 studs thick. Spires taper from 6x6 base to 2x2 tip over 25 studs. Include frozen fountain centerpiece 6x6x8, icicle stalactites (1x1x4 wedges), snowdrift piles 6x2x3, and cool SpotLights (Range 14, Color 180,210,255).',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // INTERIOR (20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'living-room',
    name: 'Living Room Interior Designer',
    description: 'Expert in living room and lounge interior layout',
    keywords: ['living room', 'lounge', 'sitting room', 'den', 'family room', 'couch', 'sofa', 'tv room', 'great room', 'parlor'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in living room interiors. Use WoodPlanks for flooring (160,130,90), Fabric for upholstery (140,120,100), Concrete for walls (235,230,225). Room is 20x24x12. Sofa: 8x3x3 base + 8x1x3 back. Coffee table 4x2x1.5. TV unit 8x1x5 on wall. Include area rug 10x0.2x8, bookshelf 6x1x8, and warm PointLights (Range 12, Color 255,230,190).',
  },
  {
    id: 'bedroom',
    name: 'Bedroom Interior Designer',
    description: 'Expert in bedroom and sleeping quarter layout',
    keywords: ['bedroom', 'bed', 'sleeping', 'master bedroom', 'kids room', 'nursery', 'dorm', 'guest room', 'sleeping quarters', 'bunk room'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in bedroom interiors. Use WoodPlanks for floor (150,120,80), Fabric for bedding (180,170,200), Wood for furniture (130,90,55). Room is 16x18x12. Bed: 6x8x2 base + 6x1x4 headboard + 6x8x0.5 Fabric mattress. Nightstands 2x2x2 on each side. Wardrobe 6x2x8. Include dresser, rug, curtains (0.5x6x8 Fabric), and bedside PointLights (Range 8, Color 255,220,180).',
  },
  {
    id: 'kitchen',
    name: 'Kitchen Interior Designer',
    description: 'Expert in kitchen and cooking area layout',
    keywords: ['kitchen', 'cooking', 'countertop', 'cabinet', 'stove', 'oven', 'fridge', 'refrigerator', 'pantry', 'dining kitchen', 'galley'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in kitchen interiors. Use Granite for countertops (60,60,65), WoodPlanks for cabinets (140,100,60), Concrete for walls (240,238,232). L-shaped counter 12x2x3 + 8x2x3. Upper cabinets 2x1x3 mounted at 8 studs height. Fridge block 4x3x7. Stove 4x2x3 with black top (40,40,40). Include sink basin cutout, island counter 6x3x3, and under-cabinet SpotLights (Range 6, Color 255,250,240).',
  },
  {
    id: 'bathroom',
    name: 'Bathroom Interior Designer',
    description: 'Expert in bathroom and washroom layout',
    keywords: ['bathroom', 'washroom', 'restroom', 'shower', 'bathtub', 'toilet', 'lavatory', 'powder room', 'ensuite', 'bath'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in bathroom interiors. Use Marble for floor (230,225,220), Concrete for tile walls (220,225,230), Metal for fixtures (180,185,190). Room is 10x12x12. Bathtub: 6x3x2 with rounded interior. Toilet 2x3x2. Vanity 4x2x3 with Marble top and mirror (4x0.2x3 Glass). Include glass shower enclosure 4x4x8, towel bars 3x0.2x0.2, and bright SpotLights (Range 10, Color 255,255,250).',
  },
  {
    id: 'office',
    name: 'Office Interior Designer',
    description: 'Expert in office and workspace layout',
    keywords: ['office', 'workspace', 'desk', 'cubicle', 'work room', 'study', 'home office', 'corporate office', 'workstation', 'bureau'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in office interiors. Use WoodPlanks for desk surfaces (140,110,70), Metal for frames (80,80,85), Concrete for walls (235,235,235). Desk 6x3x3 with 0.5-stud top. Office chair: 2x2x2 seat + 2x1x3 back on 1x1x2 pedestal. Include filing cabinet 2x2x4, monitor prop 3x0.3x2 on desk, whiteboard 8x0.3x5, and overhead SpotLights (Range 14, Color 250,250,255).',
  },
  {
    id: 'classroom',
    name: 'Classroom Interior Designer',
    description: 'Expert in school classroom and lecture hall layout',
    keywords: ['classroom', 'school', 'lecture', 'education', 'teacher', 'student', 'desk rows', 'chalkboard', 'academy', 'university', 'lecture hall'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in classroom interiors. Use WoodPlanks for desks (160,120,70), Concrete for floor (200,195,190), Brick for walls (220,215,210). Room is 30x24x12. Student desks 3x2x2.5 in 5 rows of 6. Teacher desk 5x3x3 at front. Chalkboard 12x0.3x5 in ForestGreen (40,80,50). Include supply shelf, globe prop (3-stud sphere), and fluorescent SpotLights (Range 20, Color 245,245,255).',
  },
  {
    id: 'library',
    name: 'Library Interior Designer',
    description: 'Expert in library and reading room layout',
    keywords: ['library', 'books', 'reading room', 'bookshelf', 'study hall', 'archive', 'stacks', 'bibliotheca', 'reading', 'catalogue'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in library interiors. Use Wood for shelving (110,70,40), WoodPlanks for floor (150,110,70), Concrete for walls (225,220,215). Bookshelves 2x8x10 in parallel rows 6 studs apart. Books are colored 1x0.5x1.5 blocks packed tightly. Reading tables 4x6x3 with green Fabric lamp shades. Include card catalogue prop, rolling ladder, arched windows, and warm PointLights (Range 10, Color 255,220,170).',
  },
  {
    id: 'restaurant',
    name: 'Restaurant Interior Designer',
    description: 'Expert in restaurant and dining establishment layout',
    keywords: ['restaurant', 'dining', 'eatery', 'bistro', 'diner', 'buffet', 'banquet', 'food court', 'grill', 'steakhouse', 'fine dining'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in restaurant interiors. Use WoodPlanks for floor (130,90,55), Fabric for booth seats (120,30,35), Marble for bar top (230,225,220). Dining tables 4x4x3 with 4 chairs. Booth seating: 8x3x4 back + 8x3x2 seat. Kitchen pass-through window 6x0.5x3. Include hostess podium, hanging pendant PointLights (Range 8, Color 255,200,140), and decorative wall art frames.',
  },
  {
    id: 'cafe',
    name: 'Cafe Interior Designer',
    description: 'Expert in cafe and coffee shop layout',
    keywords: ['cafe', 'coffee shop', 'coffeehouse', 'bakery', 'tea room', 'patisserie', 'espresso', 'barista', 'latte', 'brunch spot'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in cafe interiors. Use WoodPlanks for floor (170,140,100), Brick for accent wall (160,80,65), Wood for furniture (140,100,60). Counter 10x3x3 with Glass pastry display 4x2x2. Small tables 3x3x3 with 2 chairs each. Include espresso machine prop 2x1x2, chalkboard menu 6x0.3x4, potted plants, string PointLights (Range 4, Color 255,210,150) every 4 studs overhead.',
  },
  {
    id: 'bar',
    name: 'Bar Interior Designer',
    description: 'Expert in bar, pub, and nightclub interior layout',
    keywords: ['bar', 'pub', 'tavern', 'nightclub', 'saloon', 'speakeasy', 'lounge bar', 'cocktail', 'brewery', 'taproom', 'inn'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in bar interiors. Use Wood for bar counter (80,50,30), WoodPlanks for floor (100,70,40), Brick for walls (130,60,50). L-shaped bar counter 16x3x4 with DiamondPlate foot rail. Back bar shelving 16x1x8 with bottle props (1x1x2.5 cylinders in amber 180,120,40). Bar stools 2x2x3. Include dart board, pool table 5x9x3, and moody PointLights (Range 6, Color 255,160,80).',
  },
  {
    id: 'hospital-room',
    name: 'Hospital Room Designer',
    description: 'Expert in medical facility and hospital room layout',
    keywords: ['hospital', 'medical', 'clinic', 'ward', 'emergency room', 'doctor', 'patient room', 'operating room', 'surgery', 'infirmary', 'medbay'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in hospital room design. Use Concrete for walls (235,240,235), Marble for floor (230,235,230), Metal for equipment (190,195,200). Hospital bed 4x7x3 with side rails. IV stand: 0.5x0.5x6 pole with 1x1 hook. Heart monitor 2x1x2 on stand. Include curtain divider track, supply cabinet 3x1x5, sink station, and clinical SpotLights (Range 16, Color 245,250,255).',
  },
  {
    id: 'prison-cell',
    name: 'Prison Cell Designer',
    description: 'Expert in prison, jail, and detention facility design',
    keywords: ['prison', 'jail', 'cell', 'detention', 'dungeon', 'cage', 'penitentiary', 'lockup', 'incarceration', 'barred', 'cellblock'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in prison cell design. Use Concrete for walls (160,160,155), Metal for bars (100,105,110), DiamondPlate for door (120,125,130). Cell is 6x8x10. Bars: 0.5x0.5x8 cylinders spaced 1.5 studs apart across 6-stud opening. Bunk bed: 4x6x2 frame + 4x6x0.5 Fabric mattress, upper at 5 studs. Include toilet block 2x2x2, sink 1.5x1x2, and harsh SpotLights (Range 8, Color 230,230,240).',
  },
  {
    id: 'throne-room',
    name: 'Throne Room Designer',
    description: 'Expert in royal throne room and great hall design',
    keywords: ['throne room', 'throne', 'royal', 'great hall', 'palace interior', 'court', 'crown', 'king', 'queen', 'regal', 'coronation'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in throne room design. Use Marble for floor (240,235,225), Granite for pillars (120,115,110), Fabric for throne upholstery (130,25,30). Hall is 24x50x20. Throne: 4x3x6 with ornate back, raised on 8x6x2 dais. Pillars 3x3x18 every 8 studs flanking red carpet 6x40x0.2. Include banners (1x0.3x8 Fabric), chandeliers, and golden PointLights (Range 14, Color 255,220,150).',
  },
  {
    id: 'wizard-study',
    name: 'Wizard Study Designer',
    description: 'Expert in magical study and enchanted room design',
    keywords: ['wizard', 'study', 'magic room', 'alchemy', 'potion', 'enchanted', 'sorcerer', 'mage', 'spell', 'arcane', 'mystical', 'witch'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in wizard study interiors. Use Wood for shelves (90,55,30), WoodPlanks for floor (120,80,45), Cobblestone for walls (110,105,100). Circular room 14-stud diameter. Potion bottles: colored 0.5x0.5x1.5 cylinders (120,40,180), (40,180,80), (180,40,40). Include cauldron (4-stud bowl in Metal), crystal ball (2-stud Glass sphere), bookpiles, floating candle PointLights (Range 6, Color 200,160,255).',
  },
  {
    id: 'spaceship-bridge',
    name: 'Spaceship Bridge Designer',
    description: 'Expert in starship command bridge and cockpit design',
    keywords: ['bridge', 'cockpit', 'command center', 'starship', 'spaceship interior', 'helm', 'navigation', 'star trek', 'pilot seat', 'flight deck'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in spaceship bridge design. Use Metal for hull (70,75,85), Neon for displays (60,180,255), DiamondPlate for floor (90,95,100). Semi-circular layout 20x16. Captain chair centered 4x3x4. Consoles: 6x1x2 with Neon screen faces arrayed in arc. Viewscreen 16x0.3x8 Glass at front. Include tactical rail, door with sliding animation space, and blue SpotLights (Range 12, Color 100,160,255).',
  },
  {
    id: 'control-room',
    name: 'Control Room Designer',
    description: 'Expert in mission control and monitoring room design',
    keywords: ['control room', 'mission control', 'monitoring', 'security room', 'surveillance', 'operations', 'command', 'dispatch', 'war room', 'situation room'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in control room design. Use Metal for consoles (80,85,90), Concrete for walls (60,65,70), Neon for screens (40,200,120). Tiered floor: front row at 0, middle at 2 studs up, back at 4 studs. Console desks 5x2x3 with 4x0.3x2 screen props. Main display wall 20x0.5x10 with Neon. Include server rack 2x3x7, cable trays, and cool SpotLights (Range 14, Color 200,220,255).',
  },
  {
    id: 'recording-studio',
    name: 'Recording Studio Designer',
    description: 'Expert in music studio and sound booth design',
    keywords: ['recording studio', 'music studio', 'sound booth', 'studio', 'mixing', 'audio', 'producer', 'soundproof', 'vocal booth', 'band room'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in recording studio design. Use Fabric for acoustic panels (60,55,70), WoodPlanks for floor (140,105,65), Metal for equipment (75,80,85). Control room 16x12 with vocal booth 6x6. Mixing desk 8x3x3 with angled top. Monitor speakers 2x2x3 on stands. Include acoustic foam wedge panels on walls, mic stand 0.5x0.5x5, headphone hook, and dim PointLights (Range 8, Color 255,200,160).',
  },
  {
    id: 'gym',
    name: 'Gym Interior Designer',
    description: 'Expert in gymnasium, fitness center, and weight room design',
    keywords: ['gym', 'gymnasium', 'fitness', 'weight room', 'workout', 'exercise', 'training', 'crossfit', 'sports hall', 'dojo floor'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in gym interiors. Use Rubber for floor mats (50,50,55), Metal for equipment frames (100,100,105), Concrete for walls (220,220,220). Open floor 30x40. Squat rack 4x4x8 Metal frame. Bench press 2x5x2. Dumbbells: 1x1x2.5 cylinders with 2x1x1 weights. Include treadmill 2x6x4, wall mirrors (Glass 0.3 thick), pull-up bar, and bright SpotLights (Range 20, Color 255,255,250).',
  },
  {
    id: 'movie-theater',
    name: 'Movie Theater Designer',
    description: 'Expert in cinema, movie theater, and screening room design',
    keywords: ['movie theater', 'cinema', 'theater', 'screening room', 'imax', 'auditorium', 'movie', 'film', 'projection', 'multiplex'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in movie theater design. Use Fabric for seats (140,30,35), Concrete for tiered floor (60,55,55), WoodPlanks for trim (100,70,45). Screen 30x0.3x16 white Concrete. Tiered rows stepping up 2 studs per row, 8 rows. Seats 2x2x3 with folding bottom. Include aisle lighting (Neon strips 0.5x0.5 along steps, Color 80,80,120), projection booth, and dim PointLights (Range 4, Color 40,30,60).',
  },
  {
    id: 'arcade',
    name: 'Arcade Interior Designer',
    description: 'Expert in retro arcade and game center design',
    keywords: ['arcade', 'game center', 'retro', 'pinball', 'pac-man', 'game room', 'amusement', 'token', 'cabinet', 'gaming lounge'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in arcade interiors. Use Concrete for floor (40,35,50), WoodPlanks for cabinets (30,25,40), Neon for signs (255,50,200). Arcade cabinets 3x2x5 with Neon screen face and control panel shelf. Arrange in rows 4 studs apart. Include prize counter, air hockey table 5x8x3, claw machine 4x4x6 with Glass sides, carpet pattern (checkered tiles), and colorful PointLights (Range 6, Color 255,100,200).',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // VEHICLES (20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sedan',
    name: 'Sedan Vehicle Builder',
    description: 'Expert in standard sedan and family car construction',
    keywords: ['sedan', 'car', 'automobile', 'vehicle', 'family car', 'commuter', 'four door', 'saloon car', 'daily driver', 'compact car'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in sedan construction. Use Metal for body (45,85,160), Glass for windshield (180,200,220), Rubber for tires (35,35,35). Body is 6x12x4. Hood slopes down 2 studs over 4. Windshield angled 30 degrees. Wheels: 2-stud radius cylinders at 4 corners. Include headlights (1x1 SpotLight, Range 30, Color 255,250,230), tail lights (Neon 1x0.5x0.5, Color 255,20,20), side mirrors, door seams.',
  },
  {
    id: 'sports-car',
    name: 'Sports Car Builder',
    description: 'Expert in high-performance sports car and supercar design',
    keywords: ['sports car', 'supercar', 'race car', 'hypercar', 'lambo', 'ferrari', 'fast car', 'exotic car', 'coupe', 'roadster', 'muscle car'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in sports car design. Use Metal for body (200,30,30), Glass for windshield (170,190,210), Rubber for tires (30,30,30). Low profile: 5x12x3. Aggressive wedge front sloping 3 studs over 4. Wide rear with spoiler 5x0.5x1 raised 1 stud. Wheels: 2.5-stud radius. Include air intakes (recessed 1x2 slots), dual exhaust pipes (0.5 cylinders), and LED headlights (SpotLight Range 40, Color 255,255,255).',
  },
  {
    id: 'pickup-truck',
    name: 'Pickup Truck Builder',
    description: 'Expert in pickup truck and utility vehicle construction',
    keywords: ['pickup', 'truck', 'pickup truck', 'ute', 'flatbed', 'offroad', 'off-road', '4x4', 'lifted', 'hauler', 'workhorse'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in pickup truck construction. Use Metal for body (30,50,80), WoodPlanks for bed floor (140,100,60), Rubber for tires (35,35,35). Cab 6x6x5, bed 6x8x2 open top. Ride height 3 studs (lifted). Wheels: 3-stud radius with wide 1.5-stud tread. Include bull bar 6x1x2 Metal, running boards, bed rails, roof rack, and halogen SpotLights (Range 35, Color 255,240,200) for headlights.',
  },
  {
    id: 'bus',
    name: 'Bus Builder',
    description: 'Expert in bus and public transit vehicle construction',
    keywords: ['bus', 'school bus', 'transit', 'coach', 'double decker', 'shuttle', 'minibus', 'public transport', 'charter bus', 'tour bus'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in bus construction. Use Metal for body (220,180,30), Glass for windows (180,200,220), Rubber for tires (35,35,35). Body is 8x30x8. Window strip: 6x0.3x3 Glass panels every 4 studs. Door opening 3x0.5x6 at front. Wheels: 3-stud radius, dual rear axle. Include interior bench seats 6x2x2 in rows, driver area with steering wheel prop, destination sign, and headlights (SpotLight Range 25).',
  },
  {
    id: 'motorcycle',
    name: 'Motorcycle Builder',
    description: 'Expert in motorcycle and bike construction',
    keywords: ['motorcycle', 'motorbike', 'bike', 'chopper', 'cruiser', 'dirt bike', 'harley', 'scooter', 'moped', 'two wheeler', 'sportbike'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in motorcycle construction. Use Metal for frame (50,50,55), Metal for engine (70,70,75), Rubber for tires (30,30,30). Frame: 2x6x3 main body. Wheels: front 2-stud radius, rear 2.5-stud radius. Fork: two 0.5x0.5x3 angled tubes. Include exhaust pipe (0.5 cylinder, 4 studs long), handlebars 3x0.5x1, seat 2x3x0.5, and single headlight (SpotLight Range 25, Color 255,250,230).',
  },
  {
    id: 'bicycle',
    name: 'Bicycle Builder',
    description: 'Expert in bicycle and cycling vehicle construction',
    keywords: ['bicycle', 'bike', 'cycle', 'bmx', 'mountain bike', 'road bike', 'pedal', 'cycling', 'tricycle', 'fixie'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in bicycle construction. Use Metal for frame (180,30,30), Rubber for tires (30,30,30), Metal for chain (80,80,85). Diamond frame from 0.5x0.5 beams. Wheels: 2-stud radius with 0.2-stud tire width. Handlebars 2x0.5x0.5 curved. Include pedals (0.5x1 blocks), chain connecting cranks to rear wheel, seat 1x2x0.5, and optional basket 2x1.5x1.5 on front.',
  },
  {
    id: 'helicopter',
    name: 'Helicopter Builder',
    description: 'Expert in helicopter and rotorcraft construction',
    keywords: ['helicopter', 'chopper', 'heli', 'rotorcraft', 'gunship', 'rescue helicopter', 'medevac', 'apache', 'blackhawk', 'news chopper'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in helicopter construction. Use Metal for fuselage (60,80,60), Glass for canopy (180,210,230), Metal for rotors (100,100,100). Fuselage 6x14x5 with tapered tail boom 2x10x2. Main rotor: 4 blades, each 0.5x12x0.2 on hub. Tail rotor: 2 blades 0.5x3x0.2. Skid landing gear: 0.5x8 tubes. Include cockpit instruments, side doors, and navigation SpotLight (Range 40, Color 255,255,240).',
  },
  {
    id: 'airplane',
    name: 'Airplane Builder',
    description: 'Expert in commercial airplane and passenger aircraft construction',
    keywords: ['airplane', 'plane', 'aircraft', 'airliner', 'jet', 'passenger plane', 'boeing', 'airbus', 'commercial plane', 'aviation', 'propeller plane'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in airplane construction. Use Metal for fuselage (230,235,240), Glass for cockpit windows (180,200,220), Metal for engines (140,145,150). Cylindrical fuselage 8-stud diameter, 50 studs long. Wings 30 studs span, 6 studs chord, swept 15 degrees. Engine nacelles 4-stud diameter cylinders under wings. Include tail fin 6x0.5x8, horizontal stabilizers, passenger windows (0.5x1 Glass), and landing gear.',
  },
  {
    id: 'jet-fighter',
    name: 'Jet Fighter Builder',
    description: 'Expert in military fighter jet and combat aircraft construction',
    keywords: ['jet fighter', 'fighter', 'military jet', 'combat aircraft', 'f-16', 'stealth', 'bomber', 'warplane', 'interceptor', 'ace', 'dogfight'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in jet fighter construction. Use Metal for body (120,125,130), Glass for canopy (170,200,220), Neon for afterburner (255,120,30). Sleek fuselage 4x20x3. Delta wings 16-stud span, 8 studs chord. Single or twin vertical fins 4x0.5x4. Canopy: bubble Glass 3x4x2. Include missile props (0.5x3 cylinders under wings), intake scoops, afterburner glow with PointLight (Range 8, Color 255,100,20).',
  },
  {
    id: 'spaceship',
    name: 'Spaceship Builder',
    description: 'Expert in sci-fi spaceship and starship construction',
    keywords: ['spaceship', 'starship', 'spacecraft', 'shuttle', 'star wars', 'cruiser ship', 'freighter', 'corvette ship', 'interstellar', 'warp drive'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in spaceship construction. Use Metal for hull (90,100,115), Neon for engines (80,180,255), Glass for viewports (160,190,220). Asymmetric or angular hull 10x30x6. Engine nacelles with Neon glow 3x6 cylinders. Cockpit viewport 6x0.3x3 Glass. Include antenna arrays, cargo bay doors, turret mounts (2x2x3 rotating base), hull panel lines, and engine SpotLights (Range 12, Color 80,160,255).',
  },
  {
    id: 'pirate-ship',
    name: 'Pirate Ship Builder',
    description: 'Expert in wooden pirate ship and sailing vessel construction',
    keywords: ['pirate ship', 'pirate', 'galleon', 'ship', 'sailing', 'vessel', 'schooner', 'brigantine', 'jolly roger', 'seafaring', 'buccaneer'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in pirate ship construction. Use WoodPlanks for hull (110,70,35), Wood for masts (100,65,30), Fabric for sails (230,220,200). Hull 10x40x8 with curved bow and raised stern castle. Three masts 2x2x30 with cross-yards 0.5x12. Sails are 10x0.3x8 Fabric sheets. Include crow nest 4x4x1 at top, cannon props (2-stud cylinders), rope railings, skull flag, and lantern PointLights (Range 8, Color 255,180,80).',
  },
  {
    id: 'yacht',
    name: 'Yacht Builder',
    description: 'Expert in luxury yacht and pleasure boat construction',
    keywords: ['yacht', 'boat', 'luxury boat', 'cruiser boat', 'sailboat', 'catamaran', 'speedboat', 'pontoon', 'marina', 'vessel', 'watercraft'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in yacht construction. Use Metal for hull (240,245,250), Glass for windows (180,210,230), WoodPlanks for deck (170,130,80). Sleek hull 8x30x4. Upper deck cabin 6x12x4 with panoramic Glass. Sun deck 8x10 open with lounge chairs (3x1x0.5). Include helm station, railing 1-stud poles every 3 studs, swim platform at stern, and warm deck SpotLights (Range 10, Color 255,240,210).',
  },
  {
    id: 'submarine',
    name: 'Submarine Builder',
    description: 'Expert in submarine and submersible vessel construction',
    keywords: ['submarine', 'sub', 'submersible', 'u-boat', 'underwater vessel', 'deep dive', 'torpedo', 'periscope', 'bathyscaphe', 'nautilus'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in submarine construction. Use Metal for hull (80,90,100), Glass for viewport (160,200,220), Neon for running lights (40,255,120). Cylindrical hull 8-stud diameter, 35 studs long with tapered bow and stern. Conning tower 4x6x6 on top. Include periscope (0.5x0.5x4 cylinder), torpedo tubes (1-stud openings at bow), diving planes (4x0.5x1 fins), propeller, and interior green PointLights (Range 8, Color 60,200,120).',
  },
  {
    id: 'train',
    name: 'Train Builder',
    description: 'Expert in locomotive and railway vehicle construction',
    keywords: ['train', 'locomotive', 'railway', 'railroad', 'steam engine', 'freight train', 'passenger train', 'caboose', 'metro', 'subway', 'monorail'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in train construction. Use Metal for body (40,45,50), Brick for boiler (150,40,35), Metal for wheels (60,65,70). Locomotive 8x24x10. Boiler cylinder 6-stud diameter, 12 studs long. Smokestack 3x3x4 cylinder with Smoke emitter. Drive wheels 3-stud radius. Include coal tender 6x8x4, cow catcher wedge at front, cab 6x6x8 with windows, and headlamp SpotLight (Range 40, Color 255,250,220).',
  },
  {
    id: 'tank',
    name: 'Tank Builder',
    description: 'Expert in military tank and armored vehicle construction',
    keywords: ['tank', 'military tank', 'armored', 'panzer', 'artillery', 'turret vehicle', 'apc', 'infantry vehicle', 'war machine', 'heavy armor'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in tank construction. Use Metal for armor (85,95,75), DiamondPlate for treads (70,75,65), Metal for gun barrel (90,90,95). Hull 8x14x4. Turret 6x6x3 centered on hull. Main gun: 1.5-stud diameter cylinder, 10 studs long. Track assemblies: 2x14x3 with DiamondPlate. Include commander hatch, machine gun mount, ERA block details (1x1x0.5 on hull), and muzzle flash PointLight (Range 4, Color 255,200,80).',
  },
  {
    id: 'hovercraft',
    name: 'Hovercraft Builder',
    description: 'Expert in hovercraft and air-cushion vehicle construction',
    keywords: ['hovercraft', 'hover', 'air cushion', 'amphibious', 'skimmer', 'hovering', 'fan boat', 'swamp boat', 'ground effect', 'ekranoplan'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in hovercraft construction. Use Metal for hull (200,200,210), Fabric for skirt (50,50,55), Rubber for bumpers (40,40,40). Flat hull 10x16x2. Inflatable skirt: Fabric ring 1 stud thick around base extending 2 studs below hull. Rear fan housing: 4-stud cylinder with 3 blade props inside. Include pilot cabin 4x4x4 at front, cargo deck, control stick, and navigation SpotLight (Range 20, Color 255,250,240).',
  },
  {
    id: 'hot-air-balloon',
    name: 'Hot Air Balloon Builder',
    description: 'Expert in hot air balloon and airship construction',
    keywords: ['hot air balloon', 'balloon', 'airship', 'dirigible', 'blimp', 'zeppelin', 'aerostat', 'floating', 'gondola', 'sky ride'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in hot air balloon construction. Use Fabric for envelope (200,50,50) with stripe panels (255,200,50), (50,100,200). Envelope: sphere 16-stud diameter built from curved segments. Basket 4x4x3 WoodPlanks. Ropes: 4 diagonal 0.2x0.2 beams connecting basket to envelope. Include burner with Fire particle and PointLight (Range 6, Color 255,140,40), sandbag props on basket rim.',
  },
  {
    id: 'rocket',
    name: 'Rocket Builder',
    description: 'Expert in space rocket and launch vehicle construction',
    keywords: ['rocket', 'launch', 'space rocket', 'missile', 'booster', 'nasa', 'spacex', 'saturn', 'launchpad', 'liftoff', 'payload'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in rocket construction. Use Metal for body (230,235,240), Neon for engine glow (255,140,40), Concrete for launch pad (180,175,170). Cylindrical body 6-stud diameter, 40 studs tall. Nose cone: 6-to-0 taper over 8 studs. 4 fins at base, each 4x0.5x6. Include staging lines, flag decal area, umbilical tower 4x4x35 nearby, exhaust Fire with PointLight (Range 16, Color 255,120,30).',
  },
  {
    id: 'ufo',
    name: 'UFO Builder',
    description: 'Expert in flying saucer and alien spacecraft construction',
    keywords: ['ufo', 'flying saucer', 'alien ship', 'extraterrestrial', 'alien', 'saucer', 'area 51', 'abduction', 'mothership', 'close encounter'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in UFO construction. Use Metal for hull (170,180,190), Glass for dome (180,220,200), Neon for lights (120,255,120). Disc shape: 20-stud diameter, 3 studs thick in center tapering to 0.5 at edge. Dome: half-sphere 6 studs diameter on top. Ring of Neon lights around rim, 16 evenly spaced PointLights (Range 4, Color 100,255,150). Include landing legs 1x1x3, beam emitter underneath, and interior seats.',
  },
  {
    id: 'mech-suit',
    name: 'Mech Suit Builder',
    description: 'Expert in giant mech, robot, and power armor construction',
    keywords: ['mech', 'mech suit', 'robot', 'mecha', 'power armor', 'exosuit', 'titan', 'gundam', 'jaeger', 'walker', 'bipedal robot'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in mech suit construction. Use Metal for armor (100,110,120), Neon for visor (80,200,255), DiamondPlate for joints (85,90,95). Torso 6x4x8. Legs: 3x3x10 with 4x4x2 feet. Arms: 2x2x8 with 3x3x3 shoulder pads. Cockpit hatch 4x0.5x4 on chest. Include arm-mounted weapons (2-stud barrel extending 6 studs), knee and elbow joint cylinders, back thrusters, and visor PointLight (Range 6, Color 80,200,255).',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NATURE (20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'forest',
    name: 'Forest Environment Specialist',
    description: 'Expert in temperate forest and woodland biome design',
    keywords: ['forest', 'woods', 'woodland', 'trees', 'tree', 'deciduous', 'timber', 'grove', 'thicket', 'glade', 'sylvan', 'temperate forest', 'oak', 'pine', 'bush', 'shrub', 'plant', 'flower', 'log', 'stump'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in forest environments. Use Wood for trunks (85,60,30), Grass for canopy (50,110,40), Grass for ground (65,130,55). Tree trunk: 2x2 cylinder, 12-20 studs tall. Canopy: cluster of 6+ overlapping 6x2x6 Grass parts. Place 8+ trees with varied heights. Include fallen logs, mushroom props (1-stud cylinder + 2-stud disc), bush clusters, and dappled PointLights (Range 8, Color 200,230,160).',
  },
  {
    id: 'jungle',
    name: 'Jungle Environment Specialist',
    description: 'Expert in tropical jungle and rainforest biome design',
    keywords: ['jungle', 'rainforest', 'tropical', 'amazon', 'vines', 'canopy', 'equatorial', 'dense forest', 'exotic', 'primal'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in jungle environments. Use Wood for trunks (70,50,25), Grass for leaves (30,100,30), Cobblestone for ruins (90,95,80). Dense canopy layers: understory at 15 studs, mid at 25, emergent at 40. Vine ropes hanging from branches (0.5x0.5x12 Grass cylinders). Include massive buttress root trees (trunk 4x4), ancient stone ruins overgrown with vines, and misty PointLights (Range 6, Color 180,220,160).',
  },
  {
    id: 'desert',
    name: 'Desert Environment Specialist',
    description: 'Expert in arid desert and sand dune biome design',
    keywords: ['desert', 'sand', 'dunes', 'arid', 'sahara', 'oasis', 'cactus', 'wasteland', 'badlands', 'dry', 'scorched'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in desert environments. Use Sand for terrain (220,195,150), Sandstone for rocks (200,170,120), Grass for cactus (60,100,40). Rolling dunes: wedge-shaped 20x0.5x8 Sand parts overlapping. Rock formations: stacked irregular Sandstone 6x4x8. Cacti: 1x1 cylinders 6 studs tall with 1x1x2 arm branches. Include bleached bone props, desert bush, and harsh SpotLight sun (Range 60, Color 255,245,220).',
  },
  {
    id: 'tundra',
    name: 'Tundra Environment Specialist',
    description: 'Expert in arctic tundra and frozen plain biome design',
    keywords: ['tundra', 'arctic', 'frozen', 'permafrost', 'snow plain', 'polar', 'cold', 'barren', 'winter', 'frost', 'blizzard'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in tundra environments. Use Ice for snow terrain (235,240,245), Concrete for frozen ground (200,205,210), Granite for boulders (140,140,145). Flat terrain with gentle rolls. Snowdrifts: wedge parts 8x2x4. Sparse vegetation: low 1x1x2 shrubs in dark Grass (50,70,40). Include frozen lake (Glass 30x20x0.5), animal tracks, wind-bent flag poles, and pale SpotLights (Range 30, Color 220,230,255).',
  },
  {
    id: 'mountains',
    name: 'Mountain Environment Specialist',
    description: 'Expert in mountain range and alpine terrain design',
    keywords: ['mountain', 'mountains', 'alpine', 'peak', 'cliff', 'summit', 'highlands', 'ridge', 'elevation', 'rocky', 'mountainside'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in mountain environments. Use Granite for rock (120,115,110), Ice for snow caps (235,240,245), Grass for alpine meadow (70,120,50). Mountain peak: pyramid of stacked wedges 40+ studs tall. Snow line at top 30%. Cliff faces using vertical Granite slabs. Include hiking trail (2-stud wide dirt path), pine trees 2x2x15 with triangle canopy, mountain goat props, and atmospheric fog PointLights (Range 10, Color 200,210,230).',
  },
  {
    id: 'volcano',
    name: 'Volcano Environment Specialist',
    description: 'Expert in volcanic and lava terrain design',
    keywords: ['volcano', 'lava', 'volcanic', 'eruption', 'magma', 'caldera', 'crater', 'molten', 'obsidian', 'pyroclastic', 'fire mountain'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in volcanic environments. Use Basalt for rock (50,45,40), Neon for lava (255,80,20), Granite for cooled flows (60,55,50). Cone shape 30-stud base, 40 studs tall. Crater 10-stud opening at top. Lava rivers: 3-stud wide Neon channels flowing downhill. Include obsidian Glass shards, volcanic boulder props, steam vents with Smoke emitters, and lava glow PointLights (Range 12, Color 255,100,20).',
  },
  {
    id: 'ocean',
    name: 'Ocean Environment Specialist',
    description: 'Expert in open ocean and seascape design',
    keywords: ['ocean', 'sea', 'water', 'waves', 'nautical', 'maritime', 'seascape', 'deep blue', 'open water', 'tide', 'coastline'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in ocean environments. Use Glass for water surface (60,130,180), Sand for seabed (200,185,140), Cobblestone for sea rocks (100,110,105). Water plane: large Glass part at 0 elevation. Seabed 20+ studs below. Wave crests: overlapping wedge Glass parts with white foam tops (240,245,250). Include coral clusters, kelp strands (1x1x8 Grass), bobbing buoy props, and underwater PointLights (Range 10, Color 60,150,200).',
  },
  {
    id: 'river',
    name: 'River Environment Specialist',
    description: 'Expert in river, stream, and creek design',
    keywords: ['river', 'stream', 'creek', 'brook', 'rapids', 'waterway', 'flowing water', 'riverbed', 'riverbank', 'tributary', 'delta'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in river environments. Use Glass for water (70,140,170), Sand for banks (190,175,130), Cobblestone for riverbed (130,125,115). River channel 6-10 studs wide, carved 3 studs into terrain. Smooth Glass water plane. Banks slope gently over 4 studs. Include stepping stones (2x2 Cobblestone above water), reeds (0.5x0.5x4 Grass clusters at edges), log bridge, and ripple PointLights (Range 4, Color 140,200,220).',
  },
  {
    id: 'waterfall',
    name: 'Waterfall Environment Specialist',
    description: 'Expert in waterfall and cascade terrain design',
    keywords: ['waterfall', 'cascade', 'falls', 'cataract', 'plunge pool', 'rapids', 'water fall', 'cliff water', 'niagara', 'misty falls'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in waterfall environments. Use Glass for water (80,160,200), Granite for cliff (110,105,100), Grass for moss (50,100,40). Cliff face 20+ studs tall. Waterfall: vertical Glass sheet 6x0.3x20 with white Glass mist at base (240,245,250). Plunge pool 10x8x3 Glass below. Include moss-covered rocks, rainbow arc (thin Neon strips), fern clusters, and mist PointLights (Range 8, Color 200,220,240).',
  },
  {
    id: 'cave',
    name: 'Cave Environment Specialist',
    description: 'Expert in cave, cavern, and grotto environment design',
    keywords: ['cave', 'cavern', 'grotto', 'underground', 'stalactite', 'stalagmite', 'tunnel', 'mine', 'spelunking', 'subterranean', 'dungeon cave'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in cave environments. Use Granite for walls (80,75,70), Cobblestone for floor (90,85,80), Glass for crystals (180,100,255). Irregular tunnel 10x10 cross-section. Stalactites: inverted wedge 1x1x4 from ceiling. Stalagmites: wedge 1x1x3 from floor. Include underground pool (Glass 8x6x0.5), crystal clusters (Glass wedges in purple and blue), bat props, and dim PointLights (Range 6, Color 160,140,100).',
  },
  {
    id: 'canyon',
    name: 'Canyon Environment Specialist',
    description: 'Expert in canyon, gorge, and ravine terrain design',
    keywords: ['canyon', 'gorge', 'ravine', 'mesa', 'butte', 'plateau', 'grand canyon', 'slot canyon', 'cliff face', 'gulch', 'arroyo'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in canyon environments. Use Sandstone for walls (190,140,90), Sand for floor (210,185,140), Granite for hard layers (150,100,70). Canyon walls 30+ studs tall, 10-20 studs apart. Layered strata: alternate color bands every 5 studs. Include natural arch (curved sandstone bridge), mesa flat-tops, tumbleweeds (3-stud Grass spheres), and warm sunlight SpotLights (Range 40, Color 255,230,180).',
  },
  {
    id: 'swamp',
    name: 'Swamp Environment Specialist',
    description: 'Expert in swamp, bayou, and wetland biome design',
    keywords: ['swamp', 'bayou', 'marsh', 'wetland', 'bog', 'fen', 'mangrove', 'murky', 'mire', 'everglades', 'swampland'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in swamp environments. Use Glass for murky water (60,80,50), Wood for dead trees (70,55,35), Grass for moss (50,90,30). Shallow water 1-2 studs deep across terrain. Dead trees: bare trunks 2x2x12 with twisted 0.5-stud branches. Mangrove roots: tangled cylinders. Include lily pads (2x0.2x2 Grass on water), fog machines with Smoke, swamp gas Neon bubbles, and eerie PointLights (Range 6, Color 120,160,80).',
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef Environment Specialist',
    description: 'Expert in underwater coral reef and marine habitat design',
    keywords: ['coral reef', 'coral', 'reef', 'underwater', 'marine', 'tropical fish', 'snorkeling', 'diving', 'aquarium', 'atoll', 'lagoon'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in coral reef environments. Use Neon for coral (255,100,120), Grass for seaweed (40,140,60), Sand for seabed (220,200,160). Brain coral: 3-stud spheres in pink (255,130,150). Fan coral: 0.3x4x6 Neon plates. Tube coral: 1-stud cylinders clusters. Include tropical fish props (colored 1x2x0.5 wedges), sea anemones, treasure chest, and bioluminescent PointLights (Range 6, Color 100,200,255).',
  },
  {
    id: 'floating-islands',
    name: 'Floating Islands Designer',
    description: 'Expert in floating sky island and aerial terrain design',
    keywords: ['floating island', 'sky island', 'floating', 'aerial', 'skylands', 'levitating', 'sky world', 'cloud island', 'suspended', 'gravity defying'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in floating island environments. Use Grass for top surface (65,130,55), Granite for underside rock (110,100,90), Sand for dirt layer (170,140,100). Island platform 20x20 with 3-stud Grass top, 2-stud dirt, 8-stud rock tapering to a point below. Waterfalls off edges into void. Include chain links between islands, small trees, vine bridges 1x20x0.5, and ethereal PointLights (Range 10, Color 200,230,255).',
  },
  {
    id: 'crystal-cavern',
    name: 'Crystal Cavern Designer',
    description: 'Expert in magical crystal cave and gem grotto design',
    keywords: ['crystal', 'cavern', 'gem', 'geode', 'crystal cave', 'amethyst', 'quartz', 'gemstone', 'sparkle', 'prismatic', 'mineral cave'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in crystal cavern environments. Use Glass for crystals (200,120,255), Granite for cave walls (70,65,60), Neon for glowing crystals (150,80,255). Crystal formations: tapered wedge clusters 2x2x8 angled outward from walls and floor. Vary colors: purple (180,80,240), blue (80,140,240), pink (240,100,180). Include geode hollows, reflective pools, crystal archways, and gem PointLights (Range 8, Color 180,120,255).',
  },
  {
    id: 'mushroom-forest',
    name: 'Mushroom Forest Designer',
    description: 'Expert in giant mushroom and fantasy fungal biome design',
    keywords: ['mushroom', 'fungal', 'fungus', 'mycelium', 'toadstool', 'spore', 'mushroom forest', 'giant mushroom', 'fantasy forest', 'shroomland'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in mushroom forest environments. Use Concrete for stems (200,190,170), Neon for caps (180,60,200), Grass for ground moss (50,80,40). Giant mushroom: 3x3 cylinder stem 15 studs tall, cap is 10-stud diameter disc 2 studs thick. Vary sizes from 8 to 25 studs tall. Include glowing spore particles, shelf fungi on stems, bioluminescent Neon ground patches, and purple PointLights (Range 8, Color 160,80,220).',
  },
  {
    id: 'cherry-blossom-garden',
    name: 'Cherry Blossom Garden Designer',
    description: 'Expert in cherry blossom and flowering garden design',
    keywords: ['cherry blossom', 'sakura', 'blossom', 'flower garden', 'petal', 'spring', 'hanami', 'flowering tree', 'pink tree', 'bloom'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in cherry blossom gardens. Use Wood for trunks (90,60,35), Fabric for blossoms (255,180,200), Grass for ground (70,130,55). Blossom trees: trunk 2x2x10, canopy of 10+ overlapping 4x1x4 Fabric parts in pink (255,180,200) and white (255,240,245). Include stone path (2-stud Cobblestone stepping stones), koi pond (Glass 8x6), wooden bench, fallen petals on ground, and soft PointLights (Range 10, Color 255,210,220).',
  },
  {
    id: 'zen-garden',
    name: 'Zen Garden Designer',
    description: 'Expert in Japanese zen garden and rock garden design',
    keywords: ['zen garden', 'rock garden', 'karesansui', 'zen', 'meditation', 'tranquil', 'raked sand', 'bonsai', 'peaceful', 'harmony', 'japanese garden'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in zen garden design. Use Sand for raked gravel (220,215,200), Granite for feature rocks (110,105,100), Wood for fencing (120,80,45). Raked sand bed 30x30x0.5. Feature rocks: irregular Granite groups of 3 (sizes 3x2x2, 2x1x1.5, 1x1x1). Include bamboo fence 0.5x0.5x4 poles tied at top, bonsai tree (1x1x3 Wood + 3x1x3 Grass), stone lantern, and subtle PointLights (Range 6, Color 240,235,220).',
  },
  {
    id: 'tropical-beach',
    name: 'Tropical Beach Designer',
    description: 'Expert in tropical beach and island coastline design',
    keywords: ['beach', 'tropical', 'island', 'palm tree', 'shore', 'coast', 'sand beach', 'paradise', 'lagoon', 'seaside', 'shoreline', 'vacation'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in tropical beach environments. Use Sand for beach (230,215,170), Glass for ocean (50,150,200), Wood for palm trunks (110,80,45). Gentle slope from sand to water over 10 studs. Palm trees: 2x2 curved trunk 15 studs, crown of 6 drooping 1x0.5x8 Grass fronds. Include beach umbrella, tiki torch with Fire and PointLight (Range 6, Color 255,160,60), surfboard prop, hammock between palms, and coconut props.',
  },
  {
    id: 'arctic-glacier',
    name: 'Arctic Glacier Designer',
    description: 'Expert in glacier, iceberg, and frozen landscape design',
    keywords: ['glacier', 'iceberg', 'arctic', 'polar', 'ice shelf', 'frozen sea', 'ice cap', 'permafrost', 'glacial', 'ice field', 'antarctic'],
    ragCategories: ['pattern', 'building'],
    prompt: 'You specialize in arctic glacier environments. Use Ice for glacier body (200,225,245), Glass for blue ice (140,190,230), Concrete for snow (240,242,245). Massive ice blocks 20x30x15 with fractured faces. Blue ice crevasses: 2-stud wide gaps with Glass walls inside. Include iceberg chunks floating on Glass water, seal props, ice arch formation, snow drifts, and cold SpotLights (Range 20, Color 190,210,240).',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GAME MECHANICS (15)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'tycoon-dropper',
    name: 'Tycoon Dropper Specialist',
    description: 'Expert in tycoon game dropper and conveyor systems',
    keywords: ['tycoon', 'dropper', 'conveyor', 'factory tycoon', 'money printer', 'ore', 'collector', 'upgrader', 'tycoon game', 'idle', 'clicker'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in tycoon dropper systems. Use Metal for conveyors (160,165,170), Neon for upgraders (80,255,120), Brick for droppers (180,80,80). Dropper box 4x4x4 elevated on 4x4x6 legs. Conveyor belts 4x20x0.5 Metal. Collector bin 6x6x3 at end. Include upgrader arches (6x1x6 Neon frame over conveyor), cash display board, button pads 2x0.5x2 for purchases, minimum 30 parts per tycoon unit.',
  },
  {
    id: 'obby-course',
    name: 'Obby Course Specialist',
    description: 'Expert in obstacle course and parkour level design',
    keywords: ['obby', 'obstacle course', 'parkour', 'platformer', 'jumping', 'obstacle', 'difficulty', 'checkpoint', 'wall jump', 'lava jump'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in obby course design. Use Concrete for platforms (200,200,200), Neon for checkpoints (80,255,80), Brick for kill bricks (255,40,40). Platforms vary: 4x4 standard, 2x2 hard, 6x6 rest areas. Gap jumps 8-12 studs. Checkpoint pads 4x0.5x4 Neon green. Kill parts in red Neon. Include wall jumps (two walls 4 studs apart), spinning obstacles, conveyor sections, and stage number labels.',
  },
  {
    id: 'pvp-arena',
    name: 'PvP Arena Specialist',
    description: 'Expert in player-vs-player combat arena design',
    keywords: ['pvp', 'arena', 'combat', 'deathmatch', 'battle', 'fighting', 'colosseum', 'gladiator', 'versus', 'duel', 'ffa', 'free for all'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in PvP arena design. Use Concrete for floor (180,175,170), Brick for walls (140,135,130), Metal for cover objects (100,105,110). Symmetrical layout 60x60. Cover walls 4x1x6 placed strategically. Elevated sniper perches at 10 studs. Spawn rooms 8x8 on opposite sides with one-way exits. Include ammo crate props 2x2x2, health pad Neon zones 4x0.5x4 green, and arena floodlights SpotLight (Range 30, Color 255,250,240).',
  },
  {
    id: 'tower-defense',
    name: 'Tower Defense Map Specialist',
    description: 'Expert in tower defense game map and path design',
    keywords: ['tower defense', 'td', 'towers', 'creep path', 'waves', 'turret', 'defend', 'base defense', 'strategy', 'placement', 'tower game'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in tower defense map design. Use Grass for terrain (65,130,55), Cobblestone for enemy path (150,140,125), Concrete for tower pads (200,200,200). Winding path 4 studs wide with 90-degree turns. Tower placement pads 4x4x0.5 along path edges every 8 studs. Include enemy spawn portal (Neon arch 6x1x6), base to defend, difficulty ramp areas, and path PointLights (Range 6, Color 255,200,100).',
  },
  {
    id: 'racing-track',
    name: 'Racing Track Specialist',
    description: 'Expert in racing circuit and track design',
    keywords: ['racing', 'race track', 'circuit', 'track', 'speedway', 'drag strip', 'karting', 'lap', 'finish line', 'grand prix', 'nascar'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in racing track design. Use Concrete for road (80,80,85), Grass for terrain (65,130,55), Neon for start/finish (255,255,255). Track 10 studs wide, total lap 200+ studs. Include chicanes, hairpin turns (inner radius 15 studs), banked curves raised 3 studs on outside. Finish line: checkered pattern 10x0.2x1 alternating (40,40,40) and (240,240,240). Tire barriers, grandstands, and lap counter display.',
  },
  {
    id: 'capture-flag',
    name: 'Capture The Flag Map Specialist',
    description: 'Expert in CTF game map and base design',
    keywords: ['capture the flag', 'ctf', 'flag', 'base', 'team', 'red vs blue', 'capture', 'team game', 'objective', 'two teams'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in CTF map design. Use Brick for red base (180,50,50), Brick for blue base (50,50,180), Grass for field (65,130,55). Mirror-symmetrical 80x120 map. Each base 16x16 with flag pedestal 2x2x3 at center. Flag: 0.5x0.3x3 on 0.5x0.5x5 pole. Midfield has neutral cover structures. Include team spawn rooms, bridge or chokepoint, flanking routes, and team-colored PointLights (Range 10).',
  },
  {
    id: 'battle-royale',
    name: 'Battle Royale Map Specialist',
    description: 'Expert in battle royale map and shrinking zone design',
    keywords: ['battle royale', 'br', 'last man standing', 'zone', 'shrinking', 'loot', 'drop', 'survival', 'fortnite style', 'pubg style', 'royale'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in battle royale map design. Use Grass for terrain (65,130,55), Concrete for buildings (200,195,190), Neon for zone border (255,60,60). Large 200x200 map with varied terrain: hills, valleys, water. Named POIs every 50 studs with 3-5 buildings each. Include loot spawn pads 2x0.5x2 Neon yellow, vehicle spawns, watchtowers, and zone border visualization using Neon ring parts.',
  },
  {
    id: 'simulator-area',
    name: 'Simulator Game Area Specialist',
    description: 'Expert in simulator game zone and progression area design',
    keywords: ['simulator', 'sim', 'pet simulator', 'clicking', 'rebirth', 'farming sim', 'grinding', 'progression', 'zone', 'world', 'simulator game'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in simulator game zones. Use Grass for starter area (65,130,55), Sand for mid zone (220,195,150), Neon for zone gates (255,200,50). Progressive zones 40x40 each. Zone gates: Neon arch 8x1x8 with requirement text. Each zone has: resource nodes (3-stud Neon spheres), sell pad 6x0.5x6, upgrade NPC stand. Include egg pedestals, rebirth portal, leaderboard display, and zone-themed PointLights.',
  },
  {
    id: 'rpg-dungeon',
    name: 'RPG Dungeon Specialist',
    description: 'Expert in RPG dungeon crawl and encounter room design',
    keywords: ['rpg', 'dungeon', 'crawl', 'quest', 'loot', 'encounter', 'dragon', 'adventure', 'raid', 'monster room', 'treasure room', 'rpg game'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in RPG dungeon design. Use Cobblestone for floors (90,85,80), Granite for walls (75,70,65), Metal for grates (80,85,90). Room-and-corridor layout: rooms 16x16, corridors 4 wide. Door frames 4x1x6 with Metal grate doors. Include treasure chest props 2x1.5x1.5, torch sconces every 8 studs with PointLights (Range 8, Color 255,160,60), trap floor tiles (Neon red 4x0.2x4), and boss room 24x24.',
  },
  {
    id: 'puzzle-room',
    name: 'Puzzle Room Specialist',
    description: 'Expert in puzzle room and brain teaser level design',
    keywords: ['puzzle', 'puzzle room', 'brain teaser', 'logic', 'riddle', 'switch', 'maze', 'labyrinth', 'sequence', 'pattern puzzle', 'mystery room'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in puzzle room design. Use Concrete for walls (210,210,215), Neon for interactive elements (100,200,255), Metal for mechanisms (120,125,130). Room 20x20x12. Button pads 2x0.5x2 Neon blue. Pressure plates 4x0.2x4. Sliding wall panels 8x1x8. Include numbered sequence pads, laser beam lines (0.2x0.2x20 Neon red), mirror props for reflection puzzles, and state-indicator PointLights (Range 6, Color 100,200,255).',
  },
  {
    id: 'escape-room',
    name: 'Escape Room Specialist',
    description: 'Expert in escape room and locked room challenge design',
    keywords: ['escape room', 'escape', 'locked room', 'mystery', 'clue', 'key', 'combination', 'time limit', 'breakout', 'room escape', 'detective'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in escape room design. Use Brick for walls (160,150,140), WoodPlanks for furniture (130,90,55), Metal for locks (90,95,100). Interconnected rooms 12x12 each. Locked doors with keyhole props. Include desk with hidden drawer, bookshelf with fake book lever, wall safe 2x1x2 Metal, keypad prop 1x0.5x1.5, clue notes on walls, timer display, and moody PointLights (Range 8, Color 255,200,150).',
  },
  {
    id: 'minigame-lobby',
    name: 'Minigame Lobby Specialist',
    description: 'Expert in game lobby and minigame hub world design',
    keywords: ['lobby', 'hub', 'minigame', 'waiting room', 'game hub', 'portal room', 'spawn lobby', 'main menu', 'world select', 'game select'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in minigame lobby design. Use Concrete for floor (220,220,225), Neon for game portals (255,180,50), Glass for decorative walls (200,220,240). Circular hub 40-stud diameter. Game portals: 6x1x8 Neon archways around perimeter with game name labels. Central fountain or statue. Include leaderboard displays 4x0.3x6, settings NPC stand, shop area, and welcoming PointLights (Range 16, Color 255,240,220).',
  },
  {
    id: 'spawn-area',
    name: 'Spawn Area Specialist',
    description: 'Expert in game spawn point and starting area design',
    keywords: ['spawn', 'spawn area', 'starting area', 'respawn', 'beginning', 'tutorial area', 'newbie zone', 'starter', 'safe zone', 'home base'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in spawn area design. Use Grass for ground (65,130,55), Concrete for paths (200,195,190), Neon for guides (80,200,255). Open area 30x30. SpawnLocation pad 6x0.2x6 centered. Directional arrows on ground pointing to key destinations. Include welcome sign 8x0.3x4, NPC tutorial guide stand, path fork leading to different game modes, and inviting PointLights (Range 14, Color 255,245,230).',
  },
  {
    id: 'shop-system',
    name: 'Shop System Specialist',
    description: 'Expert in in-game shop and marketplace design',
    keywords: ['shop', 'store', 'marketplace', 'vendor', 'merchant', 'buy', 'sell', 'market', 'trading', 'npc shop', 'item shop', 'game store'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in in-game shop design. Use WoodPlanks for counters (140,100,60), Concrete for floor (215,210,205), Neon for price tags (255,220,50). Shop counter 10x3x3. Display shelves 8x1x6 behind counter with item pedestals 1x1x1 spaced 2 studs apart. Include category signs, purchase button pads 2x0.5x2, gold coin props (1-stud yellow cylinders), NPC merchant stand, and warm PointLights (Range 10, Color 255,230,180).',
  },
  {
    id: 'boss-arena',
    name: 'Boss Arena Specialist',
    description: 'Expert in boss fight arena and epic encounter room design',
    keywords: ['boss', 'boss arena', 'boss fight', 'boss room', 'final boss', 'raid boss', 'epic fight', 'boss battle', 'lair', 'boss encounter', 'champion arena'],
    ragCategories: ['pattern', 'building', 'dev'],
    prompt: 'You specialize in boss arena design. Use Granite for floor (70,65,60), Cobblestone for walls (80,75,70), Neon for hazard zones (255,50,50). Circular arena 40-stud diameter with 15-stud ceiling. Boss spawn platform 8x0.5x8 raised 2 studs at center. Pillar cover objects 3x3x10 at cardinal points. Include phase-change hazard rings (Neon red floor strips), loot chest spawn point, dramatic entry gate 8x2x10, and boss PointLights (Range 12, Color 255,80,60).',
  },
]
