/**
 * GET /api/ai/3d-generate/templates
 *
 * Returns 60+ pre-made 3D asset templates across 8 categories.
 * Each template can be passed directly to POST /api/ai/3d-generate.
 *
 * Optional query params:
 *   ?category=buildings   — filter to a single category (slug)
 *   ?limit=20             — max results (default: all)
 */

import { NextRequest, NextResponse } from 'next/server'

// ── Types ─────────────────────────────────────────────────────────────────────

export interface AssetTemplate {
  id:          string
  name:        string
  prompt:      string
  preview:     string    // emoji placeholder; replace with CDN URL when available
  polyCount:   number
  price:       number    // ForjeGames tokens
  type:        string
  style:       string
  tags:        string[]
}

export interface TemplateCategory {
  name:      string
  slug:      string
  icon:      string
  templates: AssetTemplate[]
}

// ── Template data ─────────────────────────────────────────────────────────────

const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  // ── Buildings (10) ──────────────────────────────────────────────────────────
  {
    name: 'Buildings',
    slug: 'buildings',
    icon: 'building',
    templates: [
      {
        id: 'medieval-castle',
        name: 'Medieval Castle',
        prompt: 'medieval stone castle with four towers, crenellated battlements, drawbridge, and a central keep, worn stone texture',
        preview: 'castle',
        polyCount: 8500,
        price: 80,
        type: 'building',
        style: 'roblox',
        tags: ['medieval', 'castle', 'fantasy'],
      },
      {
        id: 'modern-house',
        name: 'Modern House',
        prompt: 'modern two-story suburban house with flat roof, large windows, concrete and wood facade, attached garage',
        preview: 'house',
        polyCount: 4200,
        price: 50,
        type: 'building',
        style: 'stylized',
        tags: ['modern', 'house', 'suburban'],
      },
      {
        id: 'fantasy-tavern',
        name: 'Fantasy Tavern',
        prompt: 'cozy medieval fantasy tavern with thatched roof, warm lit windows, wooden sign, barrel by the door',
        preview: 'tavern',
        polyCount: 5600,
        price: 60,
        type: 'building',
        style: 'stylized',
        tags: ['fantasy', 'tavern', 'medieval'],
      },
      {
        id: 'sci-fi-base',
        name: 'Sci-Fi Base',
        prompt: 'futuristic sci-fi military base with reinforced blast doors, antenna arrays, glowing panels, concrete bunker aesthetic',
        preview: 'base',
        polyCount: 7200,
        price: 75,
        type: 'building',
        style: 'realistic',
        tags: ['scifi', 'military', 'futuristic'],
      },
      {
        id: 'wooden-cabin',
        name: 'Wooden Cabin',
        prompt: 'rustic log cabin in the woods, stone chimney, porch with railing, chopped wood pile beside it',
        preview: 'cabin',
        polyCount: 3800,
        price: 40,
        type: 'building',
        style: 'roblox',
        tags: ['cabin', 'rustic', 'nature'],
      },
      {
        id: 'wizard-tower',
        name: 'Wizard Tower',
        prompt: 'tall narrow wizard tower with spiral stone exterior, magical runes glowing on walls, conical pointed roof, observatory window near top',
        preview: 'tower',
        polyCount: 4900,
        price: 55,
        type: 'building',
        style: 'stylized',
        tags: ['wizard', 'tower', 'fantasy', 'magic'],
      },
      {
        id: 'ancient-temple',
        name: 'Ancient Temple',
        prompt: 'ancient Egyptian-style stone temple with large columns, hieroglyphic carvings on walls, broken stonework, sand-worn texture',
        preview: 'temple',
        polyCount: 9100,
        price: 85,
        type: 'building',
        style: 'realistic',
        tags: ['ancient', 'temple', 'egypt'],
      },
      {
        id: 'pirate-fort',
        name: 'Pirate Fort',
        prompt: 'wooden pirate fort with tall walls, cannon emplacements on top, skull-and-crossbones flag, rickety watchtower',
        preview: 'fort',
        polyCount: 6400,
        price: 65,
        type: 'building',
        style: 'stylized',
        tags: ['pirate', 'fort', 'ocean'],
      },
      {
        id: 'haunted-mansion',
        name: 'Haunted Mansion',
        prompt: 'Victorian haunted mansion with broken windows, overgrown vines, crumbling chimneys, iron gate entrance, dark atmosphere',
        preview: 'mansion',
        polyCount: 10200,
        price: 90,
        type: 'building',
        style: 'stylized',
        tags: ['haunted', 'mansion', 'horror', 'halloween'],
      },
      {
        id: 'neon-shop',
        name: 'Neon Arcade Shop',
        prompt: 'cyberpunk neon-lit arcade shop with flickering signs, glass display windows, graffiti-covered walls, futuristic Japanese aesthetic',
        preview: 'shop',
        polyCount: 5100,
        price: 58,
        type: 'building',
        style: 'stylized',
        tags: ['neon', 'cyberpunk', 'shop', 'arcade'],
      },
    ],
  },

  // ── Terrain (10) ────────────────────────────────────────────────────────────
  {
    name: 'Terrain',
    slug: 'terrain',
    icon: 'mountain',
    templates: [
      {
        id: 'rocky-cliff',
        name: 'Rocky Cliff',
        prompt: 'dramatic rocky cliff face with layered sedimentary rock, cracks, ledges for platforming, mossy patches',
        preview: 'cliff',
        polyCount: 3200,
        price: 35,
        type: 'terrain',
        style: 'realistic',
        tags: ['cliff', 'rock', 'nature'],
      },
      {
        id: 'floating-island',
        name: 'Floating Island',
        prompt: 'small floating island with grass on top, exposed dirt and rock underside, roots dangling below, cheerful fantasy look',
        preview: 'island',
        polyCount: 2800,
        price: 40,
        type: 'terrain',
        style: 'stylized',
        tags: ['floating', 'island', 'fantasy'],
      },
      {
        id: 'volcano',
        name: 'Volcano',
        prompt: 'active volcano cone with glowing lava streams running down channels, obsidian black rock, smoke venting from crater',
        preview: 'volcano',
        polyCount: 5500,
        price: 60,
        type: 'terrain',
        style: 'stylized',
        tags: ['volcano', 'lava', 'fire'],
      },
      {
        id: 'crystal-cave',
        name: 'Crystal Cave',
        prompt: 'cave interior with large hexagonal crystal formations growing from floor and ceiling, blue and purple tones, bioluminescent glow',
        preview: 'cave',
        polyCount: 4100,
        price: 50,
        type: 'terrain',
        style: 'stylized',
        tags: ['cave', 'crystal', 'underground'],
      },
      {
        id: 'mushroom-grove',
        name: 'Mushroom Grove',
        prompt: 'enchanted mushroom grove with oversized glowing mushrooms, twisted roots, fairy-tale atmosphere, soft ambient light',
        preview: 'mushroom',
        polyCount: 3700,
        price: 45,
        type: 'terrain',
        style: 'stylized',
        tags: ['mushroom', 'forest', 'fantasy'],
      },
      {
        id: 'desert-dunes',
        name: 'Desert Dunes',
        prompt: 'sweeping sand dunes in a desert landscape, wind-blown ripple patterns, sparse dead plants, sun-bleached bones',
        preview: 'desert',
        polyCount: 2400,
        price: 30,
        type: 'terrain',
        style: 'realistic',
        tags: ['desert', 'sand', 'dunes'],
      },
      {
        id: 'frozen-tundra',
        name: 'Frozen Tundra',
        prompt: 'frozen tundra terrain patch with cracked ice surface, embedded snow, exposed permafrost edges, aurora color palette',
        preview: 'tundra',
        polyCount: 2900,
        price: 35,
        type: 'terrain',
        style: 'realistic',
        tags: ['frozen', 'ice', 'tundra', 'snow'],
      },
      {
        id: 'underwater-reef',
        name: 'Underwater Reef',
        prompt: 'coral reef terrain piece with branching coral formations, sea anemones, colorful fish scales embedded, vibrant ocean floor',
        preview: 'reef',
        polyCount: 4800,
        price: 55,
        type: 'terrain',
        style: 'stylized',
        tags: ['underwater', 'reef', 'ocean', 'coral'],
      },
      {
        id: 'ancient-ruins',
        name: 'Ancient Ruins',
        prompt: 'crumbled stone ruins with fallen columns, overgrown grass and ivy, scattered stone blocks, archway still standing',
        preview: 'ruins',
        polyCount: 5200,
        price: 58,
        type: 'terrain',
        style: 'realistic',
        tags: ['ruins', 'ancient', 'stone'],
      },
      {
        id: 'cloud-platform',
        name: 'Cloud Platform',
        prompt: 'fluffy cloud platform suitable for sky-level gameplay, rounded edges, wispy trailing ends, soft white and light-blue tones',
        preview: 'cloud',
        polyCount: 1800,
        price: 28,
        type: 'terrain',
        style: 'stylized',
        tags: ['cloud', 'sky', 'platform'],
      },
    ],
  },

  // ── Vehicles (8) ────────────────────────────────────────────────────────────
  {
    name: 'Vehicles',
    slug: 'vehicles',
    icon: 'car',
    templates: [
      {
        id: 'sports-car',
        name: 'Sports Car',
        prompt: 'sleek sports car with aerodynamic body kit, low profile, spoiler, alloy wheels, tinted windows',
        preview: 'car',
        polyCount: 6200,
        price: 70,
        type: 'vehicle',
        style: 'stylized',
        tags: ['car', 'sports', 'racing'],
      },
      {
        id: 'pirate-ship',
        name: 'Pirate Ship',
        prompt: 'wooden pirate galleon with full sails, cannon ports along hull, crow\'s nest, weathered oak planks, anchor',
        preview: 'ship',
        polyCount: 8800,
        price: 85,
        type: 'vehicle',
        style: 'stylized',
        tags: ['pirate', 'ship', 'ocean', 'sail'],
      },
      {
        id: 'jet-fighter',
        name: 'Jet Fighter',
        prompt: 'sleek military jet fighter with delta wings, twin engine afterburners, missile hardpoints, cockpit canopy',
        preview: 'jet',
        polyCount: 5400,
        price: 65,
        type: 'vehicle',
        style: 'realistic',
        tags: ['jet', 'military', 'aircraft'],
      },
      {
        id: 'tank',
        name: 'Battle Tank',
        prompt: 'heavy battle tank with thick armored plating, large barrel cannon, tracks, reactive armor panels, military green paint',
        preview: 'tank',
        polyCount: 7100,
        price: 75,
        type: 'vehicle',
        style: 'realistic',
        tags: ['tank', 'military', 'armored'],
      },
      {
        id: 'motorcycle',
        name: 'Motorcycle',
        prompt: 'futuristic motorcycle with neon-lit frame, sleek body panels, exposed engine, racing handlebars',
        preview: 'motorcycle',
        polyCount: 4300,
        price: 55,
        type: 'vehicle',
        style: 'stylized',
        tags: ['motorcycle', 'neon', 'racing'],
      },
      {
        id: 'spaceship',
        name: 'Spaceship',
        prompt: 'compact sci-fi spaceship with curved hull, engine pods, cockpit dome, laser cannon mount, landing struts',
        preview: 'spaceship',
        polyCount: 5900,
        price: 68,
        type: 'vehicle',
        style: 'stylized',
        tags: ['spaceship', 'scifi', 'space'],
      },
      {
        id: 'hot-air-balloon',
        name: 'Hot Air Balloon',
        prompt: 'colorful hot air balloon with striped envelope, wicker basket, rope netting, brazier with visible flame',
        preview: 'balloon',
        polyCount: 2900,
        price: 38,
        type: 'vehicle',
        style: 'stylized',
        tags: ['balloon', 'sky', 'exploration'],
      },
      {
        id: 'dirt-bike',
        name: 'Dirt Bike',
        prompt: 'rugged off-road dirt bike with knobby tires, reinforced frame, suspension forks, splattered mud details',
        preview: 'dirtbike',
        polyCount: 3800,
        price: 48,
        type: 'vehicle',
        style: 'roblox',
        tags: ['dirt-bike', 'offroad', 'sports'],
      },
    ],
  },

  // ── Characters (8) ──────────────────────────────────────────────────────────
  {
    name: 'Characters',
    slug: 'characters',
    icon: 'person',
    templates: [
      {
        id: 'knight',
        name: 'Knight',
        prompt: 'medieval knight in full plate armor with a visor helmet, shield on arm, sword at side, cape, T-pose',
        preview: 'knight',
        polyCount: 7800,
        price: 90,
        type: 'character',
        style: 'stylized',
        tags: ['knight', 'medieval', 'armor'],
      },
      {
        id: 'mage',
        name: 'Mage',
        prompt: 'fantasy mage in flowing robes with arcane staff, pointy hat, glowing rune details on clothing, T-pose',
        preview: 'mage',
        polyCount: 6400,
        price: 80,
        type: 'character',
        style: 'stylized',
        tags: ['mage', 'wizard', 'fantasy', 'magic'],
      },
      {
        id: 'robot',
        name: 'Robot',
        prompt: 'boxy retro robot with glowing eyes, mechanical joints, antenna on head, chest display panel, T-pose',
        preview: 'robot',
        polyCount: 5200,
        price: 75,
        type: 'character',
        style: 'roblox',
        tags: ['robot', 'scifi', 'mechanical'],
      },
      {
        id: 'pirate',
        name: 'Pirate',
        prompt: 'swashbuckling pirate with tricorn hat, eyepatch, hook hand, long coat, knee boots, T-pose',
        preview: 'pirate',
        polyCount: 6100,
        price: 78,
        type: 'character',
        style: 'stylized',
        tags: ['pirate', 'adventure', 'ocean'],
      },
      {
        id: 'alien',
        name: 'Alien',
        prompt: 'friendly cartoon alien with large head, big black eyes, slim body, four fingers, subtle bioluminescent markings, T-pose',
        preview: 'alien',
        polyCount: 4800,
        price: 70,
        type: 'character',
        style: 'stylized',
        tags: ['alien', 'scifi', 'space'],
      },
      {
        id: 'ninja',
        name: 'Ninja',
        prompt: 'sleek ninja in black tactical outfit, mask covering lower face, throwing stars on belt, katana strapped to back, T-pose',
        preview: 'ninja',
        polyCount: 5500,
        price: 72,
        type: 'character',
        style: 'roblox',
        tags: ['ninja', 'stealth', 'martial-arts'],
      },
      {
        id: 'zombie',
        name: 'Zombie',
        prompt: 'shambling zombie with torn clothing, rotting skin patches, outstretched arms, blank eyes, T-pose',
        preview: 'zombie',
        polyCount: 5900,
        price: 74,
        type: 'character',
        style: 'stylized',
        tags: ['zombie', 'horror', 'undead'],
      },
      {
        id: 'elf-archer',
        name: 'Elf Archer',
        prompt: 'agile elf archer with leaf-green cloak, longbow in hand, quiver on back, pointed ears, forest guardian attire, T-pose',
        preview: 'elf',
        polyCount: 6800,
        price: 82,
        type: 'character',
        style: 'stylized',
        tags: ['elf', 'archer', 'fantasy', 'forest'],
      },
    ],
  },

  // ── Weapons (8) ─────────────────────────────────────────────────────────────
  {
    name: 'Weapons',
    slug: 'weapons',
    icon: 'sword',
    templates: [
      {
        id: 'great-sword',
        name: 'Great Sword',
        prompt: 'large two-handed great sword with ornate crossguard, runes etched on the blade, wrapped leather grip',
        preview: 'sword',
        polyCount: 1800,
        price: 35,
        type: 'weapon',
        style: 'stylized',
        tags: ['sword', 'melee', 'fantasy'],
      },
      {
        id: 'magic-staff',
        name: 'Magic Staff',
        prompt: 'wooden wizard staff with glowing crystal orb at top, wrapped vines, arcane symbols carved into the shaft',
        preview: 'staff',
        polyCount: 2100,
        price: 38,
        type: 'weapon',
        style: 'stylized',
        tags: ['staff', 'magic', 'fantasy'],
      },
      {
        id: 'laser-rifle',
        name: 'Laser Rifle',
        prompt: 'futuristic energy laser rifle with glowing barrel, scope, cooling vents, ergonomic grip, sci-fi design',
        preview: 'rifle',
        polyCount: 2600,
        price: 42,
        type: 'weapon',
        style: 'stylized',
        tags: ['gun', 'scifi', 'laser'],
      },
      {
        id: 'battle-axe',
        name: 'Battle Axe',
        prompt: 'double-headed battle axe with rune-carved blades, thick wooden handle wrapped in leather, bronze fittings',
        preview: 'axe',
        polyCount: 2000,
        price: 36,
        type: 'weapon',
        style: 'roblox',
        tags: ['axe', 'melee', 'medieval'],
      },
      {
        id: 'bow',
        name: 'Elven Bow',
        prompt: 'elegant elven recurve bow with carved leaf motifs, string glowing faintly, graceful curved limbs',
        preview: 'bow',
        polyCount: 1600,
        price: 32,
        type: 'weapon',
        style: 'stylized',
        tags: ['bow', 'ranged', 'fantasy', 'elf'],
      },
      {
        id: 'flail',
        name: 'Spiked Flail',
        prompt: 'medieval flail with spiked iron ball on chain, wooden handle, battle-worn metal',
        preview: 'flail',
        polyCount: 2200,
        price: 38,
        type: 'weapon',
        style: 'roblox',
        tags: ['flail', 'medieval', 'melee'],
      },
      {
        id: 'rocket-launcher',
        name: 'Rocket Launcher',
        prompt: 'shoulder-mounted rocket launcher, cylindrical barrel, targeting sight, rugged military design',
        preview: 'launcher',
        polyCount: 2800,
        price: 44,
        type: 'weapon',
        style: 'realistic',
        tags: ['rocket', 'military', 'explosive'],
      },
      {
        id: 'shadow-dagger',
        name: 'Shadow Dagger',
        prompt: 'sleek assassin dagger with black blade, shadow energy wisps curling off it, wrapped dark handle, subtle purple glow',
        preview: 'dagger',
        polyCount: 1400,
        price: 30,
        type: 'weapon',
        style: 'stylized',
        tags: ['dagger', 'assassin', 'magic', 'shadow'],
      },
    ],
  },

  // ── Furniture (8) ───────────────────────────────────────────────────────────
  {
    name: 'Furniture',
    slug: 'furniture',
    icon: 'chair',
    templates: [
      {
        id: 'throne',
        name: 'Royal Throne',
        prompt: 'ornate royal throne with red velvet cushion, gold carved armrests, tall back with crown motif, gem inlays',
        preview: 'throne',
        polyCount: 3200,
        price: 45,
        type: 'furniture',
        style: 'stylized',
        tags: ['throne', 'royal', 'medieval'],
      },
      {
        id: 'medieval-table',
        name: 'Medieval Table',
        prompt: 'heavy oak dining table with rough-hewn surface, iron bolt fittings, bench seating on each side, candelabra on top',
        preview: 'table',
        polyCount: 2400,
        price: 35,
        type: 'furniture',
        style: 'stylized',
        tags: ['table', 'medieval', 'dining'],
      },
      {
        id: 'futuristic-desk',
        name: 'Futuristic Desk',
        prompt: 'sleek futuristic holographic workstation desk, floating display panels, built-in keyboard, glowing interface, minimalist white and chrome',
        preview: 'desk',
        polyCount: 3800,
        price: 50,
        type: 'furniture',
        style: 'stylized',
        tags: ['desk', 'scifi', 'futuristic'],
      },
      {
        id: 'treasure-chest',
        name: 'Treasure Chest',
        prompt: 'wooden treasure chest with iron lock, studded lid, gold trim, slightly open revealing glowing contents',
        preview: 'chest',
        polyCount: 1800,
        price: 28,
        type: 'furniture',
        style: 'roblox',
        tags: ['chest', 'treasure', 'fantasy'],
      },
      {
        id: 'bookshelf',
        name: 'Wizard Bookshelf',
        prompt: 'tall wooden wizard bookshelf packed with colorful spell books, floating orbs, scrolls, a few books hovering mid-air',
        preview: 'bookshelf',
        polyCount: 4100,
        price: 52,
        type: 'furniture',
        style: 'stylized',
        tags: ['bookshelf', 'wizard', 'fantasy'],
      },
      {
        id: 'arcade-cabinet',
        name: 'Arcade Cabinet',
        prompt: 'retro arcade game cabinet with glowing screen, joystick and buttons, coin slot, neon side panel artwork',
        preview: 'arcade',
        polyCount: 2900,
        price: 40,
        type: 'furniture',
        style: 'stylized',
        tags: ['arcade', 'game', 'retro', 'neon'],
      },
      {
        id: 'campfire',
        name: 'Campfire',
        prompt: 'stone-ringed campfire with crackling logs, glowing ember base, smoke particles above, warm orange flames',
        preview: 'campfire',
        polyCount: 1600,
        price: 25,
        type: 'furniture',
        style: 'stylized',
        tags: ['campfire', 'fire', 'outdoor'],
      },
      {
        id: 'laboratory-bench',
        name: 'Laboratory Bench',
        prompt: 'mad scientist laboratory bench with bubbling beakers, coiled tubes, sparking Tesla coil, monitor with code readout',
        preview: 'lab',
        polyCount: 3600,
        price: 48,
        type: 'furniture',
        style: 'stylized',
        tags: ['lab', 'science', 'mad-scientist'],
      },
    ],
  },

  // ── Props (8) ────────────────────────────────────────────────────────────────
  {
    name: 'Props',
    slug: 'props',
    icon: 'box',
    templates: [
      {
        id: 'potion-bottle',
        name: 'Potion Bottle',
        prompt: 'glass potion bottle with cork stopper, glowing liquid inside, label with arcane symbol, floating sparkles',
        preview: 'potion',
        polyCount: 800,
        price: 18,
        type: 'prop',
        style: 'stylized',
        tags: ['potion', 'magic', 'item'],
      },
      {
        id: 'crate',
        name: 'Wooden Crate',
        prompt: 'wooden shipping crate with metal corner reinforcements, rope handle on lid, stenciled label on side',
        preview: 'crate',
        polyCount: 600,
        price: 12,
        type: 'prop',
        style: 'roblox',
        tags: ['crate', 'wooden', 'storage'],
      },
      {
        id: 'portal-gate',
        name: 'Portal Gate',
        prompt: 'mystical stone portal archway with swirling energy vortex inside, rune carvings on frame, magical glow',
        preview: 'portal',
        polyCount: 2800,
        price: 40,
        type: 'prop',
        style: 'stylized',
        tags: ['portal', 'magic', 'gate', 'fantasy'],
      },
      {
        id: 'gem-crystal',
        name: 'Gem Crystal',
        prompt: 'large faceted gemstone crystal growing from a rock base, deep red color, internal light refraction, sharp angular faces',
        preview: 'gem',
        polyCount: 1200,
        price: 22,
        type: 'prop',
        style: 'stylized',
        tags: ['gem', 'crystal', 'collectible'],
      },
      {
        id: 'lantern',
        name: 'Hanging Lantern',
        prompt: 'old iron hanging lantern with glass panels, warm candle flame inside, chain attachment at top, ornate metalwork',
        preview: 'lantern',
        polyCount: 1400,
        price: 24,
        type: 'prop',
        style: 'stylized',
        tags: ['lantern', 'light', 'medieval'],
      },
      {
        id: 'signpost',
        name: 'Signpost',
        prompt: 'weathered wooden signpost with multiple arrow-shaped signs pointing different directions, carved lettering, dug into ground',
        preview: 'sign',
        polyCount: 900,
        price: 16,
        type: 'prop',
        style: 'roblox',
        tags: ['sign', 'navigation', 'prop'],
      },
      {
        id: 'bomb',
        name: 'Cartoon Bomb',
        prompt: 'classic cartoon round bomb with lit fuse, shiny black surface, white skull and crossbones sticker',
        preview: 'bomb',
        polyCount: 700,
        price: 14,
        type: 'prop',
        style: 'roblox',
        tags: ['bomb', 'cartoon', 'explosive'],
      },
      {
        id: 'coin-stack',
        name: 'Gold Coin Stack',
        prompt: 'stack of gold coins with embossed crown symbol, shiny metallic surface, a few coins scattered around base',
        preview: 'coins',
        polyCount: 1100,
        price: 20,
        type: 'prop',
        style: 'stylized',
        tags: ['coins', 'gold', 'currency', 'reward'],
      },
    ],
  },

  // ── Effects (5) ──────────────────────────────────────────────────────────────
  {
    name: 'Effects',
    slug: 'effects',
    icon: 'sparkles',
    templates: [
      {
        id: 'explosion-base',
        name: 'Explosion Base',
        prompt: 'explosion burst emitter base, stylized fireball, concentric shock wave ring, stylized cartoon smoke puffs',
        preview: 'explosion',
        polyCount: 1200,
        price: 30,
        type: 'effect',
        style: 'stylized',
        tags: ['explosion', 'vfx', 'fire'],
      },
      {
        id: 'magic-circle',
        name: 'Magic Circle',
        prompt: 'flat glowing magic summoning circle with runes and symbols, layered rings, star of David geometry, arcane energy shimmering',
        preview: 'circle',
        polyCount: 1800,
        price: 35,
        type: 'effect',
        style: 'stylized',
        tags: ['magic', 'circle', 'rune', 'summon'],
      },
      {
        id: 'tornado',
        name: 'Tornado',
        prompt: 'swirling tornado funnel mesh, debris particles embedded, tapered at base, wide at top, turbulent surface detail',
        preview: 'tornado',
        polyCount: 2200,
        price: 38,
        type: 'effect',
        style: 'stylized',
        tags: ['tornado', 'wind', 'weather'],
      },
      {
        id: 'lightning-bolt',
        name: 'Lightning Bolt',
        prompt: 'jagged stylized lightning bolt shape, branching secondary bolts, glowing electric blue, frozen-in-time strike pose',
        preview: 'lightning',
        polyCount: 900,
        price: 22,
        type: 'effect',
        style: 'stylized',
        tags: ['lightning', 'electric', 'storm'],
      },
      {
        id: 'black-hole',
        name: 'Black Hole',
        prompt: 'miniature black hole sphere with accretion disc ring, distortion warping around edges, dark purple and white glow',
        preview: 'blackhole',
        polyCount: 2600,
        price: 42,
        type: 'effect',
        style: 'stylized',
        tags: ['blackhole', 'space', 'gravity', 'scifi'],
      },
    ],
  },
]

// ── Handler ───────────────────────────────────────────────────────────────────

export async function GET(req: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(req.url)
  const categoryFilter   = searchParams.get('category')?.toLowerCase()
  const limitParam       = searchParams.get('limit')
  const limit            = limitParam ? Math.min(parseInt(limitParam, 10) || 100, 200) : undefined

  let categories = TEMPLATE_CATEGORIES

  if (categoryFilter) {
    categories = categories.filter((c) => c.slug === categoryFilter)
    if (categories.length === 0) {
      return NextResponse.json(
        { error: `Category "${categoryFilter}" not found`, validCategories: TEMPLATE_CATEGORIES.map((c) => c.slug) },
        { status: 404 },
      )
    }
  }

  // Apply per-template limit if requested
  if (limit !== undefined) {
    categories = categories.map((cat) => ({
      ...cat,
      templates: cat.templates.slice(0, limit),
    }))
  }

  const totalTemplates = categories.reduce((sum, c) => sum + c.templates.length, 0)

  return NextResponse.json({
    categories,
    meta: {
      totalCategories: categories.length,
      totalTemplates,
      availableCategories: TEMPLATE_CATEGORIES.map((c) => ({ slug: c.slug, name: c.name, icon: c.icon, count: c.templates.length })),
    },
  })
}
