#!/usr/bin/env node
/**
 * Terrain Forge MCP Server — port 3004
 *
 * Tools:
 *   generate-terrain  → Biome + size + features → Roblox Luau terrain script (FillBlock/FillBall/WriteVoxels)
 *   paint-terrain     → Material + region → Luau terrain painting script
 *   create-water      → Water type + position → Luau water creation script
 *
 * All tools output executable Roblox Luau code that creates real terrain when run via the Studio plugin.
 * Transport: StreamableHTTP over Node http on /mcp
 * Auth:      ANTHROPIC_API_KEY from process.env (used for biome metadata enrichment)
 */

import { createServer, IncomingMessage, ServerResponse } from 'node:http'
import { randomUUID } from 'node:crypto'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js'
import { isInitializeRequest } from '@modelcontextprotocol/sdk/types.js'
import Anthropic from '@anthropic-ai/sdk'
import { z } from 'zod'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PORT = Number(process.env.TERRAIN_FORGE_PORT ?? 3004)

// ---------------------------------------------------------------------------
// Anthropic client
// ---------------------------------------------------------------------------

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY ?? '' })
const CLAUDE_MODEL = 'claude-3-5-sonnet-20241022'

function meterUsage(tool: string, inputTokens: number, outputTokens: number): void {
  const costUsd = (inputTokens / 1_000_000) * 3.0 + (outputTokens / 1_000_000) * 15.0
  process.stderr.write(
    `[terrain-forge] ${tool}: ${inputTokens}in/${outputTokens}out ($${costUsd.toFixed(6)})\n`,
  )
}

// ---------------------------------------------------------------------------
// Terrain data types
// ---------------------------------------------------------------------------
interface HeightmapPoint {
  x: number
  z: number
  height: number
  material: string
}

interface TerrainRegion {
  x: number
  z: number
  width: number
  height: number
}

interface MaterialMap {
  region: TerrainRegion
  materials: Array<{
    x: number
    z: number
    material: string
    color?: string
  }>
}

// ---------------------------------------------------------------------------
// Roblox material list
// ---------------------------------------------------------------------------
const ROBLOX_MATERIALS = [
  'Grass', 'Dirt', 'Sand', 'Rock', 'Sandstone', 'Snow', 'Mud',
  'WoodPlanks', 'SmoothPlastic', 'LeafyGrass', 'Asphalt', 'Cobblestone',
  'Ice', 'Water', 'Ground', 'Limestone', 'Basalt', 'Glacier',
  'Slate', 'CrackedLava', 'Salt', 'Concrete', 'Fabric',
]

// ---------------------------------------------------------------------------
// Biome → default material mapping
// ---------------------------------------------------------------------------
const BIOME_MATERIALS: Record<string, string[]> = {
  forest: ['LeafyGrass', 'Grass', 'Dirt', 'Mud'],
  desert: ['Sand', 'Sandstone', 'Salt', 'Rock'],
  arctic: ['Snow', 'Ice', 'Glacier', 'Rock'],
  volcanic: ['CrackedLava', 'Basalt', 'Rock', 'Slate'],
  ocean: ['Water', 'Sand', 'Rock', 'Limestone'],
  swamp: ['Mud', 'Grass', 'LeafyGrass', 'Dirt'],
  mountains: ['Rock', 'Slate', 'Snow', 'Limestone'],
  plains: ['Grass', 'Ground', 'Dirt', 'LeafyGrass'],
  urban: ['Concrete', 'Asphalt', 'Cobblestone', 'WoodPlanks'],
}

// ---------------------------------------------------------------------------
// Luau code generators — produce executable Roblox scripts
// ---------------------------------------------------------------------------

/**
 * Returns the Enum.Material string Luau expression for a material name.
 */
function luauMaterial(mat: string): string {
  // Roblox Terrain materials use Enum.Material.<Name>
  const valid = new Set(ROBLOX_MATERIALS)
  const resolved = valid.has(mat) ? mat : 'Grass'
  return `Enum.Material.${resolved}`
}

/**
 * Generates a Luau script that fills the terrain with FillBlock/FillBall calls
 * based on a heightmap. The script is meant to be run via the Studio command bar
 * or the ForjeGames Studio plugin.
 */
function generateTerrainLuau(params: {
  heightmap: HeightmapPoint[]
  originX: number
  originY: number
  originZ: number
  voxelSize: number
  biome: string
  waterLevel: number | null
}): string {
  const { heightmap, originX, originY, originZ, voxelSize, biome, waterLevel } = params

  const lines: string[] = [
    `-- Generated by ForjeGames Terrain Forge`,
    `-- Biome: ${biome}`,
    `-- Points: ${heightmap.length}`,
    `local terrain = workspace.Terrain`,
    `local vs = ${voxelSize} -- voxel size in studs`,
    ``,
    `-- Fill base terrain layer`,
    `terrain:Clear()`,
    ``,
  ]

  for (const pt of heightmap) {
    const worldX = originX + pt.x
    const worldY = originY + pt.height
    const worldZ = originZ + pt.z
    const mat = luauMaterial(pt.material)
    const blockH = Math.max(4, pt.height)
    lines.push(
      `terrain:FillBlock(CFrame.new(${worldX}, ${originY + blockH / 2}, ${worldZ}), ` +
        `Vector3.new(vs, ${blockH}, vs), ${mat})`,
    )
  }

  // Optional water layer
  if (waterLevel !== null && waterLevel > 0) {
    lines.push(``)
    lines.push(`-- Water layer at elevation ${waterLevel}`)
    for (const pt of heightmap) {
      if (pt.height < waterLevel) {
        const worldX = originX + pt.x
        const worldZ = originZ + pt.z
        const waterH = waterLevel - pt.height
        lines.push(
          `terrain:FillBlock(CFrame.new(${worldX}, ${originY + waterLevel - waterH / 2}, ${worldZ}), ` +
            `Vector3.new(vs, ${waterH}, vs), Enum.Material.Water)`,
        )
      }
    }
  }

  lines.push(``)
  lines.push(`print("[TerrainForge] Terrain generation complete — ${heightmap.length} voxels placed")`)
  return lines.join('\n')
}

/**
 * Generates a Luau script that paints a terrain region with a given material.
 * Uses Terrain:FillBlock on a grid of voxels within the region.
 */
function generatePaintTerrainLuau(params: {
  region: TerrainRegion
  material: string
  originX: number
  originY: number
  originZ: number
  voxelSize: number
  terrainHeight: number
}): string {
  const { region, material, originX, originY, originZ, voxelSize, terrainHeight } = params
  const mat = luauMaterial(material)

  const lines: string[] = [
    `-- Generated by ForjeGames Terrain Forge — Paint: ${material}`,
    `local terrain = workspace.Terrain`,
    `local vs = ${voxelSize}`,
    ``,
  ]

  for (let z = region.z; z < region.z + region.height; z += voxelSize) {
    for (let x = region.x; x < region.x + region.width; x += voxelSize) {
      const worldX = originX + x
      const worldZ = originZ + z
      lines.push(
        `terrain:FillBlock(CFrame.new(${worldX}, ${originY + terrainHeight / 2}, ${worldZ}), ` +
          `Vector3.new(vs, ${terrainHeight}, vs), ${mat})`,
      )
    }
  }

  lines.push(``)
  lines.push(`print("[TerrainForge] Paint complete — material: ${material}")`)
  return lines.join('\n')
}

/**
 * Generates a Luau script that creates water terrain in a region.
 * Supports ocean (fills flat), river (linear strip), and lake (FillBall).
 */
function generateWaterLuau(params: {
  waterType: 'ocean' | 'river' | 'lake'
  x: number
  y: number
  z: number
  width: number
  depth: number
  length: number
}): string {
  const { waterType, x, y, z, width, depth, length } = params

  const lines: string[] = [
    `-- Generated by ForjeGames Terrain Forge — Water: ${waterType}`,
    `local terrain = workspace.Terrain`,
    ``,
  ]

  if (waterType === 'ocean' || waterType === 'river') {
    // FillBlock for flat water bodies
    const cx = x + width / 2
    const cy = y - depth / 2
    const cz = z + length / 2
    lines.push(
      `terrain:FillBlock(`,
      `  CFrame.new(${cx}, ${cy}, ${cz}),`,
      `  Vector3.new(${width}, ${depth}, ${length}),`,
      `  Enum.Material.Water`,
      `)`,
    )
    if (waterType === 'ocean') {
      // Also fill the sea bed with Sand
      lines.push(``)
      lines.push(
        `terrain:FillBlock(`,
        `  CFrame.new(${cx}, ${cy - depth}, ${cz}),`,
        `  Vector3.new(${width}, ${depth}, ${length}),`,
        `  Enum.Material.Sand`,
        `)`,
      )
    }
  } else {
    // Lake — FillBall for natural round shape
    const radius = Math.min(width, length) / 2
    lines.push(
      `terrain:FillBall(`,
      `  Vector3.new(${x + width / 2}, ${y - radius * 0.4}, ${z + length / 2}),`,
      `  ${radius},`,
      `  Enum.Material.Water`,
      `)`,
    )
    // Slightly larger rock basin underneath
    lines.push(``)
    lines.push(
      `terrain:FillBall(`,
      `  Vector3.new(${x + width / 2}, ${y - radius * 0.9}, ${z + length / 2}),`,
      `  ${radius * 1.1},`,
      `  Enum.Material.Rock`,
      `)`,
    )
  }

  lines.push(``)
  lines.push(`print("[TerrainForge] Water (${waterType}) placed at ${x}, ${y}, ${z}")`)
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Claude biome enrichment (optional — degrades gracefully)
// ---------------------------------------------------------------------------

interface BiomeMeta {
  biome: string
  elevationProfile: string
  baseElevation: number
  elevationVariance: number
  primaryMaterial: string
  secondaryMaterial: string
  features: string[]
  waterLevel: number | null
}

async function getBiomeMeta(description: string): Promise<BiomeMeta> {
  if (!process.env.ANTHROPIC_API_KEY) {
    // Fallback: infer from keywords
    const lower = description.toLowerCase()
    const biome =
      lower.includes('snow') || lower.includes('arctic') ? 'arctic' :
      lower.includes('desert') || lower.includes('sand') ? 'desert' :
      lower.includes('ocean') || lower.includes('sea') ? 'ocean' :
      lower.includes('mountain') ? 'mountains' :
      lower.includes('volcano') || lower.includes('lava') ? 'volcanic' :
      lower.includes('swamp') || lower.includes('marsh') ? 'swamp' :
      lower.includes('city') || lower.includes('urban') ? 'urban' :
      'forest'

    const mats = BIOME_MATERIALS[biome] ?? BIOME_MATERIALS['forest']!
    return {
      biome,
      elevationProfile: biome === 'mountains' ? 'mountainous' : biome === 'desert' ? 'flat' : 'rolling',
      baseElevation: biome === 'ocean' ? 10 : 40,
      elevationVariance: biome === 'mountains' ? 40 : 15,
      primaryMaterial: mats[0]!,
      secondaryMaterial: mats[1] ?? 'Rock',
      features: [],
      waterLevel: biome === 'ocean' ? 30 : biome === 'swamp' ? 25 : null,
    }
  }

  const response = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 600,
    system: `You are a Roblox terrain generation engine. Given a biome description, output ONLY valid JSON:
{
  "biome": string,
  "elevationProfile": "flat"|"rolling"|"hilly"|"mountainous",
  "baseElevation": number,
  "elevationVariance": number,
  "primaryMaterial": string,
  "secondaryMaterial": string,
  "features": string[],
  "waterLevel": number|null
}
Valid materials: ${ROBLOX_MATERIALS.join(', ')}`,
    messages: [{ role: 'user', content: description }],
  })

  meterUsage('get-biome-meta', response.usage.input_tokens, response.usage.output_tokens)

  const raw = response.content
    .filter((b) => b.type === 'text')
    .map((b) => (b as Anthropic.TextBlock).text)
    .join('')

  try {
    return JSON.parse(raw) as BiomeMeta
  } catch {
    const match = raw.match(/```(?:json)?\s*([\s\S]+?)```/)
    if (match) return JSON.parse(match[1]) as BiomeMeta
    // Final fallback
    const mats = BIOME_MATERIALS['forest']!
    return {
      biome: 'forest',
      elevationProfile: 'rolling',
      baseElevation: 40,
      elevationVariance: 15,
      primaryMaterial: mats[0]!,
      secondaryMaterial: mats[1] ?? 'Rock',
      features: [],
      waterLevel: null,
    }
  }
}

// ---------------------------------------------------------------------------
// MCP server — tool registration
// ---------------------------------------------------------------------------

function buildMcpServer(): McpServer {
  const mcp = new McpServer({ name: 'terrain-forge', version: '1.0.0' })

  // ── generate-terrain ────────────────────────────────────────────────────────

  mcp.registerTool(
    'generate-terrain',
    {
      title: 'Generate Terrain',
      description:
        'Generate a Roblox Luau script that creates terrain using Terrain:FillBlock and FillBall. Pass the returned luauScript to the Studio plugin to instantly create the terrain.',
      inputSchema: z.object({
        biome: z
          .string()
          .min(2)
          .describe('Biome description (e.g. "snowy mountain range with frozen lake", "tropical jungle")'),
        size: z
          .object({ width: z.number().default(512), depth: z.number().default(512) })
          .default({ width: 512, depth: 512 })
          .describe('Terrain footprint in studs'),
        features: z
          .array(z.string())
          .default([])
          .describe('Additional features (e.g. ["river", "cliffs", "volcanic vents"])'),
        originX: z.number().default(0).describe('World X origin in studs'),
        originY: z.number().default(0).describe('World Y origin in studs'),
        originZ: z.number().default(0).describe('World Z origin in studs'),
        voxelSize: z.number().int().default(4).describe('Voxel size in studs (4 = default Roblox terrain)'),
        seed: z.number().optional().describe('Seed for reproducible noise'),
      }),
    },
    async ({ biome, size, features, originX, originY, originZ, voxelSize, seed }) => {
      const meta = await getBiomeMeta(
        features.length > 0 ? `${biome}, features: ${features.join(', ')}` : biome,
      )

      const rng = createRng(seed ?? Date.now())
      const gridSize = Math.floor(Math.min(size.width, size.depth) / voxelSize)
      const clampedGrid = Math.min(gridSize, 64) // cap at 64×64 to keep script size sane
      const heightmap: HeightmapPoint[] = []

      for (let gz = 0; gz < clampedGrid; gz++) {
        for (let gx = 0; gx < clampedGrid; gx++) {
          const nx = gx / clampedGrid
          const nz = gz / clampedGrid
          let elevation = meta.baseElevation + noiseOctaves(rng, nx, nz, meta.elevationProfile) * meta.elevationVariance
          elevation = Math.max(4, Math.min(100, elevation))

          const biomeDefaults = BIOME_MATERIALS[meta.biome] ?? BIOME_MATERIALS['forest']!
          let material: string
          if (meta.waterLevel !== null && elevation < meta.waterLevel) {
            material = 'Water'
          } else if (elevation > 80) {
            material = meta.biome === 'arctic' ? 'Glacier' : 'Rock'
          } else if (elevation > 60) {
            material = meta.secondaryMaterial ?? biomeDefaults[1] ?? 'Rock'
          } else {
            material = meta.primaryMaterial ?? biomeDefaults[0] ?? 'Grass'
          }

          heightmap.push({
            x: Math.round((gx / clampedGrid) * size.width),
            z: Math.round((gz / clampedGrid) * size.depth),
            height: Math.round(elevation * 10) / 10,
            material,
          })
        }
      }

      const luauScript = generateTerrainLuau({
        heightmap,
        originX,
        originY,
        originZ,
        voxelSize,
        biome: meta.biome,
        waterLevel: meta.waterLevel,
      })

      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify({
              luauScript,
              meta,
              voxelCount: heightmap.length,
              gridSize: clampedGrid,
              size,
              seed: seed ?? null,
            }),
          },
        ],
      }
    },
  )

  // ── paint-terrain ───────────────────────────────────────────────────────────

  mcp.registerTool(
    'paint-terrain',
    {
      title: 'Paint Terrain',
      description:
        'Generate a Roblox Luau script that paints a rectangular region of terrain with a specified Roblox material using Terrain:FillBlock.',
      inputSchema: z.object({
        material: z
          .string()
          .describe(`Roblox terrain material. Valid: ${ROBLOX_MATERIALS.join(', ')}`),
        region: z.object({
          x: z.number().describe('Region X start in studs'),
          z: z.number().describe('Region Z start in studs'),
          width: z.number().describe('Region width in studs'),
          height: z.number().describe('Region height (Z depth) in studs'),
        }),
        originX: z.number().default(0),
        originY: z.number().default(0),
        originZ: z.number().default(0),
        voxelSize: z.number().int().default(4),
        terrainHeight: z.number().default(20).describe('Height of each painted voxel column in studs'),
      }),
    },
    async ({ material, region, originX, originY, originZ, voxelSize, terrainHeight }) => {
      if (!ROBLOX_MATERIALS.includes(material)) {
        throw new Error(`Invalid material "${material}". Valid: ${ROBLOX_MATERIALS.join(', ')}`)
      }

      const luauScript = generatePaintTerrainLuau({
        region,
        material,
        originX,
        originY,
        originZ,
        voxelSize,
        terrainHeight,
      })

      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify({ luauScript, material, region, voxelSize }),
          },
        ],
      }
    },
  )

  // ── create-water ────────────────────────────────────────────────────────────

  mcp.registerTool(
    'create-water',
    {
      title: 'Create Water',
      description:
        'Generate a Roblox Luau script that creates water terrain using Terrain:FillBlock (ocean/river) or Terrain:FillBall (lake).',
      inputSchema: z.object({
        waterType: z
          .enum(['ocean', 'river', 'lake'])
          .describe('Type of water body to create'),
        x: z.number().default(0).describe('World X position in studs'),
        y: z.number().default(0).describe('World Y position (water surface) in studs'),
        z: z.number().default(0).describe('World Z position in studs'),
        width: z.number().default(256).describe('Water width in studs (X axis)'),
        depth: z.number().default(20).describe('Water depth in studs'),
        length: z.number().default(256).describe('Water length in studs (Z axis)'),
      }),
    },
    async ({ waterType, x, y, z, width, depth, length }) => {
      const luauScript = generateWaterLuau({ waterType, x, y, z, width, depth, length })
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify({ luauScript, waterType, x, y, z, width, depth, length }),
          },
        ],
      }
    },
  )

  return mcp
}

// ---------------------------------------------------------------------------
// HTTP server — StreamableHTTP transport
// ---------------------------------------------------------------------------

const mcpServer = buildMcpServer()
const transports = new Map<string, StreamableHTTPServerTransport>()

async function readBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let raw = ''
    req.setEncoding('utf8')
    req.on('data', (chunk: string) => { raw += chunk })
    req.on('end', () => {
      try { resolve(JSON.parse(raw)) } catch { resolve(undefined) }
    })
    req.on('error', reject)
  })
}

function sendJson(res: ServerResponse, statusCode: number, body: unknown): void {
  const payload = JSON.stringify(body)
  res.writeHead(statusCode, {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(payload),
  })
  res.end(payload)
}

const httpServer = createServer(async (req: IncomingMessage, res: ServerResponse) => {
  if (req.url === '/health' && req.method === 'GET') {
    sendJson(res, 200, { status: 'ok', server: 'terrain-forge', port: PORT })
    return
  }

  if (req.url !== '/mcp') {
    sendJson(res, 404, { error: 'Not found. POST /mcp or GET /health' })
    return
  }

  try {
    if (req.method === 'POST') {
      const body = await readBody(req)
      const sessionId = req.headers['mcp-session-id'] as string | undefined

      if (sessionId && transports.has(sessionId)) {
        await transports.get(sessionId)!.handleRequest(req, res, body)
        return
      }

      if (!sessionId && isInitializeRequest(body)) {
        const transport = new StreamableHTTPServerTransport({
          sessionIdGenerator: () => randomUUID(),
          onsessioninitialized: (id) => { transports.set(id, transport) },
        })
        transport.onclose = () => {
          if (transport.sessionId) transports.delete(transport.sessionId)
        }
        await mcpServer.connect(transport)
        await transport.handleRequest(req, res, body)
        return
      }

      // Stateless (used by mcp-client.ts)
      const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined })
      await mcpServer.connect(transport)
      await transport.handleRequest(req, res, body)
      return
    }

    if (req.method === 'GET') {
      const sessionId = req.headers['mcp-session-id'] as string | undefined
      if (sessionId && transports.has(sessionId)) {
        await transports.get(sessionId)!.handleRequest(req, res)
        return
      }
      sendJson(res, 400, { jsonrpc: '2.0', error: { code: -32000, message: 'Invalid session' }, id: null })
      return
    }

    if (req.method === 'DELETE') {
      const sessionId = req.headers['mcp-session-id'] as string | undefined
      if (sessionId && transports.has(sessionId)) {
        await transports.get(sessionId)!.handleRequest(req, res)
        transports.delete(sessionId)
        return
      }
      sendJson(res, 404, { error: 'Session not found' })
      return
    }

    sendJson(res, 405, { error: 'Method not allowed' })
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    process.stderr.write(`[terrain-forge] Request error: ${message}\n`)
    if (!res.headersSent) {
      sendJson(res, 500, {
        jsonrpc: '2.0',
        error: { code: -32603, message: 'Internal server error', data: message },
        id: null,
      })
    }
  }
})

httpServer.listen(PORT, () => {
  process.stderr.write(`[terrain-forge] MCP server listening on http://localhost:${PORT}/mcp\n`)
})

httpServer.on('error', (err: NodeJS.ErrnoException) => {
  process.stderr.write(`[terrain-forge] Server error: ${err.message}\n`)
  process.exit(1)
})

process.on('SIGTERM', async () => {
  process.stderr.write('[terrain-forge] Shutting down...\n')
  await mcpServer.close()
  httpServer.close(() => process.exit(0))
})
