import type { GameMechanic } from '../../orchestrator/types'

export interface CollectibleItem {
  id: string
  name: string
  reward: number
  respawnSeconds?: number
}

/**
 * Collection mechanic — ProximityPrompt-based world pickup system.
 *
 * Generates a server script that:
 *   - Scans workspace.Collectibles for tagged parts
 *   - Attaches ProximityPrompts (if missing)
 *   - Awards currency and respawns the part after a cooldown
 */
export function generateCollectionMechanic(
  items: CollectibleItem[] = [],
  opts: { currencyModule?: string; folder?: string } = {},
): GameMechanic {
  const list: CollectibleItem[] =
    items.length > 0
      ? items
      : [
          { id: 'rock', name: 'Rock', reward: 5, respawnSeconds: 6 },
          { id: 'crystal', name: 'Crystal', reward: 20, respawnSeconds: 15 },
          { id: 'goldOre', name: 'Gold Ore', reward: 50, respawnSeconds: 30 },
        ]

  const currencyModule = opts.currencyModule ?? 'CoinsService'
  const folderName = opts.folder ?? 'Collectibles'

  const itemsLua = list
    .map(
      (i) =>
        `    ${i.id} = { id = "${i.id}", name = "${i.name}", reward = ${i.reward}, respawn = ${i.respawnSeconds ?? 10} },`,
    )
    .join('\n')

  const luauCode = `--!strict
-- CollectionService — ProximityPrompt-based world pickups
-- Auto-generated by ForjeGames Orchestrator

local Workspace         = game:GetService("Workspace")
local ServerScriptService = game:GetService("ServerScriptService")

type Collectible = { id: string, name: string, reward: number, respawn: number }

local CATALOG: { [string]: Collectible } = {
${itemsLua}
}

local function tryRequire(name: string): any
    local folder = ServerScriptService:FindFirstChild("Economy")
    if folder then
        local m = folder:FindFirstChild(name)
        if m and m:IsA("ModuleScript") then
            local ok, mod = pcall(require, m)
            if ok then return mod end
        end
    end
    return nil
end

local Currency = tryRequire("${currencyModule}")

local folder = Workspace:FindFirstChild("${folderName}")
if not folder then
    folder = Instance.new("Folder")
    folder.Name   = "${folderName}"
    folder.Parent = Workspace
end

local function matchCatalog(part: BasePart): Collectible?
    local idAttr = part:GetAttribute("CollectibleId")
    if typeof(idAttr) == "string" and CATALOG[idAttr] then
        return CATALOG[idAttr]
    end
    -- Fall back to matching by name
    local low = part.Name:lower()
    for id, entry in pairs(CATALOG) do
        if low:find(id:lower(), 1, true) then return entry end
    end
    return nil
end

local function attach(part: BasePart)
    if not part:IsA("BasePart") then return end
    local entry = matchCatalog(part)
    if not entry then return end

    local prompt = part:FindFirstChildOfClass("ProximityPrompt")
    if not prompt then
        prompt = Instance.new("ProximityPrompt")
        prompt.ActionText  = "Collect"
        prompt.ObjectText  = entry.name
        prompt.HoldDuration = 0.3
        prompt.MaxActivationDistance = 10
        prompt.Parent = part
    end

    prompt.Triggered:Connect(function(player: Player)
        if not part.Parent then return end
        if Currency and typeof(Currency.Add) == "function" then
            Currency.Add(player, entry.reward)
        end
        -- Hide + respawn
        part.Transparency = 1
        part.CanCollide   = false
        if prompt then prompt.Enabled = false end
        task.delay(entry.respawn, function()
            if part and part.Parent then
                part.Transparency = 0
                part.CanCollide   = true
                if prompt then prompt.Enabled = true end
            end
        end)
    end)
end

-- Attach to existing + future descendants
for _, desc in ipairs(folder:GetDescendants()) do
    if desc:IsA("BasePart") then attach(desc) end
end
folder.DescendantAdded:Connect(function(d)
    if d:IsA("BasePart") then attach(d) end
end)

return { Catalog = CATALOG }
`

  return {
    id: 'collection',
    type: 'collection',
    name: 'Collection System',
    scriptPath: 'ServerScriptService/Collection/CollectionService.server.lua',
    luauCode,
    dependencies: [`currency_${currencyModule.toLowerCase().replace(/service$/, '')}`],
  }
}
