import type { GameMechanic } from '../../orchestrator/types'

/**
 * Generic schema-based DataStore service.
 * Emits a ProfileStore-lite ModuleScript that:
 *   - Loads a per-player profile with retry + default schema merge
 *   - Debounces writes and flushes on shutdown
 *   - Exposes Get/Set/Update/Save functions
 */
export function generateDataStoreMechanic(
  schema: Record<string, unknown> = { level: 1, xp: 0, lastLogin: 0, unlocks: {} },
  name: string = 'PlayerProfile',
): GameMechanic {
  const safeName = name.replace(/[^A-Za-z0-9]/g, '') || 'PlayerProfile'
  const defaultLua = tableToLua(schema, 1)

  const luauCode = `--!strict
-- ${safeName}Store — debounced profile store with default schema merge
-- Auto-generated by ForjeGames Orchestrator

local Players          = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")
local RunService       = game:GetService("RunService")

local DEFAULT: { [string]: any } = ${defaultLua}

local store = DataStoreService:GetDataStore("${safeName}V1")
local profiles: { [number]: { [string]: any } } = {}
local dirty: { [number]: boolean } = {}

local ${safeName}Store = {}

local function deepMerge(dst: { [string]: any }, src: { [string]: any })
    for k, v in pairs(src) do
        if typeof(v) == "table" and typeof(dst[k]) == "table" then
            deepMerge(dst[k], v)
        elseif dst[k] == nil then
            dst[k] = v
        end
    end
end

local function clone(tbl: { [string]: any }): { [string]: any }
    local out: { [string]: any } = {}
    for k, v in pairs(tbl) do
        if typeof(v) == "table" then
            out[k] = clone(v :: { [string]: any })
        else
            out[k] = v
        end
    end
    return out
end

local function keyFor(uid: number): string
    return "u_" .. tostring(uid)
end

function ${safeName}Store.Get(player: Player): { [string]: any }
    return profiles[player.UserId] or clone(DEFAULT)
end

function ${safeName}Store.Set(player: Player, key: string, value: any): ()
    local p = profiles[player.UserId]
    if not p then return end
    p[key] = value
    dirty[player.UserId] = true
end

function ${safeName}Store.Update(player: Player, fn: ({ [string]: any }) -> ()): ()
    local p = profiles[player.UserId]
    if not p then return end
    fn(p)
    dirty[player.UserId] = true
end

function ${safeName}Store.Save(player: Player): ()
    local p = profiles[player.UserId]
    if not p then return end
    pcall(function()
        store:UpdateAsync(keyFor(player.UserId), function()
            return p
        end)
    end)
    dirty[player.UserId] = false
end

local function load(player: Player)
    local data
    local ok = false
    for attempt = 1, 3 do
        ok, data = pcall(function()
            return store:GetAsync(keyFor(player.UserId))
        end)
        if ok then break end
        task.wait(1)
    end
    if not ok or typeof(data) ~= "table" then
        data = clone(DEFAULT)
    else
        deepMerge(data, DEFAULT) -- merge-in new default fields for existing saves
    end
    profiles[player.UserId] = data
end

Players.PlayerAdded:Connect(load)
Players.PlayerRemoving:Connect(function(player)
    ${safeName}Store.Save(player)
    profiles[player.UserId] = nil
    dirty[player.UserId] = nil
end)

-- Periodic autosave
if not RunService:IsStudio() or RunService:IsRunning() then
    task.spawn(function()
        while true do
            task.wait(45)
            for uid, isDirty in pairs(dirty) do
                if isDirty then
                    local player = Players:GetPlayerByUserId(uid)
                    if player then ${safeName}Store.Save(player) end
                end
            end
        end
    end)
end

game:BindToClose(function()
    for _, player in ipairs(Players:GetPlayers()) do
        ${safeName}Store.Save(player)
    end
    task.wait(1)
end)

return ${safeName}Store
`

  return {
    id: `datastore_${safeName.toLowerCase()}`,
    type: 'datastore',
    name: `${safeName} Store`,
    scriptPath: `ServerScriptService/Data/${safeName}Store.lua`,
    luauCode,
    dependencies: [],
  }
}

/** Render a plain JS object as a Lua table literal with 4-space indent. */
function tableToLua(obj: unknown, depth: number): string {
  const pad = (d: number) => '    '.repeat(d)
  if (obj === null || obj === undefined) return 'nil'
  if (typeof obj === 'number') return Number.isFinite(obj) ? String(obj) : '0'
  if (typeof obj === 'boolean') return obj ? 'true' : 'false'
  if (typeof obj === 'string') return `"${obj.replace(/"/g, '\\"')}"`
  if (Array.isArray(obj)) {
    if (obj.length === 0) return '{}'
    const parts = obj.map((v) => `${pad(depth + 1)}${tableToLua(v, depth + 1)},`).join('\n')
    return `{\n${parts}\n${pad(depth)}}`
  }
  if (typeof obj === 'object') {
    const entries = Object.entries(obj as Record<string, unknown>)
    if (entries.length === 0) return '{}'
    const parts = entries
      .map(([k, v]) => `${pad(depth + 1)}${/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k) ? k : `["${k}"]`} = ${tableToLua(v, depth + 1)},`)
      .join('\n')
    return `{\n${parts}\n${pad(depth)}}`
  }
  return 'nil'
}
