import type { GameMechanic } from '../../orchestrator/types'

/**
 * Inventory mechanic — slot-based per-player inventory with DataStore persistence.
 *
 * Supports: add/remove/has/count/serialize with stack limits and max-slots.
 */
export function generateInventoryMechanic(
  name: string = 'PlayerInventory',
  opts: { maxSlots?: number; defaultStackSize?: number } = {},
): GameMechanic {
  const safeName = name.replace(/[^A-Za-z0-9]/g, '') || 'PlayerInventory'
  const maxSlots = opts.maxSlots ?? 50
  const stackSize = opts.defaultStackSize ?? 99

  const luauCode = `--!strict
-- ${safeName} — slot-based persistent player inventory
-- Auto-generated by ForjeGames Orchestrator

local Players           = game:GetService("Players")
local DataStoreService  = game:GetService("DataStoreService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local store = DataStoreService:GetDataStore("${safeName}V1")

type Slot = { id: string, count: number }
type Bag  = { [number]: Slot }

local ${safeName} = {}
local bags: { [number]: Bag } = {}

local MAX_SLOTS  = ${maxSlots}
local STACK_SIZE = ${stackSize}

-- RemoteEvent setup
local function ensureRemote(): RemoteEvent
    local folder = ReplicatedStorage:FindFirstChild("InventoryRemotes")
    if not folder then
        folder = Instance.new("Folder")
        folder.Name = "InventoryRemotes"
        folder.Parent = ReplicatedStorage
    end
    local rem = folder:FindFirstChild("${safeName}Changed")
    if not rem then
        rem = Instance.new("RemoteEvent")
        rem.Name = "${safeName}Changed"
        rem.Parent = folder
    end
    return rem :: RemoteEvent
end
local remote = ensureRemote()

local function getBag(player: Player): Bag
    local bag = bags[player.UserId]
    if not bag then
        bag = {}
        bags[player.UserId] = bag
    end
    return bag
end

local function serialize(bag: Bag): { Slot }
    local out: { Slot } = {}
    for _, slot in pairs(bag) do
        table.insert(out, { id = slot.id, count = slot.count })
    end
    return out
end

local function pushToClient(player: Player): ()
    remote:FireClient(player, serialize(getBag(player)))
end

function ${safeName}.Add(player: Player, itemId: string, amount: number): boolean
    if amount <= 0 then return false end
    local bag = getBag(player)
    local remaining = amount

    -- Fill existing stacks first
    for _, slot in pairs(bag) do
        if remaining <= 0 then break end
        if slot.id == itemId and slot.count < STACK_SIZE then
            local space = STACK_SIZE - slot.count
            local take = math.min(space, remaining)
            slot.count += take
            remaining -= take
        end
    end

    -- Allocate new slots
    while remaining > 0 do
        if #bag >= MAX_SLOTS then
            pushToClient(player)
            return false
        end
        local take = math.min(STACK_SIZE, remaining)
        table.insert(bag, { id = itemId, count = take })
        remaining -= take
    end

    pushToClient(player)
    return true
end

function ${safeName}.Remove(player: Player, itemId: string, amount: number): boolean
    if amount <= 0 then return false end
    local bag = getBag(player)
    local total = ${safeName}.Count(player, itemId)
    if total < amount then return false end

    local remaining = amount
    for i = #bag, 1, -1 do
        local slot = bag[i]
        if slot.id == itemId then
            local take = math.min(slot.count, remaining)
            slot.count -= take
            remaining -= take
            if slot.count <= 0 then
                table.remove(bag, i)
            end
            if remaining <= 0 then break end
        end
    end
    pushToClient(player)
    return true
end

function ${safeName}.Count(player: Player, itemId: string): number
    local bag = getBag(player)
    local total = 0
    for _, slot in pairs(bag) do
        if slot.id == itemId then total += slot.count end
    end
    return total
end

function ${safeName}.Has(player: Player, itemId: string, amount: number?): boolean
    return ${safeName}.Count(player, itemId) >= (amount or 1)
end

function ${safeName}.GetAll(player: Player): { Slot }
    return serialize(getBag(player))
end

function ${safeName}.Clear(player: Player): ()
    bags[player.UserId] = {}
    pushToClient(player)
end

-- ── Persistence ──────────────────────────────────────────────────────────────

local function keyFor(uid: number): string
    return "u_" .. tostring(uid)
end

local function load(player: Player): ()
    local ok, data = pcall(function()
        return store:GetAsync(keyFor(player.UserId))
    end)
    if ok and typeof(data) == "table" then
        bags[player.UserId] = data :: Bag
    else
        bags[player.UserId] = {}
    end
    pushToClient(player)
end

local function save(userId: number): ()
    local bag = bags[userId]
    if not bag then return end
    pcall(function()
        store:UpdateAsync(keyFor(userId), function()
            return bag
        end)
    end)
end

Players.PlayerAdded:Connect(load)
Players.PlayerRemoving:Connect(function(player)
    save(player.UserId)
    bags[player.UserId] = nil
end)

game:BindToClose(function()
    for uid in pairs(bags) do
        save(uid)
    end
    task.wait(1)
end)

return ${safeName}
`

  return {
    id: `inventory_${safeName.toLowerCase()}`,
    type: 'inventory',
    name: safeName,
    scriptPath: `ServerScriptService/Economy/${safeName}.lua`,
    luauCode,
    dependencies: [],
  }
}
