import type { GameMechanic } from '../../orchestrator/types'
import { safeLuaIdentifier } from '../../luau/identifier'

/**
 * Global OrderedDataStore leaderboard for a named stat.
 *
 * Emits a ModuleScript that:
 *   - Accepts score submissions
 *   - Reads the top N via GetSortedAsync
 *   - Caches results for 60s to respect DataStore budgets
 */
export function generateLeaderboardMechanic(
  stat: string = 'Coins',
  opts: { top?: number } = {},
): GameMechanic {
  const safeStat = safeLuaIdentifier(stat, 'Coins')
  const top = opts.top ?? 100

  const luauCode = `--!strict
-- ${safeStat}Leaderboard — global sorted leaderboard powered by OrderedDataStore
-- Auto-generated by ForjeGames Orchestrator

local DataStoreService  = game:GetService("DataStoreService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players           = game:GetService("Players")

local ods = DataStoreService:GetOrderedDataStore("${safeStat}LeaderboardV1")

local Leaderboard = {}
local cache: { entries: { { userId: number, value: number, name: string } }, at: number } = { entries = {}, at = 0 }
local CACHE_TTL = 60
local TOP = ${top}

local function fetchTop(): { { userId: number, value: number, name: string } }
    local now = os.clock()
    if (now - cache.at) < CACHE_TTL and #cache.entries > 0 then
        return cache.entries
    end
    local ok, pages = pcall(function()
        return ods:GetSortedAsync(false, TOP)
    end)
    if not ok or not pages then
        return cache.entries
    end
    local entries = {}
    for _, entry in ipairs(pages:GetCurrentPage()) do
        local uid = tonumber(entry.key) or 0
        local name = "Player"
        pcall(function()
            name = Players:GetNameFromUserIdAsync(uid)
        end)
        table.insert(entries, { userId = uid, value = entry.value, name = name })
    end
    cache.entries = entries
    cache.at      = now
    return entries
end

function Leaderboard.Submit(player: Player, value: number): ()
    if value < 0 then return end
    pcall(function()
        ods:SetAsync(tostring(player.UserId), math.floor(value))
    end)
end

function Leaderboard.GetTop(): { { userId: number, value: number, name: string } }
    return fetchTop()
end

-- Remote API
local folder = ReplicatedStorage:FindFirstChild("LeaderboardRemotes") or Instance.new("Folder")
folder.Name   = "LeaderboardRemotes"
folder.Parent = ReplicatedStorage

local rf = folder:FindFirstChild("Get${safeStat}Top") :: RemoteFunction
if not rf then
    rf = Instance.new("RemoteFunction")
    rf.Name = "Get${safeStat}Top"
    rf.Parent = folder
end
rf.OnServerInvoke = function(_player)
    return fetchTop()
end

-- Automatic periodic refresh (keeps cache warm)
task.spawn(function()
    while true do
        task.wait(CACHE_TTL)
        fetchTop()
    end
end)

return Leaderboard
`

  return {
    id: `leaderboard_${safeStat.toLowerCase()}`,
    type: 'leaderboard',
    name: `${safeStat} Leaderboard`,
    scriptPath: `ServerScriptService/Leaderboards/${safeStat}Leaderboard.lua`,
    luauCode,
    dependencies: [],
  }
}
