import type { GameMechanic } from '../../orchestrator/types'
import { safeLuaIdentifier } from '../../luau/identifier'
import { safeLuaString } from '../../luau/string'

export interface ShopItem {
  id: string
  name: string
  price: number
  description?: string
}

/**
 * Shop mechanic — server-authoritative item purchasing via a RemoteFunction.
 * Depends on a currency mechanic for `Spend` and on an inventory mechanic
 * (if items are inventory-backed) for `Add`.
 */
export function generateShopMechanic(
  name: string = 'MainShop',
  items: ShopItem[] = [],
  opts: { currencyModule?: string; inventoryModule?: string } = {},
): GameMechanic {
  const safeName = safeLuaIdentifier(name, 'MainShop')
  const currencyModule = safeLuaIdentifier(opts.currencyModule ?? 'CoinsService', 'CoinsService')
  const inventoryModule = safeLuaIdentifier(opts.inventoryModule ?? 'PlayerInventory', 'PlayerInventory')

  const defaultItems: ShopItem[] =
    items.length > 0
      ? items
      : [
          { id: 'wood_pickaxe', name: 'Wooden Pickaxe', price: 50, description: 'A basic tool' },
          { id: 'stone_pickaxe', name: 'Stone Pickaxe', price: 200, description: 'Stronger and sharper' },
          { id: 'iron_pickaxe', name: 'Iron Pickaxe', price: 800, description: 'Premium mining tool' },
        ]

  const itemsLuau = defaultItems
    .map(
      (it) =>
        `    { id = ${q(it.id)}, name = ${q(it.name)}, price = ${Math.max(0, Math.floor(it.price))}, description = ${q(it.description ?? '')} },`,
    )
    .join('\n')

  const luauCode = `--!strict
-- ${safeName} — server-authoritative shop
-- Auto-generated by ForjeGames Orchestrator

local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerScriptService = game:GetService("ServerScriptService")

type ShopItem = { id: string, name: string, price: number, description: string }

local ITEMS: { ShopItem } = {
${itemsLuau}
}

-- Lookups
local byId: { [string]: ShopItem } = {}
for _, it in ipairs(ITEMS) do byId[it.id] = it end

-- Service imports (tolerant: fall back to stub if module not found)
local function tryRequire(name: string): any
    local folder = ServerScriptService:FindFirstChild("Economy")
    if folder then
        local m = folder:FindFirstChild(name)
        if m and m:IsA("ModuleScript") then
            local ok, mod = pcall(require, m)
            if ok then return mod end
        end
    end
    return nil
end

local Currency  = tryRequire("${currencyModule}")
local Inventory = tryRequire("${inventoryModule}")

-- Remotes
local folder = ReplicatedStorage:FindFirstChild("ShopRemotes") or Instance.new("Folder")
folder.Name   = "ShopRemotes"
folder.Parent = ReplicatedStorage

local getItems  = folder:FindFirstChild("Get${safeName}Items") :: RemoteFunction
if not getItems then
    getItems = Instance.new("RemoteFunction")
    getItems.Name   = "Get${safeName}Items"
    getItems.Parent = folder
end

local purchase  = folder:FindFirstChild("${safeName}Purchase") :: RemoteFunction
if not purchase then
    purchase = Instance.new("RemoteFunction")
    purchase.Name   = "${safeName}Purchase"
    purchase.Parent = folder
end

-- Rate limit: one purchase / 0.5s per player
local lastPurchase: { [number]: number } = {}

getItems.OnServerInvoke = function(_player: Player)
    return ITEMS
end

purchase.OnServerInvoke = function(player: Player, itemId: string)
    if typeof(itemId) ~= "string" then
        return { ok = false, error = "invalid_item" }
    end
    local now = os.clock()
    if (lastPurchase[player.UserId] or 0) > now - 0.5 then
        return { ok = false, error = "rate_limited" }
    end
    lastPurchase[player.UserId] = now

    local item = byId[itemId]
    if not item then return { ok = false, error = "unknown_item" } end

    if not Currency or typeof(Currency.Spend) ~= "function" then
        return { ok = false, error = "currency_unavailable" }
    end
    if not Currency.Spend(player, item.price) then
        return { ok = false, error = "insufficient_funds" }
    end

    if Inventory and typeof(Inventory.Add) == "function" then
        Inventory.Add(player, item.id, 1)
    end

    return { ok = true, itemId = item.id, name = item.name, price = item.price }
end

Players.PlayerRemoving:Connect(function(player)
    lastPurchase[player.UserId] = nil
end)

return { Items = ITEMS }
`

  return {
    id: `shop_${safeName.toLowerCase()}`,
    type: 'shop',
    name: safeName,
    scriptPath: `ServerScriptService/Economy/${safeName}.lua`,
    luauCode,
    dependencies: [`currency_${currencyModule.toLowerCase().replace(/service$/, '')}`, `inventory_${inventoryModule.toLowerCase()}`],
  }
}

function q(s: string): string {
  return `"${safeLuaString(s)}"`
}
