'use client'

import Link from 'next/link'
import ShowcaseCard from './ShowcaseCard'
import { SHOWCASE_GAMES } from '@/lib/showcase-data'

/**
 * Showcase gallery section for the marketing landing page. Renders the first
 * eight entries from `SHOWCASE_GAMES` in a compact 4-up grid — the full
 * gallery with filters lives at `/showcase`.
 */
const HOME_SHOWCASE_COUNT = 8

export default function ShowcasePreview() {
  const featured = SHOWCASE_GAMES.slice(0, HOME_SHOWCASE_COUNT)

  return (
    <section id="showcase" className="py-16 sm:py-20 px-6 scroll-mt-20" style={{ background: '#050810' }}>
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-end justify-between gap-4 mb-10 sm:mb-14">
          <div className="min-w-0">
            <p
              className="text-[12px] font-medium uppercase tracking-widest mb-3"
              style={{ color: 'var(--gold, #D4AF37)' }}
            >
              Showcase
            </p>
            <h2
              className="font-bold tracking-tight"
              style={{ color: 'var(--text-primary, rgba(255,255,255,0.9))', fontSize: 'clamp(1.75rem, 5vw, 2.25rem)' }}
            >
              See what gets built.
            </h2>
            <p className="text-base sm:text-lg mt-3" style={{ color: '#8B95B0' }}>
              Real Roblox games and maps — generated by AI in minutes, not months.
            </p>
          </div>
          <Link
            href="/showcase"
            className="flex-shrink-0 flex items-center gap-2 text-sm font-medium px-5 py-2.5 rounded-lg transition-all duration-200 w-full sm:w-auto justify-center sm:justify-start"
            style={{
              color: '#D4AF37',
              border: '1px solid rgba(212,175,55,0.25)',
              background: 'rgba(212,175,55,0.06)',
            }}
          >
            View full gallery
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M5 12h14M12 5l7 7-7 7" />
            </svg>
          </Link>
        </div>

        {/* Cards grid — 2 rows of 4 on desktop */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {featured.map((game) => (
            <ShowcaseCard key={game.id} game={game} variant="compact" />
          ))}
        </div>

        {/* Bottom prompt example */}
        <div
          className="mt-10 rounded-xl p-4 sm:p-5 flex flex-col sm:flex-row items-center justify-between gap-4"
          style={{
            background: 'rgba(212,175,55,0.04)',
            border: '1px solid rgba(212,175,55,0.12)',
          }}
        >
          <div className="flex items-center gap-3 min-w-0">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
              style={{
                background: 'rgba(212,175,55,0.12)',
                border: '1px solid rgba(212,175,55,0.25)',
              }}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#D4AF37" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
                <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                <line x1="12" y1="19" x2="12" y2="22" />
              </svg>
            </div>
            <p className="text-sm" style={{ color: '#8B95B0' }}>
              Each of these was built from a single prompt like:&nbsp;
              <span className="font-mono" style={{ color: 'var(--gold, #D4AF37)' }}>
                &ldquo;build a medieval castle with a moat and drawbridge&rdquo;
              </span>
            </p>
          </div>
          <Link
            href="/editor"
            className="flex-shrink-0 text-sm font-semibold px-5 py-2.5 rounded-lg transition-all duration-200 nav-cta-gold w-full sm:w-auto text-center"
          >
            Try it yourself
          </Link>
        </div>
      </div>
    </section>
  )
}
