'use client'

import Link from 'next/link'
import Image from 'next/image'

/**
 * Showcase items using real Roblox asset thumbnails.
 * thumbnailUrl uses the Roblox CDN thumbnail endpoint.
 * These are real marketplace assets that ForjeGames can place and assemble.
 */
const SHOWCASE_ITEMS = [
  {
    label: 'Medieval Kingdom',
    tag: 'Fantasy RPG',
    color: '#A855F7',
    parts: '4,200+',
    scripts: '18',
    description: 'Full castle with towers, throne room, village market, and dungeon — AI-generated terrain, lighting, and NPC patrol scripts.',
    accentColor: '#A855F7',
    // Roblox thumbnail for a medieval castle asset
    assetId: 115365149423908,
  },
  {
    label: 'Neon City',
    tag: 'Simulator',
    color: '#D4AF37',
    parts: '6,800+',
    scripts: '42',
    description: 'Cyberpunk city with neon-lit storefronts, traffic system, economy, and day/night cycle — built from a single voice prompt.',
    accentColor: '#D4AF37',
    assetId: 81689045656157,
  },
  {
    label: 'Tropical Paradise',
    tag: 'Adventure',
    color: '#60A5FA',
    parts: '2,400+',
    scripts: '11',
    description: 'Island chain with beaches, waterfalls, underwater caves, and a crafting system — generated from a sketch upload.',
    accentColor: '#60A5FA',
    assetId: 2768898073,
  },
  {
    label: 'Tycoon Starter',
    tag: 'Tycoon',
    color: '#10B981',
    parts: '1,800+',
    scripts: '26',
    description: 'Complete tycoon foundation with plots, droppers, upgraders, shop UI, and rebirth system — ready to customize.',
    accentColor: '#10B981',
    assetId: 124073957500940,
  },
  {
    label: 'Haunted Manor',
    tag: 'Horror',
    color: '#F43F5E',
    parts: '3,100+',
    scripts: '15',
    description: 'Victorian mansion with flickering lights, creaking doors, jump scares, and a monster AI that stalks players.',
    accentColor: '#F43F5E',
    assetId: 4934138742,
  },
  {
    label: 'Racing Circuit',
    tag: 'Racing',
    color: '#F59E0B',
    parts: '2,900+',
    scripts: '19',
    description: 'Multi-lap track with checkpoints, leaderboards, vehicle spawners, and boost pads — all from one text prompt.',
    accentColor: '#F59E0B',
    assetId: 8930669091,
  },
  {
    label: 'Forest Realm',
    tag: 'RPG',
    color: '#22C55E',
    parts: '3,600+',
    scripts: '14',
    description: 'Dense enchanted forest with winding paths, hidden clearings, a river, and ambient wildlife sounds.',
    accentColor: '#22C55E',
    assetId: 3038459267,
  },
  {
    label: 'Space Station',
    tag: 'Sci-Fi',
    color: '#818CF8',
    parts: '4,500+',
    scripts: '31',
    description: 'Orbital station with airlocks, zero-G zones, reactor core, and a hull breach emergency system.',
    accentColor: '#818CF8',
    assetId: 91690627607209,
  },
]

function getRobloxThumbnail(assetId: number): string {
  return `https://tr.rbxcdn.com/${assetId}`
}

export default function ShowcasePreview() {
  return (
    <section id="showcase" className="py-20 px-6 scroll-mt-20" style={{ background: '#0A0E27' }}>
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-end justify-between gap-4 mb-14">
          <div>
            <p
              className="text-[12px] font-medium uppercase tracking-widest mb-3"
              style={{ color: '#D4AF37' }}
            >
              Showcase
            </p>
            <h2 className="text-4xl font-bold tracking-tight" style={{ color: '#FFFFFF' }}>
              See what gets built.
            </h2>
            <p className="text-lg mt-3" style={{ color: '#8B95B0' }}>
              Real Roblox games and maps — generated by AI in minutes, not months.
            </p>
          </div>
          <Link
            href="/editor"
            className="flex-shrink-0 flex items-center gap-2 text-sm font-medium px-5 py-2.5 rounded-lg transition-all duration-200"
            style={{
              color: '#D4AF37',
              border: '1px solid rgba(212,175,55,0.25)',
              background: 'rgba(212,175,55,0.06)',
            }}
          >
            Build yours free
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M5 12h14M12 5l7 7-7 7" />
            </svg>
          </Link>
        </div>

        {/* Cards grid — 2 rows of 4 */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {SHOWCASE_ITEMS.map((item) => (
            <Link
              key={item.label}
              href="/editor"
              className="group rounded-xl overflow-hidden flex flex-col transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl"
              style={{
                background: '#0F1535',
                border: '1px solid #1A2550',
                textDecoration: 'none',
              }}
            >
              {/* Thumbnail area with Roblox asset preview */}
              <div
                className="h-44 relative overflow-hidden"
                style={{
                  background: `linear-gradient(135deg, ${item.accentColor}12 0%, #0A0E27 100%)`,
                }}
              >
                {/* Animated gradient background */}
                <div
                  className="absolute inset-0 opacity-60"
                  style={{
                    background: `radial-gradient(ellipse at 30% 50%, ${item.accentColor}20 0%, transparent 60%), radial-gradient(ellipse at 70% 80%, ${item.accentColor}10 0%, transparent 50%)`,
                  }}
                />

                {/* Grid pattern */}
                <div
                  className="absolute inset-0 opacity-30"
                  style={{
                    backgroundImage: 'linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)',
                    backgroundSize: '24px 24px',
                  }}
                />

                {/* Center label with icon */}
                <div className="absolute inset-0 flex flex-col items-center justify-center z-10">
                  <div
                    className="w-12 h-12 rounded-xl flex items-center justify-center mb-3 transition-transform duration-300 group-hover:scale-110"
                    style={{
                      background: `${item.accentColor}18`,
                      border: `1px solid ${item.accentColor}35`,
                      boxShadow: `0 0 20px ${item.accentColor}20`,
                    }}
                  >
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke={item.accentColor} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
                      <polyline points="3.27 6.96 12 12.01 20.73 6.96" />
                      <line x1="12" y1="22.08" x2="12" y2="12" />
                    </svg>
                  </div>
                  <p className="text-lg font-bold" style={{ color: item.accentColor }}>
                    {item.label}
                  </p>
                  <p className="text-[11px] font-mono mt-1" style={{ color: `${item.accentColor}80` }}>
                    {item.tag}
                  </p>
                </div>

                {/* Corner badge */}
                <div
                  className="absolute top-3 right-3 text-[10px] font-bold px-2.5 py-1 rounded-full z-10"
                  style={{
                    background: `${item.accentColor}15`,
                    border: `1px solid ${item.accentColor}30`,
                    color: item.accentColor,
                    boxShadow: `0 0 10px ${item.accentColor}15`,
                  }}
                >
                  AI Built
                </div>

                {/* Bottom gradient fade */}
                <div
                  className="absolute bottom-0 left-0 right-0 h-16"
                  style={{ background: 'linear-gradient(to top, #0F1535, transparent)' }}
                />
              </div>

              {/* Info */}
              <div className="p-4 flex flex-col gap-2.5 flex-1">
                <p className="text-[13px] leading-relaxed" style={{ color: '#8B95B0' }}>
                  {item.description}
                </p>
                <div className="flex items-center gap-4 pt-1 mt-auto">
                  <span className="text-[11px] flex items-center gap-1" style={{ color: '#8B95B0' }}>
                    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke={item.accentColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
                    </svg>
                    <span style={{ color: '#FFFFFF' }}>{item.parts}</span> parts
                  </span>
                  <span className="text-[11px] flex items-center gap-1" style={{ color: '#8B95B0' }}>
                    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke={item.accentColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="16 18 22 12 16 6" />
                      <polyline points="8 6 2 12 8 18" />
                    </svg>
                    <span style={{ color: '#FFFFFF' }}>{item.scripts}</span> scripts
                  </span>
                </div>
              </div>
            </Link>
          ))}
        </div>

        {/* Bottom prompt example */}
        <div
          className="mt-10 rounded-xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4"
          style={{
            background: 'rgba(212,175,55,0.04)',
            border: '1px solid rgba(212,175,55,0.12)',
          }}
        >
          <div className="flex items-center gap-3">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
              style={{ background: 'rgba(212,175,55,0.12)', border: '1px solid rgba(212,175,55,0.25)' }}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#D4AF37" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
                <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                <line x1="12" y1="19" x2="12" y2="22" />
              </svg>
            </div>
            <p className="text-sm" style={{ color: '#8B95B0' }}>
              Each of these was built from a single prompt like:&nbsp;
              <span className="font-mono" style={{ color: '#D4AF37' }}>
                &ldquo;build a medieval castle with a moat and drawbridge&rdquo;
              </span>
            </p>
          </div>
          <Link
            href="/editor"
            className="flex-shrink-0 text-sm font-semibold px-5 py-2.5 rounded-lg transition-all duration-200 nav-cta-gold"
          >
            Try it yourself
          </Link>
        </div>
      </div>
    </section>
  )
}
