/**
 * Agent registry — 50+ specialized agent definitions for the ForjeGames orchestration system.
 *
 * Design rules:
 *  - Pure data module: no API calls, no side effects at import time
 *  - costPerCall is the *estimated* platform token spend (not Anthropic raw tokens)
 *  - model reflects the minimum capability tier required for the task
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type AgentModel = 'claude-opus' | 'claude-sonnet' | 'claude-haiku'
export type AgentCategory = 'build' | 'analyze' | 'optimize' | 'research' | 'business' | 'growth'

export interface AgentDef {
  id: string
  name: string
  description: string
  /** Keywords that help the router match this agent to a user request */
  capabilities: string[]
  model: AgentModel
  /** Estimated ForjeGames platform token cost for a single call */
  costPerCall: number
  category: AgentCategory
  /** If true, this agent can accept the output of another agent as its input */
  chainable: boolean
  /** Agent IDs this agent typically hands off to after completing its task */
  defaultChain?: string[]
  /** Minimum subscription tier required to use this agent */
  minTier: 'FREE' | 'HOBBY' | 'CREATOR' | 'STUDIO'
}

// ─── Registry data ────────────────────────────────────────────────────────────

const REGISTRY: AgentDef[] = [
  // ─── BUILD (15) ─────────────────────────────────────────────────────────────

  {
    id: 'terrain-gen',
    name: 'Terrain Generator',
    description: 'Generates Roblox terrain from text descriptions: biomes, mountains, rivers, lakes, and custom heightmaps using Terrain:FillBlock/FillBall APIs.',
    capabilities: ['terrain', 'biome', 'landscape', 'heightmap', 'mountain', 'river', 'lake', 'forest', 'desert', 'snow', 'grass', 'water', 'valley', 'hill', 'flatten', 'raise'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'build',
    chainable: true,
    defaultChain: ['asset-placer', 'lighting-expert'],
    minTier: 'FREE',
  },
  {
    id: 'city-builder',
    name: 'City Builder',
    description: 'Designs and scripts entire city districts: road grids, building placement, zoning rules, pedestrian paths, and district theming for tycoons and simulators.',
    capabilities: ['city', 'building', 'district', 'road', 'street', 'urban', 'town', 'shop', 'house', 'skyscraper', 'plaza', 'park', 'residential', 'commercial'],
    model: 'claude-sonnet',
    costPerCall: 80,
    category: 'build',
    chainable: true,
    defaultChain: ['npc-creator', 'lighting-expert'],
    minTier: 'HOBBY',
  },
  {
    id: 'npc-creator',
    name: 'NPC Creator',
    description: 'Creates fully-scripted NPCs with patrol AI, dialogue trees, quest-giving, shopkeeper behaviour, and idle animations. Outputs server Luau scripts.',
    capabilities: ['npc', 'character', 'enemy', 'guard', 'villager', 'merchant', 'mob', 'ai', 'patrol', 'dialogue', 'shopkeeper', 'quest giver', 'spawn'],
    model: 'claude-sonnet',
    costPerCall: 60,
    category: 'build',
    chainable: true,
    defaultChain: ['script-writer'],
    minTier: 'FREE',
  },
  {
    id: 'script-writer',
    name: 'Luau Script Writer',
    description: 'Writes production-quality Luau scripts: ServerScripts, LocalScripts, ModuleScripts. Follows security best practices — server authority, no client trust, pcall wrapping.',
    capabilities: ['script', 'luau', 'code', 'function', 'module', 'server', 'client', 'remoteEvent', 'remoteFunction', 'datastore', 'profilestore', 'bindableEvent', 'coroutine', 'task'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'build',
    chainable: true,
    defaultChain: ['code-reviewer'],
    minTier: 'FREE',
  },
  {
    id: 'ui-designer',
    name: 'UI Designer',
    description: 'Builds Roblox ScreenGuis, BillboardGuis, and SurfaceGuis with full Luau scripts. Specialises in HUDs, shops, inventories, and leaderboards.',
    capabilities: ['ui', 'gui', 'hud', 'menu', 'screen', 'button', 'inventory', 'leaderboard', 'shop', 'dialog', 'frame', 'textlabel', 'imagelabel', 'tween', 'animation'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'build',
    chainable: true,
    defaultChain: ['script-writer'],
    minTier: 'FREE',
  },
  {
    id: 'lighting-expert',
    name: 'Lighting Expert',
    description: 'Configures Roblox Lighting service: Atmosphere, Bloom, ColorCorrection, SunRaysEffect, DepthOfField, and ShadowMap for cinematic looks.',
    capabilities: ['lighting', 'atmosphere', 'fog', 'sky', 'bloom', 'glow', 'ambient', 'shadow', 'sunrise', 'sunset', 'night', 'dusk', 'dawn', 'post processing', 'colorgrading'],
    model: 'claude-haiku',
    costPerCall: 20,
    category: 'build',
    chainable: true,
    defaultChain: [],
    minTier: 'FREE',
  },
  {
    id: 'audio-placer',
    name: 'Audio Placer',
    description: 'Places and configures Sound objects, ambient audio zones, music playlists, and spatial audio for immersive worlds.',
    capabilities: ['sound', 'music', 'audio', 'sfx', 'ambient', 'playlist', 'spatial', 'reverb', 'equalize', 'volume', 'looping'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'build',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'particle-fx',
    name: 'Particle FX Artist',
    description: 'Creates ParticleEmitter, Trail, Beam, and SpecialMesh effects for spells, explosions, weather, and environmental ambience.',
    capabilities: ['particle', 'fire', 'smoke', 'sparkle', 'trail', 'beam', 'explosion', 'magic', 'weather', 'rain', 'snow', 'dust', 'glow', 'aura', 'vfx'],
    model: 'claude-haiku',
    costPerCall: 25,
    category: 'build',
    chainable: true,
    defaultChain: [],
    minTier: 'FREE',
  },
  {
    id: 'vehicle-builder',
    name: 'Vehicle Builder',
    description: 'Builds driveable vehicles using VehicleSeat, BodyMover, and constraint-based physics. Covers cars, boats, planes, and karts.',
    capabilities: ['vehicle', 'car', 'truck', 'boat', 'plane', 'kart', 'drive', 'seat', 'physics', 'bodyvelocity', 'constraint', 'wheel', 'engine'],
    model: 'claude-sonnet',
    costPerCall: 70,
    category: 'build',
    chainable: true,
    defaultChain: ['script-writer'],
    minTier: 'HOBBY',
  },
  {
    id: 'weapon-smith',
    name: 'Weapon Smith',
    description: 'Creates weapons with full tool scripts: swords, guns, staffs. Handles hitbox detection, damage, cooldowns, and visual feedback.',
    capabilities: ['weapon', 'sword', 'gun', 'tool', 'melee', 'ranged', 'hitbox', 'damage', 'attack', 'projectile', 'cooldown', 'combat'],
    model: 'claude-sonnet',
    costPerCall: 65,
    category: 'build',
    chainable: true,
    defaultChain: ['combat-system'],
    minTier: 'HOBBY',
  },
  {
    id: 'economy-designer',
    name: 'Economy Designer',
    description: 'Designs in-game economies: currency sinks, reward curves, shop pricing, daily rewards, and pass monetization that keeps players engaged without predatory loops.',
    capabilities: ['economy', 'currency', 'shop', 'price', 'reward', 'token', 'pass', 'gamepass', 'monetization', 'sink', 'inflation', 'store', 'daily'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'build',
    chainable: true,
    defaultChain: ['script-writer'],
    minTier: 'CREATOR',
  },
  {
    id: 'quest-writer',
    name: 'Quest Writer',
    description: 'Writes quest chains with objectives, branching dialogue, reward tables, and tracker UI. Outputs modular quest data tables and handler scripts.',
    capabilities: ['quest', 'mission', 'objective', 'story', 'task', 'reward', 'dialogue', 'npc', 'narrative', 'chain', 'tracker', 'progression'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'build',
    chainable: true,
    defaultChain: ['npc-creator', 'ui-designer'],
    minTier: 'HOBBY',
  },
  {
    id: 'combat-system',
    name: 'Combat System Builder',
    description: 'Builds full combat systems: server-authoritative hit detection, combo inputs, status effects, health bars, knockback, and anti-cheat guards.',
    capabilities: ['combat', 'pvp', 'fight', 'hitbox', 'combo', 'status', 'stun', 'knockback', 'health', 'shield', 'dodge', 'block', 'anti-cheat'],
    model: 'claude-sonnet',
    costPerCall: 90,
    category: 'build',
    chainable: true,
    defaultChain: ['script-writer', 'code-reviewer'],
    minTier: 'CREATOR',
  },
  {
    id: 'mesh-generator',
    name: 'Mesh Generator',
    description: 'Generates optimised 3D mesh descriptions and Meshy.ai prompts for custom props, characters, and environment pieces.',
    capabilities: ['mesh', '3d', 'model', 'prop', 'asset', 'obj', 'fbx', 'lowpoly', 'character', 'creature', 'environment', 'meshy'],
    model: 'claude-haiku',
    costPerCall: 30,
    category: 'build',
    chainable: false,
    minTier: 'CREATOR',
  },
  {
    id: 'texture-artist',
    name: 'Texture Artist',
    description: 'Generates Fal.ai texture prompts for PBR materials: albedo, normal, roughness, and metallic maps for any surface type.',
    capabilities: ['texture', 'material', 'pbr', 'surface', 'paint', 'skin', 'fabric', 'metal', 'wood', 'stone', 'fal', 'diffuse', 'normal map'],
    model: 'claude-haiku',
    costPerCall: 25,
    category: 'build',
    chainable: false,
    minTier: 'CREATOR',
  },

  // ─── ANALYZE (10) ───────────────────────────────────────────────────────────

  {
    id: 'game-dna-scanner',
    name: 'Game DNA Scanner',
    description: 'Deep-analyzes a competitor Roblox game by ID: extracts mechanics, monetization loops, player progression, retention hooks, and genre conventions.',
    capabilities: ['analyze', 'competitor', 'game', 'scan', 'reverse engineer', 'monetization', 'progression', 'retention', 'mechanic', 'loop'],
    model: 'claude-sonnet',
    costPerCall: 100,
    category: 'analyze',
    chainable: true,
    defaultChain: ['feature-predictor'],
    minTier: 'CREATOR',
  },
  {
    id: 'performance-auditor',
    name: 'Performance Auditor',
    description: 'Audits Luau scripts and build configurations for performance issues: part count, runservice loops, memory leaks, instance pooling gaps, and mobile frame-rate risks.',
    capabilities: ['performance', 'fps', 'lag', 'memory', 'optimize', 'part count', 'runservice', 'heartbeat', 'renderstepped', 'mobile', 'instance'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'analyze',
    chainable: true,
    defaultChain: ['cost-reducer'],
    minTier: 'FREE',
  },
  {
    id: 'code-reviewer',
    name: 'Code Reviewer',
    description: 'Reviews Luau code for security vulnerabilities, logic bugs, deprecated APIs, and style issues. Flags client-trust violations and missing pcall wrappers.',
    capabilities: ['review', 'security', 'bug', 'vulnerability', 'deprecated', 'pcall', 'server authority', 'remote event', 'sanitize', 'validate'],
    model: 'claude-sonnet',
    costPerCall: 40,
    category: 'analyze',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'security-checker',
    name: 'Security Checker',
    description: 'Identifies exploitable remote handlers, missing server-side validation, DataStore key injection risks, and anti-cheat gaps.',
    capabilities: ['security', 'exploit', 'remote', 'validation', 'datastore', 'cheat', 'injection', 'sanitize', 'fireremote', 'trust'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'analyze',
    chainable: false,
    minTier: 'HOBBY',
  },
  {
    id: 'accessibility-auditor',
    name: 'Accessibility Auditor',
    description: 'Reviews UI contrast ratios, text sizes, colorblind modes, screen reader labels, and mobile touch target sizing against WCAG-adapted Roblox guidelines.',
    capabilities: ['accessibility', 'contrast', 'colorblind', 'font size', 'mobile', 'touch target', 'screen reader', 'a11y', 'wcag'],
    model: 'claude-haiku',
    costPerCall: 20,
    category: 'analyze',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'seo-optimizer',
    name: 'SEO Optimizer',
    description: 'Optimizes Roblox game metadata: title, description, tags, genre, and thumbnail guidance to maximise organic discovery on the Roblox search and discovery feeds.',
    capabilities: ['seo', 'search', 'discovery', 'metadata', 'title', 'description', 'tag', 'thumbnail', 'genre', 'ranking', 'impression'],
    model: 'claude-haiku',
    costPerCall: 20,
    category: 'analyze',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'ux-analyzer',
    name: 'UX Analyzer',
    description: 'Evaluates onboarding flow, first-session experience, tutorial clarity, UI hierarchy, and player frustration points.',
    capabilities: ['ux', 'onboarding', 'tutorial', 'friction', 'first session', 'flow', 'user experience', 'clarity', 'confusion', 'drop-off'],
    model: 'claude-sonnet',
    costPerCall: 40,
    category: 'analyze',
    chainable: true,
    defaultChain: ['onboarding-optimizer'],
    minTier: 'HOBBY',
  },
  {
    id: 'monetization-advisor',
    name: 'Monetization Advisor',
    description: 'Advises on Roblox monetization: gamepass placement, Developer Product timing, VIP server pricing, bundle strategies, and ethical spend triggers for the 8-16 demographic.',
    capabilities: ['monetization', 'gamepass', 'developer product', 'robux', 'vip', 'bundle', 'upsell', 'revenue', 'conversion', 'arpu', 'ltv'],
    model: 'claude-sonnet',
    costPerCall: 60,
    category: 'analyze',
    chainable: false,
    minTier: 'CREATOR',
  },
  {
    id: 'player-behavior',
    name: 'Player Behavior Analyst',
    description: 'Interprets playtime data, session lengths, quit points, and feature engagement to produce actionable design recommendations.',
    capabilities: ['player', 'behavior', 'engagement', 'retention', 'session', 'playtime', 'analytics', 'churn', 'dau', 'mau', 'cohort'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'analyze',
    chainable: true,
    defaultChain: ['feature-predictor'],
    minTier: 'STUDIO',
  },
  {
    id: 'competitor-scanner',
    name: 'Competitor Scanner',
    description: 'Surveys the top-100 Roblox games in a target genre, extracts common patterns, identifies gaps, and produces a feature differentiation matrix.',
    capabilities: ['competitor', 'market', 'genre', 'top games', 'benchmark', 'differentiation', 'gap', 'trend', 'landscape'],
    model: 'claude-haiku',
    costPerCall: 35,
    category: 'analyze',
    chainable: true,
    defaultChain: ['game-dna-scanner'],
    minTier: 'CREATOR',
  },

  // ─── OPTIMIZE (8) ───────────────────────────────────────────────────────────

  {
    id: 'prompt-optimizer',
    name: 'Prompt Optimizer',
    description: 'Rewrites user prompts for maximum AI output quality: adds context, specifies constraints, and injects domain keywords to reduce token waste.',
    capabilities: ['prompt', 'rewrite', 'improve', 'quality', 'output', 'rephrase', 'context', 'instruction'],
    model: 'claude-haiku',
    costPerCall: 10,
    category: 'optimize',
    chainable: true,
    defaultChain: [],
    minTier: 'FREE',
  },
  {
    id: 'cache-manager',
    name: 'Cache Manager',
    description: 'Identifies repeated agent calls that could be cached, manages Redis TTL strategy, and reports cache hit rates to reduce platform token burn.',
    capabilities: ['cache', 'redis', 'ttl', 'hit rate', 'dedup', 'memoize', 'repeat', 'token saving'],
    model: 'claude-haiku',
    costPerCall: 8,
    category: 'optimize',
    chainable: false,
    minTier: 'HOBBY',
  },
  {
    id: 'cost-reducer',
    name: 'Cost Reducer',
    description: 'Audits a forje session token spend, identifies over-priced agent calls, and recommends model downgrades or prompt compression strategies.',
    capabilities: ['cost', 'token', 'spend', 'reduce', 'budget', 'model', 'downgrade', 'compress', 'efficiency'],
    model: 'claude-haiku',
    costPerCall: 12,
    category: 'optimize',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'bundle-optimizer',
    name: 'Bundle Optimizer',
    description: 'Analyzes Next.js bundle sizes, flags heavy client-side imports, and suggests dynamic import strategies to hit LCP < 2s targets.',
    capabilities: ['bundle', 'next.js', 'webpack', 'import', 'dynamic', 'lcp', 'performance', 'chunk', 'tree shaking'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'optimize',
    chainable: false,
    minTier: 'CREATOR',
  },
  {
    id: 'query-optimizer',
    name: 'Query Optimizer',
    description: 'Reviews Prisma queries for N+1 patterns, missing indexes, unbounded selects, and transaction size issues against the ForjeGames Postgres schema.',
    capabilities: ['query', 'prisma', 'database', 'n+1', 'index', 'slow', 'postgres', 'transaction', 'join', 'select'],
    model: 'claude-sonnet',
    costPerCall: 35,
    category: 'optimize',
    chainable: false,
    minTier: 'CREATOR',
  },
  {
    id: 'asset-compressor',
    name: 'Asset Compressor',
    description: 'Advises on Roblox asset optimisation: texture resolution targets, mesh polygon budgets, audio bitrate settings, and decal atlas strategies.',
    capabilities: ['asset', 'compress', 'texture', 'resolution', 'polygon', 'lod', 'atlas', 'bitrate', 'filesize', 'budget'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'optimize',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'load-balancer',
    name: 'Load Balancer Advisor',
    description: 'Reviews server architecture for Roblox server capacity, TeleportService routing, cross-server messaging patterns, and MessagingService usage.',
    capabilities: ['load balancer', 'server', 'teleport', 'cross-server', 'messaging', 'capacity', 'shard', 'scale'],
    model: 'claude-sonnet',
    costPerCall: 40,
    category: 'optimize',
    chainable: false,
    minTier: 'STUDIO',
  },
  {
    id: 'cdn-optimizer',
    name: 'CDN Optimizer',
    description: 'Optimises Vercel Edge, Cloudflare CDN rules, image caching headers, and API response caching for ForjeGames.com.',
    capabilities: ['cdn', 'vercel', 'cloudflare', 'cache', 'edge', 'header', 'image', 'api response', 'ttl'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'optimize',
    chainable: false,
    minTier: 'STUDIO',
  },

  // ─── RESEARCH (7) ───────────────────────────────────────────────────────────

  {
    id: 'trend-finder',
    name: 'Trend Finder',
    description: 'Identifies emerging Roblox game genres, mechanic trends, and seasonal content opportunities by parsing the Trending and Featured feeds.',
    capabilities: ['trend', 'emerging', 'genre', 'seasonal', 'viral', 'popular', 'up and coming', 'discovery', 'forecast'],
    model: 'claude-haiku',
    costPerCall: 25,
    category: 'research',
    chainable: true,
    defaultChain: ['competitor-scanner'],
    minTier: 'FREE',
  },
  {
    id: 'marketplace-scout',
    name: 'Marketplace Scout',
    description: 'Searches the Roblox asset marketplace for suitable models, plugins, audio, and decals matching a description, returning top 5 candidates with IDs and ratings.',
    capabilities: ['marketplace', 'asset', 'search', 'model', 'plugin', 'audio', 'decal', 'free', 'rbxm', 'id'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'research',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'tutorial-creator',
    name: 'Tutorial Creator',
    description: 'Writes step-by-step tutorials for ForjeGames features and Roblox development topics in the platform voice: concise, numbered, code-included.',
    capabilities: ['tutorial', 'guide', 'how to', 'documentation', 'step by step', 'example', 'walkthrough'],
    model: 'claude-haiku',
    costPerCall: 20,
    category: 'research',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'doc-writer',
    name: 'Doc Writer',
    description: 'Generates API documentation, README files, JSDoc comments, and Luau module docstrings from existing code.',
    capabilities: ['documentation', 'api docs', 'readme', 'jsdoc', 'comment', 'docstring', 'reference', 'spec'],
    model: 'claude-haiku',
    costPerCall: 20,
    category: 'research',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'changelog-generator',
    name: 'Changelog Generator',
    description: 'Produces developer-friendly changelogs from git diffs and Prisma migration files.',
    capabilities: ['changelog', 'release notes', 'git', 'diff', 'migration', 'version', 'update'],
    model: 'claude-haiku',
    costPerCall: 12,
    category: 'research',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'feedback-analyzer',
    name: 'Feedback Analyzer',
    description: 'Summarises player feedback, support tickets, and Discord messages into categorised actionable insights with sentiment scores.',
    capabilities: ['feedback', 'review', 'sentiment', 'player', 'support', 'discord', 'community', 'complaint', 'request'],
    model: 'claude-haiku',
    costPerCall: 20,
    category: 'research',
    chainable: true,
    defaultChain: ['feature-predictor'],
    minTier: 'HOBBY',
  },
  {
    id: 'feature-predictor',
    name: 'Feature Predictor',
    description: 'Predicts the highest-ROI next features to build based on player behavior data, competitor gaps, and platform trends. Outputs a prioritised roadmap.',
    capabilities: ['feature', 'roadmap', 'priority', 'predict', 'roi', 'next', 'build', 'plan', 'backlog'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'research',
    chainable: false,
    minTier: 'CREATOR',
  },

  // ─── BUSINESS (5) ───────────────────────────────────────────────────────────

  {
    id: 'llc-connector',
    name: 'LLC Connector',
    description: 'Bridges ForjeGames with the Flip or Flop LLC City game: syncs virtual property listings, business simulations, and player economy data.',
    capabilities: ['llc', 'flip or flop', 'business', 'property', 'virtual', 'sync', 'connect', 'economy', 'simulation'],
    model: 'claude-sonnet',
    costPerCall: 60,
    category: 'business',
    chainable: false,
    minTier: 'STUDIO',
  },
  {
    id: 'stripe-manager',
    name: 'Stripe Manager',
    description: 'Handles Stripe subscription changes, one-off charges, webhook event interpretation, and refund workflows for ForjeGames billing.',
    capabilities: ['stripe', 'billing', 'subscription', 'invoice', 'refund', 'webhook', 'payment', 'checkout'],
    model: 'claude-sonnet',
    costPerCall: 40,
    category: 'business',
    chainable: false,
    minTier: 'STUDIO',
  },
  {
    id: 'team-provisioner',
    name: 'Team Provisioner',
    description: 'Sets up team workspaces: invites members, assigns roles, configures shared API keys, and provisions per-seat token allowances.',
    capabilities: ['team', 'workspace', 'invite', 'role', 'permission', 'member', 'provision', 'seat', 'collaboration'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'business',
    chainable: false,
    minTier: 'STUDIO',
  },
  {
    id: 'white-label-builder',
    name: 'White Label Builder',
    description: 'Generates white-label builds of ForjeGames features for studio partners: custom branding, isolated environments, and API key scoping.',
    capabilities: ['white label', 'partner', 'branding', 'custom', 'resell', 'studio', 'api', 'scope'],
    model: 'claude-sonnet',
    costPerCall: 80,
    category: 'business',
    chainable: false,
    minTier: 'STUDIO',
  },
  {
    id: 'partner-api',
    name: 'Partner API Designer',
    description: 'Designs and documents REST or webhook APIs for third-party integrations, LLC partners, and studio white-label customers.',
    capabilities: ['api', 'rest', 'webhook', 'integration', 'partner', 'endpoint', 'schema', 'openapi', 'sdk'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'business',
    chainable: true,
    defaultChain: ['doc-writer'],
    minTier: 'STUDIO',
  },

  // ─── GROWTH (5) ─────────────────────────────────────────────────────────────

  {
    id: 'referral-engine',
    name: 'Referral Engine',
    description: 'Designs and tunes referral programs: reward amounts, viral coefficient targets, fraud prevention, and Stripe-connected referral payouts.',
    capabilities: ['referral', 'viral', 'invite', 'growth', 'reward', 'share', 'coefficient', 'fraud', 'affiliate'],
    model: 'claude-sonnet',
    costPerCall: 40,
    category: 'growth',
    chainable: false,
    minTier: 'CREATOR',
  },
  {
    id: 'email-campaigner',
    name: 'Email Campaigner',
    description: 'Writes and schedules React Email campaigns via Resend: onboarding drips, re-engagement sequences, and announcement blasts.',
    capabilities: ['email', 'campaign', 'drip', 'onboarding', 're-engagement', 'newsletter', 'resend', 'react email', 'sequence'],
    model: 'claude-haiku',
    costPerCall: 20,
    category: 'growth',
    chainable: false,
    minTier: 'HOBBY',
  },
  {
    id: 'social-poster',
    name: 'Social Poster',
    description: 'Generates platform-tuned social copy for Twitter/X, Discord announcements, and TikTok scripts for Roblox game updates.',
    capabilities: ['social', 'twitter', 'discord', 'tiktok', 'post', 'announcement', 'copy', 'marketing', 'community'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'growth',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'community-manager',
    name: 'Community Manager',
    description: 'Drafts community update posts, patch notes, event announcements, and moderation responses tailored to Roblox\'s 8-16 audience.',
    capabilities: ['community', 'update', 'patch notes', 'event', 'moderation', 'post', 'roblox', 'devforum', 'discord'],
    model: 'claude-haiku',
    costPerCall: 15,
    category: 'growth',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'onboarding-optimizer',
    name: 'Onboarding Optimizer',
    description: 'Redesigns first-run experiences for ForjeGames users: cuts activation time-to-value, increases tutorial completion, and reduces early churn.',
    capabilities: ['onboarding', 'activation', 'time to value', 'tutorial', 'first run', 'wizard', 'churn', 'aha moment'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'growth',
    chainable: false,
    minTier: 'CREATOR',
  },

  // ─── BUILD (continued) ──────────────────────────────────────────────────────

  {
    id: 'obby-architect',
    name: 'Obby Architect',
    description: 'Designs and scripts obstacle courses with checkpoints, difficulty curves, killbricks, moving platforms, and stage-save systems.',
    capabilities: ['obby', 'obstacle', 'checkpoint', 'parkour', 'jump', 'platform', 'stage', 'difficulty', 'killbrick'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'build',
    chainable: true,
    defaultChain: ['script-writer', 'particle-fx'],
    minTier: 'FREE',
  },
  {
    id: 'tycoon-builder',
    name: 'Tycoon Builder',
    description: 'Creates full tycoon game loops: droppers, conveyors, upgrades, rebirth systems, and tycoon plots with purchase buttons.',
    capabilities: ['tycoon', 'dropper', 'conveyor', 'upgrade', 'rebirth', 'plot', 'factory', 'money', 'cash'],
    model: 'claude-sonnet',
    costPerCall: 75,
    category: 'build',
    chainable: true,
    defaultChain: ['economy-designer', 'ui-designer'],
    minTier: 'HOBBY',
  },
  {
    id: 'simulator-engine',
    name: 'Simulator Engine',
    description: 'Builds simulator game loops: click/tap mechanics, pet systems, egg hatching, multipliers, rebirths, and world progression.',
    capabilities: ['simulator', 'click', 'tap', 'pet', 'egg', 'hatch', 'multiplier', 'rebirth', 'world'],
    model: 'claude-sonnet',
    costPerCall: 70,
    category: 'build',
    chainable: true,
    defaultChain: ['economy-designer', 'ui-designer'],
    minTier: 'HOBBY',
  },
  {
    id: 'horror-designer',
    name: 'Horror Designer',
    description: 'Creates horror game atmospheres: jumpscares, dark lighting, ambient audio, chase mechanics, hiding spots, and tension pacing.',
    capabilities: ['horror', 'jumpscare', 'dark', 'scary', 'chase', 'hide', 'ambient', 'tension', 'monster', 'fear'],
    model: 'claude-sonnet',
    costPerCall: 65,
    category: 'build',
    chainable: true,
    defaultChain: ['lighting-expert', 'audio-placer', 'npc-creator'],
    minTier: 'HOBBY',
  },
  {
    id: 'roleplay-world',
    name: 'Roleplay World Builder',
    description: 'Designs roleplay environments with job systems, houses, cars, daily routines, and social interaction mechanics.',
    capabilities: ['roleplay', 'rp', 'job', 'house', 'car', 'routine', 'social', 'life sim', 'adopt'],
    model: 'claude-sonnet',
    costPerCall: 80,
    category: 'build',
    chainable: true,
    defaultChain: ['city-builder', 'npc-creator', 'vehicle-builder'],
    minTier: 'HOBBY',
  },
  {
    id: 'pvp-arena',
    name: 'PvP Arena Builder',
    description: 'Creates competitive PvP arenas: spawn systems, weapon kits, round managers, scoreboard, kill tracking, and map layouts.',
    capabilities: ['pvp', 'arena', 'fight', 'battle', 'spawn', 'round', 'scoreboard', 'kill', 'deathmatch', 'team'],
    model: 'claude-sonnet',
    costPerCall: 65,
    category: 'build',
    chainable: true,
    defaultChain: ['weapon-smith', 'combat-system', 'ui-designer'],
    minTier: 'FREE',
  },
  {
    id: 'racing-track',
    name: 'Racing Track Builder',
    description: 'Designs race tracks with checkpoints, lap systems, boost pads, leaderboards, and vehicle handling configs.',
    capabilities: ['race', 'racing', 'track', 'lap', 'boost', 'drift', 'checkpoint', 'speed', 'kart', 'car'],
    model: 'claude-sonnet',
    costPerCall: 60,
    category: 'build',
    chainable: true,
    defaultChain: ['vehicle-builder', 'script-writer'],
    minTier: 'FREE',
  },
  {
    id: 'story-writer',
    name: 'Story Writer',
    description: 'Writes game narratives, cutscene scripts, NPC dialogues, lore documents, and branching storylines with player choices.',
    capabilities: ['story', 'narrative', 'cutscene', 'dialogue', 'lore', 'branch', 'choice', 'chapter', 'ending'],
    model: 'claude-opus',
    costPerCall: 90,
    category: 'build',
    chainable: true,
    defaultChain: ['quest-writer', 'npc-creator'],
    minTier: 'CREATOR',
  },
  {
    id: 'pet-system',
    name: 'Pet System Builder',
    description: 'Creates complete pet systems: hatching, rarity tiers, evolution, trading, following AI, inventory, and pet stats.',
    capabilities: ['pet', 'hatch', 'egg', 'rarity', 'evolve', 'trade', 'follow', 'inventory', 'legendary', 'mythic'],
    model: 'claude-sonnet',
    costPerCall: 65,
    category: 'build',
    chainable: true,
    defaultChain: ['ui-designer', 'economy-designer'],
    minTier: 'HOBBY',
  },
  {
    id: 'inventory-system',
    name: 'Inventory System',
    description: 'Builds item inventories with DataStore persistence, drag-and-drop UI, stacking, equipping, and item rarity systems.',
    capabilities: ['inventory', 'item', 'backpack', 'equip', 'stack', 'slot', 'drag', 'drop', 'storage', 'chest'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'build',
    chainable: true,
    defaultChain: ['script-writer', 'ui-designer'],
    minTier: 'FREE',
  },
  {
    id: 'datastore-manager',
    name: 'DataStore Manager',
    description: 'Implements robust DataStore/ProfileStore save systems with auto-save, session locking, migration, and data versioning.',
    capabilities: ['datastore', 'save', 'data', 'persist', 'profilestore', 'session', 'migration', 'backup', 'load'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'build',
    chainable: true,
    minTier: 'FREE',
  },
  {
    id: 'animation-creator',
    name: 'Animation Creator',
    description: 'Creates Roblox animations: walk cycles, attack moves, emotes, idle animations, and animation state machines with Animator scripts.',
    capabilities: ['animation', 'animate', 'walk', 'run', 'attack', 'emote', 'idle', 'dance', 'keyframe', 'animator'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'build',
    chainable: true,
    minTier: 'HOBBY',
  },
  {
    id: 'weather-system',
    name: 'Weather System',
    description: 'Creates dynamic weather: rain, snow, fog, thunderstorms, day/night cycles, and seasonal transitions with atmosphere and particle effects.',
    capabilities: ['weather', 'rain', 'snow', 'fog', 'storm', 'thunder', 'day', 'night', 'season', 'atmosphere', 'wind'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'build',
    chainable: true,
    defaultChain: ['lighting-expert', 'particle-fx'],
    minTier: 'FREE',
  },
  {
    id: 'map-painter',
    name: 'Map Painter',
    description: 'Paints terrain materials across the map: grass, sand, rock, mud, snow, ice — creates natural-looking biome transitions.',
    capabilities: ['paint', 'material', 'grass', 'sand', 'rock', 'mud', 'biome', 'transition', 'ground', 'surface'],
    model: 'claude-haiku',
    costPerCall: 30,
    category: 'build',
    chainable: true,
    defaultChain: ['terrain-gen'],
    minTier: 'FREE',
  },
  {
    id: 'water-world',
    name: 'Water World Builder',
    description: 'Creates underwater environments, swimming mechanics, boats, fishing systems, and ocean terrain with coral and sea life.',
    capabilities: ['water', 'ocean', 'swim', 'boat', 'fish', 'fishing', 'underwater', 'coral', 'sea', 'dive', 'beach'],
    model: 'claude-sonnet',
    costPerCall: 60,
    category: 'build',
    chainable: true,
    defaultChain: ['terrain-gen', 'npc-creator'],
    minTier: 'HOBBY',
  },
  {
    id: 'dungeon-generator',
    name: 'Dungeon Generator',
    description: 'Procedurally generates dungeon layouts with rooms, corridors, traps, treasure, boss rooms, and difficulty scaling.',
    capabilities: ['dungeon', 'procedural', 'room', 'corridor', 'trap', 'treasure', 'boss', 'maze', 'roguelike'],
    model: 'claude-sonnet',
    costPerCall: 70,
    category: 'build',
    chainable: true,
    defaultChain: ['combat-system', 'npc-creator'],
    minTier: 'HOBBY',
  },
  {
    id: 'shop-builder',
    name: 'Shop Builder',
    description: 'Creates in-game shops with purchase UIs, currency displays, item previews, Robux integration via GamePasses/DevProducts.',
    capabilities: ['shop', 'store', 'buy', 'purchase', 'gamepass', 'devproduct', 'robux', 'currency', 'premium'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'build',
    chainable: true,
    defaultChain: ['ui-designer', 'economy-designer'],
    minTier: 'FREE',
  },
  {
    id: 'lobby-designer',
    name: 'Lobby Designer',
    description: 'Creates game lobbies with teleport pads, queue systems, voting screens, player count displays, and intermission timers.',
    capabilities: ['lobby', 'teleport', 'queue', 'vote', 'intermission', 'waiting', 'hub', 'portal', 'minigame'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'build',
    chainable: true,
    defaultChain: ['ui-designer', 'script-writer'],
    minTier: 'FREE',
  },
  {
    id: 'tower-defense',
    name: 'Tower Defense Builder',
    description: 'Creates tower defense games: paths, wave spawners, tower placement, upgrade trees, enemy types, and boss waves.',
    capabilities: ['tower defense', 'td', 'wave', 'tower', 'path', 'enemy wave', 'upgrade tree', 'placement'],
    model: 'claude-sonnet',
    costPerCall: 75,
    category: 'build',
    chainable: true,
    defaultChain: ['npc-creator', 'combat-system', 'economy-designer'],
    minTier: 'HOBBY',
  },
  {
    id: 'building-tools',
    name: 'Building Tools Creator',
    description: 'Creates sandbox building tools: place, rotate, resize, delete, copy, color picker, material selector — like Build A Boat or Bloxburg tools.',
    capabilities: ['build tool', 'place', 'rotate', 'resize', 'sandbox', 'creative', 'construction', 'block'],
    model: 'claude-sonnet',
    costPerCall: 65,
    category: 'build',
    chainable: true,
    defaultChain: ['ui-designer', 'script-writer'],
    minTier: 'HOBBY',
  },
  {
    id: 'admin-panel',
    name: 'Admin Panel Builder',
    description: 'Creates in-game admin systems: ban, kick, teleport, speed, fly, spectate, server announcements, and permission tiers.',
    capabilities: ['admin', 'ban', 'kick', 'moderate', 'command', 'permission', 'spectate', 'fly', 'announce'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'build',
    chainable: true,
    minTier: 'FREE',
  },
  {
    id: 'leaderboard-system',
    name: 'Leaderboard System',
    description: 'Creates global and in-game leaderboards with OrderedDataStore, displaying top players, personal bests, and seasonal rankings.',
    capabilities: ['leaderboard', 'rank', 'top', 'score', 'best', 'record', 'season', 'global', 'stats'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'build',
    chainable: true,
    defaultChain: ['ui-designer'],
    minTier: 'FREE',
  },
  {
    id: 'trading-system',
    name: 'Trading System',
    description: 'Builds peer-to-peer trading systems with secure item exchange, trade confirmations, scam prevention, and trade history logging.',
    capabilities: ['trade', 'trading', 'exchange', 'offer', 'accept', 'decline', 'scam prevention', 'peer'],
    model: 'claude-sonnet',
    costPerCall: 60,
    category: 'build',
    chainable: true,
    defaultChain: ['ui-designer', 'datastore-manager'],
    minTier: 'HOBBY',
  },
  {
    id: 'cutscene-director',
    name: 'Cutscene Director',
    description: 'Scripts camera cutscenes with cinematic movements, dialogue overlays, camera shakes, zoom effects, and event triggers.',
    capabilities: ['cutscene', 'camera', 'cinematic', 'pan', 'zoom', 'shake', 'intro', 'outro', 'flyover'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'build',
    chainable: true,
    defaultChain: ['story-writer'],
    minTier: 'HOBBY',
  },
  {
    id: 'minimap-builder',
    name: 'Minimap Builder',
    description: 'Creates in-game minimaps with player tracking, POI markers, fog of war, and zoom controls using ViewportFrames.',
    capabilities: ['minimap', 'map', 'viewport', 'tracking', 'marker', 'radar', 'compass', 'poi'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'build',
    chainable: true,
    defaultChain: ['ui-designer'],
    minTier: 'HOBBY',
  },
  {
    id: 'music-composer',
    name: 'Music Composer',
    description: 'Selects and layers background music, creates adaptive music systems that change with gameplay state, and manages audio zones.',
    capabilities: ['music', 'soundtrack', 'bgm', 'adaptive', 'zone', 'jukebox', 'playlist', 'ambience'],
    model: 'claude-sonnet',
    costPerCall: 40,
    category: 'build',
    chainable: true,
    defaultChain: ['audio-placer'],
    minTier: 'FREE',
  },
  {
    id: 'door-system',
    name: 'Door & Gate System',
    description: 'Creates interactive doors, gates, and barriers with keycards, passcodes, proximity triggers, and team-based access.',
    capabilities: ['door', 'gate', 'keycard', 'passcode', 'barrier', 'lock', 'unlock', 'open', 'close', 'access'],
    model: 'claude-haiku',
    costPerCall: 30,
    category: 'build',
    chainable: true,
    minTier: 'FREE',
  },
  {
    id: 'conveyor-system',
    name: 'Conveyor System',
    description: 'Creates conveyor belts, launchers, teleporters, and transport mechanics for tycoons and factory games.',
    capabilities: ['conveyor', 'belt', 'launcher', 'transport', 'pipe', 'tube', 'teleporter', 'elevator'],
    model: 'claude-haiku',
    costPerCall: 35,
    category: 'build',
    chainable: true,
    minTier: 'FREE',
  },

  // ─── ANALYZE (continued) ────────────────────────────────────────────────────

  {
    id: 'exploit-detector',
    name: 'Exploit Detector',
    description: 'Scans scripts for common exploits: RemoteEvent abuse, speed hacks, noclip, teleport exploits, and anti-cheat bypass patterns.',
    capabilities: ['exploit', 'hack', 'cheat', 'anti-cheat', 'remote abuse', 'speed hack', 'noclip', 'teleport hack'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'analyze',
    chainable: true,
    defaultChain: ['security-checker'],
    minTier: 'HOBBY',
  },
  {
    id: 'memory-profiler',
    name: 'Memory Profiler',
    description: 'Analyzes memory usage patterns: instance leaks, connection leaks, table accumulation, and recommends cleanup strategies.',
    capabilities: ['memory', 'leak', 'garbage', 'instance count', 'connection', 'cleanup', 'destroy', 'profile'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'analyze',
    chainable: true,
    defaultChain: ['performance-auditor'],
    minTier: 'HOBBY',
  },
  {
    id: 'mobile-optimizer',
    name: 'Mobile Optimizer',
    description: 'Analyzes games for mobile performance: touch controls, UI scaling, draw call reduction, LOD suggestions, and memory limits.',
    capabilities: ['mobile', 'phone', 'tablet', 'touch', 'small screen', 'low end', 'fps', 'optimize'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'analyze',
    chainable: true,
    defaultChain: ['performance-auditor'],
    minTier: 'HOBBY',
  },
  {
    id: 'age-rating-checker',
    name: 'Age Rating Checker',
    description: 'Reviews game content for Roblox age rating guidelines: violence levels, text chat filtering, UGC compliance, and COPPA requirements.',
    capabilities: ['age rating', 'coppa', 'content', 'violence', 'filter', 'compliance', 'guideline', 'moderation'],
    model: 'claude-sonnet',
    costPerCall: 40,
    category: 'analyze',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'retention-analyzer',
    name: 'Retention Analyzer',
    description: 'Analyzes game design for player retention: session length, progression hooks, daily rewards, and engagement loops.',
    capabilities: ['retention', 'engagement', 'session', 'daily', 'reward', 'hook', 'loop', 'stickiness', 'dau'],
    model: 'claude-opus',
    costPerCall: 85,
    category: 'analyze',
    chainable: true,
    defaultChain: ['monetization-advisor'],
    minTier: 'CREATOR',
  },
  {
    id: 'localization-checker',
    name: 'Localization Checker',
    description: 'Checks games for localization readiness: hardcoded strings, UI text overflow, RTL support, and translation file generation.',
    capabilities: ['localization', 'language', 'translate', 'i18n', 'string', 'rtl', 'unicode', 'locale'],
    model: 'claude-haiku',
    costPerCall: 30,
    category: 'analyze',
    chainable: false,
    minTier: 'HOBBY',
  },

  // ─── OPTIMIZE (continued) ───────────────────────────────────────────────────

  {
    id: 'render-optimizer',
    name: 'Render Optimizer',
    description: 'Reduces draw calls, optimizes mesh complexity, applies streaming-enabled best practices, and manages LOD groups.',
    capabilities: ['render', 'draw call', 'mesh', 'streaming', 'lod', 'occlusion', 'culling', 'polygon'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'optimize',
    chainable: true,
    defaultChain: ['performance-auditor'],
    minTier: 'HOBBY',
  },
  {
    id: 'network-optimizer',
    name: 'Network Optimizer',
    description: 'Reduces network bandwidth: RemoteEvent batching, data compression, replication filtering, and tick rate optimization.',
    capabilities: ['network', 'bandwidth', 'remote', 'replication', 'latency', 'ping', 'server', 'throttle'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'optimize',
    chainable: true,
    minTier: 'HOBBY',
  },
  {
    id: 'script-optimizer',
    name: 'Script Optimizer',
    description: 'Refactors Luau scripts for performance: loop optimization, table pooling, coroutine usage, and micro-benchmark analysis.',
    capabilities: ['optimize script', 'refactor', 'loop', 'pool', 'coroutine', 'benchmark', 'luau perf', 'fast'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'optimize',
    chainable: true,
    defaultChain: ['code-reviewer'],
    minTier: 'HOBBY',
  },

  // ─── RESEARCH (continued) ──────────────────────────────────────────────────

  {
    id: 'genre-researcher',
    name: 'Genre Researcher',
    description: 'Analyzes top-performing games in any Roblox genre: mechanics breakdown, monetization strategies, UI patterns, and success factors.',
    capabilities: ['genre', 'research', 'top games', 'popular', 'trending', 'discover', 'category', 'inspiration'],
    model: 'claude-opus',
    costPerCall: 80,
    category: 'research',
    chainable: true,
    defaultChain: ['trend-finder'],
    minTier: 'CREATOR',
  },
  {
    id: 'update-planner',
    name: 'Update Planner',
    description: 'Plans game updates: prioritizes features by player impact, creates patch notes, and schedules release timelines.',
    capabilities: ['update', 'patch', 'release', 'roadmap', 'feature priority', 'schedule', 'plan', 'version'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'research',
    chainable: false,
    minTier: 'HOBBY',
  },
  {
    id: 'thumbnail-advisor',
    name: 'Thumbnail Advisor',
    description: 'Designs game icons and thumbnails that maximize click-through: composition, color psychology, text overlay, and A/B test suggestions.',
    capabilities: ['thumbnail', 'icon', 'click', 'cover', 'image', 'banner', 'a/b test', 'ctr'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'research',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'devforum-scout',
    name: 'DevForum Scout',
    description: 'Searches Roblox DevForum patterns: finds solutions, best practices, API changes, and community-tested approaches for your problems.',
    capabilities: ['devforum', 'community', 'solution', 'best practice', 'api change', 'documentation', 'help'],
    model: 'claude-haiku',
    costPerCall: 25,
    category: 'research',
    chainable: false,
    minTier: 'FREE',
  },

  // ─── GROWTH (continued) ─────────────────────────────────────────────────────

  {
    id: 'group-manager',
    name: 'Group Manager',
    description: 'Optimizes Roblox group pages: wall posts, shout scheduling, rank management, group game organization, and member engagement.',
    capabilities: ['group', 'rank', 'member', 'shout', 'wall', 'social', 'clan', 'team'],
    model: 'claude-haiku',
    costPerCall: 30,
    category: 'growth',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'youtube-advisor',
    name: 'YouTube Advisor',
    description: 'Plans YouTube content for game promotion: video ideas, titles, thumbnails, descriptions, tags, and upload schedules.',
    capabilities: ['youtube', 'video', 'content', 'promotion', 'viral', 'upload', 'title', 'tag', 'seo'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'growth',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'tiktok-advisor',
    name: 'TikTok Advisor',
    description: 'Creates TikTok content strategies for game promotion: trending sounds, hook formats, gameplay clips, and viral patterns.',
    capabilities: ['tiktok', 'short', 'viral', 'hook', 'trend', 'clip', 'sound', 'reels', 'shorts'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'growth',
    chainable: false,
    minTier: 'FREE',
  },
  {
    id: 'sponsor-optimizer',
    name: 'Sponsor Optimizer',
    description: 'Optimizes Roblox Sponsored Experiences ads: targeting, budget allocation, bid strategies, and ROI analysis.',
    capabilities: ['sponsor', 'ad', 'advertise', 'bid', 'budget', 'target', 'roi', 'cpi', 'impression'],
    model: 'claude-sonnet',
    costPerCall: 55,
    category: 'growth',
    chainable: false,
    minTier: 'CREATOR',
  },
  {
    id: 'event-planner',
    name: 'Event Planner',
    description: 'Plans in-game events: seasonal updates, limited-time modes, holiday themes, countdown timers, and exclusive rewards.',
    capabilities: ['event', 'seasonal', 'holiday', 'limited time', 'countdown', 'exclusive', 'special', 'celebration'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'growth',
    chainable: true,
    defaultChain: ['ui-designer'],
    minTier: 'HOBBY',
  },
  {
    id: 'badge-designer',
    name: 'Badge Designer',
    description: 'Designs achievement badge systems: milestones, secret badges, progression badges, and notification displays.',
    capabilities: ['badge', 'achievement', 'milestone', 'unlock', 'trophy', 'secret', 'progress', 'award'],
    model: 'claude-haiku',
    costPerCall: 30,
    category: 'growth',
    chainable: true,
    defaultChain: ['ui-designer'],
    minTier: 'FREE',
  },
  {
    id: 'daily-reward-system',
    name: 'Daily Reward System',
    description: 'Creates daily login reward systems: streak bonuses, spinning wheels, mystery boxes, and progressive reward tiers.',
    capabilities: ['daily', 'login', 'streak', 'reward', 'spin', 'wheel', 'mystery box', 'bonus', 'consecutive'],
    model: 'claude-sonnet',
    costPerCall: 45,
    category: 'growth',
    chainable: true,
    defaultChain: ['ui-designer', 'datastore-manager'],
    minTier: 'FREE',
  },
  {
    id: 'gamepass-advisor',
    name: 'GamePass Advisor',
    description: 'Designs GamePass and DevProduct strategies: pricing tiers, value propositions, bundle offers, and conversion optimization.',
    capabilities: ['gamepass', 'devproduct', 'monetize', 'price', 'premium', 'vip', 'bundle', 'pass'],
    model: 'claude-sonnet',
    costPerCall: 50,
    category: 'growth',
    chainable: true,
    defaultChain: ['economy-designer'],
    minTier: 'HOBBY',
  },

  // ─── BUILD — Genre Specialists ──────────────────────────────────────────────

  { id: 'fps-builder', name: 'FPS Builder', description: 'Creates first-person shooter games: weapon viewmodels, recoil systems, hitbox detection, ammo, and reload mechanics.', capabilities: ['fps', 'shooter', 'gun', 'recoil', 'hitbox', 'ammo', 'reload', 'aim'], model: 'claude-sonnet', costPerCall: 70, category: 'build', chainable: true, defaultChain: ['weapon-smith', 'combat-system'], minTier: 'HOBBY' },
  { id: 'rpg-system', name: 'RPG System Builder', description: 'Creates RPG mechanics: XP, leveling, skill trees, stat allocation, classes, and passive abilities.', capabilities: ['rpg', 'xp', 'level', 'skill tree', 'stat', 'class', 'ability', 'passive', 'mana'], model: 'claude-sonnet', costPerCall: 75, category: 'build', chainable: true, defaultChain: ['combat-system', 'ui-designer'], minTier: 'HOBBY' },
  { id: 'survival-builder', name: 'Survival Builder', description: 'Creates survival game systems: hunger, thirst, crafting, base building, resource gathering, and day/night threats.', capabilities: ['survival', 'hunger', 'thirst', 'craft', 'base', 'resource', 'gather', 'build'], model: 'claude-sonnet', costPerCall: 75, category: 'build', chainable: true, defaultChain: ['inventory-system', 'weather-system'], minTier: 'HOBBY' },
  { id: 'puzzle-maker', name: 'Puzzle Maker', description: 'Designs puzzle mechanics: switches, pressure plates, color matching, sequence puzzles, and environmental riddles.', capabilities: ['puzzle', 'switch', 'plate', 'sequence', 'riddle', 'logic', 'match', 'brain teaser'], model: 'claude-sonnet', costPerCall: 50, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'sports-builder', name: 'Sports Game Builder', description: 'Creates sports games: soccer, basketball, football — ball physics, scoring, teams, timer, and referee logic.', capabilities: ['sports', 'soccer', 'basketball', 'football', 'ball', 'goal', 'score', 'team', 'timer'], model: 'claude-sonnet', costPerCall: 60, category: 'build', chainable: true, minTier: 'HOBBY' },
  { id: 'farming-system', name: 'Farming System', description: 'Creates farming games: planting, watering, harvesting, crop growth timers, soil types, and barn storage.', capabilities: ['farm', 'plant', 'harvest', 'crop', 'water', 'grow', 'soil', 'barn', 'seed'], model: 'claude-sonnet', costPerCall: 55, category: 'build', chainable: true, defaultChain: ['economy-designer'], minTier: 'FREE' },
  { id: 'cooking-system', name: 'Cooking System', description: 'Creates cooking game mechanics: recipes, ingredient combining, cooking minigames, restaurant management, and order systems.', capabilities: ['cook', 'recipe', 'ingredient', 'restaurant', 'kitchen', 'order', 'chef', 'food'], model: 'claude-sonnet', costPerCall: 50, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'social-system', name: 'Social System', description: 'Creates friend systems, party invites, trading, gifting, chat channels, and social hubs.', capabilities: ['friend', 'party', 'social', 'gift', 'chat', 'invite', 'hub', 'community'], model: 'claude-sonnet', costPerCall: 55, category: 'build', chainable: true, minTier: 'HOBBY' },
  { id: 'minigame-pack', name: 'Minigame Pack', description: 'Creates collections of minigames: floor is lava, tag, hide and seek, red light green light, musical chairs, and more.', capabilities: ['minigame', 'party', 'floor is lava', 'tag', 'hide seek', 'red light', 'musical chairs'], model: 'claude-sonnet', costPerCall: 65, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'boss-builder', name: 'Boss Builder', description: 'Creates boss fight encounters: attack patterns, phase transitions, health bars, weak points, and cinematic intros.', capabilities: ['boss', 'fight', 'phase', 'attack pattern', 'health bar', 'weak point', 'encounter'], model: 'claude-sonnet', costPerCall: 70, category: 'build', chainable: true, defaultChain: ['combat-system', 'npc-creator'], minTier: 'HOBBY' },

  // ─── BUILD — Environment & Props ────────────────────────────────────────────

  { id: 'tree-generator', name: 'Tree Generator', description: 'Creates procedural trees, bushes, and vegetation with varied species, sizes, and seasonal color variants.', capabilities: ['tree', 'bush', 'vegetation', 'plant', 'leaf', 'branch', 'forest', 'foliage'], model: 'claude-haiku', costPerCall: 25, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'furniture-placer', name: 'Furniture Placer', description: 'Places interior furniture: tables, chairs, beds, shelves, decorations with realistic room layouts.', capabilities: ['furniture', 'table', 'chair', 'bed', 'shelf', 'interior', 'decoration', 'room'], model: 'claude-haiku', costPerCall: 30, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'road-builder', name: 'Road Builder', description: 'Creates road networks: intersections, traffic lights, crosswalks, highways, bridges, and tunnels with lane markings.', capabilities: ['road', 'highway', 'bridge', 'tunnel', 'intersection', 'traffic light', 'lane', 'path'], model: 'claude-sonnet', costPerCall: 45, category: 'build', chainable: true, defaultChain: ['city-builder'], minTier: 'FREE' },
  { id: 'space-builder', name: 'Space Builder', description: 'Creates space environments: planets, asteroids, space stations, zero-gravity physics, and starfields.', capabilities: ['space', 'planet', 'asteroid', 'station', 'galaxy', 'star', 'zero gravity', 'orbit', 'moon'], model: 'claude-sonnet', costPerCall: 65, category: 'build', chainable: true, minTier: 'HOBBY' },
  { id: 'castle-builder', name: 'Castle Builder', description: 'Specializes in medieval castles: walls, towers, keeps, moats, drawbridges, throne rooms, and dungeons.', capabilities: ['castle', 'medieval', 'tower', 'moat', 'drawbridge', 'throne', 'fortress', 'keep'], model: 'claude-sonnet', costPerCall: 60, category: 'build', chainable: true, defaultChain: ['lighting-expert'], minTier: 'FREE' },
  { id: 'ship-builder', name: 'Ship Builder', description: 'Creates ships and boats: pirate ships, yachts, submarines, battleships with functional movement and crew areas.', capabilities: ['ship', 'boat', 'pirate', 'yacht', 'submarine', 'sail', 'naval', 'crew', 'anchor'], model: 'claude-sonnet', costPerCall: 65, category: 'build', chainable: true, defaultChain: ['vehicle-builder'], minTier: 'HOBBY' },
  { id: 'aircraft-builder', name: 'Aircraft Builder', description: 'Creates aircraft: planes, helicopters, jets, and drones with flight physics, controls, and landing systems.', capabilities: ['plane', 'helicopter', 'jet', 'aircraft', 'fly', 'wing', 'propeller', 'landing', 'drone'], model: 'claude-sonnet', costPerCall: 65, category: 'build', chainable: true, defaultChain: ['vehicle-builder'], minTier: 'HOBBY' },
  { id: 'train-system', name: 'Train System', description: 'Creates train systems: tracks, stations, switches, schedules, passenger cars, and automated train routes.', capabilities: ['train', 'rail', 'track', 'station', 'locomotive', 'passenger', 'railway', 'switch'], model: 'claude-sonnet', costPerCall: 60, category: 'build', chainable: true, minTier: 'HOBBY' },
  { id: 'destruction-system', name: 'Destruction System', description: 'Creates destructible environments: breakable walls, explosive barrels, debris physics, and repair mechanics.', capabilities: ['destroy', 'break', 'explode', 'debris', 'destructible', 'demolish', 'collapse', 'explosion'], model: 'claude-sonnet', costPerCall: 55, category: 'build', chainable: true, minTier: 'HOBBY' },
  { id: 'camera-system', name: 'Camera System', description: 'Creates custom camera systems: third-person, isometric, top-down, shoulder cam, and cinematic camera rails.', capabilities: ['camera', 'third person', 'isometric', 'top down', 'shoulder', 'orbit', 'follow', 'viewport'], model: 'claude-sonnet', costPerCall: 45, category: 'build', chainable: true, minTier: 'FREE' },

  // ─── BUILD — Advanced Systems ───────────────────────────────────────────────

  { id: 'matchmaking', name: 'Matchmaking System', description: 'Creates matchmaking: skill-based pairing, queue management, lobby filling, and server teleportation.', capabilities: ['matchmaking', 'queue', 'pair', 'skill based', 'lobby', 'server', 'teleport service'], model: 'claude-sonnet', costPerCall: 60, category: 'build', chainable: true, minTier: 'CREATOR' },
  { id: 'replay-system', name: 'Replay System', description: 'Records and replays gameplay: position tracking, action recording, playback controls, and killcam.', capabilities: ['replay', 'record', 'playback', 'killcam', 'demo', 'rewind', 'slow motion'], model: 'claude-sonnet', costPerCall: 65, category: 'build', chainable: true, minTier: 'CREATOR' },
  { id: 'crafting-system', name: 'Crafting System', description: 'Creates crafting mechanics: recipes, material gathering, workbenches, crafting queues, and blueprint discovery.', capabilities: ['craft', 'recipe', 'material', 'workbench', 'blueprint', 'smelt', 'forge', 'combine'], model: 'claude-sonnet', costPerCall: 55, category: 'build', chainable: true, defaultChain: ['inventory-system', 'ui-designer'], minTier: 'HOBBY' },
  { id: 'zone-system', name: 'Zone System', description: 'Creates area-based systems: safe zones, PvP zones, level-gated areas, capture points, and territory control.', capabilities: ['zone', 'area', 'region', 'territory', 'capture', 'safe zone', 'pvp zone', 'gate'], model: 'claude-sonnet', costPerCall: 50, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'notification-system', name: 'Notification System', description: 'Creates in-game notifications: toast popups, achievement banners, friend alerts, and system messages with queuing.', capabilities: ['notification', 'toast', 'alert', 'popup', 'banner', 'message', 'announce'], model: 'claude-haiku', costPerCall: 25, category: 'build', chainable: true, defaultChain: ['ui-designer'], minTier: 'FREE' },
  { id: 'timer-system', name: 'Timer System', description: 'Creates countdown timers, round clocks, cooldown displays, and time-based event triggers.', capabilities: ['timer', 'countdown', 'clock', 'cooldown', 'round', 'time limit', 'stopwatch'], model: 'claude-haiku', costPerCall: 20, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'team-system', name: 'Team System', description: 'Creates team-based gameplay: auto-balancing, team colors, team spawns, scoreboards, and team-specific tools.', capabilities: ['team', 'auto balance', 'red blue', 'team spawn', 'versus', 'side', 'faction'], model: 'claude-sonnet', costPerCall: 45, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'portals-system', name: 'Portal System', description: 'Creates teleportation portals between places, worlds, or servers using TeleportService with loading screens.', capabilities: ['portal', 'teleport', 'warp', 'world', 'dimension', 'loading screen', 'place'], model: 'claude-sonnet', costPerCall: 45, category: 'build', chainable: true, minTier: 'FREE' },
  { id: 'clothing-system', name: 'Clothing System', description: 'Creates avatar customization: outfit saving, wardrobe UI, accessory equipping, and try-on previews.', capabilities: ['clothing', 'outfit', 'wardrobe', 'accessory', 'avatar', 'customize', 'dress up', 'fashion'], model: 'claude-sonnet', costPerCall: 50, category: 'build', chainable: true, defaultChain: ['ui-designer'], minTier: 'HOBBY' },
  { id: 'magic-system', name: 'Magic System', description: 'Creates magic/ability systems: spell casting, mana management, elemental types, cooldowns, and spell effects.', capabilities: ['magic', 'spell', 'mana', 'elemental', 'cast', 'wizard', 'power', 'ability', 'fireball'], model: 'claude-sonnet', costPerCall: 65, category: 'build', chainable: true, defaultChain: ['particle-fx', 'combat-system'], minTier: 'HOBBY' },
  { id: 'stealth-system', name: 'Stealth System', description: 'Creates stealth mechanics: detection meters, line of sight, noise systems, disguises, and alert states.', capabilities: ['stealth', 'sneak', 'detect', 'line of sight', 'noise', 'disguise', 'alert', 'invisible'], model: 'claude-sonnet', costPerCall: 55, category: 'build', chainable: true, defaultChain: ['npc-creator'], minTier: 'HOBBY' },
  { id: 'dialogue-tree', name: 'Dialogue Tree Builder', description: 'Creates branching dialogue systems with choices, consequences, reputation effects, and voice line triggers.', capabilities: ['dialogue', 'conversation', 'choice', 'branch', 'npc talk', 'reputation', 'response'], model: 'claude-sonnet', costPerCall: 50, category: 'build', chainable: true, defaultChain: ['npc-creator', 'quest-writer'], minTier: 'FREE' },
  { id: 'map-voting', name: 'Map Voting System', description: 'Creates map/mode voting systems between rounds with timer, majority selection, and random tiebreaker.', capabilities: ['map vote', 'mode select', 'vote', 'election', 'round select', 'pick map'], model: 'claude-haiku', costPerCall: 25, category: 'build', chainable: true, defaultChain: ['ui-designer'], minTier: 'FREE' },
  { id: 'gacha-system', name: 'Gacha System', description: 'Creates gacha/loot box mechanics: rarity tiers, pity systems, animation reveals, and pull history tracking.', capabilities: ['gacha', 'loot box', 'pull', 'summon', 'pity', 'rarity', 'banner', 'roll'], model: 'claude-sonnet', costPerCall: 60, category: 'build', chainable: true, defaultChain: ['economy-designer', 'ui-designer'], minTier: 'HOBBY' },
  { id: 'clicker-system', name: 'Clicker System', description: 'Creates idle/clicker game mechanics: auto-clickers, prestige, offline earnings, and exponential scaling.', capabilities: ['clicker', 'idle', 'prestige', 'auto', 'offline', 'incremental', 'tap', 'afk'], model: 'claude-sonnet', costPerCall: 50, category: 'build', chainable: true, defaultChain: ['economy-designer'], minTier: 'FREE' },

  // ─── ANALYZE (more) ─────────────────────────────────────────────────────────

  { id: 'physics-analyzer', name: 'Physics Analyzer', description: 'Analyzes physics usage: constraint optimization, collision group setup, anchoring, and physics step costs.', capabilities: ['physics', 'constraint', 'collision', 'anchor', 'ragdoll', 'joint', 'weld', 'body mover'], model: 'claude-sonnet', costPerCall: 50, category: 'analyze', chainable: true, minTier: 'HOBBY' },
  { id: 'datastore-auditor', name: 'DataStore Auditor', description: 'Audits DataStore usage: rate limiting, key structure, data size, session locking, and backup strategies.', capabilities: ['datastore audit', 'rate limit', 'key structure', 'data size', 'session lock', 'budget'], model: 'claude-sonnet', costPerCall: 45, category: 'analyze', chainable: true, minTier: 'HOBBY' },
  { id: 'script-complexity', name: 'Script Complexity Analyzer', description: 'Measures cyclomatic complexity, nesting depth, function length, and coupling between Luau modules.', capabilities: ['complexity', 'nesting', 'coupling', 'cyclomatic', 'module', 'dependency', 'clean code'], model: 'claude-sonnet', costPerCall: 40, category: 'analyze', chainable: true, defaultChain: ['code-reviewer'], minTier: 'HOBBY' },
  { id: 'sound-auditor', name: 'Sound Auditor', description: 'Audits audio usage: volume balancing, distance falloff, audio ID validity, and SoundGroup organization.', capabilities: ['sound audit', 'volume', 'audio', 'distance', 'falloff', 'soundgroup', 'music'], model: 'claude-haiku', costPerCall: 25, category: 'analyze', chainable: true, minTier: 'FREE' },
  { id: 'part-count-optimizer', name: 'Part Count Optimizer', description: 'Reduces part count via union suggestions, mesh replacements, and CSG operations for better performance.', capabilities: ['part count', 'union', 'csg', 'merge', 'reduce', 'instance count', 'optimization'], model: 'claude-sonnet', costPerCall: 50, category: 'analyze', chainable: true, defaultChain: ['performance-auditor'], minTier: 'HOBBY' },

  // ─── GROWTH (more) ──────────────────────────────────────────────────────────

  { id: 'discord-bot', name: 'Discord Bot Builder', description: 'Creates Discord bot integrations: server stats, game links, role rewards, and webhook notifications.', capabilities: ['discord', 'bot', 'webhook', 'role', 'server', 'notification', 'integration'], model: 'claude-sonnet', costPerCall: 50, category: 'growth', chainable: false, minTier: 'HOBBY' },
  { id: 'game-description', name: 'Game Description Writer', description: 'Writes optimized Roblox game descriptions with keywords, emojis, formatting, and call-to-action.', capabilities: ['description', 'about', 'text', 'keyword', 'seo', 'discover', 'search'], model: 'claude-sonnet', costPerCall: 35, category: 'growth', chainable: false, minTier: 'FREE' },
  { id: 'merch-designer', name: 'Merch Designer', description: 'Creates UGC-ready clothing and accessory designs for the Roblox Avatar Shop with pricing recommendations.', capabilities: ['merch', 'ugc', 'clothing', 'accessory', 'avatar shop', 'design', 'sell'], model: 'claude-sonnet', costPerCall: 55, category: 'growth', chainable: false, minTier: 'CREATOR' },
  { id: 'collab-finder', name: 'Collaboration Finder', description: 'Identifies potential collaboration partners: complementary game devs, YouTubers, and cross-promotion opportunities.', capabilities: ['collab', 'partner', 'cross promote', 'influencer', 'network', 'joint venture'], model: 'claude-sonnet', costPerCall: 50, category: 'growth', chainable: false, minTier: 'CREATOR' },
  { id: 'ab-tester', name: 'A/B Tester', description: 'Sets up A/B testing frameworks: feature flags, variant assignment, metric tracking, and statistical analysis.', capabilities: ['a/b test', 'variant', 'feature flag', 'experiment', 'split test', 'metric', 'conversion'], model: 'claude-sonnet', costPerCall: 55, category: 'growth', chainable: true, minTier: 'CREATOR' },
]

// ─── Lookup helpers ───────────────────────────────────────────────────────────

/** Returns a copy of the full registry — never mutate the returned array */
export function getAllAgents(): AgentDef[] {
  return [...REGISTRY]
}

/** Returns one agent by id, or undefined */
export function getAgent(id: string): AgentDef | undefined {
  return REGISTRY.find((a) => a.id === id)
}

/** Returns all agents in a specific category */
export function getAgentsByCategory(category: AgentCategory): AgentDef[] {
  return REGISTRY.filter((a) => a.category === category)
}

/**
 * Returns the Anthropic model string for a given AgentDef model tier.
 * Update these strings as new Claude releases land.
 */
export function resolveModelId(model: AgentModel): string {
  switch (model) {
    case 'claude-opus':
      return 'claude-opus-4-5'
    case 'claude-sonnet':
      return 'claude-sonnet-4-5'
    case 'claude-haiku':
      return 'claude-haiku-3-5'
  }
}

/** Estimated cost in platform tokens for a model tier + message length */
export function estimateCallCost(agentDef: AgentDef, promptChars: number): number {
  // Base cost from registry + 1 token per ~200 chars of user prompt (rough Luau/text ratio)
  const promptSurcharge = Math.ceil(promptChars / 200)
  return agentDef.costPerCall + promptSurcharge
}
