/**
 * Roblox Builders — pure code-generation functions for every Roblox Studio
 * building operation.  Every exported function returns a self-contained Luau
 * string that can be pasted into the Command Bar or run via robloxstudio_run_script.
 *
 * Design rules:
 *  - Each function is stateless and pure (same params → same output)
 *  - All generated scripts wrap mutations in ChangeHistoryService waypoints
 *  - Realistic stud dimensions (characters are ~5 studs tall)
 *  - Materials and colors map to Roblox Enum.Material / Color3.fromRGB values
 *  - Complex structures group parts into a Model with a descriptive Name
 *  - All anchored = true by default; physics parts are explicit
 *  - No global variable leakage across generated scripts
 */

// ─── Shared helpers ───────────────────────────────────────────────────────────

/** Normalise a Color3-ish value to a Luau Color3.fromRGB(...) literal */
function colorLiteral(color: [number, number, number] | string): string {
  if (Array.isArray(color)) {
    return `Color3.fromRGB(${color[0]}, ${color[1]}, ${color[2]})`
  }
  return color // caller supplied a raw literal like 'Color3.new(1,1,1)'
}

/** Normalise a Vector3-ish value to a Luau Vector3.new(...) literal */
function v3(vec: Vector3Param): string {
  return `Vector3.new(${vec.x}, ${vec.y}, ${vec.z})`
}

function cf(vec: Vector3Param): string {
  return `CFrame.new(${vec.x}, ${vec.y}, ${vec.z})`
}

/** Wrap a Luau script body in a ChangeHistoryService waypoint pair */
function wrapWaypoint(name: string, body: string): string {
  return `-- Auto-generated by ForjeGames roblox-builders
local ChangeHistoryService = game:GetService("ChangeHistoryService")
ChangeHistoryService:SetWaypoint("Before_${name}")

${body}

ChangeHistoryService:SetWaypoint("After_${name}")
`
}

/** Emit a Luau block that creates a BasePart with common properties set */
function emitPart(opts: {
  varName: string
  partClass?: string
  parent?: string
  name: string
  position: Vector3Param
  size: Vector3Param
  color: [number, number, number] | string
  material: string
  anchored?: boolean
  castShadow?: boolean
  transparency?: number
  cframe?: string
}): string {
  const {
    varName,
    partClass = 'Part',
    parent = 'workspace',
    name,
    position,
    size,
    color,
    material,
    anchored = true,
    castShadow = true,
    transparency = 0,
    cframe,
  } = opts

  const pos = cframe ?? cf(position)

  return `local ${varName} = Instance.new("${partClass}")
${varName}.Name = "${name}"
${varName}.Size = ${v3(size)}
${varName}.CFrame = ${pos}
${varName}.Color = ${colorLiteral(color)}
${varName}.Material = Enum.Material.${material}
${varName}.Anchored = ${anchored}
${varName}.CastShadow = ${castShadow}
${varName}.Transparency = ${transparency}
${varName}.Parent = ${parent}`
}

// ─── Shared TypeScript types ──────────────────────────────────────────────────

export interface Vector3Param {
  x: number
  y: number
  z: number
}

// ─── Basic Parts ─────────────────────────────────────────────────────────────

export interface BuildPartParams {
  name: string
  position: Vector3Param
  size: Vector3Param
  color: [number, number, number]
  material: string
  anchored?: boolean
}

export function buildPart(params: BuildPartParams): string {
  const { name, position, size, color, material, anchored = true } = params
  const body = `${emitPart({ varName: 'part', name, position, size, color, material, anchored })}`
  return wrapWaypoint('BuildPart', body)
}

export interface BuildWedgeParams {
  name: string
  position: Vector3Param
  size: Vector3Param
  color: [number, number, number]
  material: string
  rotation?: Vector3Param
}

export function buildWedge(params: BuildWedgeParams): string {
  const { name, position, size, color, material, rotation } = params
  const rot = rotation ?? { x: 0, y: 0, z: 0 }
  const body = `${emitPart({
    varName: 'wedge',
    partClass: 'WedgePart',
    name,
    position,
    size,
    color,
    material,
    cframe: `CFrame.new(${position.x}, ${position.y}, ${position.z}) * CFrame.Angles(math.rad(${rot.x}), math.rad(${rot.y}), math.rad(${rot.z}))`,
  })}`
  return wrapWaypoint('BuildWedge', body)
}

export interface BuildCylinderParams {
  name: string
  position: Vector3Param
  size: Vector3Param
  color: [number, number, number]
  material: string
}

export function buildCylinder(params: BuildCylinderParams): string {
  const { name, position, size, color, material } = params
  const body = `${emitPart({ varName: 'cyl', partClass: 'Part', name, position, size, color, material })}
cyl.Shape = Enum.PartType.Cylinder`
  return wrapWaypoint('BuildCylinder', body)
}

export interface BuildSphereParams {
  name: string
  position: Vector3Param
  size: Vector3Param
  color: [number, number, number]
  material: string
}

export function buildSphere(params: BuildSphereParams): string {
  const { name, position, size, color, material } = params
  const body = `${emitPart({ varName: 'sphere', partClass: 'Part', name, position, size, color, material })}
sphere.Shape = Enum.PartType.Ball`
  return wrapWaypoint('BuildSphere', body)
}

export interface BuildTrussParams {
  name: string
  position: Vector3Param
  size: Vector3Param
}

export function buildTruss(params: BuildTrussParams): string {
  const { name, position, size } = params
  const body = `local truss = Instance.new("TrussPart")
truss.Name = "${name}"
truss.Size = ${v3(size)}
truss.CFrame = ${cf(position)}
truss.Anchored = true
truss.Parent = workspace`
  return wrapWaypoint('BuildTruss', body)
}

// ─── Complex Structures ───────────────────────────────────────────────────────

export interface BuildWallParams {
  start: Vector3Param
  end: Vector3Param
  height: number
  thickness: number
  material: string
  color: [number, number, number]
  windows?: Array<{ offsetAlongWall: number; width: number; windowHeight: number; fromBottom: number }>
}

export function buildWall(params: BuildWallParams): string {
  const { start, end, height, thickness, material, color, windows = [] } = params

  const body = `local model = Instance.new("Model")
model.Name = "Wall"
model.Parent = workspace

local dx = ${end.x} - ${start.x}
local dz = ${end.z} - ${start.z}
local length = math.sqrt(dx * dx + dz * dz)
local angle = math.atan2(dx, dz)
local midX = (${start.x} + ${end.x}) / 2
local midZ = (${start.z} + ${end.z}) / 2
local midY = ${start.y} + ${height / 2}

local wall = Instance.new("Part")
wall.Name = "WallBody"
wall.Size = Vector3.new(${thickness}, ${height}, length)
wall.CFrame = CFrame.new(midX, midY, midZ) * CFrame.Angles(0, angle, 0)
wall.Color = ${colorLiteral(color)}
wall.Material = Enum.Material.${material}
wall.Anchored = true
wall.Parent = model
${
  windows.length === 0
    ? ''
    : `
-- Window cutouts (visual recesses)
${windows
  .map((w, i) => {
    const wCenterY = w.fromBottom + w.windowHeight / 2
    return `local win${i} = Instance.new("Part")
win${i}.Name = "WindowRecess_${i}"
win${i}.Size = Vector3.new(${thickness + 0.2}, ${w.windowHeight}, ${w.width})
win${i}.CFrame = CFrame.new(midX, ${start.y} + ${wCenterY}, midZ) * CFrame.Angles(0, angle, 0) * CFrame.new(0, 0, ${w.offsetAlongWall - length / 2})
win${i}.Color = Color3.fromRGB(140, 200, 220)
win${i}.Material = Enum.Material.Glass
win${i}.Transparency = 0.5
win${i}.Anchored = true
win${i}.Parent = model`
  })
  .join('\n')}
`
}`

  return wrapWaypoint('BuildWall', body)
}

export interface BuildFloorParams {
  position: Vector3Param
  sizeX: number
  sizeZ: number
  material: string
  color: [number, number, number]
  thickness?: number
}

export function buildFloor(params: BuildFloorParams): string {
  const { position, sizeX, sizeZ, material, color, thickness = 1 } = params
  const body = emitPart({
    varName: 'floor',
    name: 'Floor',
    position,
    size: { x: sizeX, y: thickness, z: sizeZ },
    color,
    material,
  })
  return wrapWaypoint('BuildFloor', body)
}

export type RoofStyle = 'flat' | 'gabled' | 'hip'

export interface BuildRoofParams {
  position: Vector3Param
  sizeX: number
  sizeZ: number
  style: RoofStyle
  material: string
  color?: [number, number, number]
  peakHeight?: number
}

export function buildRoof(params: BuildRoofParams): string {
  const { position, sizeX, sizeZ, style, material, color = [120, 80, 60], peakHeight = 4 } = params

  const colorLit = colorLiteral(color)

  let body = `local roofModel = Instance.new("Model")
roofModel.Name = "Roof_${style}"
roofModel.Parent = workspace\n`

  if (style === 'flat') {
    body += emitPart({
      varName: 'roof',
      name: 'RoofFlat',
      position,
      size: { x: sizeX + 2, y: 1, z: sizeZ + 2 },
      color,
      material,
      parent: 'roofModel',
    })
  } else if (style === 'gabled') {
    // Two wedge slopes meeting at a ridge
    body += `
local halfZ = ${sizeZ / 2}
local slope1 = Instance.new("WedgePart")
slope1.Name = "GableSlope1"
slope1.Size = Vector3.new(${sizeX}, ${peakHeight}, halfZ)
slope1.CFrame = CFrame.new(${position.x}, ${position.y + peakHeight / 2}, ${position.z - sizeZ / 4}) * CFrame.Angles(0, 0, 0)
slope1.Color = ${colorLit}
slope1.Material = Enum.Material.${material}
slope1.Anchored = true
slope1.Parent = roofModel

local slope2 = Instance.new("WedgePart")
slope2.Name = "GableSlope2"
slope2.Size = Vector3.new(${sizeX}, ${peakHeight}, halfZ)
slope2.CFrame = CFrame.new(${position.x}, ${position.y + peakHeight / 2}, ${position.z + sizeZ / 4}) * CFrame.Angles(0, math.pi, 0)
slope2.Color = ${colorLit}
slope2.Material = Enum.Material.${material}
slope2.Anchored = true
slope2.Parent = roofModel`
  } else {
    // Hip roof — four wedge faces
    body += `
local hw = ${sizeX / 2}
local hz = ${sizeZ / 2}

local hipFront = Instance.new("WedgePart")
hipFront.Name = "HipFront"
hipFront.Size = Vector3.new(${sizeX}, ${peakHeight}, ${sizeZ / 2})
hipFront.CFrame = CFrame.new(${position.x}, ${position.y + peakHeight / 2}, ${position.z - sizeZ / 4})
hipFront.Color = ${colorLit}
hipFront.Material = Enum.Material.${material}
hipFront.Anchored = true
hipFront.Parent = roofModel

local hipBack = Instance.new("WedgePart")
hipBack.Name = "HipBack"
hipBack.Size = Vector3.new(${sizeX}, ${peakHeight}, ${sizeZ / 2})
hipBack.CFrame = CFrame.new(${position.x}, ${position.y + peakHeight / 2}, ${position.z + sizeZ / 4}) * CFrame.Angles(0, math.pi, 0)
hipBack.Color = ${colorLit}
hipBack.Material = Enum.Material.${material}
hipBack.Anchored = true
hipBack.Parent = roofModel`
  }

  return wrapWaypoint('BuildRoof', body)
}

export interface BuildStairsParams {
  start: Vector3Param
  end: Vector3Param
  steps: number
  width: number
  material: string
  color?: [number, number, number]
}

export function buildStairs(params: BuildStairsParams): string {
  const { start, end, steps, width, material, color = [180, 160, 140] } = params

  const body = `local stairsModel = Instance.new("Model")
stairsModel.Name = "Stairs"
stairsModel.Parent = workspace

local totalHeight = ${end.y} - ${start.y}
local totalDepth = math.sqrt((${end.x} - ${start.x})^2 + (${end.z} - ${start.z})^2)
local stepH = totalHeight / ${steps}
local stepD = totalDepth / ${steps}
local dirX = (${end.x} - ${start.x}) / ${steps}
local dirZ = (${end.z} - ${start.z}) / ${steps}

for i = 0, ${steps - 1} do
  local step = Instance.new("Part")
  step.Name = "Step_" .. i
  step.Size = Vector3.new(${width}, stepH, stepD)
  step.CFrame = CFrame.new(
    ${start.x} + dirX * i + dirX / 2,
    ${start.y} + stepH * i + stepH / 2,
    ${start.z} + dirZ * i + dirZ / 2
  )
  step.Color = ${colorLiteral(color)}
  step.Material = Enum.Material.${material}
  step.Anchored = true
  step.Parent = stairsModel
end`

  return wrapWaypoint('BuildStairs', body)
}

export type DoorStyle = 'single' | 'double' | 'arch'

export interface BuildDoorParams {
  position: Vector3Param
  size: Vector3Param
  style: DoorStyle
  color?: [number, number, number]
  material?: string
  wallThickness?: number
}

export function buildDoor(params: BuildDoorParams): string {
  const { position, size, style, color = [100, 60, 30], material = 'Wood', wallThickness = 1 } = params
  const frameThick = 0.4

  const body = `local doorModel = Instance.new("Model")
doorModel.Name = "Door_${style}"
doorModel.Parent = workspace

-- Door frame
local frameThick = ${frameThick}
local frameParts = {
  {size = Vector3.new(frameThick, ${size.y}, ${wallThickness + 0.2}), offset = Vector3.new(-${size.x / 2 + frameThick / 2}, 0, 0)},
  {size = Vector3.new(frameThick, ${size.y}, ${wallThickness + 0.2}), offset = Vector3.new(${size.x / 2 + frameThick / 2}, 0, 0)},
  {size = Vector3.new(${size.x + frameThick * 2}, frameThick, ${wallThickness + 0.2}), offset = Vector3.new(0, ${size.y / 2 + frameThick / 2}, 0)},
}
for i, fp in ipairs(frameParts) do
  local f = Instance.new("Part")
  f.Name = "Frame_" .. i
  f.Size = fp.size
  f.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z}) * CFrame.new(fp.offset)
  f.Color = ${colorLiteral(color)}
  f.Material = Enum.Material.${material}
  f.Anchored = true
  f.Parent = doorModel
end

-- Door panel(s)
${
  style === 'double'
    ? `for _, side in ipairs({-1, 1}) do
  local panel = Instance.new("Part")
  panel.Name = "DoorPanel_" .. side
  panel.Size = Vector3.new(${size.x / 2 - 0.1}, ${size.y - 0.2}, 0.15)
  panel.CFrame = CFrame.new(${position.x} + side * ${size.x / 4}, ${position.y}, ${position.z})
  panel.Color = ${colorLiteral(color)}
  panel.Material = Enum.Material.${material}
  panel.Anchored = true
  panel.Parent = doorModel
end`
    : `local panel = Instance.new("Part")
panel.Name = "DoorPanel"
panel.Size = Vector3.new(${size.x - 0.2}, ${size.y - 0.2}, 0.15)
panel.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z})
panel.Color = ${colorLiteral(color)}
panel.Material = Enum.Material.${material}
panel.Anchored = true
panel.Parent = doorModel`
}`

  return wrapWaypoint('BuildDoor', body)
}

export type WindowStyle = 'single' | 'double' | 'round'

export interface BuildWindowParams {
  position: Vector3Param
  size: Vector3Param
  style: WindowStyle
  frameColor?: [number, number, number]
}

export function buildWindow(params: BuildWindowParams): string {
  const { position, size, style, frameColor = [220, 220, 220] } = params
  const frameThick = 0.3

  const body = `local winModel = Instance.new("Model")
winModel.Name = "Window_${style}"
winModel.Parent = workspace

local frameThick = ${frameThick}
-- Outer frame sides
local sides = {
  {sz = Vector3.new(frameThick, ${size.y}, frameThick), off = Vector3.new(-${size.x / 2}, 0, 0)},
  {sz = Vector3.new(frameThick, ${size.y}, frameThick), off = Vector3.new(${size.x / 2}, 0, 0)},
  {sz = Vector3.new(${size.x + frameThick * 2}, frameThick, frameThick), off = Vector3.new(0, ${size.y / 2}, 0)},
  {sz = Vector3.new(${size.x + frameThick * 2}, frameThick, frameThick), off = Vector3.new(0, -${size.y / 2}, 0)},
}
for i, s in ipairs(sides) do
  local fr = Instance.new("Part")
  fr.Name = "Frame_" .. i
  fr.Size = s.sz
  fr.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z}) * CFrame.new(s.off)
  fr.Color = ${colorLiteral(frameColor)}
  fr.Material = Enum.Material.SmoothPlastic
  fr.Anchored = true
  fr.Parent = winModel
end

-- Glass pane
local glass = Instance.new("Part")
glass.Name = "Glass"
glass.Size = Vector3.new(${size.x - 0.1}, ${size.y - 0.1}, 0.1)
glass.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z})
glass.Color = Color3.fromRGB(140, 200, 220)
glass.Material = Enum.Material.Glass
glass.Transparency = 0.4
glass.Anchored = true
glass.Parent = winModel

${
  style === 'round'
    ? `-- Round top cylinder accent
local arc = Instance.new("Part")
arc.Shape = Enum.PartType.Cylinder
arc.Name = "RoundTop"
arc.Size = Vector3.new(0.15, ${size.x}, ${size.x})
arc.CFrame = CFrame.new(${position.x}, ${position.y + size.y / 2}, ${position.z}) * CFrame.Angles(0, 0, math.rad(90))
arc.Color = ${colorLiteral(frameColor)}
arc.Material = Enum.Material.SmoothPlastic
arc.Transparency = 0.6
arc.Anchored = true
arc.Parent = winModel`
    : ''
}`

  return wrapWaypoint('BuildWindow', body)
}

export type FenceStyle = 'wood' | 'iron' | 'chain'

export interface BuildFenceParams {
  points: Vector3Param[]
  height: number
  style: FenceStyle
  spacing?: number
}

export function buildFence(params: BuildFenceParams): string {
  const { points, height, style, spacing = 3 } = params

  const colors: Record<FenceStyle, string> = {
    wood: 'Color3.fromRGB(120, 80, 50)',
    iron: 'Color3.fromRGB(60, 60, 70)',
    chain: 'Color3.fromRGB(140, 130, 100)',
  }
  const materials: Record<FenceStyle, string> = {
    wood: 'Wood',
    iron: 'Metal',
    chain: 'Metal',
  }

  const body = `local fenceModel = Instance.new("Model")
fenceModel.Name = "Fence_${style}"
fenceModel.Parent = workspace

local fenceColor = ${colors[style]}
local fenceMat = Enum.Material.${materials[style]}
local postSize = Vector3.new(0.4, ${height}, 0.4)
local railH = ${height * 0.7}
local railSize = Vector3.new(0.2, 0.2, 0)

local pts = {
${points.map((p) => `  Vector3.new(${p.x}, ${p.y}, ${p.z}),`).join('\n')}
}

for i = 1, #pts - 1 do
  local a, b = pts[i], pts[i + 1]
  local dx, dz = b.X - a.X, b.Z - a.Z
  local segLen = math.sqrt(dx*dx + dz*dz)
  local angle = math.atan2(dx, dz)
  local numPosts = math.ceil(segLen / ${spacing}) + 1

  -- Rail beam
  local rail = Instance.new("Part")
  rail.Name = "Rail_" .. i
  rail.Size = Vector3.new(0.2, 0.2, segLen)
  rail.CFrame = CFrame.new((a.X+b.X)/2, a.Y + railH, (a.Z+b.Z)/2) * CFrame.Angles(0, angle, 0)
  rail.Color = fenceColor
  rail.Material = fenceMat
  rail.Anchored = true
  rail.Parent = fenceModel

  -- Posts
  for j = 0, numPosts - 1 do
    local t = j / math.max(numPosts - 1, 1)
    local px = a.X + dx * t
    local pz = a.Z + dz * t
    local post = Instance.new("Part")
    post.Name = "Post_" .. i .. "_" .. j
    post.Size = postSize
    post.CFrame = CFrame.new(px, a.Y + ${height / 2}, pz)
    post.Color = fenceColor
    post.Material = fenceMat
    post.Anchored = true
    post.Parent = fenceModel
  end
end`

  return wrapWaypoint('BuildFence', body)
}

export type BridgeStyle = 'wood' | 'stone' | 'suspension'

export interface BuildBridgeParams {
  start: Vector3Param
  end: Vector3Param
  width: number
  style: BridgeStyle
}

export function buildBridge(params: BuildBridgeParams): string {
  const { start, end, width, style } = params

  const body = `local bridgeModel = Instance.new("Model")
bridgeModel.Name = "Bridge_${style}"
bridgeModel.Parent = workspace

local ax, ay, az = ${start.x}, ${start.y}, ${start.z}
local bx, by, bz = ${end.x}, ${end.y}, ${end.z}
local dx, dz = bx - ax, bz - az
local length = math.sqrt(dx*dx + dz*dz)
local angle = math.atan2(dx, dz)
local midX, midY, midZ = (ax+bx)/2, (ay+by)/2, (az+bz)/2

-- Deck
local deck = Instance.new("Part")
deck.Name = "BridgeDeck"
deck.Size = Vector3.new(${width}, 0.8, length)
deck.CFrame = CFrame.new(midX, midY, midZ) * CFrame.Angles(0, angle, 0)
deck.Color = ${style === 'wood' ? 'Color3.fromRGB(120, 80, 50)' : style === 'stone' ? 'Color3.fromRGB(150, 140, 130)' : 'Color3.fromRGB(80, 80, 90)'}
deck.Material = ${style === 'wood' ? 'Enum.Material.Wood' : style === 'stone' ? 'Enum.Material.Cobblestone' : 'Enum.Material.Metal'}
deck.Anchored = true
deck.Parent = bridgeModel

${
  style === 'suspension'
    ? `-- Suspension towers
for _, side in ipairs({-1, 1}) do
  local tower = Instance.new("Part")
  tower.Name = "Tower_" .. side
  tower.Size = Vector3.new(1, 12, 1)
  tower.CFrame = CFrame.new(midX + side * (length * 0.35), midY + 6, midZ) * CFrame.Angles(0, angle, 0)
  tower.Color = Color3.fromRGB(80, 80, 90)
  tower.Material = Enum.Material.Metal
  tower.Anchored = true
  tower.Parent = bridgeModel
end`
    : `-- Side rails
for _, side in ipairs({-1, 1}) do
  local rail = Instance.new("Part")
  rail.Name = "Rail_" .. side
  rail.Size = Vector3.new(0.4, 3, length)
  rail.CFrame = CFrame.new(midX, midY + 1.5, midZ) * CFrame.Angles(0, angle, 0) * CFrame.new(side * ${width / 2}, 0, 0)
  rail.Color = deck.Color
  rail.Material = deck.Material
  rail.Anchored = true
  rail.Parent = bridgeModel
end`
}`

  return wrapWaypoint('BuildBridge', body)
}

// ─── Buildings (Compound) ─────────────────────────────────────────────────────

export type HouseStyle = 'cottage' | 'modern' | 'tudor' | 'cabin'

export interface BuildHouseParams {
  position: Vector3Param
  floors?: number
  style?: HouseStyle
  material?: string
  color?: [number, number, number]
  roofColor?: [number, number, number]
  windows?: boolean
  door?: boolean
  floorHeight?: number
  footprintX?: number
  footprintZ?: number
}

export function buildHouse(params: BuildHouseParams): string {
  const {
    position,
    floors = 1,
    style = 'cottage',
    material = 'Brick',
    color = [200, 180, 160],
    roofColor = [100, 70, 50],
    windows = true,
    door = true,
    floorHeight = 8,
    footprintX = 18,
    footprintZ = 14,
  } = params

  const wallThick = 1
  const totalHeight = floors * floorHeight
  const colorLit = colorLiteral(color)
  const roofColorLit = colorLiteral(roofColor)

  const body = `local houseModel = Instance.new("Model")
houseModel.Name = "House_${style}"
houseModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}
local fw, fd = ${footprintX}, ${footprintZ}
local wallH = ${totalHeight}
local wallT = ${wallThick}

-- Foundation slab
local foundation = Instance.new("Part")
foundation.Name = "Foundation"
foundation.Size = Vector3.new(fw + 2, 1, fd + 2)
foundation.CFrame = CFrame.new(px, py - 0.5, pz)
foundation.Color = Color3.fromRGB(160, 150, 140)
foundation.Material = Enum.Material.Concrete
foundation.Anchored = true
foundation.Parent = houseModel

-- Walls (four sides)
local wallDefs = {
  {sz = Vector3.new(fw, wallH, wallT), off = Vector3.new(0, wallH/2, -fd/2)}, -- front
  {sz = Vector3.new(fw, wallH, wallT), off = Vector3.new(0, wallH/2,  fd/2)}, -- back
  {sz = Vector3.new(wallT, wallH, fd), off = Vector3.new(-fw/2, wallH/2, 0)}, -- left
  {sz = Vector3.new(wallT, wallH, fd), off = Vector3.new( fw/2, wallH/2, 0)}, -- right
}
for i, wd in ipairs(wallDefs) do
  local wall = Instance.new("Part")
  wall.Name = "Wall_" .. i
  wall.Size = wd.sz
  wall.CFrame = CFrame.new(px, py, pz) * CFrame.new(wd.off)
  wall.Color = ${colorLit}
  wall.Material = Enum.Material.${material}
  wall.Anchored = true
  wall.Parent = houseModel
end

-- Floor
local floor = Instance.new("Part")
floor.Name = "Floor"
floor.Size = Vector3.new(fw - wallT*2, 0.5, fd - wallT*2)
floor.CFrame = CFrame.new(px, py + 0.25, pz)
floor.Color = Color3.fromRGB(180, 160, 130)
floor.Material = Enum.Material.Wood
floor.Anchored = true
floor.Parent = houseModel

-- Ceiling
local ceiling = Instance.new("Part")
ceiling.Name = "Ceiling"
ceiling.Size = Vector3.new(fw - wallT*2, 0.5, fd - wallT*2)
ceiling.CFrame = CFrame.new(px, py + wallH - 0.25, pz)
ceiling.Color = Color3.fromRGB(230, 220, 200)
ceiling.Material = Enum.Material.SmoothPlastic
ceiling.Anchored = true
ceiling.Parent = houseModel

-- Gabled roof
local halfFD = fd / 2
local peakH = ${style === 'cottage' ? 5 : style === 'cabin' ? 6 : 4}

local roofSlope1 = Instance.new("WedgePart")
roofSlope1.Name = "RoofSlope1"
roofSlope1.Size = Vector3.new(fw + 2, peakH, halfFD + 1)
roofSlope1.CFrame = CFrame.new(px, py + wallH + peakH/2, pz - halfFD/2 - 0.5)
roofSlope1.Color = ${roofColorLit}
roofSlope1.Material = Enum.Material.${style === 'cabin' ? 'Wood' : 'Slate'}
roofSlope1.Anchored = true
roofSlope1.Parent = houseModel

local roofSlope2 = Instance.new("WedgePart")
roofSlope2.Name = "RoofSlope2"
roofSlope2.Size = Vector3.new(fw + 2, peakH, halfFD + 1)
roofSlope2.CFrame = CFrame.new(px, py + wallH + peakH/2, pz + halfFD/2 + 0.5) * CFrame.Angles(0, math.pi, 0)
roofSlope2.Color = ${roofColorLit}
roofSlope2.Material = roofSlope1.Material
roofSlope2.Anchored = true
roofSlope2.Parent = houseModel

${
  door
    ? `-- Door opening (bright interior visible)
local doorPanel = Instance.new("Part")
doorPanel.Name = "Door"
doorPanel.Size = Vector3.new(4, 6, 0.2)
doorPanel.CFrame = CFrame.new(px, py + 3, pz - fd/2 - 0.01)
doorPanel.Color = Color3.fromRGB(100, 60, 30)
doorPanel.Material = Enum.Material.Wood
doorPanel.Anchored = true
doorPanel.Parent = houseModel`
    : ''
}

${
  windows
    ? `-- Windows (front and back walls)
local windowPositions = {
  Vector3.new(px - fw/4, py + wallH/2, pz - fd/2 - 0.01),
  Vector3.new(px + fw/4, py + wallH/2, pz - fd/2 - 0.01),
  Vector3.new(px - fw/4, py + wallH/2, pz + fd/2 + 0.01),
  Vector3.new(px + fw/4, py + wallH/2, pz + fd/2 + 0.01),
}
for i, wpos in ipairs(windowPositions) do
  local win = Instance.new("Part")
  win.Name = "Window_" .. i
  win.Size = Vector3.new(3, 3, 0.15)
  win.CFrame = CFrame.new(wpos)
  win.Color = Color3.fromRGB(140, 200, 220)
  win.Material = Enum.Material.Glass
  win.Transparency = 0.3
  win.Anchored = true
  win.Parent = houseModel
end`
    : ''
}`

  return wrapWaypoint('BuildHouse', body)
}

export interface BuildCastleParams {
  position: Vector3Param
  size?: number
  towers?: number
  wallHeight?: number
  towerHeight?: number
  material?: string
  color?: [number, number, number]
  moat?: boolean
  gate?: boolean
}

export function buildCastle(params: BuildCastleParams): string {
  const {
    position,
    size = 60,
    towers = 4,
    wallHeight = 14,
    towerHeight = 20,
    material = 'Cobblestone',
    color = [160, 150, 140],
    moat = false,
    gate = true,
  } = params

  const body = `local castleModel = Instance.new("Model")
castleModel.Name = "Castle"
castleModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}
local half = ${size / 2}
local wallH = ${wallHeight}
local wallT = 4
local castleColor = ${colorLiteral(color)}
local castleMat = Enum.Material.${material}

-- Four curtain walls
local walls = {
  {sz = Vector3.new(${size}, wallH, wallT), cf = CFrame.new(px, py + wallH/2, pz - half)},
  {sz = Vector3.new(${size}, wallH, wallT), cf = CFrame.new(px, py + wallH/2, pz + half)},
  {sz = Vector3.new(wallT, wallH, ${size}), cf = CFrame.new(px - half, py + wallH/2, pz)},
  {sz = Vector3.new(wallT, wallH, ${size}), cf = CFrame.new(px + half, py + wallH/2, pz)},
}
for i, w in ipairs(walls) do
  local wall = Instance.new("Part")
  wall.Name = "Wall_" .. i
  wall.Size = w.sz
  wall.CFrame = w.cf
  wall.Color = castleColor
  wall.Material = castleMat
  wall.Anchored = true
  wall.Parent = castleModel
end

-- Corner towers
local towerPositions = {
  Vector3.new(px - half, py, pz - half),
  Vector3.new(px + half, py, pz - half),
  Vector3.new(px - half, py, pz + half),
  Vector3.new(px + half, py, pz + half),
}
for i = 1, ${Math.min(towers, 4)} do
  local tp = towerPositions[i]
  local tower = Instance.new("Part")
  tower.Name = "Tower_" .. i
  tower.Size = Vector3.new(8, ${towerHeight}, 8)
  tower.CFrame = CFrame.new(tp.X, py + ${towerHeight / 2}, tp.Z)
  tower.Color = castleColor
  tower.Material = castleMat
  tower.Anchored = true
  tower.Parent = castleModel

  -- Battlements on top
  for b = 0, 3 do
    local merlon = Instance.new("Part")
    merlon.Name = "Merlon_" .. i .. "_" .. b
    merlon.Size = Vector3.new(2, 2, 2)
    local ba = (b / 4) * math.pi * 2
    merlon.CFrame = CFrame.new(tp.X + math.cos(ba)*3, py + ${towerHeight} + 1, tp.Z + math.sin(ba)*3)
    merlon.Color = castleColor
    merlon.Material = castleMat
    merlon.Anchored = true
    merlon.Parent = castleModel
  end

  -- Conical tower roof
  local cone = Instance.new("Part")
  cone.Shape = Enum.PartType.Ball
  cone.Name = "TowerRoof_" .. i
  cone.Size = Vector3.new(9, 6, 9)
  cone.CFrame = CFrame.new(tp.X, py + ${towerHeight} + 3, tp.Z)
  cone.Color = Color3.fromRGB(80, 60, 100)
  cone.Material = Enum.Material.Slate
  cone.Anchored = true
  cone.Parent = castleModel
end

${
  gate
    ? `-- Gatehouse arch
local gateBase = Instance.new("Part")
gateBase.Name = "GateBase"
gateBase.Size = Vector3.new(10, wallH, wallT + 4)
gateBase.CFrame = CFrame.new(px, py + wallH/2, pz - half - 2)
gateBase.Color = castleColor
gateBase.Material = castleMat
gateBase.Anchored = true
gateBase.Parent = castleModel

local gateArch = Instance.new("Part")
gateArch.Name = "GateOpening"
gateArch.Size = Vector3.new(5, 8, wallT + 5)
gateArch.CFrame = CFrame.new(px, py + 4, pz - half - 2)
gateArch.Color = Color3.fromRGB(20, 20, 20)
gateArch.Material = Enum.Material.SmoothPlastic
gateArch.Anchored = true
gateArch.Parent = castleModel`
    : ''
}

${
  moat
    ? `-- Moat (water ring)
local moatParts = {
  {sz = Vector3.new(${size + 24}, 2, 8), cf = CFrame.new(px, py - 1, pz - half - 4)},
  {sz = Vector3.new(${size + 24}, 2, 8), cf = CFrame.new(px, py - 1, pz + half + 4)},
  {sz = Vector3.new(8, 2, ${size}),      cf = CFrame.new(px - half - 4, py - 1, pz)},
  {sz = Vector3.new(8, 2, ${size}),      cf = CFrame.new(px + half + 4, py - 1, pz)},
}
for i, mp in ipairs(moatParts) do
  local moatPart = Instance.new("Part")
  moatPart.Name = "Moat_" .. i
  moatPart.Size = mp.sz
  moatPart.CFrame = mp.cf
  moatPart.Color = Color3.fromRGB(40, 80, 120)
  moatPart.Material = Enum.Material.Water
  moatPart.Anchored = true
  moatPart.Transparency = 0.3
  moatPart.Parent = castleModel
end`
    : ''
}`

  return wrapWaypoint('BuildCastle', body)
}

export type ShopType = 'general' | 'weapon' | 'potion'

export interface BuildShopParams {
  position: Vector3Param
  type?: ShopType
  sign?: string
  color?: [number, number, number]
}

export function buildShop(params: BuildShopParams): string {
  const { position, type = 'general', sign = type.toUpperCase() + ' SHOP', color = [200, 170, 130] } = params

  const accentColors: Record<ShopType, string> = {
    general: 'Color3.fromRGB(220, 180, 60)',
    weapon: 'Color3.fromRGB(180, 60, 60)',
    potion: 'Color3.fromRGB(100, 60, 180)',
  }

  const body = `local shopModel = Instance.new("Model")
shopModel.Name = "Shop_${type}"
shopModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}
local accentColor = ${accentColors[type]}
local wallColor = ${colorLiteral(color)}

-- Main structure
local dims = {
  {name="FrontWall", sz=Vector3.new(14, 10, 1), off=Vector3.new(0, 5, -7)},
  {name="BackWall",  sz=Vector3.new(14, 10, 1), off=Vector3.new(0, 5,  7)},
  {name="LeftWall",  sz=Vector3.new(1, 10, 14), off=Vector3.new(-7, 5, 0)},
  {name="RightWall", sz=Vector3.new(1, 10, 14), off=Vector3.new( 7, 5, 0)},
  {name="Floor",     sz=Vector3.new(14, 0.5,14), off=Vector3.new(0, 0.25, 0)},
}
for _, d in ipairs(dims) do
  local p = Instance.new("Part")
  p.Name = d.name
  p.Size = d.sz
  p.CFrame = CFrame.new(px, py, pz) * CFrame.new(d.off)
  p.Color = wallColor
  p.Material = Enum.Material.Brick
  p.Anchored = true
  p.Parent = shopModel
end

-- Awning
local awning = Instance.new("WedgePart")
awning.Name = "Awning"
awning.Size = Vector3.new(14, 1.5, 4)
awning.CFrame = CFrame.new(px, py + 9, pz - 9) * CFrame.Angles(math.rad(-20), 0, 0)
awning.Color = accentColor
awning.Material = Enum.Material.Fabric
awning.Anchored = true
awning.Parent = shopModel

-- Roof
local roof = Instance.new("Part")
roof.Name = "Roof"
roof.Size = Vector3.new(15, 0.5, 15)
roof.CFrame = CFrame.new(px, py + 10.25, pz)
roof.Color = ${colorLiteral([80, 60, 40])}
roof.Material = Enum.Material.Slate
roof.Anchored = true
roof.Parent = shopModel

-- Sign billboard
local signPart = Instance.new("Part")
signPart.Name = "SignPart"
signPart.Size = Vector3.new(10, 2.5, 0.3)
signPart.CFrame = CFrame.new(px, py + 12, pz - 7.1)
signPart.Color = accentColor
signPart.Material = Enum.Material.SmoothPlastic
signPart.Anchored = true
signPart.Parent = shopModel

local billboard = Instance.new("BillboardGui")
billboard.Size = UDim2.new(0, 300, 0, 75)
billboard.StudsOffset = Vector3.new(0, 0, 0.2)
billboard.AlwaysOnTop = false
billboard.Parent = signPart

local signLabel = Instance.new("TextLabel")
signLabel.Size = UDim2.fromScale(1, 1)
signLabel.BackgroundTransparency = 1
signLabel.Text = "${sign}"
signLabel.TextScaled = true
signLabel.Font = Enum.Font.GothamBold
signLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
signLabel.Parent = billboard`

  return wrapWaypoint('BuildShop', body)
}

export type SkyscraperStyle = 'modern' | 'art-deco'

export interface BuildSkyscraperParams {
  position: Vector3Param
  floors?: number
  style?: SkyscraperStyle
  color?: [number, number, number]
  glassColor?: [number, number, number]
  footprintX?: number
  footprintZ?: number
}

export function buildSkyscraper(params: BuildSkyscraperParams): string {
  const {
    position,
    floors = 15,
    style = 'modern',
    color = [180, 190, 200],
    glassColor = [120, 180, 220],
    footprintX = 20,
    footprintZ = 20,
  } = params

  const floorH = 4
  const totalH = floors * floorH

  const body = `local skyscraperModel = Instance.new("Model")
skyscraperModel.Name = "Skyscraper_${style}"
skyscraperModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}
local fw, fd = ${footprintX}, ${footprintZ}
local totalH = ${totalH}
local floorH = ${floorH}

-- Core structural column
local core = Instance.new("Part")
core.Name = "Core"
core.Size = Vector3.new(fw, totalH, fd)
core.CFrame = CFrame.new(px, py + totalH/2, pz)
core.Color = ${colorLiteral(color)}
core.Material = Enum.Material.${style === 'art-deco' ? 'Marble' : 'SmoothPlastic'}
core.Anchored = true
core.Parent = skyscraperModel

-- Glass curtain wall panels (every floor, 4 sides)
local panelThick = 0.3
local sides = {
  {off = Vector3.new(0, 0, -fd/2 - panelThick/2), sz = Vector3.new(fw - 1, floorH - 0.4, panelThick)},
  {off = Vector3.new(0, 0,  fd/2 + panelThick/2), sz = Vector3.new(fw - 1, floorH - 0.4, panelThick)},
  {off = Vector3.new(-fw/2 - panelThick/2, 0, 0), sz = Vector3.new(panelThick, floorH - 0.4, fd - 1)},
  {off = Vector3.new( fw/2 + panelThick/2, 0, 0), sz = Vector3.new(panelThick, floorH - 0.4, fd - 1)},
}

for floor = 0, ${floors - 1} do
  local floorCenterY = py + floor * floorH + floorH/2
  for si, s in ipairs(sides) do
    local glass = Instance.new("Part")
    glass.Name = "Glass_" .. floor .. "_" .. si
    glass.Size = s.sz
    glass.CFrame = CFrame.new(px + s.off.X, floorCenterY + s.off.Y, pz + s.off.Z)
    glass.Color = ${colorLiteral(glassColor)}
    glass.Material = Enum.Material.Glass
    glass.Transparency = ${style === 'art-deco' ? 0.5 : 0.35}
    glass.Anchored = true
    glass.Parent = skyscraperModel
  end
end

${
  style === 'art-deco'
    ? `-- Art-deco spire
local spire = Instance.new("Part")
spire.Name = "Spire"
spire.Shape = Enum.PartType.Cylinder
spire.Size = Vector3.new(1, 20, 1)
spire.CFrame = CFrame.new(px, py + totalH + 10, pz)
spire.Color = Color3.fromRGB(220, 190, 100)
spire.Material = Enum.Material.Metal
spire.Anchored = true
spire.Parent = skyscraperModel`
    : `-- Modern antenna
local antenna = Instance.new("Part")
antenna.Name = "Antenna"
antenna.Shape = Enum.PartType.Cylinder
antenna.Size = Vector3.new(0.5, 12, 0.5)
antenna.CFrame = CFrame.new(px, py + totalH + 6, pz)
antenna.Color = Color3.fromRGB(200, 200, 210)
antenna.Material = Enum.Material.Metal
antenna.Anchored = true
antenna.Parent = skyscraperModel`
}`

  return wrapWaypoint('BuildSkyscraper', body)
}

// ─── Terrain ──────────────────────────────────────────────────────────────────

export type Biome = 'grass' | 'desert' | 'snow' | 'forest' | 'swamp' | 'volcanic'

export interface BuildTerrainParams {
  biome: Biome
  sizeX: number
  sizeZ: number
  heightScale?: number
  waterLevel?: number
  position?: Vector3Param
}

export function buildTerrain(params: BuildTerrainParams): string {
  const { biome, sizeX, sizeZ, heightScale = 20, waterLevel = 0, position = { x: 0, y: 0, z: 0 } } = params

  const biomeMaterials: Record<Biome, { surface: string; fill: string; water: string }> = {
    grass: { surface: 'Grass', fill: 'Ground', water: 'Water' },
    desert: { surface: 'Sand', fill: 'Sand', water: 'Water' },
    snow: { surface: 'Snow', fill: 'Glacier', water: 'Ice' },
    forest: { surface: 'Grass', fill: 'Mud', water: 'Water' },
    swamp: { surface: 'Mud', fill: 'Ground', water: 'Water' },
    volcanic: { surface: 'Basalt', fill: 'Basalt', water: 'Water' },
  }

  const mats = biomeMaterials[biome]

  const body = `local terrain = workspace.Terrain
terrain:Clear()

local sizeX = ${sizeX}
local sizeZ = ${sizeZ}
local cellSize = 4  -- Roblox terrain cell size in studs
local heightScale = ${heightScale}
local waterLevel = ${waterLevel}
local ox, oy, oz = ${position.x}, ${position.y}, ${position.z}

-- Simple noise-based heightmap
for xi = 0, math.floor(sizeX / cellSize) do
  for zi = 0, math.floor(sizeZ / cellSize) do
    local wx = ox + xi * cellSize - sizeX / 2
    local wz = oz + zi * cellSize - sizeZ / 2

    -- Layered noise for natural terrain
    local n1 = math.noise(wx * 0.008, wz * 0.008) * 1.0
    local n2 = math.noise(wx * 0.02, wz * 0.02) * 0.4
    local n3 = math.noise(wx * 0.06, wz * 0.06) * 0.1
    local height = (n1 + n2 + n3) * heightScale + oy

    if height < waterLevel then
      -- Fill below water with water material
      terrain:FillBlock(
        CFrame.new(wx, (height + waterLevel) / 2, wz),
        Vector3.new(cellSize, waterLevel - height, cellSize),
        Enum.Material.${mats.water}
      )
    else
      local fillHeight = height - oy
      if fillHeight > 1 then
        terrain:FillBlock(
          CFrame.new(wx, oy + fillHeight / 2, wz),
          Vector3.new(cellSize, fillHeight, cellSize),
          Enum.Material.${mats.fill}
        )
      end
      -- Surface cap
      terrain:FillBlock(
        CFrame.new(wx, height + 0.5, wz),
        Vector3.new(cellSize, 1, cellSize),
        Enum.Material.${mats.surface}
      )
    end
  end
end

print("Terrain generated: ${biome} biome, " .. sizeX .. "x" .. sizeZ .. " studs")`

  return wrapWaypoint('BuildTerrain', body)
}

export type TreeSpecies = 'oak' | 'pine' | 'palm' | 'cherry'

export interface BuildTreeParams {
  position: Vector3Param
  species?: TreeSpecies
  size?: number
  trunkColor?: [number, number, number]
  leafColor?: [number, number, number]
}

export function buildTree(params: BuildTreeParams): string {
  const { position, species = 'oak', size = 1 } = params

  const defaults: Record<TreeSpecies, { trunk: [number, number, number]; leaf: [number, number, number] }> = {
    oak: { trunk: [100, 70, 40], leaf: [60, 110, 40] },
    pine: { trunk: [80, 55, 30], leaf: [40, 90, 50] },
    palm: { trunk: [140, 110, 60], leaf: [50, 130, 50] },
    cherry: { trunk: [90, 60, 45], leaf: [220, 120, 160] },
  }

  const d = defaults[species]
  const trunkColor = colorLiteral(params.trunkColor ?? d.trunk)
  const leafColor = colorLiteral(params.leafColor ?? d.leaf)

  const body = `local treeModel = Instance.new("Model")
treeModel.Name = "Tree_${species}"
treeModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}
local s = ${size}

-- Trunk
local trunk = Instance.new("Part")
trunk.Name = "Trunk"
trunk.Size = Vector3.new(s * 1.2, s * ${species === 'palm' ? 10 : 6}, s * 1.2)
trunk.CFrame = CFrame.new(px, py + s * ${species === 'palm' ? 5 : 3}, pz)
trunk.Color = ${trunkColor}
trunk.Material = Enum.Material.Wood
trunk.Anchored = true
trunk.Parent = treeModel

${
  species === 'oak'
    ? `-- Oak: large round canopy with 3-5 lobes
for i = 0, 3 do
  local a = (i / 4) * math.pi * 2
  local canopy = Instance.new("Part")
  canopy.Shape = Enum.PartType.Ball
  canopy.Name = "Canopy_" .. i
  canopy.Size = Vector3.new(s*5, s*4, s*5)
  canopy.CFrame = CFrame.new(px + math.cos(a)*s*2, py + s*7 + math.sin(a)*s, pz + math.sin(a)*s*2)
  canopy.Color = ${leafColor}
  canopy.Material = Enum.Material.LeafyGrass
  canopy.Anchored = true
  canopy.CastShadow = false
  canopy.Parent = treeModel
end
local topCanopy = Instance.new("Part")
topCanopy.Shape = Enum.PartType.Ball
topCanopy.Name = "CanopyTop"
topCanopy.Size = Vector3.new(s*6, s*5, s*6)
topCanopy.CFrame = CFrame.new(px, py + s*9, pz)
topCanopy.Color = ${leafColor}
topCanopy.Material = Enum.Material.LeafyGrass
topCanopy.Anchored = true
topCanopy.CastShadow = false
topCanopy.Parent = treeModel`
    : species === 'pine'
    ? `-- Pine: stacked conical tiers
for tier = 0, 3 do
  local tierSize = s * (4 - tier * 0.6)
  local tierH = s * (2 - tier * 0.3)
  local tierY = py + s*4 + tier * s * 2.5
  local tierPart = Instance.new("Part")
  tierPart.Shape = Enum.PartType.Ball
  tierPart.Name = "Tier_" .. tier
  tierPart.Size = Vector3.new(tierSize, tierH, tierSize)
  tierPart.CFrame = CFrame.new(px, tierY, pz)
  tierPart.Color = ${leafColor}
  tierPart.Material = Enum.Material.LeafyGrass
  tierPart.Anchored = true
  tierPart.CastShadow = false
  tierPart.Parent = treeModel
end`
    : species === 'palm'
    ? `-- Palm: curved fronds at top
for i = 0, 5 do
  local a = (i / 6) * math.pi * 2
  local frond = Instance.new("Part")
  frond.Name = "Frond_" .. i
  frond.Size = Vector3.new(s*0.6, s*0.3, s*5)
  frond.CFrame = CFrame.new(px + math.cos(a)*s*2.5, py + s*10.5 - 1, pz + math.sin(a)*s*2.5) * CFrame.Angles(math.rad(-20), a, 0)
  frond.Color = ${leafColor}
  frond.Material = Enum.Material.LeafyGrass
  frond.Anchored = true
  frond.Parent = treeModel
end`
    : `-- Cherry: airy blossom cloud
for i = 0, 4 do
  local a = (i / 5) * math.pi * 2
  local cloud = Instance.new("Part")
  cloud.Shape = Enum.PartType.Ball
  cloud.Name = "Blossom_" .. i
  cloud.Size = Vector3.new(s*4, s*3, s*4)
  cloud.CFrame = CFrame.new(px + math.cos(a)*s*2.5, py + s*7, pz + math.sin(a)*s*2.5)
  cloud.Color = ${leafColor}
  cloud.Material = Enum.Material.Neon
  cloud.Transparency = 0.4
  cloud.Anchored = true
  cloud.CastShadow = false
  cloud.Parent = treeModel
end`
}`

  return wrapWaypoint('BuildTree', body)
}

export interface BuildRockParams {
  position: Vector3Param
  size: Vector3Param
  material?: string
  color?: [number, number, number]
  cluster?: boolean
}

export function buildRock(params: BuildRockParams): string {
  const { position, size, material = 'Rock', color = [130, 120, 110], cluster = false } = params

  const body = `local rockModel = Instance.new("Model")
rockModel.Name = "Rock"
rockModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}

local mainRock = Instance.new("Part")
mainRock.Name = "MainRock"
mainRock.Size = Vector3.new(${size.x}, ${size.y}, ${size.z})
mainRock.CFrame = CFrame.new(px, py + ${size.y / 2}, pz) * CFrame.Angles(0, math.random() * math.pi * 2, math.rad(math.random(-15, 15)))
mainRock.Color = ${colorLiteral(color)}
mainRock.Material = Enum.Material.${material}
mainRock.Anchored = true
mainRock.Parent = rockModel

${
  cluster
    ? `-- Cluster of smaller rocks
for i = 1, 3 do
  local smallRock = Instance.new("Part")
  smallRock.Name = "Rock_" .. i
  local sc = ${size.x} * (0.3 + math.random() * 0.4)
  smallRock.Size = Vector3.new(sc, sc * 0.7, sc)
  local angle = (i / 3) * math.pi * 2 + math.random() * 1
  smallRock.CFrame = CFrame.new(
    px + math.cos(angle) * ${size.x * 0.8},
    py + sc * 0.35,
    pz + math.sin(angle) * ${size.z * 0.8}
  ) * CFrame.Angles(0, math.random() * math.pi, math.rad(math.random(-20, 20)))
  smallRock.Color = ${colorLiteral(color)}
  smallRock.Material = Enum.Material.${material}
  smallRock.Anchored = true
  smallRock.Parent = rockModel
end`
    : ''
}`

  return wrapWaypoint('BuildRock', body)
}

export interface BuildWaterParams {
  position: Vector3Param
  sizeX: number
  sizeZ: number
  depth?: number
  color?: [number, number, number]
}

export function buildWater(params: BuildWaterParams): string {
  const { position, sizeX, sizeZ, depth = 4, color = [40, 100, 160] } = params

  const body = `local waterModel = Instance.new("Model")
waterModel.Name = "Water"
waterModel.Parent = workspace

-- Water surface
local surface = Instance.new("Part")
surface.Name = "WaterSurface"
surface.Size = Vector3.new(${sizeX}, 0.5, ${sizeZ})
surface.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z})
surface.Color = ${colorLiteral(color)}
surface.Material = Enum.Material.Water
surface.Transparency = 0.3
surface.Anchored = true
surface.Parent = waterModel

-- Bottom
local bottom = Instance.new("Part")
bottom.Name = "WaterBottom"
bottom.Size = Vector3.new(${sizeX + 2}, 1, ${sizeZ + 2})
bottom.CFrame = CFrame.new(${position.x}, ${position.y - depth}, ${position.z})
bottom.Color = Color3.fromRGB(60, 80, 70)
bottom.Material = Enum.Material.Mud
bottom.Anchored = true
bottom.Parent = waterModel

-- Side walls
local sides = {
  {sz=Vector3.new(${sizeX}, ${depth}, 1), off=Vector3.new(0, -${depth / 2}, -${sizeZ / 2})},
  {sz=Vector3.new(${sizeX}, ${depth}, 1), off=Vector3.new(0, -${depth / 2},  ${sizeZ / 2})},
  {sz=Vector3.new(1, ${depth}, ${sizeZ}), off=Vector3.new(-${sizeX / 2}, -${depth / 2}, 0)},
  {sz=Vector3.new(1, ${depth}, ${sizeZ}), off=Vector3.new( ${sizeX / 2}, -${depth / 2}, 0)},
}
for i, sw in ipairs(sides) do
  local wall = Instance.new("Part")
  wall.Name = "WaterWall_" .. i
  wall.Size = sw.sz
  wall.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z}) * CFrame.new(sw.off)
  wall.Color = Color3.fromRGB(60, 80, 70)
  wall.Material = Enum.Material.Mud
  wall.Anchored = true
  wall.Parent = waterModel
end`

  return wrapWaypoint('BuildWater', body)
}

export interface BuildPathParams {
  points: Vector3Param[]
  width?: number
  material?: string
  color?: [number, number, number]
  raised?: number
}

export function buildPath(params: BuildPathParams): string {
  const { points, width = 4, material = 'Cobblestone', color = [160, 150, 140], raised = 0.2 } = params

  const body = `local pathModel = Instance.new("Model")
pathModel.Name = "Path"
pathModel.Parent = workspace

local pts = {
${points.map((p) => `  Vector3.new(${p.x}, ${p.y}, ${p.z}),`).join('\n')}
}

for i = 1, #pts - 1 do
  local a, b = pts[i], pts[i + 1]
  local dx, dy, dz = b.X - a.X, b.Y - a.Y, b.Z - a.Z
  local length = math.sqrt(dx*dx + dy*dy + dz*dz)
  local angle = math.atan2(dx, dz)

  local segment = Instance.new("Part")
  segment.Name = "PathSegment_" .. i
  segment.Size = Vector3.new(${width}, 0.4, length)
  segment.CFrame = CFrame.new((a.X+b.X)/2, (a.Y+b.Y)/2 + ${raised}, (a.Z+b.Z)/2) * CFrame.Angles(0, angle, 0)
  segment.Color = ${colorLiteral(color)}
  segment.Material = Enum.Material.${material}
  segment.Anchored = true
  segment.Parent = pathModel
end`

  return wrapWaypoint('BuildPath', body)
}

// ─── Lighting ─────────────────────────────────────────────────────────────────

export interface BuildLightingParams {
  timeOfDay?: string
  ambient?: [number, number, number]
  fog?: { color: [number, number, number]; start: number; end: number }
  bloom?: { intensity: number; size: number; threshold: number }
  sunRays?: { intensity: number; spread: number }
  colorCorrection?: { brightness: number; contrast: number; saturation: number }
  shadowSoftness?: number
}

export function buildLighting(params: BuildLightingParams): string {
  const {
    timeOfDay = '14:00:00',
    ambient = [80, 80, 100],
    fog,
    bloom,
    sunRays,
    colorCorrection,
    shadowSoftness = 0.25,
  } = params

  const body = `local Lighting = game:GetService("Lighting")
Lighting.TimeOfDay = "${timeOfDay}"
Lighting.Ambient = ${colorLiteral(ambient)}
Lighting.ShadowSoftness = ${shadowSoftness}

-- Remove existing post-processing effects
for _, child in ipairs(Lighting:GetChildren()) do
  if child:IsA("PostEffect") or child:IsA("Atmosphere") then
    child:Destroy()
  end
end

${
  fog
    ? `-- Atmosphere (fog)
local atmo = Instance.new("Atmosphere")
atmo.Color = ${colorLiteral(fog.color)}
atmo.Density = 0.3
atmo.Offset = 0.25
atmo.Parent = Lighting`
    : `-- Default atmosphere
local atmo = Instance.new("Atmosphere")
atmo.Density = 0.15
atmo.Offset = 0.1
atmo.Parent = Lighting`
}

${
  bloom
    ? `-- Bloom
local bloom = Instance.new("BloomEffect")
bloom.Intensity = ${bloom.intensity}
bloom.Size = ${bloom.size}
bloom.Threshold = ${bloom.threshold}
bloom.Parent = Lighting`
    : `local bloom = Instance.new("BloomEffect")
bloom.Intensity = 0.3
bloom.Size = 24
bloom.Threshold = 0.95
bloom.Parent = Lighting`
}

${
  sunRays
    ? `-- Sun rays
local rays = Instance.new("SunRaysEffect")
rays.Intensity = ${sunRays.intensity}
rays.Spread = ${sunRays.spread}
rays.Parent = Lighting`
    : ''
}

${
  colorCorrection
    ? `-- Color correction
local cc = Instance.new("ColorCorrectionEffect")
cc.Brightness = ${colorCorrection.brightness}
cc.Contrast = ${colorCorrection.contrast}
cc.Saturation = ${colorCorrection.saturation}
cc.Parent = Lighting`
    : ''
}

print("Lighting configured: " .. "${timeOfDay}")`

  return wrapWaypoint('BuildLighting', body)
}

export interface BuildPointLightParams {
  position: Vector3Param
  color?: [number, number, number]
  brightness?: number
  range?: number
  name?: string
  shadows?: boolean
}

export function buildPointLight(params: BuildPointLightParams): string {
  const { position, color = [255, 220, 160], brightness = 5, range = 20, name = 'PointLight', shadows = true } = params

  const body = `local lightAnchor = Instance.new("Part")
lightAnchor.Name = "${name}_Anchor"
lightAnchor.Size = Vector3.new(0.3, 0.3, 0.3)
lightAnchor.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z})
lightAnchor.Color = ${colorLiteral(color)}
lightAnchor.Material = Enum.Material.Neon
lightAnchor.Anchored = true
lightAnchor.CanCollide = false
lightAnchor.Parent = workspace

local light = Instance.new("PointLight")
light.Name = "${name}"
light.Color = ${colorLiteral(color)}
light.Brightness = ${brightness}
light.Range = ${range}
light.Shadows = ${shadows}
light.Parent = lightAnchor`

  return wrapWaypoint('BuildPointLight', body)
}

export interface BuildSpotLightParams {
  position: Vector3Param
  direction?: Vector3Param
  angle?: number
  color?: [number, number, number]
  brightness?: number
  range?: number
  name?: string
}

export function buildSpotLight(params: BuildSpotLightParams): string {
  const {
    position,
    direction = { x: 0, y: -1, z: 0 },
    angle = 45,
    color = [255, 255, 220],
    brightness = 8,
    range = 30,
    name = 'SpotLight',
  } = params

  const body = `local spotAnchor = Instance.new("Part")
spotAnchor.Name = "${name}_Anchor"
spotAnchor.Size = Vector3.new(0.5, 0.5, 0.5)
spotAnchor.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z}) * CFrame.lookAt(Vector3.new(0,0,0), Vector3.new(${direction.x}, ${direction.y}, ${direction.z}))
spotAnchor.Color = ${colorLiteral(color)}
spotAnchor.Material = Enum.Material.Neon
spotAnchor.Anchored = true
spotAnchor.CanCollide = false
spotAnchor.Parent = workspace

local spot = Instance.new("SpotLight")
spot.Name = "${name}"
spot.Color = ${colorLiteral(color)}
spot.Brightness = ${brightness}
spot.Range = ${range}
spot.Angle = ${angle}
spot.Shadows = true
spot.Face = Enum.NormalId.Front
spot.Parent = spotAnchor`

  return wrapWaypoint('BuildSpotLight', body)
}

// ─── NPCs ─────────────────────────────────────────────────────────────────────

export interface NPCAppearance {
  bodyColor?: [number, number, number]
  shirtColor?: [number, number, number]
  pantsColor?: [number, number, number]
  headColor?: [number, number, number]
}

export interface BuildNPCParams {
  name: string
  position: Vector3Param
  appearance?: NPCAppearance
  dialogue?: string[]
  patrol?: Vector3Param[]
  health?: number
  walkSpeed?: number
}

export function buildNPC(params: BuildNPCParams): string {
  const {
    name,
    position,
    appearance = {},
    dialogue = ['Hello, traveler!', 'Have a wonderful day!'],
    patrol = [],
    health = 100,
    walkSpeed = 10,
  } = params

  const bodyColor = colorLiteral(appearance.bodyColor ?? [200, 160, 120])
  const shirtColor = colorLiteral(appearance.shirtColor ?? [80, 120, 180])
  const pantsColor = colorLiteral(appearance.pantsColor ?? [60, 80, 120])

  const body = `-- NPC: ${name}
local npcModel = Instance.new("Model")
npcModel.Name = "${name}"
npcModel.Parent = workspace

-- Humanoid root part
local hrp = Instance.new("Part")
hrp.Name = "HumanoidRootPart"
hrp.Size = Vector3.new(2, 2, 1)
hrp.CFrame = CFrame.new(${position.x}, ${position.y + 3}, ${position.z})
hrp.Color = ${bodyColor}
hrp.Transparency = 1
hrp.CanCollide = false
hrp.Parent = npcModel

-- Torso
local torso = Instance.new("Part")
torso.Name = "Torso"
torso.Size = Vector3.new(2, 2, 1)
torso.CFrame = CFrame.new(${position.x}, ${position.y + 3}, ${position.z})
torso.Color = ${shirtColor}
torso.Material = Enum.Material.SmoothPlastic
torso.Anchored = false
torso.Parent = npcModel

-- Head
local head = Instance.new("Part")
head.Name = "Head"
head.Size = Vector3.new(2, 1, 1)
head.CFrame = CFrame.new(${position.x}, ${position.y + 4.5}, ${position.z})
head.Color = ${bodyColor}
head.Material = Enum.Material.SmoothPlastic
head.Anchored = false
head.Parent = npcModel

-- Left Arm
local lArm = Instance.new("Part")
lArm.Name = "Left Arm"
lArm.Size = Vector3.new(1, 2, 1)
lArm.CFrame = CFrame.new(${position.x} - 1.5, ${position.y + 3}, ${position.z})
lArm.Color = ${shirtColor}
lArm.Material = Enum.Material.SmoothPlastic
lArm.Parent = npcModel

-- Right Arm
local rArm = Instance.new("Part")
rArm.Name = "Right Arm"
rArm.Size = Vector3.new(1, 2, 1)
rArm.CFrame = CFrame.new(${position.x} + 1.5, ${position.y + 3}, ${position.z})
rArm.Color = ${shirtColor}
rArm.Material = Enum.Material.SmoothPlastic
rArm.Parent = npcModel

-- Left Leg
local lLeg = Instance.new("Part")
lLeg.Name = "Left Leg"
lLeg.Size = Vector3.new(1, 2, 1)
lLeg.CFrame = CFrame.new(${position.x} - 0.5, ${position.y + 1}, ${position.z})
lLeg.Color = ${pantsColor}
lLeg.Material = Enum.Material.SmoothPlastic
lLeg.Parent = npcModel

-- Right Leg
local rLeg = Instance.new("Part")
rLeg.Name = "Right Leg"
rLeg.Size = Vector3.new(1, 2, 1)
rLeg.CFrame = CFrame.new(${position.x} + 0.5, ${position.y + 1}, ${position.z})
rLeg.Color = ${pantsColor}
rLeg.Material = Enum.Material.SmoothPlastic
rLeg.Parent = npcModel

-- Humanoid
local humanoid = Instance.new("Humanoid")
humanoid.Health = ${health}
humanoid.MaxHealth = ${health}
humanoid.WalkSpeed = ${walkSpeed}
humanoid.Parent = npcModel

-- Weld all parts to HRP
local parts = {torso, head, lArm, rArm, lLeg, rLeg}
local offsets = {
  CFrame.new(0, 0, 0),
  CFrame.new(0, 1.5, 0),
  CFrame.new(-1.5, 0, 0),
  CFrame.new(1.5, 0, 0),
  CFrame.new(-0.5, -2, 0),
  CFrame.new(0.5, -2, 0),
}
for i, part in ipairs(parts) do
  local weld = Instance.new("Weld")
  weld.Part0 = hrp
  weld.Part1 = part
  weld.C1 = offsets[i]:Inverse()
  weld.Parent = hrp
end
npcModel.PrimaryPart = hrp

-- Name tag
local billboard = Instance.new("BillboardGui")
billboard.Size = UDim2.new(0, 160, 0, 40)
billboard.StudsOffset = Vector3.new(0, 3, 0)
billboard.AlwaysOnTop = false
billboard.Parent = head

local nameLabel = Instance.new("TextLabel")
nameLabel.Size = UDim2.fromScale(1, 1)
nameLabel.BackgroundTransparency = 1
nameLabel.Text = "${name}"
nameLabel.TextScaled = true
nameLabel.Font = Enum.Font.GothamBold
nameLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
nameLabel.TextStrokeTransparency = 0.5
nameLabel.Parent = billboard

-- Dialogue script (proximity)
local script = Instance.new("Script")
script.Name = "NPCDialogue"
script.Source = [=[
local dialogue = {${dialogue.map((d) => `"${d}"`).join(', ')}}
local lineIdx = 1
local npc = script.Parent
local hrp = npc:WaitForChild("HumanoidRootPart")
local proximity = Instance.new("ProximityPrompt")
proximity.ActionText = "Talk"
proximity.ObjectText = "${name}"
proximity.MaxActivationDistance = 8
proximity.Parent = hrp
proximity.Triggered:Connect(function(player)
  local line = dialogue[lineIdx]
  lineIdx = (lineIdx % #dialogue) + 1
  -- Chat bubble
  game:GetService("Chat"):Chat(hrp, line, Enum.ChatColor.White)
end)
]=]
script.Parent = npcModel

${
  patrol.length >= 2
    ? `-- Patrol script
local patrolScript = Instance.new("Script")
patrolScript.Name = "PatrolScript"
patrolScript.Source = [=[
local npc = script.Parent
local humanoid = npc:WaitForChild("Humanoid")
local pts = {
${patrol.map((p) => `  Vector3.new(${p.x}, ${p.y}, ${p.z}),`).join('\n')}
}
local idx = 1
while task.wait(0.1) do
  local target = pts[idx]
  humanoid:MoveTo(target)
  humanoid.MoveToFinished:Wait()
  idx = (idx % #pts) + 1
end
]=]
patrolScript.Parent = npcModel`
    : ''
}`

  return wrapWaypoint('BuildNPC', body)
}

export interface BuildEnemyParams {
  name: string
  position: Vector3Param
  type?: 'melee' | 'ranged' | 'boss'
  health?: number
  damage?: number
  loot?: string[]
  detectionRange?: number
  color?: [number, number, number]
}

export function buildEnemy(params: BuildEnemyParams): string {
  const {
    name,
    position,
    type = 'melee',
    health = 50,
    damage = 15,
    loot = [],
    detectionRange = 25,
    color = [180, 60, 60],
  } = params

  const body = `local enemyModel = Instance.new("Model")
enemyModel.Name = "${name}"
enemyModel.Parent = workspace

local hrp = Instance.new("Part")
hrp.Name = "HumanoidRootPart"
hrp.Size = Vector3.new(2, 2, 1)
hrp.CFrame = CFrame.new(${position.x}, ${position.y + 3}, ${position.z})
hrp.Transparency = 1
hrp.CanCollide = false
hrp.Parent = enemyModel

local torso = Instance.new("Part")
torso.Name = "Torso"
torso.Size = Vector3.new(2, 2, 1)
torso.CFrame = CFrame.new(${position.x}, ${position.y + 3}, ${position.z})
torso.Color = ${colorLiteral(color)}
torso.Material = Enum.Material.${type === 'boss' ? 'Neon' : 'SmoothPlastic'}
torso.Parent = enemyModel

local head = Instance.new("Part")
head.Name = "Head"
head.Size = Vector3.new(2, 1, 1)
head.CFrame = CFrame.new(${position.x}, ${position.y + 4.5}, ${position.z})
head.Color = ${colorLiteral(color)}
head.Material = Enum.Material.SmoothPlastic
head.Parent = enemyModel

local humanoid = Instance.new("Humanoid")
humanoid.Health = ${health}
humanoid.MaxHealth = ${health}
humanoid.WalkSpeed = ${type === 'boss' ? 12 : 8}
humanoid.Parent = enemyModel

-- Weld
local tw = Instance.new("Weld")
tw.Part0 = hrp; tw.Part1 = torso; tw.C1 = CFrame.new(); tw.Parent = hrp
local hw = Instance.new("Weld")
hw.Part0 = hrp; hw.Part1 = head; hw.C1 = CFrame.new(0, -1.5, 0); hw.Parent = hrp
enemyModel.PrimaryPart = hrp

-- Combat + AI script (server)
local combatScript = Instance.new("Script")
combatScript.Name = "EnemyAI"
combatScript.Source = [=[
-- Enemy AI: ${name} | Type: ${type} | Damage: ${damage} | Detection: ${detectionRange}
local enemy = script.Parent
local humanoid = enemy:WaitForChild("Humanoid")
local hrp = enemy:WaitForChild("HumanoidRootPart")
local Players = game:GetService("Players")
local damage = ${damage}
local detectionRange = ${detectionRange}
local attackCooldown = ${type === 'boss' ? 1 : 1.5}
local lastAttack = 0

local function findNearestPlayer()
  local nearest, minDist = nil, detectionRange
  for _, player in ipairs(Players:GetPlayers()) do
    local char = player.Character
    if char then
      local charHRP = char:FindFirstChild("HumanoidRootPart")
      if charHRP then
        local dist = (charHRP.Position - hrp.Position).Magnitude
        if dist < minDist then
          nearest, minDist = char, dist
        end
      end
    end
  end
  return nearest
end

game:GetService("RunService").Heartbeat:Connect(function()
  if humanoid.Health <= 0 then return end
  local target = findNearestPlayer()
  if target then
    local targetHRP = target:FindFirstChild("HumanoidRootPart")
    if targetHRP then
      humanoid:MoveTo(targetHRP.Position)
      local dist = (targetHRP.Position - hrp.Position).Magnitude
      if dist < 5 and (os.clock() - lastAttack) > attackCooldown then
        lastAttack = os.clock()
        local targetHum = target:FindFirstChildOfClass("Humanoid")
        if targetHum then
          targetHum:TakeDamage(damage)
        end
      end
    end
  end
end)

humanoid.Died:Connect(function()
  ${loot.length > 0 ? `-- Drop loot\nlocal lootTable = {${loot.map((l) => `"${l}"`).join(', ')}}` : '-- No loot configured'}
  task.wait(3)
  enemy:Destroy()
end)
]=]
combatScript.Parent = enemyModel`

  return wrapWaypoint('BuildEnemy', body)
}

export interface BuildShopkeeperParams {
  name: string
  position: Vector3Param
  items: Array<{ name: string; price: number; currency?: string }>
  dialogue?: string[]
  color?: [number, number, number]
}

export function buildShopkeeper(params: BuildShopkeeperParams): string {
  const { name, position, items, dialogue = [`Welcome to my shop!`, `Browse my wares, friend.`], color = [160, 130, 100] } = params

  const body = `-- Shopkeeper: ${name}
-- Uses buildNPC base then adds shop ProximityPrompt logic
${buildNPC({ name, position, appearance: { shirtColor: color }, dialogue })}

-- Override dialogue script with shop GUI trigger
-- (In production wire to your ShopRemote; this is a standalone demo version)
local shopScript = Instance.new("LocalScript")
shopScript.Name = "ShopkeeperClient"
shopScript.Source = [=[
-- Items: ${items.map((i) => `${i.name} (${i.price} ${i.currency ?? 'Coins'})`).join(', ')}
local items = {
${items.map((i) => `  {name="${i.name}", price=${i.price}, currency="${i.currency ?? 'Coins'}"},`).join('\n')}
}
print("Shopkeeper ${name} ready with " .. #items .. " items")
]=]
shopScript.Parent = game:GetService("StarterPlayer").StarterCharacterScripts`

  return wrapWaypoint('BuildShopkeeper', body)
}

// ─── Vehicles ─────────────────────────────────────────────────────────────────

export interface BuildCarParams {
  name: string
  position: Vector3Param
  speed?: number
  color?: [number, number, number]
  seats?: number
}

export function buildCar(params: BuildCarParams): string {
  const { name, position, speed = 60, color = [200, 50, 50], seats = 2 } = params

  const body = `local carModel = Instance.new("Model")
carModel.Name = "${name}"
carModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}
local carColor = ${colorLiteral(color)}

-- Body
local body = Instance.new("Part")
body.Name = "Body"
body.Size = Vector3.new(7, 2.5, 14)
body.CFrame = CFrame.new(px, py + 2, pz)
body.Color = carColor
body.Material = Enum.Material.SmoothPlastic
body.Anchored = false
body.Parent = carModel

-- Cabin roof
local cabin = Instance.new("Part")
cabin.Name = "Cabin"
cabin.Size = Vector3.new(6, 1.5, 7)
cabin.CFrame = CFrame.new(px, py + 3.75, pz + 0.5)
cabin.Color = carColor
cabin.Material = Enum.Material.SmoothPlastic
cabin.Anchored = false
cabin.Parent = carModel
local cabinWeld = Instance.new("Weld")
cabinWeld.Part0 = body; cabinWeld.Part1 = cabin
cabinWeld.C0 = CFrame.new(0, 1.75, 0.5)
cabinWeld.Parent = body

-- Windshield
local windshield = Instance.new("Part")
windshield.Name = "Windshield"
windshield.Size = Vector3.new(5.5, 1.5, 0.1)
windshield.CFrame = CFrame.new(px, py + 3.75, pz - 3)
windshield.Color = Color3.fromRGB(140, 200, 220)
windshield.Material = Enum.Material.Glass
windshield.Transparency = 0.4
windshield.Anchored = false
windshield.Parent = carModel
local wsWeld = Instance.new("Weld")
wsWeld.Part0 = body; wsWeld.Part1 = windshield
wsWeld.C0 = CFrame.new(0, 1.75, -3)
wsWeld.Parent = body

-- Wheels (4 positions)
local wheelOffsets = {
  Vector3.new(-3.8, -1.2,  4.5),
  Vector3.new( 3.8, -1.2,  4.5),
  Vector3.new(-3.8, -1.2, -4.5),
  Vector3.new( 3.8, -1.2, -4.5),
}
for i, off in ipairs(wheelOffsets) do
  local wheel = Instance.new("Part")
  wheel.Name = "Wheel_" .. i
  wheel.Shape = Enum.PartType.Cylinder
  wheel.Size = Vector3.new(1.2, 2.4, 2.4)
  wheel.CFrame = CFrame.new(px + off.X, py + off.Y, pz + off.Z) * CFrame.Angles(0, 0, math.rad(90))
  wheel.Color = Color3.fromRGB(30, 30, 30)
  wheel.Material = Enum.Material.SmoothPlastic
  wheel.Anchored = false
  wheel.Parent = carModel

  local weld = Instance.new("Weld")
  weld.Part0 = body
  weld.Part1 = wheel
  weld.C0 = CFrame.new(off) * CFrame.Angles(0, 0, math.rad(90))
  weld.Parent = body
end

-- VehicleSeat (driver)
local driverSeat = Instance.new("VehicleSeat")
driverSeat.Name = "DriverSeat"
driverSeat.Size = Vector3.new(2, 1, 2)
driverSeat.CFrame = CFrame.new(px - 1.5, py + 3.25, pz + 1)
driverSeat.MaxSpeed = ${speed}
driverSeat.Torque = 30
driverSeat.TurnSpeed = 1.5
driverSeat.Color = Color3.fromRGB(40, 40, 50)
driverSeat.Anchored = false
driverSeat.Parent = carModel
local dsWeld = Instance.new("Weld")
dsWeld.Part0 = body; dsWeld.Part1 = driverSeat
dsWeld.C0 = CFrame.new(-1.5, 1.25, 1)
dsWeld.Parent = body

${
  seats > 1
    ? `-- Passenger seat
local passengerSeat = Instance.new("Seat")
passengerSeat.Name = "PassengerSeat"
passengerSeat.Size = Vector3.new(2, 1, 2)
passengerSeat.CFrame = CFrame.new(px + 1.5, py + 3.25, pz + 1)
passengerSeat.Anchored = false
passengerSeat.Color = Color3.fromRGB(40, 40, 50)
passengerSeat.Parent = carModel
local psWeld = Instance.new("Weld")
psWeld.Part0 = body; psWeld.Part1 = passengerSeat
psWeld.C0 = CFrame.new(1.5, 1.25, 1)
psWeld.Parent = body`
    : ''
}

carModel.PrimaryPart = body`

  return wrapWaypoint('BuildCar', body)
}

export interface BuildBoatParams {
  name: string
  position: Vector3Param
  speed?: number
  color?: [number, number, number]
}

export function buildBoat(params: BuildBoatParams): string {
  const { name, position, speed = 40, color = [160, 120, 60] } = params

  const body = `local boatModel = Instance.new("Model")
boatModel.Name = "${name}"
boatModel.Parent = workspace

local px, py, pz = ${position.x}, ${position.y}, ${position.z}
local boatColor = ${colorLiteral(color)}

-- Hull
local hull = Instance.new("Part")
hull.Name = "Hull"
hull.Size = Vector3.new(8, 3, 18)
hull.CFrame = CFrame.new(px, py + 1.5, pz)
hull.Color = boatColor
hull.Material = Enum.Material.Wood
hull.Anchored = false
hull.Parent = boatModel

-- Deck
local deck = Instance.new("Part")
deck.Name = "Deck"
deck.Size = Vector3.new(7.5, 0.5, 16)
deck.CFrame = CFrame.new(px, py + 3.25, pz)
deck.Color = Color3.fromRGB(180, 150, 100)
deck.Material = Enum.Material.Wood
deck.Anchored = false
deck.Parent = boatModel
local deckWeld = Instance.new("Weld")
deckWeld.Part0 = hull; deckWeld.Part1 = deck; deckWeld.C0 = CFrame.new(0, 1.75, 0); deckWeld.Parent = hull

-- Mast
local mast = Instance.new("Part")
mast.Name = "Mast"
mast.Shape = Enum.PartType.Cylinder
mast.Size = Vector3.new(0.6, 14, 0.6)
mast.CFrame = CFrame.new(px, py + 10.5, pz - 2) * CFrame.Angles(0, 0, math.rad(90))
mast.Color = Color3.fromRGB(120, 90, 50)
mast.Material = Enum.Material.Wood
mast.Anchored = false
mast.Parent = boatModel
local mastWeld = Instance.new("Weld")
mastWeld.Part0 = hull; mastWeld.Part1 = mast; mastWeld.C0 = CFrame.new(0, 9, -2) * CFrame.Angles(0, 0, math.rad(90)); mastWeld.Parent = hull

-- Sail
local sail = Instance.new("Part")
sail.Name = "Sail"
sail.Size = Vector3.new(0.3, 8, 7)
sail.CFrame = CFrame.new(px, py + 13, pz - 2)
sail.Color = Color3.fromRGB(240, 230, 200)
sail.Material = Enum.Material.Fabric
sail.Transparency = 0.1
sail.Anchored = false
sail.Parent = boatModel
local sailWeld = Instance.new("Weld")
sailWeld.Part0 = hull; sailWeld.Part1 = sail; sailWeld.C0 = CFrame.new(0, 11.5, -2); sailWeld.Parent = hull

-- Helm seat
local helm = Instance.new("VehicleSeat")
helm.Name = "Helm"
helm.Size = Vector3.new(2, 1, 2)
helm.CFrame = CFrame.new(px, py + 4.5, pz + 5)
helm.MaxSpeed = ${speed}
helm.Torque = 20
helm.TurnSpeed = 1
helm.Color = Color3.fromRGB(100, 70, 40)
helm.Anchored = false
helm.Parent = boatModel
local helmWeld = Instance.new("Weld")
helmWeld.Part0 = hull; helmWeld.Part1 = helm; helmWeld.C0 = CFrame.new(0, 3, 5); helmWeld.Parent = hull

boatModel.PrimaryPart = hull`

  return wrapWaypoint('BuildBoat', body)
}

// ─── Game Systems ─────────────────────────────────────────────────────────────

export interface BuildSpawnPointParams {
  position: Vector3Param
  teamColor?: [number, number, number]
  name?: string
  size?: number
}

export function buildSpawnPoint(params: BuildSpawnPointParams): string {
  const { position, teamColor = [0, 170, 255], name = 'SpawnLocation', size = 6 } = params

  const body = `local spawn = Instance.new("SpawnLocation")
spawn.Name = "${name}"
spawn.Size = Vector3.new(${size}, 1, ${size})
spawn.CFrame = CFrame.new(${position.x}, ${position.y}, ${position.z})
spawn.BrickColor = BrickColor.new(Color3.fromRGB(${teamColor[0]}, ${teamColor[1]}, ${teamColor[2]}))
spawn.Material = Enum.Material.Neon
spawn.Transparency = 0.5
spawn.Anchored = true
spawn.AllowTeamChangeOnTouch = false
spawn.Parent = workspace

-- Spawn ring decoration
local ring = Instance.new("Part")
ring.Name = "SpawnRing"
ring.Shape = Enum.PartType.Cylinder
ring.Size = Vector3.new(0.3, ${size + 2}, ${size + 2})
ring.CFrame = CFrame.new(${position.x}, ${position.y + 0.5}, ${position.z}) * CFrame.Angles(0, 0, math.rad(90))
ring.Color = Color3.fromRGB(${teamColor[0]}, ${teamColor[1]}, ${teamColor[2]})
ring.Material = Enum.Material.Neon
ring.Transparency = 0.3
ring.Anchored = true
ring.CanCollide = false
ring.Parent = workspace`

  return wrapWaypoint('BuildSpawnPoint', body)
}

export interface BuildCheckpointParams {
  position: Vector3Param
  number: number
  color?: [number, number, number]
  width?: number
  height?: number
}

export function buildCheckpoint(params: BuildCheckpointParams): string {
  const { position, number, color = [0, 200, 100], width = 10, height = 8 } = params

  const body = `local cpModel = Instance.new("Model")
cpModel.Name = "Checkpoint_${number}"
cpModel.Parent = workspace

-- Left post
local lPost = Instance.new("Part")
lPost.Name = "LeftPost"
lPost.Size = Vector3.new(1, ${height}, 1)
lPost.CFrame = CFrame.new(${position.x} - ${width / 2}, ${position.y + height / 2}, ${position.z})
lPost.Color = ${colorLiteral(color)}
lPost.Material = Enum.Material.Neon
lPost.Anchored = true
lPost.Parent = cpModel

-- Right post
local rPost = Instance.new("Part")
rPost.Name = "RightPost"
rPost.Size = Vector3.new(1, ${height}, 1)
rPost.CFrame = CFrame.new(${position.x} + ${width / 2}, ${position.y + height / 2}, ${position.z})
rPost.Color = ${colorLiteral(color)}
rPost.Material = Enum.Material.Neon
rPost.Anchored = true
rPost.Parent = cpModel

-- Cross beam
local beam = Instance.new("Part")
beam.Name = "Beam"
beam.Size = Vector3.new(${width + 2}, 1, 1)
beam.CFrame = CFrame.new(${position.x}, ${position.y + height}, ${position.z})
beam.Color = ${colorLiteral(color)}
beam.Material = Enum.Material.Neon
beam.Anchored = true
beam.Parent = cpModel

-- Number sign
local signPart = Instance.new("Part")
signPart.Name = "NumberSign"
signPart.Size = Vector3.new(3, 3, 0.3)
signPart.CFrame = CFrame.new(${position.x}, ${position.y + height / 2}, ${position.z})
signPart.Color = ${colorLiteral(color)}
signPart.Material = Enum.Material.SmoothPlastic
signPart.Anchored = true
signPart.Parent = cpModel

local bb = Instance.new("BillboardGui")
bb.Size = UDim2.new(0, 80, 0, 80)
bb.AlwaysOnTop = false
bb.Parent = signPart

local lbl = Instance.new("TextLabel")
lbl.Size = UDim2.fromScale(1, 1)
lbl.BackgroundTransparency = 1
lbl.Text = "${number}"
lbl.TextScaled = true
lbl.Font = Enum.Font.GothamBold
lbl.TextColor3 = Color3.fromRGB(255, 255, 255)
lbl.Parent = bb

-- Trigger zone (touch detection)
local trigger = Instance.new("Part")
trigger.Name = "CheckpointTrigger"
trigger.Size = Vector3.new(${width}, ${height}, 2)
trigger.CFrame = CFrame.new(${position.x}, ${position.y + height / 2}, ${position.z})
trigger.Transparency = 1
trigger.CanCollide = false
trigger.Anchored = true
trigger.Parent = cpModel`

  return wrapWaypoint('BuildCheckpoint', body)
}

export interface BuildLeaderboardParams {
  stats: string[]
  position?: Vector3Param
  title?: string
  color?: [number, number, number]
}

export function buildLeaderboard(params: BuildLeaderboardParams): string {
  const { stats, position = { x: 0, y: 0, z: 0 }, title = 'LEADERBOARD', color = [30, 30, 50] } = params

  const body = `local lbModel = Instance.new("Model")
lbModel.Name = "Leaderboard"
lbModel.Parent = workspace

-- Board backing
local board = Instance.new("Part")
board.Name = "Board"
board.Size = Vector3.new(14, 10, 0.5)
board.CFrame = CFrame.new(${position.x}, ${position.y + 5}, ${position.z})
board.Color = ${colorLiteral(color)}
board.Material = Enum.Material.SmoothPlastic
board.Anchored = true
board.Parent = lbModel

-- Left post
local lp = Instance.new("Part")
lp.Name = "LeftPost"
lp.Size = Vector3.new(0.8, 12, 0.8)
lp.CFrame = CFrame.new(${position.x} - 7.5, ${position.y + 6}, ${position.z})
lp.Color = ${colorLiteral(color)}
lp.Material = Enum.Material.Metal
lp.Anchored = true
lp.Parent = lbModel

-- Right post
local rp = Instance.new("Part")
rp.Name = "RightPost"
rp.Size = Vector3.new(0.8, 12, 0.8)
rp.CFrame = CFrame.new(${position.x} + 7.5, ${position.y + 6}, ${position.z})
rp.Color = ${colorLiteral(color)}
rp.Material = Enum.Material.Metal
rp.Anchored = true
rp.Parent = lbModel

-- SurfaceGui for live data
local gui = Instance.new("SurfaceGui")
gui.Face = Enum.NormalId.Front
gui.CanvasSize = Vector2.new(400, 300)
gui.SizingMode = Enum.SurfaceGuiSizingMode.FixedSize
gui.Parent = board

local titleLabel = Instance.new("TextLabel")
titleLabel.Size = UDim2.new(1, 0, 0.2, 0)
titleLabel.BackgroundColor3 = Color3.fromRGB(255, 200, 50)
titleLabel.Text = "${title}"
titleLabel.TextScaled = true
titleLabel.Font = Enum.Font.GothamBold
titleLabel.TextColor3 = Color3.fromRGB(20, 20, 20)
titleLabel.Parent = gui

-- Stats columns header
local statsHeader = Instance.new("TextLabel")
statsHeader.Size = UDim2.new(1, 0, 0.12, 0)
statsHeader.Position = UDim2.new(0, 0, 0.2, 0)
statsHeader.BackgroundColor3 = Color3.fromRGB(20, 20, 40)
statsHeader.Text = "Player  |  ${stats.join('  |  ')}"
statsHeader.TextScaled = true
statsHeader.Font = Enum.Font.Gotham
statsHeader.TextColor3 = Color3.fromRGB(180, 180, 200)
statsHeader.Parent = gui

-- Entries (populated at runtime via server script)
local entriesFrame = Instance.new("Frame")
entriesFrame.Size = UDim2.new(1, 0, 0.68, 0)
entriesFrame.Position = UDim2.new(0, 0, 0.32, 0)
entriesFrame.BackgroundTransparency = 1
entriesFrame.Parent = gui

local listLayout = Instance.new("UIListLayout")
listLayout.SortOrder = Enum.SortOrder.LayoutOrder
listLayout.Parent = entriesFrame

-- Updater script (server)
local updater = Instance.new("Script")
updater.Name = "LeaderboardUpdater"
updater.Source = [=[
local board = script.Parent
local gui = board:FindFirstChildWhichIsA("BasePart"):FindFirstChildOfClass("SurfaceGui")
local entriesFrame = gui:FindFirstChild("Frame")
local Players = game:GetService("Players")
local statKeys = {${stats.map((s) => `"${s}"`).join(', ')}}

local function updateBoard()
  -- Clear existing rows
  for _, child in ipairs(entriesFrame:GetChildren()) do
    if child:IsA("TextLabel") then child:Destroy() end
  end
  -- Collect and sort players by first stat
  local entries = {}
  for _, player in ipairs(Players:GetPlayers()) do
    local ls = player:FindFirstChild("leaderstats")
    if ls then
      local val = ls:FindFirstChild(statKeys[1])
      table.insert(entries, {player = player, value = val and val.Value or 0})
    end
  end
  table.sort(entries, function(a, b) return a.value > b.value end)
  for rank, entry in ipairs(entries) do
    if rank > 10 then break end
    local row = Instance.new("TextLabel")
    row.Size = UDim2.new(1, 0, 0, 24)
    row.LayoutOrder = rank
    row.BackgroundColor3 = rank % 2 == 0 and Color3.fromRGB(25, 25, 45) or Color3.fromRGB(30, 30, 55)
    row.Text = rank .. ". " .. entry.player.Name .. "  " .. entry.value
    row.TextScaled = true
    row.Font = Enum.Font.Gotham
    row.TextColor3 = rank == 1 and Color3.fromRGB(255, 215, 0) or Color3.fromRGB(200, 200, 220)
    row.Parent = entriesFrame
  end
end

-- Update every 10 seconds
while true do
  pcall(updateBoard)
  task.wait(10)
end
]=]
updater.Parent = lbModel`

  return wrapWaypoint('BuildLeaderboard', body)
}

export interface ShopItem {
  name: string
  price: number
  currency?: string
  description?: string
  icon?: string
}

export interface BuildShopSystemParams {
  items: ShopItem[]
  shopName?: string
  position?: Vector3Param
  currencyStatKey?: string
}

export function buildShopSystem(params: BuildShopSystemParams): string {
  const { items, shopName = 'Shop', position = { x: 0, y: 0, z: 0 }, currencyStatKey = 'Coins' } = params

  const body = `-- Shop System: ${shopName}
-- Architecture: server-authoritative, client fires RemoteFunction, server validates and charges
-- Generated by ForjeGames roblox-builders

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

-- RemoteFunction for purchases (server-authoritative)
local purchaseRemote = Instance.new("RemoteFunction")
purchaseRemote.Name = "${shopName}Purchase"
purchaseRemote.Parent = ReplicatedStorage

-- Item catalogue (server-side truth)
local ITEMS: {[string]: {price: number, currency: string, description: string}} = {
${items.map((i) => `  ["${i.name}"] = {price = ${i.price}, currency = "${i.currency ?? currencyStatKey}", description = "${i.description ?? ''}"},`).join('\n')}
}

-- Server handler
purchaseRemote.OnServerInvoke = function(player, itemName)
  -- Validate: item exists
  local item = ITEMS[itemName]
  if not item then
    return {success = false, error = "Item not found"}
  end

  -- Validate: player has enough currency
  local ls = player:FindFirstChild("leaderstats")
  if not ls then
    return {success = false, error = "Leaderstats not found"}
  end
  local currencyStat = ls:FindFirstChild(item.currency)
  if not currencyStat then
    return {success = false, error = "Currency stat not found"}
  end
  if currencyStat.Value < item.price then
    return {success = false, error = "Insufficient funds"}
  end

  -- Deduct and grant
  currencyStat.Value = currencyStat.Value - item.price
  -- TODO: grant item to player inventory here

  return {success = true, itemName = itemName}
end

-- Shop NPC / interact point
local shopPart = Instance.new("Part")
shopPart.Name = "${shopName}_InteractPoint"
shopPart.Size = Vector3.new(4, 6, 1)
shopPart.CFrame = CFrame.new(${position.x}, ${position.y + 3}, ${position.z})
shopPart.Color = Color3.fromRGB(220, 180, 60)
shopPart.Material = Enum.Material.Neon
shopPart.Anchored = true
shopPart.Parent = workspace

local proximity = Instance.new("ProximityPrompt")
proximity.ActionText = "Open Shop"
proximity.ObjectText = "${shopName}"
proximity.MaxActivationDistance = 8
proximity.Parent = shopPart

-- Client GUI (LocalScript in StarterGui recommended — this is a minimal scaffold)
local clientScript = Instance.new("LocalScript")
clientScript.Name = "${shopName}Client"
clientScript.Source = [=[
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local purchaseRemote = ReplicatedStorage:WaitForChild("${shopName}Purchase")

local items = {
${items.map((i) => `  {name="${i.name}", price=${i.price}, currency="${i.currency ?? currencyStatKey}"},`).join('\n')}
}

local function buyItem(itemName)
  local result = purchaseRemote:InvokeServer(itemName)
  if result.success then
    print("Purchased: " .. itemName)
  else
    warn("Purchase failed: " .. (result.error or "unknown"))
  end
end

-- Wire up to your GUI buttons here
-- Example: buyItem("${items[0]?.name ?? 'Sword'}")
]=]
clientScript.Parent = game:GetService("StarterPlayer").StarterPlayerScripts`

  return wrapWaypoint('BuildShopSystem', body)
}
