/**
 * error-recovery.ts — Automated detect-fix-verify loop for script errors
 *
 * When the console shows a runtime error from an AI-generated script:
 * 1. Parse the error (script name, line number, message)
 * 2. Check if the script was recently generated by AI (within 5 minutes)
 * 3. Read the failing script source from Studio
 * 4. Send error + source to AI for fix
 * 5. Apply the fix via modify_script
 * 6. Watch console for 10 seconds for recurrence
 * 7. Max 3 retries, then give up and notify user
 *
 * Matches Ropilot's self-healing loop and Lemonade's "Agent Playtest."
 */

export interface ConsoleError {
  message: string
  type: string // 'Error' | 'Warning'
  timestamp: number
  scriptName?: string
  lineNumber?: number
}

export interface ErrorFixAttempt {
  error: ConsoleError
  scriptPath: string
  originalSource: string
  fixedSource: string
  success: boolean
  attempt: number
  model: string
  timestamp: number
}

/**
 * Parse a Roblox console error message to extract script name and line number.
 * Example: "ServerScriptService.GameManager:15: attempt to index nil with 'Health'"
 */
export function parseConsoleError(message: string): { scriptName: string | null; lineNumber: number | null; errorText: string } {
  // Pattern: ServiceName.ScriptName:LineNumber: error message
  const match = message.match(/^([A-Za-z]+(?:\.[A-Za-z_]\w*)+):(\d+):\s*(.+)$/)
  if (match) {
    return {
      scriptName: match[1],
      lineNumber: parseInt(match[2], 10),
      errorText: match[3],
    }
  }

  // Pattern: Script 'ScriptName', Line N
  const match2 = message.match(/Script\s+'([^']+)',\s*Line\s+(\d+)/i)
  if (match2) {
    return {
      scriptName: match2[1],
      lineNumber: parseInt(match2[2], 10),
      errorText: message,
    }
  }

  // Pattern: [ForjeGames TempExec] Error: ...
  const match3 = message.match(/\[ForjeGames.*?\]\s*Error:\s*(.+)/)
  if (match3) {
    return {
      scriptName: null,
      lineNumber: null,
      errorText: match3[1],
    }
  }

  return { scriptName: null, lineNumber: null, errorText: message }
}

/**
 * Build the fix prompt for the AI, including error context and original source.
 */
export function buildFixPrompt(opts: {
  errorMessage: string
  scriptPath: string
  scriptSource: string
  lineNumber: number | null
  originalPrompt?: string
  attempt: number
}): string {
  const { errorMessage, scriptPath, scriptSource, lineNumber, originalPrompt, attempt } = opts

  let prompt = `FIX THIS RUNTIME ERROR in "${scriptPath}":\n\n`
  prompt += `ERROR: ${errorMessage}\n`
  if (lineNumber) prompt += `LINE: ${lineNumber}\n`
  if (attempt > 1) prompt += `ATTEMPT: ${attempt}/3 (previous fix didn't work)\n`
  prompt += `\n`

  if (originalPrompt) {
    prompt += `ORIGINAL REQUEST: ${originalPrompt}\n\n`
  }

  prompt += `CURRENT SCRIPT SOURCE:\n\`\`\`lua\n${scriptSource}\n\`\`\`\n\n`

  prompt += `INSTRUCTIONS:\n`
  prompt += `1. Diagnose the root cause of the error\n`
  prompt += `2. Fix the issue in the script\n`
  prompt += `3. Add a comment explaining what was wrong and how you fixed it\n`
  prompt += `4. Output the COMPLETE fixed script (not a diff)\n`
  prompt += `5. Make sure the fix handles edge cases (nil checks, pcall where needed)\n`
  prompt += `6. Do NOT change the script's purpose or remove existing functionality\n`

  return prompt
}

/**
 * Determine if a console error should trigger auto-fix.
 * Filters out noise like Chat script warnings, Animate default errors, etc.
 */
export function shouldAutoFix(error: ConsoleError): boolean {
  const msg = error.message.toLowerCase()

  // Skip ForjeGames internal messages
  if (msg.includes('[forjegames]') && !msg.includes('error')) return false

  // Skip common Roblox default script noise
  if (msg.includes('animate') && msg.includes('default')) return false
  if (msg.includes('chat') && msg.includes('legacy')) return false
  if (msg.includes('accessory') && msg.includes('handle')) return false

  // Skip HTTP-related errors (not script bugs)
  if (msg.includes('http') && msg.includes('not enabled')) return false
  if (msg.includes('http') && msg.includes('403')) return false

  // Only auto-fix actual errors, not warnings
  if (error.type !== 'Error' && error.type !== 'MessageError' && !error.type.includes('Error')) {
    return false
  }

  return true
}
