// luau-templates-buildings.ts
// Building generator functions for ForjeGames AI pipeline
// Each returns complete Luau code using Instance.new("Part")

interface HouseParams { style?: 'modern' | 'suburban' | 'cabin' | 'victorian'; floors?: number; rooms?: number }
interface ShopParams { type?: 'clothing' | 'grocery' | 'bakery' | 'general'; size?: 'small' | 'medium' | 'large' }
interface CastleParams { size?: 'small' | 'medium' | 'large' }
interface ApartmentParams { floors?: number; unitsPerFloor?: number }
interface RestaurantParams { type?: 'fast_food' | 'fine_dining' | 'cafe' }
interface OfficeParams { floors?: number }
interface WarehouseParams { width?: number; depth?: number }
interface SchoolParams {}
interface HospitalParams {}
interface ChurchParams {}
interface GasStationParams {}
interface BarnParams {}
interface LighthouseParams {}
interface PrisonParams {}
interface SpaceStationParams {}

const LUAU_HEADER = (name: string) => `-- ${name} generated by ForjeGames
local ChangeHistoryService = game:GetService("ChangeHistoryService")
local rec = ChangeHistoryService:TryBeginRecording("ForjeGames Build")
local m = Instance.new("Model") m.Name = "${name}"
local sp = Vector3.new(0,0,0)
local function P(n,s,p,mat,col,sh)
  local part = Instance.new(sh or "Part") part.Name=n part.Anchored=true
  part.Size=s part.CFrame=CFrame.new(p) part.Material=Enum.Material[mat]
  part.Color=Color3.fromRGB(col[1],col[2],col[3])
  part.Parent=m return part
end
local function L(par,bright,rng,col)
  local l=Instance.new("PointLight") l.Brightness=bright l.Range=rng
  l.Color=Color3.fromRGB(col[1],col[2],col[3]) l.Parent=par
end
`;

const LUAU_FOOTER = `m.Parent = workspace
if rec then ChangeHistoryService:FinishRecording(rec, Enum.FinishRecordingOperation.Commit) end
`;

export function generateHouse(params: HouseParams): string {
  const style = params.style ?? 'suburban';
  const floors = Math.min(Math.max(params.floors ?? 2, 1), 3);
  const wallMat = style === 'cabin' ? 'WoodPlanks' : style === 'victorian' ? 'Brick' : style === 'modern' ? 'Concrete' : 'Brick';
  const roofMat = style === 'cabin' ? 'Wood' : 'Slate';
  const wallColor = style === 'modern' ? '[235,235,235]' : style === 'cabin' ? '[139,90,43]' : style === 'victorian' ? '[180,140,100]' : '[210,180,140]';
  const roofColor = style === 'modern' ? '[80,80,90]' : '[80,50,30]';
  const floorH = 5;
  const code = LUAU_HEADER('House') + `
-- Foundation
P("Foundation",Vector3.new(22,1,18),Vector3.new(0,-0.5,0),"Concrete",{100,100,100})
-- Porch slab
P("PorchSlab",Vector3.new(8,0.5,5),Vector3.new(0,-0.25,11.5),"Concrete",{120,120,120})
-- Porch steps
for i=0,2 do
  P("Step"..i,Vector3.new(6,0.5,1),Vector3.new(0,-0.5+i*0.25,14-i*0.5),"Concrete",{130,130,130})
end
-- Floor slabs
for f=0,${floors - 1} do
  P("Floor"..f,Vector3.new(20,0.5,16),Vector3.new(0,f*${floorH},0),"Wood",{180,150,100})
end
-- Walls per floor
for f=0,${floors - 1} do
  local y=f*${floorH}+${floorH / 2}
  P("WallFront"..f,Vector3.new(20,${floorH},0.5),Vector3.new(0,y,8),"${wallMat}",${wallColor})
  P("WallBack"..f,Vector3.new(20,${floorH},0.5),Vector3.new(0,y,-8),"${wallMat}",${wallColor})
  P("WallLeft"..f,Vector3.new(0.5,${floorH},16),Vector3.new(-10,y,0),"${wallMat}",${wallColor})
  P("WallRight"..f,Vector3.new(0.5,${floorH},16),Vector3.new(10,y,0),"${wallMat}",${wallColor})
end
-- Windows (front, per floor)
for f=0,${floors - 1} do
  for w=-1,1 do
    if w~=0 then
      P("Win"..f..w,Vector3.new(3,2.5,0.3),Vector3.new(w*5,f*${floorH}+2,8.2),"Glass",{160,210,230})
    end
  end
end
-- Door frame
P("DoorFrame",Vector3.new(3,4,0.6),Vector3.new(0,2,8),"Wood",{100,70,40})
P("DoorPanel",Vector3.new(2.6,3.8,0.4),Vector3.new(0,2,8.1),"Wood",{120,80,50})
-- Porch columns
for cx=-3,3,6 do
  P("Col"..cx,Vector3.new(0.6,4,0.6),Vector3.new(cx,-0.5+2,13.5),"Wood",{220,200,170})
end
-- Roof
P("RoofBase",Vector3.new(22,1,20),Vector3.new(0,${floors * floorH},0),"${roofMat}",${roofColor})
P("RoofPeakL",Vector3.new(22,0.5,10),CFrame.new(-5,${floors * floorH + 2.5},0)*CFrame.Angles(0,0,math.rad(30))),"${roofMat}",${roofColor})
P("RoofPeakR",Vector3.new(22,0.5,10),CFrame.new(5,${floors * floorH + 2.5},0)*CFrame.Angles(0,0,math.rad(-30))),"${roofMat}",${roofColor})
P("RoofRidge",Vector3.new(22,0.8,1),Vector3.new(0,${floors * floorH + 4},0),"${roofMat}",${roofColor})
-- Chimney
P("ChimneyBase",Vector3.new(2,${floors * floorH + 3},2),Vector3.new(6,${floors * floorH / 2},−5),"Brick",{160,90,60})
P("ChimneyTop",Vector3.new(2.4,0.5,2.4),Vector3.new(6,${floors * floorH + 3.25},-5),"Brick",{140,80,50})
-- Interior furniture (ground floor)
P("Sofa",Vector3.new(4,1.2,1.8),Vector3.new(-4,1.1,-3),"Fabric",{90,100,160})
P("SofaBack",Vector3.new(4,1.8,0.4),Vector3.new(-4,1.8,-3.8),"Fabric",{80,90,150})
P("CoffeeTable",Vector3.new(2.5,0.4,1.2),Vector3.new(-4,0.7,−1),"Wood",{140,100,60})
P("TV",Vector3.new(4,2.5,0.2),Vector3.new(4,2,-7.7),"Metal",{30,30,35})
P("TVStand",Vector3.new(4,1,1),Vector3.new(4,0.5,-7.2),"Wood",{100,70,40})
P("DiningTable",Vector3.new(3,0.5,2),Vector3.new(5,0.9,3),"Wood",{160,120,70})
for cx=-1,1 do P("Chair"..cx,Vector3.new(1,0.8,1),Vector3.new(5+cx*1.5,0.9,4.5),"Wood",{140,100,60}) end
P("KitchenCounter",Vector3.new(5,1.1,1),Vector3.new(-6,0.55,-7),"Marble",{230,225,220})
P("Sink",Vector3.new(1.5,0.2,0.8),Vector3.new(-7,1.1,-7),"Metal",{200,200,200})
P("Stove",Vector3.new(2,1.2,1),Vector3.new(-4,0.6,-7),"Metal",{60,60,65})
-- Ceiling lights
local cl1=P("Light1",Vector3.new(0.5,0.2,0.5),Vector3.new(0,${floorH - 0.2},0),"Metal",{255,240,200})
L(cl1,3,18,{255,240,200})
local cl2=P("Light2",Vector3.new(0.5,0.2,0.5),Vector3.new(6,${floorH - 0.2},3),"Metal",{255,240,200})
L(cl2,2,14,{255,240,200})
` + LUAU_FOOTER;
  return code;
}

export function generateShop(params: ShopParams): string {
  const type = params.type ?? 'general';
  const size = params.size ?? 'medium';
  const w = size === 'small' ? 14 : size === 'large' ? 28 : 20;
  const d = size === 'small' ? 12 : size === 'large' ? 24 : 16;
  const h = 6;
  const wallColor = type === 'bakery' ? '[230,200,160]' : type === 'clothing' ? '[180,160,200]' : type === 'grocery' ? '[160,200,160]' : '[210,205,200]';
  const signColor = type === 'bakery' ? '[210,120,40]' : type === 'clothing' ? '[120,80,180]' : type === 'grocery' ? '[40,160,80]' : '[60,120,200]';
  const code = LUAU_HEADER('Shop_' + type) + `
-- Foundation
P("Foundation",Vector3.new(${w + 2},0.8,${d + 2}),Vector3.new(0,-0.4,0),"Concrete",{110,110,110})
-- Floor
P("Floor",Vector3.new(${w},0.4,${d}),Vector3.new(0,0.2,0),"Marble",{240,240,235})
-- Walls
P("WallFront_L",Vector3.new(${w / 2 - 3},${h},0.4),Vector3.new(-${w / 4 + 1.5},${h / 2},${d / 2}),"Concrete",${wallColor})
P("WallFront_R",Vector3.new(${w / 2 - 3},${h},0.4),Vector3.new(${w / 4 + 1.5},${h / 2},${d / 2}),"Concrete",${wallColor})
P("WallBack",Vector3.new(${w},${h},0.4),Vector3.new(0,${h / 2},-${d / 2}),"Concrete",${wallColor})
P("WallLeft",Vector3.new(0.4,${h},${d}),Vector3.new(-${w / 2},${h / 2},0),"Concrete",${wallColor})
P("WallRight",Vector3.new(0.4,${h},${d}),Vector3.new(${w / 2},${h / 2},0),"Concrete",${wallColor})
-- Ceiling
P("Ceiling",Vector3.new(${w},0.4,${d}),Vector3.new(0,${h + 0.2},0),"Concrete",{200,200,200})
-- Roof overhang
P("Overhang",Vector3.new(${w + 4},0.5,4),Vector3.new(0,${h + 0.5},${d / 2 + 2}),"Concrete",{180,180,180})
-- Glass front door
P("DoorGlass",Vector3.new(4,${h - 1},0.3),Vector3.new(0,${(h - 1) / 2},${d / 2}),"Glass",{180,220,240})
-- Windows (side walls)
for i=-1,1 do
  P("WinLeft"..i,Vector3.new(2.5,2.5,0.3),Vector3.new(-${w / 2},3,i*4),"Glass",{180,220,240})
  P("WinRight"..i,Vector3.new(2.5,2.5,0.3),Vector3.new(${w / 2},3,i*4),"Glass",{180,220,240})
end
-- Sign board
P("SignBoard",Vector3.new(${w - 2},1.5,0.5),Vector3.new(0,${h + 1.2},${d / 2}),"Wood",${signColor})
P("SignLight",Vector3.new(0.3,0.3,0.3),Vector3.new(0,${h + 1.2},${d / 2 + 0.5}),"Metal",{255,240,180})
-- Interior shelves
for row=0,2 do
  for side=-1,1,2 do
    P("Shelf"..row..side,Vector3.new(0.4,3,${d - 4}),Vector3.new(side*(${w / 2 - 1}),1.5,-1+row*0.1),"Wood",{160,120,70})
    for shelf=0,2 do
      P("ShelfBoard"..row..side..shelf,Vector3.new(0.5,0.1,${d - 4}),Vector3.new(side*(${w / 2 - 0.9}),shelf,−1),"Wood",{150,110,65})
    end
  end
end
-- Center display
P("DisplayTable",Vector3.new(${w / 2 - 2},1,${d / 2 - 2}),Vector3.new(0,0.5,0),"Wood",{180,140,80})
P("DisplayGlass",Vector3.new(${w / 2 - 2.2},0.2,${d / 2 - 2.2}),Vector3.new(0,1.1,0),"Glass",{200,230,245})
-- Counter / register
P("Counter",Vector3.new(4,1.2,1.5),Vector3.new(0,0.6,-${d / 2 - 2}),"Wood",{140,100,60})
P("RegisterBox",Vector3.new(0.8,0.6,0.6),Vector3.new(1,1.4,-${d / 2 - 2}),"Metal",{60,65,70})
-- Ceiling lights
for lx=-2,2 do
  local lp=P("CeilLight"..lx,Vector3.new(0.5,0.15,0.5),Vector3.new(lx*${w / 6},${h},lx*${d / 8}),"Metal",{255,245,210})
  L(lp,4,16,{255,245,210})
end
` + LUAU_FOOTER;
  return code;
}

export function generateCastle(params: CastleParams): string {
  const size = params.size ?? 'medium';
  const scale = size === 'small' ? 0.6 : size === 'large' ? 1.5 : 1;
  const W = Math.round(50 * scale);
  const H = Math.round(20 * scale);
  const T = Math.round(30 * scale);
  const towerH = Math.round(H * 1.6);
  const wallThick = 3;
  const code = LUAU_HEADER('Castle') + `
local sc=${scale}
-- Ground
P("Ground",Vector3.new(${W + 20},1,${W + 20}),Vector3.new(0,-0.5,0),"Grass",{80,120,60})
-- Moat (decorative water planes)
P("MoatN",Vector3.new(${W + 16},0.4,6),Vector3.new(0,0.2,${W / 2 + 8}),"SmoothPlastic",{60,100,180})
P("MoatS",Vector3.new(${W + 16},0.4,6),Vector3.new(0,0.2,-${W / 2 + 8}),"SmoothPlastic",{60,100,180})
P("MoatE",Vector3.new(6,0.4,${W + 4}),Vector3.new(${W / 2 + 8},0.2,0),"SmoothPlastic",{60,100,180})
P("MoatW",Vector3.new(6,0.4,${W + 4}),Vector3.new(-${W / 2 + 8},0.2,0),"SmoothPlastic",{60,100,180})
-- Outer walls
P("WallN",Vector3.new(${W},${H},${wallThick}),Vector3.new(0,${H / 2},${W / 2}),"Brick",{140,130,120})
P("WallS",Vector3.new(${W},${H},${wallThick}),Vector3.new(0,${H / 2},-${W / 2}),"Brick",{140,130,120})
P("WallE",Vector3.new(${wallThick},${H},${W}),Vector3.new(${W / 2},${H / 2},0),"Brick",{140,130,120})
P("WallW",Vector3.new(${wallThick},${H},${W}),Vector3.new(-${W / 2},${H / 2},0),"Brick",{140,130,120})
-- Battlements (merlons)
for i=-4,4 do
  P("MerlonN"..i,Vector3.new(${Math.max(2, Math.round(2 * scale))},${Math.round(3 * scale)},${wallThick}),Vector3.new(i*${Math.round(5 * scale)},${H + 1.5},${W / 2}),"Brick",{130,120,110})
  P("MerlonS"..i,Vector3.new(${Math.max(2, Math.round(2 * scale))},${Math.round(3 * scale)},${wallThick}),Vector3.new(i*${Math.round(5 * scale)},${H + 1.5},-${W / 2}),"Brick",{130,120,110})
  P("MerlonE"..i,Vector3.new(${wallThick},${Math.round(3 * scale)},${Math.max(2, Math.round(2 * scale))}),Vector3.new(${W / 2},${H + 1.5},i*${Math.round(5 * scale)}),"Brick",{130,120,110})
  P("MerlonW"..i,Vector3.new(${wallThick},${Math.round(3 * scale)},${Math.max(2, Math.round(2 * scale))}),Vector3.new(-${W / 2},${H + 1.5},i*${Math.round(5 * scale)}),"Brick",{130,120,110})
end
-- Corner towers
local tpos={{${W / 2},${W / 2}},{${W / 2},-${W / 2}},{-${W / 2},${W / 2}},{-${W / 2},-${W / 2}}}
for i,tp in ipairs(tpos) do
  P("Tower"..i,Vector3.new(${T / 3},${towerH},${T / 3}),Vector3.new(tp[1],${towerH / 2},tp[2]),"Brick",{130,125,115})
  -- Tower top cone approximation
  P("TowerCone"..i,Vector3.new(${T / 3 + 2},${Math.round(8 * scale)},${T / 3 + 2}),Vector3.new(tp[1],${towerH + Math.round(4 * scale)},tp[2]),"Slate",{60,55,50})
  -- Tower windows
  for tw=0,2 do
    P("TWin"..i..tw,Vector3.new(${Math.round(2 * scale)},${Math.round(3 * scale)},${wallThick}),Vector3.new(tp[1],tw*${Math.round(6 * scale)}+${Math.round(5 * scale)},tp[2]+${T / 6 + 1}),"Glass",{160,200,230})
  end
end
-- Gatehouse (south wall)
P("GateArchL",Vector3.new(4,${H * 0.7},${wallThick + 1}),Vector3.new(-4,${H * 0.35},-${W / 2}),"Brick",{150,140,130})
P("GateArchR",Vector3.new(4,${H * 0.7},${wallThick + 1}),Vector3.new(4,${H * 0.35},-${W / 2}),"Brick",{150,140,130})
P("GateArchTop",Vector3.new(8,4,${wallThick + 1}),Vector3.new(0,${H * 0.7 + 2},-${W / 2}),"Brick",{150,140,130})
P("Portcullis",Vector3.new(7,${H * 0.6},0.5),Vector3.new(0,${H * 0.3},-${W / 2 + 1}),"Metal",{80,80,85})
-- Drawbridge
P("Drawbridge",Vector3.new(8,0.8,10),Vector3.new(0,0.4,-${W / 2 + 7}),"Wood",{130,100,60})
-- Keep (central building)
P("Keep",Vector3.new(${Math.round(W * 0.4)},${Math.round(H * 1.2)},${Math.round(W * 0.4)}),Vector3.new(0,${Math.round(H * 0.6)},0),"Brick",{155,145,130})
P("KeepRoof",Vector3.new(${Math.round(W * 0.42)},${Math.round(4 * scale)},${Math.round(W * 0.42)}),Vector3.new(0,${Math.round(H * 1.2 + 2 * scale)},0),"Slate",{70,65,60})
-- Keep windows
for kf=0,2 do
  for kw=-1,1,2 do
    P("KeepWin"..kf..kw,Vector3.new(${Math.round(3 * scale)},${Math.round(4 * scale)},0.4),Vector3.new(kw*${Math.round(W * 0.14)},kf*${Math.round(7 * scale)}+${Math.round(4 * scale)},${Math.round(W * 0.2)}),"Glass",{160,200,230})
  end
end
-- Interior courtyard torch lights
for ti=0,3 do
  local ang=ti*math.pi/2
  local tx=math.cos(ang)*${Math.round(W * 0.3)}
  local tz=math.sin(ang)*${Math.round(W * 0.3)}
  local torch=P("Torch"..ti,Vector3.new(0.5,2,0.5),Vector3.new(tx,3,tz),"Wood",{130,100,50})
  L(torch,5,20,{255,180,80})
end
-- Throne room (inside keep, decorative)
P("Throne",Vector3.new(3,4,2),Vector3.new(0,2,6),"Wood",{160,120,60})
P("ThroneBack",Vector3.new(3,5,0.5),Vector3.new(0,3.5,7),"Wood",{140,100,50})
P("ThroneArmL",Vector3.new(0.5,2,2),Vector3.new(-1.75,2.5,6),"Wood",{140,100,50})
P("ThroneArmR",Vector3.new(0.5,2,2),Vector3.new(1.75,2.5,6),"Wood",{140,100,50})
P("RedCarpet",Vector3.new(4,0.1,14),Vector3.new(0,0.3,0),"Fabric",{160,30,30})
` + LUAU_FOOTER;
  return code;
}

export function generateApartment(params: ApartmentParams): string {
  const floors = Math.min(Math.max(params.floors ?? 6, 2), 10);
  const units = Math.min(Math.max(params.unitsPerFloor ?? 4, 2), 6);
  const floorH = 5;
  const bW = units * 8;
  const bD = 14;
  const code = LUAU_HEADER('Apartment') + `
-- Foundation
P("Foundation",Vector3.new(${bW + 4},1.5,${bD + 4}),Vector3.new(0,-0.75,0),"Concrete",{100,100,100})
-- Ground floor lobby
P("LobbyFloor",Vector3.new(${bW},0.4,${bD}),Vector3.new(0,0.2,0),"Marble",{240,235,230})
P("LobbyDesk",Vector3.new(5,1.2,1.5),Vector3.new(-${bW / 2 - 3},0.6,${bD / 2 - 2}),"Wood",{160,120,70})
P("MailBoxes",Vector3.new(3,4,0.5),Vector3.new(${bW / 2 - 2},2,${bD / 2 - 2}),"Metal",{170,170,175})
-- Floors and units
for f=0,${floors - 1} do
  local fy=f*${floorH}
  -- Floor slab
  P("FloorSlab"..f,Vector3.new(${bW},0.4,${bD}),Vector3.new(0,fy,0),"Concrete",{160,160,160})
  -- Walls per floor
  P("WallBack"..f,Vector3.new(${bW},${floorH},0.4),Vector3.new(0,fy+${floorH / 2},-${bD / 2}),"Concrete",{200,195,190})
  P("WallLeft"..f,Vector3.new(0.4,${floorH},${bD}),Vector3.new(-${bW / 2},fy+${floorH / 2},0),"Concrete",{200,195,190})
  P("WallRight"..f,Vector3.new(0.4,${floorH},${bD}),Vector3.new(${bW / 2},fy+${floorH / 2},0),"Concrete",{200,195,190})
  -- Front wall with windows + balconies
  for u=0,${units - 1} do
    local ux=-${bW / 2 - 4}+u*8
    -- Window
    P("Win"..f.."_"..u,Vector3.new(4,3,0.3),Vector3.new(ux,fy+2.5,${bD / 2}),"Glass",{170,215,235})
    -- Balcony slab
    P("Balcony"..f.."_"..u,Vector3.new(4.5,0.3,2.5),Vector3.new(ux,fy-0.15,${bD / 2 + 1.25}),"Concrete",{185,185,185})
    -- Balcony railing
    P("Rail"..f.."_"..u,Vector3.new(4.5,0.8,0.1),Vector3.new(ux,fy+0.25,${bD / 2 + 2.45}),"Metal",{120,120,125})
    P("RailL"..f.."_"..u,Vector3.new(0.1,0.8,2.5),Vector3.new(ux-2.2,fy+0.25,${bD / 2 + 1.25}),"Metal",{120,120,125})
    P("RailR"..f.."_"..u,Vector3.new(0.1,0.8,2.5),Vector3.new(ux+2.2,fy+0.25,${bD / 2 + 1.25}),"Metal",{120,120,125})
    -- Unit divider walls
    if u>0 then
      P("Divider"..f.."_"..u,Vector3.new(0.3,${floorH},${bD}),Vector3.new(ux-4,fy+${floorH / 2},0),"Concrete",{195,190,185})
    end
  end
end
-- Roof
P("Roof",Vector3.new(${bW + 2},1,${bD + 2}),Vector3.new(0,${floors * floorH + 0.5},0),"Concrete",{170,165,160})
-- Rooftop railing
P("RoofRailN",Vector3.new(${bW},0.9,0.2),Vector3.new(0,${floors * floorH + 0.95},${bD / 2 + 1}),"Metal",{140,140,145})
P("RoofRailS",Vector3.new(${bW},0.9,0.2),Vector3.new(0,${floors * floorH + 0.95},-${bD / 2 + 1}),"Metal",{140,140,145})
P("RoofRailE",Vector3.new(0.2,0.9,${bD + 2}),Vector3.new(${bW / 2 + 1},${floors * floorH + 0.95},0),"Metal",{140,140,145})
P("RoofRailW",Vector3.new(0.2,0.9,${bD + 2}),Vector3.new(-${bW / 2 + 1},${floors * floorH + 0.95},0),"Metal",{140,140,145})
-- Elevator shaft
P("ElevShaft",Vector3.new(3,${floors * floorH + 2},3),Vector3.new(0,${(floors * floorH) / 2},-${bD / 2 - 2}),"Concrete",{180,180,180})
P("ElevDoor",Vector3.new(2,3,0.3),Vector3.new(0,1.5,-${bD / 2 - 3.5}),"Metal",{160,160,165})
-- Hallway lights per floor
for f=0,${floors - 1} do
  local lp=P("HallLight"..f,Vector3.new(0.4,0.15,0.4),Vector3.new(0,f*${floorH}+${floorH - 0.3},0),"Metal",{255,245,210})
  L(lp,3,14,{255,245,210})
end
-- Parking area
P("Parking",Vector3.new(${bW},0.2,12),Vector3.new(0,0,-${bD / 2 + 8}),"Concrete",{130,130,130})
for sp=0,${units} do
  P("ParkLine"..sp,Vector3.new(0.2,0.25,12),Vector3.new(-${bW / 2 - 0}+sp*${bW / units},0.2,-${bD / 2 + 8}),"Concrete",{255,255,255})
end
` + LUAU_FOOTER;
  return code;
}

export function generateRestaurant(params: RestaurantParams): string {
  const type = params.type ?? 'cafe';
  const wallCol = type === 'fine_dining' ? '[50,40,35]' : type === 'fast_food' ? '[220,60,40]' : '[200,180,150]';
  const floorCol = type === 'fine_dining' ? '[60,45,30]' : '[220,210,195]';
  const floorMat = type === 'fine_dining' ? 'Marble' : 'Wood';
  const code = LUAU_HEADER('Restaurant_' + type) + `
-- Foundation & exterior
P("Slab",Vector3.new(28,0.8,22),Vector3.new(0,-0.4,0),"Concrete",{120,120,120})
P("Floor",Vector3.new(26,0.4,20),Vector3.new(0,0.2,0),"${floorMat}",${floorCol})
P("WallFrontL",Vector3.new(8,6,0.4),Vector3.new(-9,3,10),"Brick",${wallCol})
P("WallFrontR",Vector3.new(8,6,0.4),Vector3.new(9,3,10),"Brick",${wallCol})
P("WallBack",Vector3.new(26,6,0.4),Vector3.new(0,3,-10),"Brick",${wallCol})
P("WallLeft",Vector3.new(0.4,6,20),Vector3.new(-13,3,0),"Brick",${wallCol})
P("WallRight",Vector3.new(0.4,6,20),Vector3.new(13,3,0),"Brick",${wallCol})
P("Ceiling",Vector3.new(26,0.4,20),Vector3.new(0,6.2,0),"Concrete",{210,205,200})
-- Large front glass windows
P("FrontGlass",Vector3.new(9,5,0.3),Vector3.new(0,3,10),"Glass",{180,220,240})
-- Sign
P("Sign",Vector3.new(20,1.8,0.5),Vector3.new(0,7.5,10),"Wood",${wallCol})
-- Entry door
P("Door",Vector3.new(3,5,0.4),Vector3.new(0,2.5,10),"Glass",{180,220,240})
-- Dining tables
for row=0,2 do
  for col=-1,1 do
    local tx=col*7 tz=(row-1)*5
    P("DineTable"..row..col,Vector3.new(2.5,0.6,2.5),Vector3.new(tx,0.9,tz),"Wood",{170,130,80})
    -- Chairs around table
    P("ChairN"..row..col,Vector3.new(1.2,0.9,1.2),Vector3.new(tx,0.9,tz+2),"Wood",{140,100,60})
    P("ChairS"..row..col,Vector3.new(1.2,0.9,1.2),Vector3.new(tx,0.9,tz-2),"Wood",{140,100,60})
    P("ChairE"..row..col,Vector3.new(1.2,0.9,1.2),Vector3.new(tx+2,0.9,tz),"Wood",{140,100,60})
    P("ChairW"..row..col,Vector3.new(1.2,0.9,1.2),Vector3.new(tx-2,0.9,tz),"Wood",{140,100,60})
    -- Table candle/flower
    local decor=P("Decor"..row..col,Vector3.new(0.3,0.5,0.3),Vector3.new(tx,1.5,tz),"Metal",{220,200,150})
    if "${type}"=="fine_dining" then L(decor,1,4,{255,220,150}) end
  end
end
-- Bar / counter area
P("BarCounter",Vector3.new(12,1.2,1.5),Vector3.new(0,0.6,-8),"Wood",{120,85,50})
P("BarTop",Vector3.new(12.4,0.2,1.8),Vector3.new(0,1.3,-8),"Marble",{230,225,220})
-- Bar stools
for bs=-2,2 do
  P("Stool"..bs,Vector3.new(0.8,1,0.8),Vector3.new(bs*2,1,-6.5),"Wood",{110,80,45})
  P("StoolSeat"..bs,Vector3.new(1,0.2,1),Vector3.new(bs*2,1.55,-6.5),"Fabric",{80,60,40})
end
-- Kitchen pass window
P("PassWindow",Vector3.new(8,1.5,0.3),Vector3.new(0,4.5,-10),"Metal",{180,180,185})
-- Refrigerators (back wall)
for r=-1,1 do
  P("Fridge"..r,Vector3.new(2,5,1.2),Vector3.new(r*4,2.5,-9.4),"Metal",{200,200,205})
  P("FridgeGlass"..r,Vector3.new(1.6,4,0.2),Vector3.new(r*4,2.5,-9),"Glass",{180,215,235})
end
-- Pendant lights
for px=-2,2 do
  local pl=P("PendantLight"..px,Vector3.new(0.6,0.6,0.6),Vector3.new(px*4.5,5.5,0),"Metal",{60,60,65})
  L(pl,4,14,{255,240,200})
end
-- Exit sign
local ex=P("ExitSign",Vector3.new(1.5,0.5,0.2),Vector3.new(0,5.8,10),"Plastic",{0,180,60})
L(ex,2,6,{0,220,80})
` + LUAU_FOOTER;
  return code;
}

export function generateOffice(params: OfficeParams): string {
  const floors = Math.min(Math.max(params.floors ?? 4, 2), 8);
  const fH = 5;
  const bW = 30;
  const bD = 20;
  const code = LUAU_HEADER('OfficeBuilding') + `
-- Foundation
P("Foundation",Vector3.new(${bW + 4},1.5,${bD + 4}),Vector3.new(0,-0.75,0),"Concrete",{110,110,110})
-- Floors
for f=0,${floors - 1} do
  local fy=f*${fH}
  P("FloorSlab"..f,Vector3.new(${bW},0.4,${bD}),Vector3.new(0,fy,0),"Marble",{230,225,220})
  -- Glass curtain walls (front + back)
  P("GlassFront"..f,Vector3.new(${bW},${fH},0.4),Vector3.new(0,fy+${fH / 2},${bD / 2}),"Glass",{170,210,240})
  P("GlassBack"..f,Vector3.new(${bW},${fH},0.4),Vector3.new(0,fy+${fH / 2},-${bD / 2}),"Glass",{170,210,240})
  -- Solid side walls
  P("WallLeft"..f,Vector3.new(0.5,${fH},${bD}),Vector3.new(-${bW / 2},fy+${fH / 2},0),"Concrete",{200,200,200})
  P("WallRight"..f,Vector3.new(0.5,${fH},${bD}),Vector3.new(${bW / 2},fy+${fH / 2},0),"Concrete",{200,200,200})
  -- Floor spandrels (horizontal bands between floors)
  P("SpandrelF"..f,Vector3.new(${bW},0.8,0.5),Vector3.new(0,fy,${bD / 2}),"Concrete",{180,180,185})
  P("SpandrelB"..f,Vector3.new(${bW},0.8,0.5),Vector3.new(0,fy,-${bD / 2}),"Concrete",{180,180,185})
  -- Desks (open plan)
  for desk=0,4 do
    for row=0,1 do
      local dx=-${bW / 2 - 3}+desk*5 dz=(row-0.5)*6
      P("Desk"..f..desk..row,Vector3.new(2.5,0.8,1.2),Vector3.new(dx,fy+1.2,dz),"Wood",{180,150,100})
      P("Chair"..f..desk..row,Vector3.new(1,1,1),Vector3.new(dx,fy+1,dz+1.5),"Fabric",{60,80,100})
      P("Monitor"..f..desk..row,Vector3.new(2,1.2,0.15),Vector3.new(dx,fy+2,dz-0.3),"Metal",{30,30,35})
    end
  end
  -- Office partitions
  for pt=0,3 do
    P("Partition"..f..pt,Vector3.new(0.1,1.8,6),Vector3.new(-${bW / 2 - 2.5}+pt*6,fy+1.5,0),"Fabric",{160,160,170})
  end
  -- Ceiling lights
  for lx=-2,2 do
    local lp=P("OffLight"..f..lx,Vector3.new(3,0.15,0.6),Vector3.new(lx*5,fy+${fH - 0.2},0),"Metal",{255,250,240})
    L(lp,5,18,{255,250,240})
  end
end
-- Lobby (ground floor features)
P("ReceptionDesk",Vector3.new(8,1.1,2),Vector3.new(0,0.55,${bD / 2 - 4}),"Wood",{140,110,70})
P("ReceptionSign",Vector3.new(6,1,0.2),Vector3.new(0,2,${bD / 2 - 2.8}),"Metal",{200,200,205})
P("LobbyBench1",Vector3.new(5,0.5,1.2),Vector3.new(-8,0.5,${bD / 2 - 2}),"Fabric",{70,90,120})
P("LobbyBench2",Vector3.new(5,0.5,1.2),Vector3.new(8,0.5,${bD / 2 - 2}),"Fabric",{70,90,120})
P("LobbyTree1",Vector3.new(1,3,1),Vector3.new(-10,1.5,${bD / 2 - 2}),"Wood",{80,120,60})
P("LobbyTree2",Vector3.new(1,3,1),Vector3.new(10,1.5,${bD / 2 - 2}),"Wood",{80,120,60})
-- Core elevator/stairs
P("Core",Vector3.new(6,${floors * fH + 2},6),Vector3.new(0,${(floors * fH) / 2},-${bD / 2 - 4}),"Concrete",{190,190,190})
P("ElevDoor1",Vector3.new(2,3.5,0.3),Vector3.new(-1.5,1.75,-${bD / 2 - 7}),"Metal",{160,160,165})
P("ElevDoor2",Vector3.new(2,3.5,0.3),Vector3.new(1.5,1.75,-${bD / 2 - 7}),"Metal",{160,160,165})
-- Roof
P("Roof",Vector3.new(${bW + 2},1,${bD + 2}),Vector3.new(0,${floors * fH + 0.5},0),"Concrete",{180,180,180})
P("RoofParapet",Vector3.new(${bW + 2},1,0.3),Vector3.new(0,${floors * fH + 1},${bD / 2 + 1}),"Concrete",{170,170,170})
-- Signage on top
P("BuildingSign",Vector3.new(10,2,0.5),Vector3.new(0,${floors * fH + 2},${bD / 2 + 1.2}),"Metal",{50,50,55})
local sl=P("SignLight",Vector3.new(0.3,0.3,0.3),Vector3.new(0,${floors * fH + 2},${bD / 2 + 1.5}),"Metal",{200,220,255})
L(sl,3,12,{200,220,255})
` + LUAU_FOOTER;
  return code;
}

export function generateWarehouse(params: WarehouseParams): string {
  const W = 40;
  const D = 30;
  const H = 12;
  const code = LUAU_HEADER('Warehouse') + `
-- Foundation
P("Foundation",Vector3.new(${W + 4},1,${D + 4}),Vector3.new(0,-0.5,0),"Concrete",{120,120,120})
P("ConcreteFloor",Vector3.new(${W},0.4,${D}),Vector3.new(0,0.2,0),"Concrete",{160,160,160})
-- Painted floor lines
for fl=-2,2 do
  P("FloorLine"..fl,Vector3.new(0.2,0.45,${D}),Vector3.new(fl*6,0.25,0),"Concrete",{255,255,0})
end
-- Metal walls
P("WallFront",Vector3.new(${W},${H},0.5),Vector3.new(0,${H / 2},${D / 2}),"Metal",{160,165,170})
P("WallBack",Vector3.new(${W},${H},0.5),Vector3.new(0,${H / 2},-${D / 2}),"Metal",{160,165,170})
P("WallLeft",Vector3.new(0.5,${H},${D}),Vector3.new(-${W / 2},${H / 2},0),"Metal",{155,160,165})
P("WallRight",Vector3.new(0.5,${H},${D}),Vector3.new(${W / 2},${H / 2},0),"Metal",{155,160,165})
-- Roof with skylights
P("Roof",Vector3.new(${W + 1},1,${D + 1}),Vector3.new(0,${H + 0.5},0),"Metal",{140,145,150})
for sk=-1,1 do
  P("Skylight"..sk,Vector3.new(6,0.4,${D - 4}),Vector3.new(sk*10,${H + 0.7},0),"Glass",{200,230,250})
end
-- Roof ridge beam
P("RidgeBeam",Vector3.new(${W},1.2,1.2),Vector3.new(0,${H + 1.1},0),"Metal",{130,135,140})
-- Support columns
for cx=-1,1,2 do
  for cz=-1,0,1 do
    P("Col"..cx..cz,Vector3.new(1,${H},1),Vector3.new(cx*${W / 3},${H / 2},cz*${D / 3}),"Metal",{150,155,160})
  end
end
-- Loading dock doors
for ld=-1,1 do
  P("DockDoor"..ld,Vector3.new(5,8,0.6),Vector3.new(ld*10,4,${D / 2}),"Metal",{100,105,110})
  P("DockBumper"..ld,Vector3.new(6,1,0.8),Vector3.new(ld*10,0.5,${D / 2 + 0.5}),"Rubber" in Enum.Material and "Rubber" or "Concrete",{40,40,40})
  P("DockPlatform"..ld,Vector3.new(6,0.6,4),Vector3.new(ld*10,0.3,${D / 2 + 3}),"Concrete",{130,130,130})
end
-- Office section (corner)
P("OfficeWallFront",Vector3.new(10,6,0.4),Vector3.new(-${W / 2 - 5},3,-${D / 2 - 4}),"Concrete",{200,200,200})
P("OfficeWallSide",Vector3.new(0.4,6,8),Vector3.new(-${W / 2 - 10},3,-${D / 2 - 4}),"Concrete",{200,200,200})
P("OfficeDesk",Vector3.new(3,0.8,1.5),Vector3.new(-${W / 2 - 6},0.8,-${D / 2 - 5}),"Wood",{160,120,70})
P("OfficeChair",Vector3.new(1,1,1),Vector3.new(-${W / 2 - 6},0.9,-${D / 2 - 3.5}),"Fabric",{60,80,100})
-- Pallet racks
for rack=0,3 do
  local rz=-${D / 2 - 3}+rack*6
  P("RackL"..rack,Vector3.new(1,8,${D / 4}),Vector3.new(-${W / 2 - 2},4,rz),"Metal",{220,130,40})
  P("RackR"..rack,Vector3.new(1,8,${D / 4}),Vector3.new(${W / 2 - 2},4,rz),"Metal",{220,130,40})
  for shelf=0,2 do
    P("RackShelfL"..rack..shelf,Vector3.new(1.5,0.2,${D / 4}),Vector3.new(-${W / 2 - 2},shelf*2.5+1.2,rz),"Metal",{200,120,35})
    P("RackShelfR"..rack..shelf,Vector3.new(1.5,0.2,${D / 4}),Vector3.new(${W / 2 - 2},shelf*2.5+1.2,rz),"Metal",{200,120,35})
    -- Boxes on shelves
    P("BoxL"..rack..shelf,Vector3.new(1.4,1.4,1.4),Vector3.new(-${W / 2 - 2},shelf*2.5+2,rz),"Wood",{180,150,100})
    P("BoxR"..rack..shelf,Vector3.new(1.4,1.4,1.4),Vector3.new(${W / 2 - 2},shelf*2.5+2,rz),"Wood",{180,150,100})
  end
end
-- Forklift (decorative)
P("ForkBody",Vector3.new(2.5,3,4),Vector3.new(5,1.5,5),"Metal",{220,180,40})
P("ForkMast",Vector3.new(0.5,5,0.5),Vector3.new(5,2.5,7),"Metal",{200,165,35})
P("ForkArmL",Vector3.new(0.3,0.3,3),Vector3.new(4.5,1.5,5.5),"Metal",{190,155,30})
P("ForkArmR",Vector3.new(0.3,0.3,3),Vector3.new(5.5,1.5,5.5),"Metal",{190,155,30})
-- Industrial ceiling lights
for lx=-2,2 do
  for lz=-1,1 do
    local lp=P("IndLight"..lx..lz,Vector3.new(1.5,0.5,1.5),Vector3.new(lx*7,${H - 0.3},lz*7),"Metal",{200,200,205})
    L(lp,6,22,{255,250,230})
  end
end
` + LUAU_FOOTER;
  return code;
}

export function generateSchool(params: SchoolParams): string {
  const code = LUAU_HEADER('School') + `
-- Foundation & grounds
P("Ground",Vector3.new(80,0.6,60),Vector3.new(0,-0.3,0),"Grass",{80,130,70})
P("Foundation",Vector3.new(50,1,40),Vector3.new(0,-0.5,0),"Concrete",{130,130,130})
P("MainFloor",Vector3.new(48,0.4,38),Vector3.new(0,0.7,0),"Concrete",{200,195,190})
-- Exterior walls
P("WallFront",Vector3.new(48,9,0.5),Vector3.new(0,4.5,19),"Brick",{190,160,130})
P("WallBack",Vector3.new(48,9,0.5),Vector3.new(0,4.5,-19),"Brick",{190,160,130})
P("WallLeft",Vector3.new(0.5,9,38),Vector3.new(-24,4.5,0),"Brick",{190,160,130})
P("WallRight",Vector3.new(0.5,9,38),Vector3.new(24,4.5,0),"Brick",{190,160,130})
-- Second floor
P("Floor2",Vector3.new(48,0.4,38),Vector3.new(0,9.7,0),"Concrete",{195,190,185})
for f=0,1 do
  local fy=f*9
  for w=-3,3 do
    if w~=0 then
      P("FrontWin"..f..w,Vector3.new(3,4,0.3),Vector3.new(w*5,fy+5,19.2),"Glass",{170,215,235})
    end
  end
end
-- Roof
P("Roof",Vector3.new(50,1,40),Vector3.new(0,18.5,0),"Concrete",{170,165,160})
-- Front entrance
P("EntranceCanopy",Vector3.new(12,0.6,5),Vector3.new(0,5,22),"Concrete",{180,178,175})
for cp=-1,1,2 do
  P("CanopyCol"..cp,Vector3.new(0.7,5,0.7),Vector3.new(cp*5,2.5,24),"Concrete",{200,200,200})
end
P("EntranceDoorL",Vector3.new(2.5,4.5,0.4),Vector3.new(-1.5,2.25,19),"Glass",{170,215,235})
P("EntranceDoorR",Vector3.new(2.5,4.5,0.4),Vector3.new(1.5,2.25,19),"Glass",{170,215,235})
P("SchoolSign",Vector3.new(16,2,0.5),Vector3.new(0,8.5,19.3),"Brick",{100,140,100})
-- Hallway
P("Hallway",Vector3.new(6,8.5,36),Vector3.new(0,4.25,0),"Concrete",{210,205,200})
P("HallFloor",Vector3.new(6,0.2,36),Vector3.new(0,0.9,0),"Concrete",{230,225,220})
-- Lockers (hallway sides)
for lk=-7,7 do
  P("LockerL"..lk,Vector3.new(0.8,4,0.6),Vector3.new(-3.5,2.5,lk*2.3),"Metal",{80,100,130})
  P("LockerR"..lk,Vector3.new(0.8,4,0.6),Vector3.new(3.5,2.5,lk*2.3),"Metal",{80,100,130})
end
-- Classrooms (left and right of hallway)
for rm=0,2 do
  local rz=(rm-1)*12
  for side=-1,1,2 do
    local rx=side*15
    P("ClassFloor"..rm..side,Vector3.new(10,0.2,10),Vector3.new(rx,0.9,rz),"Wood",{180,150,100})
    P("ClassWallDiv"..rm..side,Vector3.new(0.3,8.5,10),Vector3.new(rx-side*5,4.25,rz),"Brick",{185,160,130})
    -- Desks
    for dr=0,1 do
      for dc=-1,1 do
        P("ClassDesk"..rm..side..dr..dc,Vector3.new(1.5,0.7,1.2),Vector3.new(rx+dc*2.5,1,rz+dr*3-1.5),"Wood",{170,140,90})
        P("ClassChair"..rm..side..dr..dc,Vector3.new(1,0.9,1),Vector3.new(rx+dc*2.5,0.9,rz+dr*3-0.2),"Wood",{130,100,60})
      end
    end
    -- Teacher desk
    P("TeacherDesk"..rm..side,Vector3.new(2.5,0.9,1.5),Vector3.new(rx,1,rz-4),"Wood",{140,110,65})
    P("Blackboard"..rm..side,Vector3.new(8,2.5,0.2),Vector3.new(rx,3.5,rz-4.9),"Slate",{40,60,50})
    -- Window in classroom
    P("ClassWin"..rm..side,Vector3.new(4,3,0.3),Vector3.new(rx+side*4,4,rz+4.9),"Glass",{170,215,235})
  end
end
-- Cafeteria (end of building)
P("CafeFloor",Vector3.new(20,0.2,12),Vector3.new(0,0.9,-13),"Concrete",{210,200,190})
for ct=-2,2 do
  P("CafeTable"..ct,Vector3.new(4,0.7,1.2),Vector3.new(ct*4,1,-13),"Wood",{160,130,80})
  P("CafeBenchL"..ct,Vector3.new(4,0.4,0.8),Vector3.new(ct*4,0.5,-11.8),"Wood",{140,110,65})
  P("CafeBenchR"..ct,Vector3.new(4,0.4,0.8),Vector3.new(ct*4,0.5,-14.2),"Wood",{140,110,65})
end
P("ServCounter",Vector3.new(16,1.1,1.5),Vector3.new(0,0.55,-17),"Metal",{180,180,185})
-- Gym/auditorium wing
P("GymFloor",Vector3.new(20,0.2,14),Vector3.new(-30,0.9,0),"Wood",{180,150,100})
P("GymWallL",Vector3.new(0.5,10,14),Vector3.new(-40,5,0),"Brick",{180,155,130})
P("GymWallR",Vector3.new(0.5,10,14),Vector3.new(-20,5,0),"Brick",{180,155,130})
P("GymRoof",Vector3.new(22,1,16),Vector3.new(-30,10.5,0),"Concrete",{160,160,160})
P("BasketballHoop",Vector3.new(0.2,0.2,0.2),Vector3.new(-39,7,0),"Metal",{220,130,40})
-- Flagpole
P("Flagpole",Vector3.new(0.3,12,0.3),Vector3.new(15,6,-28),"Metal",{200,200,205})
P("Flag",Vector3.new(4,2.5,0.1),Vector3.new(17,11,-28),"Fabric",{220,40,40})
-- Ceiling lights
for lx=-3,3 do
  local lp=P("HallLight"..lx,Vector3.new(0.4,0.15,0.4),Vector3.new(0,8.6,lx*5),"Metal",{255,245,210})
  L(lp,4,16,{255,245,210})
end
` + LUAU_FOOTER;
  return code;
}

export function generateHospital(params: HospitalParams): string {
  const code = LUAU_HEADER('Hospital') + `
-- Foundation
P("Foundation",Vector3.new(60,1.5,50),Vector3.new(0,-0.75,0),"Concrete",{140,140,140})
-- Floors (3 story)
for f=0,2 do
  local fy=f*6
  P("FloorSlab"..f,Vector3.new(58,0.4,48),Vector3.new(0,fy,0),"Marble",{245,245,242})
  P("WallFront"..f,Vector3.new(58,6,0.5),Vector3.new(0,fy+3,24),"Concrete",{235,235,232})
  P("WallBack"..f,Vector3.new(58,6,0.5),Vector3.new(0,fy+3,-24),"Concrete",{235,235,232})
  P("WallLeft"..f,Vector3.new(0.5,6,48),Vector3.new(-29,fy+3,0),"Concrete",{235,235,232})
  P("WallRight"..f,Vector3.new(0.5,6,48),Vector3.new(29,fy+3,0),"Concrete",{235,235,232})
  -- Windows per floor
  for w=-4,4 do
    if w~=0 then
      P("WinF"..f..w,Vector3.new(3.5,3.5,0.3),Vector3.new(w*5.5,fy+3.5,24.2),"Glass",{180,220,240})
      P("WinB"..f..w,Vector3.new(3.5,3.5,0.3),Vector3.new(w*5.5,fy+3.5,-24.2),"Glass",{180,220,240})
    end
  end
end
-- Roof
P("Roof",Vector3.new(60,1,50),Vector3.new(0,18.5,0),"Concrete",{200,200,200})
-- Helipad on roof
P("Helipad",Vector3.new(14,0.3,14),Vector3.new(0,19.15,0),"Concrete",{220,220,220})
P("HelipadCircle",Vector3.new(12,0.31,12),Vector3.new(0,19.16,0),"Concrete",{80,80,80})
P("HeliH1",Vector3.new(10,0.32,1.2),Vector3.new(0,19.17,0),"Concrete",{255,255,255})
P("HeliH2",Vector3.new(1.2,0.32,6),Vector3.new(0,19.17,0),"Concrete",{255,255,255})
-- Emergency entrance
P("ERCanopy",Vector3.new(20,0.6,8),Vector3.new(10,6,28),"Metal",{200,200,205})
P("ERSign",Vector3.new(8,2,0.5),Vector3.new(10,5,24.3),"Concrete",{200,40,40})
P("ERSignLight",Vector3.new(0.3,0.3,0.3),Vector3.new(10,5,24.6),"Metal",{255,60,60})
local erl=P("ERLight",Vector3.new(0.4,0.4,0.4),Vector3.new(10,4.5,24.6),"Metal",{255,60,60})
L(erl,5,15,{255,60,60})
-- ER bay doors
for bd=-1,1 do
  P("ERDoor"..bd,Vector3.new(4,5,0.4),Vector3.new(bd*5+10,2.5,24),"Metal",{220,220,225})
end
-- Main entrance lobby
P("LobbyFloor",Vector3.new(20,0.2,10),Vector3.new(-14,0.9,20),"Marble",{250,248,245})
P("RecDesk",Vector3.new(8,1.2,2),Vector3.new(-14,0.6,15),"Wood",{160,130,80})
P("WaitChair1",Vector3.new(1.2,1,1.2),Vector3.new(-18,0.9,20),"Fabric",{60,100,160})
P("WaitChair2",Vector3.new(1.2,1,1.2),Vector3.new(-16,0.9,20),"Fabric",{60,100,160})
P("WaitChair3",Vector3.new(1.2,1,1.2),Vector3.new(-12,0.9,20),"Fabric",{60,100,160})
-- Patient rooms (each floor)
for f=0,2 do
  local fy=f*6
  for rm=0,3 do
    local rz=-20+rm*9
    for side=-1,1,2 do
      local rx=side*22
      P("RoomWall"..f..rm..side,Vector3.new(8,5.5,0.3),Vector3.new(rx,fy+3,rz),"Concrete",{230,228,225})
      P("Bed"..f..rm..side,Vector3.new(3,0.6,6),Vector3.new(rx,fy+0.8,rz),"Metal",{220,220,225})
      P("Mattress"..f..rm..side,Vector3.new(2.8,0.3,5.8),Vector3.new(rx,fy+1.15,rz),"Fabric",{255,255,255})
      P("BedTable"..f..rm..side,Vector3.new(1.2,0.7,1.2),Vector3.new(rx+side*2,fy+1,rz+2.5),"Metal",{190,190,195})
      P("IVPole"..f..rm..side,Vector3.new(0.2,5,0.2),Vector3.new(rx+side*1.5,fy+2.5,rz+2.5),"Metal",{200,200,205})
      P("RoomLight"..f..rm..side,Vector3.new(2,0.15,0.6),Vector3.new(rx,fy+5.5,rz),"Metal",{255,250,245})
      local rl=P("RoomPointLight"..f..rm..side,Vector3.new(0.3,0.2,0.3),Vector3.new(rx,fy+5.6,rz),"Metal",{255,250,245})
      L(rl,3,10,{255,250,245})
    end
  end
end
-- Corridor lights
for f=0,2 do
  for cl=-4,4 do
    local lp=P("CorLight"..f..cl,Vector3.new(0.4,0.15,0.4),Vector3.new(cl*5,f*6+5.7,0),"Metal",{255,248,235})
    L(lp,4,15,{255,248,235})
  end
end
-- Ambulance bay
P("AmbBay",Vector3.new(14,0.4,10),Vector3.new(10,0.2,34),"Concrete",{180,180,180})
P("AmbLine",Vector3.new(12,0.45,0.3),Vector3.new(10,0.25,34),"Concrete",{255,255,0})
-- Red cross on front
P("CrossV",Vector3.new(1.5,6,0.6),Vector3.new(0,12,24.3),"Concrete",{210,40,40})
P("CrossH",Vector3.new(6,1.5,0.6),Vector3.new(0,13.5,24.3),"Concrete",{210,40,40})
` + LUAU_FOOTER;
  return code;
}

export function generateChurch(params: ChurchParams): string {
  const code = LUAU_HEADER('Church') + `
-- Foundation and steps
P("Foundation",Vector3.new(24,1,44),Vector3.new(0,-0.5,0),"Concrete",{160,150,140})
for s=0,3 do
  P("Step"..s,Vector3.new(14-s*1.5,0.4,2),Vector3.new(0,s*0.4-0.4,21+s*1.2),"Concrete",{180,170,160})
end
P("Floor",Vector3.new(22,0.4,42),Vector3.new(0,0.2,0),"Marble",{240,235,228})
-- Nave walls
P("WallLeft",Vector3.new(0.6,12,40),Vector3.new(-11,6,0),"Brick",{190,175,155})
P("WallRight",Vector3.new(0.6,12,40),Vector3.new(11,6,0),"Brick",{190,175,155})
P("WallBack",Vector3.new(22,12,0.6),Vector3.new(0,6,-21),"Brick",{190,175,155})
-- Front facade
P("FacadeLeft",Vector3.new(7,12,0.6),Vector3.new(-7,6,21),"Brick",{190,175,155})
P("FacadeRight",Vector3.new(7,12,0.6),Vector3.new(7,6,21),"Brick",{190,175,155})
P("FacadeTop",Vector3.new(22,4,0.6),Vector3.new(0,14,21),"Brick",{185,170,150})
-- Rose window
P("RoseWin",Vector3.new(5,5,0.4),Vector3.new(0,14,21.1),"Glass",{200,150,220})
P("RoseWinRing",Vector3.new(5.5,5.5,0.3),Vector3.new(0,14,21),"Brick",{170,155,140})
-- Tall arched windows (sides)
for w=-2,2 do
  if w~=0 then
    P("LeftWin"..w,Vector3.new(2,5,0.3),Vector3.new(-11,8,w*7),"Glass",{180,200,230})
    P("RightWin"..w,Vector3.new(2,5,0.3),Vector3.new(11,8,w*7),"Glass",{180,200,230})
  end
end
-- Nave roof (gabled)
P("RoofLeft",Vector3.new(0.5,0.5,42),CFrame.new(-8,14,0)*CFrame.Angles(0,0,math.rad(40))),"Brick",{130,120,110})
P("RoofRight",Vector3.new(0.5,0.5,42),CFrame.new(8,14,0)*CFrame.Angles(0,0,math.rad(-40))),"Brick",{130,120,110})
P("RoofRidge",Vector3.new(0.8,0.8,42),Vector3.new(0,16,0),"Slate",{100,95,90})
-- Bell tower
P("TowerBase",Vector3.new(8,28,8),Vector3.new(-8,14,21),"Brick",{180,165,148})
P("TowerBelfry",Vector3.new(9,4,9),Vector3.new(-8,29.5,21),"Brick",{170,155,140})
P("TowerSpire",Vector3.new(6,12,6),Vector3.new(-8,35,21),"Slate",{100,95,90})
-- Bell tower windows
for tw=0,1 do
  P("TBWin"..tw,Vector3.new(2,4,0.3),Vector3.new(-8,14+tw*6,25),"Glass",{180,200,230})
  P("TBWinB"..tw,Vector3.new(2,4,0.3),Vector3.new(-8,14+tw*6,17),"Glass",{180,200,230})
end
P("Bell",Vector3.new(2,2,2),Vector3.new(-8,28.5,21),"Metal",{200,180,100})
-- Interior pews (rows)
for pew=0,7 do
  local pz=-15+pew*3.5
  P("PewLeft"..pew,Vector3.new(6,1,1),Vector3.new(-5.5,0.7,pz),"Wood",{120,85,50})
  P("PewLeftBack"..pew,Vector3.new(6,1.5,0.3),Vector3.new(-5.5,1.4,pz+0.7),"Wood",{110,75,45})
  P("PewRight"..pew,Vector3.new(6,1,1),Vector3.new(5.5,0.7,pz),"Wood",{120,85,50})
  P("PewRightBack"..pew,Vector3.new(6,1.5,0.3),Vector3.new(5.5,1.4,pz+0.7),"Wood",{110,75,45})
end
-- Altar
P("Altar",Vector3.new(5,1.2,2),Vector3.new(0,0.6,-16),"Marble",{240,235,228})
P("AltarTop",Vector3.new(5.2,0.2,2.2),Vector3.new(0,1.3,-16),"Marble",{250,245,238})
P("Crucifix",Vector3.new(0.4,4,0.4),Vector3.new(0,5,-20),"Wood",{100,75,45})
P("CrucifixBar",Vector3.new(2.5,0.4,0.4),Vector3.new(0,7,-20),"Wood",{100,75,45})
-- Candles on altar
for c=-1,1 do
  local candle=P("Candle"..c,Vector3.new(0.3,1.5,0.3),Vector3.new(c*1.5,1.95,-16),"Metal",{255,250,240})
  L(candle,2,6,{255,220,150})
end
-- Baptismal font
P("Font",Vector3.new(2,1.5,2),Vector3.new(9,0.75,18),"Marble",{230,225,218})
P("FontBasin",Vector3.new(1.8,0.5,1.8),Vector3.new(9,1.5,18),"Marble",{240,235,228})
-- Pipe organ
P("OrganCase",Vector3.new(8,8,2),Vector3.new(0,4,-20),"Wood",{110,80,45})
for op=0,5 do
  P("OrganPipe"..op,Vector3.new(0.5,4+op*0.6,0.5),Vector3.new(-2.5+op*0.9,4+op*0.3,-20),"Metal",{180,170,150})
end
-- Chandelier
local ch=P("Chandelier",Vector3.new(4,0.5,4),Vector3.new(0,11,0),"Metal",{200,185,130})
L(ch,6,25,{255,240,200})
for ca=0,7 do
  local ang=ca*math.pi/4
  local cx=math.cos(ang)*1.5 cz=math.sin(ang)*1.5
  local candle2=P("ChanArm"..ca,Vector3.new(0.3,0.8,0.3),Vector3.new(cx,10.5,cz),"Metal",{195,180,125})
  L(candle2,1.5,5,{255,220,150})
end
` + LUAU_FOOTER;
  return code;
}

export function generateGasStation(params: GasStationParams): string {
  const code = LUAU_HEADER('GasStation') + `
-- Concrete lot
P("Lot",Vector3.new(40,0.4,35),Vector3.new(0,0.2,0),"Concrete",{180,175,170})
-- Painted lines
for pl=0,2 do
  P("ParkLine"..pl,Vector3.new(0.2,0.45,8),Vector3.new(-12+pl*6,0.25,-10),"Concrete",{255,255,255})
end
-- Main canopy (fuel island cover)
P("Canopy",Vector3.new(28,0.8,16),Vector3.new(0,8,2),"Metal",{220,220,225})
P("CanopyEdgeF",Vector3.new(28,0.5,0.4),Vector3.new(0,7.6,10),"Metal",{200,40,40})
P("CanopyEdgeB",Vector3.new(28,0.5,0.4),Vector3.new(0,7.6,-6),"Metal",{200,40,40})
P("CanopyEdgeL",Vector3.new(0.4,0.5,16),Vector3.new(-14,7.6,2),"Metal",{200,40,40})
P("CanopyEdgeR",Vector3.new(0.4,0.5,16),Vector3.new(14,7.6,2),"Metal",{200,40,40})
-- Canopy columns
for cx=-2,2,4 do
  P("CanopyCol"..cx,Vector3.new(0.8,8,0.8),Vector3.new(cx*5,4,2),"Metal",{210,210,215})
end
-- Fuel pumps
for pump=0,2 do
  local px=-8+pump*8
  P("PumpBody"..pump,Vector3.new(1.5,3.5,0.8),Vector3.new(px,1.75,0),"Metal",{220,220,225})
  P("PumpScreen"..pump,Vector3.new(1,1.2,0.2),Vector3.new(px,3,0.5),"Glass",{80,180,240})
  P("PumpNozzleL"..pump,Vector3.new(0.3,0.3,1.5),Vector3.new(px-0.9,2.5,0),"Metal",{60,60,65})
  P("PumpNozzleR"..pump,Vector3.new(0.3,0.3,1.5),Vector3.new(px+0.9,2.5,0),"Metal",{60,60,65})
  P("PumpBase"..pump,Vector3.new(2,0.4,1.2),Vector3.new(px,0.2,0),"Concrete",{160,160,160})
  -- Price display
  P("Price"..pump,Vector3.new(0.8,0.5,0.15),Vector3.new(px,3.8,0.5),"Metal",{255,180,0})
end
-- Convenience store
P("StoreFloor",Vector3.new(16,0.4,12),Vector3.new(10,0.4,-10),"Concrete",{200,195,190})
P("StoreWallL",Vector3.new(0.4,5,12),Vector3.new(2,2.5,-10),"Brick",{200,195,190})
P("StoreWallR",Vector3.new(0.4,5,12),Vector3.new(18,2.5,-10),"Brick",{200,195,190})
P("StoreWallB",Vector3.new(16,5,0.4),Vector3.new(10,2.5,-16),"Brick",{200,195,190})
P("StoreWallFrontL",Vector3.new(4,5,0.4),Vector3.new(4,2.5,-4),"Brick",{200,195,190})
P("StoreWallFrontR",Vector3.new(4,5,0.4),Vector3.new(16,2.5,-4),"Brick",{200,195,190})
P("StoreGlass",Vector3.new(7,4.5,0.3),Vector3.new(10,2.75,-4),"Glass",{170,215,235})
P("StoreRoof",Vector3.new(16.5,0.6,12.5),Vector3.new(10,5.3,-10),"Metal",{180,180,185})
P("StoreSign",Vector3.new(14,1.5,0.5),Vector3.new(10,6.5,-4.2),"Metal",{200,40,40})
local ssl=P("StoreSignLight",Vector3.new(0.3,0.3,0.3),Vector3.new(10,6.5,-3.8),"Metal",{255,100,100})
L(ssl,3,10,{255,100,100})
-- Interior shelves
P("Shelf1",Vector3.new(0.4,3,8),Vector3.new(3.5,1.5,-10),"Wood",{150,120,70})
P("Shelf2",Vector3.new(0.4,3,8),Vector3.new(6.5,1.5,-10),"Wood",{150,120,70})
P("FridgeWall",Vector3.new(10,4,0.5),Vector3.new(10,2,-15.5),"Metal",{200,200,205})
for fw=0,2 do
  P("FridgeGlass"..fw,Vector3.new(2.8,3,0.3),Vector3.new(5+fw*3,2,-15.3),"Glass",{170,215,235})
end
P("StoreCounter",Vector3.new(4,1.1,1.5),Vector3.new(16.5,0.55,-5.5),"Wood",{140,110,65})
-- Air pump station
P("AirPump",Vector3.new(0.5,1.2,0.5),Vector3.new(-17,0.6,10),"Metal",{120,120,125})
P("AirPumpBox",Vector3.new(1,1,0.8),Vector3.new(-17,1.5,10),"Metal",{100,100,105})
-- Trash cans
for tc=0,1 do
  P("TrashCan"..tc,Vector3.new(1,1.5,1),Vector3.new(14+tc*3,0.75,9),"Metal",{80,80,85})
end
-- Overhead canopy lights
for ol=-2,2 do
  local lp=P("CanopyLight"..ol,Vector3.new(1,0.3,1),Vector3.new(ol*5,7.7,2),"Metal",{255,250,230})
  L(lp,5,20,{255,250,230})
end
` + LUAU_FOOTER;
  return code;
}

export function generateBarn(params: BarnParams): string {
  const code = LUAU_HEADER('Barn') + `
-- Foundation
P("Foundation",Vector3.new(26,0.8,20),Vector3.new(0,-0.4,0),"Concrete",{140,130,120})
-- Dirt/hay floor
P("Floor",Vector3.new(24,0.3,18),Vector3.new(0,0.15,0),"Wood",{160,130,80})
-- Wooden frame posts
local posts={{-12,-9},{-12,-3},{-12,3},{-12,9},{12,-9},{12,-3},{12,3},{12,9},{0,-9},{0,9}}
for i,pos in ipairs(posts) do
  P("Post"..i,Vector3.new(1,10,1),Vector3.new(pos[1],5,pos[2]),"Wood",{120,90,50})
end
-- Red barn walls
P("WallFrontL",Vector3.new(9,10,0.5),Vector3.new(-8,5,10),"WoodPlanks",{180,40,40})
P("WallFrontR",Vector3.new(9,10,0.5),Vector3.new(8,5,10),"WoodPlanks",{180,40,40})
P("WallFrontTop",Vector3.new(24,4,0.5),Vector3.new(0,12,10),"WoodPlanks",{180,40,40})
P("WallBack",Vector3.new(24,14,0.5),Vector3.new(0,7,-10),"WoodPlanks",{180,40,40})
P("WallLeft",Vector3.new(0.5,10,18),Vector3.new(-12,5,0),"WoodPlanks",{175,38,38})
P("WallRight",Vector3.new(0.5,10,18),Vector3.new(12,5,0),"WoodPlanks",{175,38,38})
-- Gabled loft
P("LoftFloor",Vector3.new(24,0.4,18),Vector3.new(0,10.2,0),"Wood",{150,120,70})
P("LoftWallL",Vector3.new(0.5,6,18),Vector3.new(-12,13,0),"WoodPlanks",{180,40,40})
P("LoftWallR",Vector3.new(0.5,6,18),Vector3.new(12,13,0),"WoodPlanks",{180,40,40})
-- Roof
P("RoofLeft",Vector3.new(14,0.5,20),CFrame.new(-6,16.5,0)*CFrame.Angles(0,0,math.rad(30))),"WoodPlanks",{100,60,40})
P("RoofRight",Vector3.new(14,0.5,20),CFrame.new(6,16.5,0)*CFrame.Angles(0,0,math.rad(-30))),"WoodPlanks",{100,60,40})
P("RoofRidge",Vector3.new(1,0.6,20.5),Vector3.new(0,19.5,0),"Wood",{90,55,35})
-- Hay bales
for hb=0,4 do
  local hx=-9+hb*3 hz=7
  P("HayBale"..hb,Vector3.new(2,2,2),Vector3.new(hx,1.3,hz),"Fabric",{200,170,80})
end
-- Stacked hay
P("HayStack1",Vector3.new(4,2,3),Vector3.new(-8,1.3,7),"Fabric",{195,165,75})
P("HayStack2",Vector3.new(4,2,3),Vector3.new(-8,3.3,7),"Fabric",{200,170,80})
-- Horse stalls
for stall=0,2 do
  local sx=-7+stall*6
  P("StallFront"..stall,Vector3.new(5.5,4,0.3),Vector3.new(sx,2,-7.5),"Wood",{130,90,50})
  P("StallDoor"..stall,Vector3.new(5,3.5,0.2),Vector3.new(sx,1.75,-7.3),"Wood",{140,100,55})
  P("StallDiv"..stall,Vector3.new(0.3,4,4),Vector3.new(sx+2.75,2,-5.5),"Wood",{130,90,50})
  -- Feed bucket
  P("Bucket"..stall,Vector3.new(0.8,0.8,0.8),Vector3.new(sx,0.7,-8.5),"Metal",{80,80,85})
end
-- Tractor (decorative)
P("TractorBody",Vector3.new(4,3,6),Vector3.new(7,1.5,5),"Metal",{40,120,60})
P("TractorHood",Vector3.new(3,2,3),Vector3.new(7,3.5,7.5),"Metal",{35,110,55})
P("WheelFL",Vector3.new(1.5,2,1.5),Vector3.new(5,1.5,7.5),"Rubber" in Enum.Material and "Rubber" or "Metal",{30,30,30})
P("WheelFR",Vector3.new(1.5,2,1.5),Vector3.new(9,1.5,7.5),"Metal",{30,30,30})
P("WheelRL",Vector3.new(2,2.5,2),Vector3.new(5,1.5,2.5),"Metal",{25,25,25})
P("WheelRR",Vector3.new(2,2.5,2),Vector3.new(9,1.5,2.5),"Metal",{25,25,25})
-- Barn doors (large sliding)
P("DoorL",Vector3.new(5.5,9,0.6),Vector3.new(-4,4.5,10),"Wood",{160,110,60})
P("DoorR",Vector3.new(5.5,9,0.6),Vector3.new(4,4.5,10),"Wood",{160,110,60})
P("DoorRail",Vector3.new(22,0.4,0.4),Vector3.new(0,9.5,10.2),"Metal",{160,155,150})
-- Hay loft ladder
for lr=0,5 do
  P("Rung"..lr,Vector3.new(1.5,0.2,0.2),Vector3.new(10.5,1+lr*1.6,-7),"Wood",{130,90,50})
end
P("LadderL",Vector3.new(0.2,9.5,0.3),Vector3.new(9.8,5,-7),"Wood",{120,85,45})
P("LadderR",Vector3.new(0.2,9.5,0.3),Vector3.new(11.2,5,-7),"Wood",{120,85,45})
-- Lantern lights
for lt=-1,1,2 do
  local lan=P("Lantern"..lt,Vector3.new(0.8,1.5,0.8),Vector3.new(lt*9,8,10),"Metal",{180,160,80})
  L(lan,4,18,{255,200,100})
end
-- Weather vane
P("WeatherVane",Vector3.new(0.2,3,0.2),Vector3.new(0,20.5,0),"Metal",{180,170,140})
P("WeatherCock",Vector3.new(2,1,0.1),Vector3.new(0,22,0),"Metal",{190,175,140})
` + LUAU_FOOTER;
  return code;
}

export function generateLighthouse(params: LighthouseParams): string {
  const code = LUAU_HEADER('Lighthouse') + `
-- Rocky base / cliff
P("Rock1",Vector3.new(18,4,18),Vector3.new(0,-2,0),"Slate",{100,95,90})
P("Rock2",Vector3.new(14,3,14),Vector3.new(2,-1,2),"Slate",{110,105,100})
P("Rock3",Vector3.new(12,2.5,12),Vector3.new(-1,0,−1),"Concrete",{120,115,110})
-- Keeper's cottage
P("CottageFloor",Vector3.new(10,0.4,8),Vector3.new(8,0.7,0),"Concrete",{160,150,140})
P("CottageWallF",Vector3.new(10,4,0.4),Vector3.new(8,2.7,4),"Brick",{200,170,140})
P("CottageWallB",Vector3.new(10,4,0.4),Vector3.new(8,2.7,-4),"Brick",{200,170,140})
P("CottageWallL",Vector3.new(0.4,4,8),Vector3.new(3,2.7,0),"Brick",{195,165,138})
P("CottageWallR",Vector3.new(0.4,4,8),Vector3.new(13,2.7,0),"Brick",{195,165,138})
P("CottageRoofL",Vector3.new(11,0.4,4.5),CFrame.new(5,5.5,0)*CFrame.Angles(0,0,math.rad(30))),"Slate",{80,70,60})
P("CottageRoofR",Vector3.new(11,0.4,4.5),CFrame.new(11,5.5,0)*CFrame.Angles(0,0,math.rad(-30))),"Slate",{80,70,60})
P("CottageDoor",Vector3.new(1.5,3,0.4),Vector3.new(8,1.5,4.1),"Wood",{110,80,45})
P("CottageWin",Vector3.new(1.8,1.8,0.3),Vector3.new(10.5,3,4.2),"Glass",{170,215,235})
-- Tower base (wide)
P("TowerBase",Vector3.new(5,3,5),Vector3.new(0,1.5,0),"Brick",{235,225,210})
-- Tower cylinder (stacked rings)
for ring=0,9 do
  local ry=ring*3+3
  local rad=2.5-ring*0.12
  P("Ring"..ring,Vector3.new(rad*2,3,rad*2),Vector3.new(0,ry+1.5,0),"Brick",{230+ring,220+ring,205+ring})
end
-- Red stripe bands
for stripe=0,4 do
  local sy=stripe*6+4
  P("Stripe"..stripe,Vector3.new(4.8-stripe*0.22,1,4.8-stripe*0.22),Vector3.new(0,sy,0),"Brick",{200,40,40})
end
-- Tower door
P("TowerDoor",Vector3.new(1.5,2.5,0.3),Vector3.new(0,1.25,2.6),"Wood",{120,85,50})
P("TowerDoorArch",Vector3.new(2,0.6,0.3),Vector3.new(0,2.8,2.6),"Brick",{220,210,195})
-- Gallery walkway
P("Gallery",Vector3.new(6,0.8,6),Vector3.new(0,31,0),"Metal",{160,155,150})
P("GalleryRailN",Vector3.new(6,1,0.15),Vector3.new(0,31.5,3),"Metal",{140,135,130})
P("GalleryRailS",Vector3.new(6,1,0.15),Vector3.new(0,31.5,-3),"Metal",{140,135,130})
P("GalleryRailE",Vector3.new(0.15,1,6),Vector3.new(3,31.5,0),"Metal",{140,135,130})
P("GalleryRailW",Vector3.new(0.15,1,6),Vector3.new(-3,31.5,0),"Metal",{140,135,130})
-- Lantern room
P("LanternRoom",Vector3.new(4,5,4),Vector3.new(0,34.5,0),"Metal",{180,180,185})
P("LanternGlass1",Vector3.new(3.5,3.5,0.2),Vector3.new(0,34.5,2.1),"Glass",{180,220,240})
P("LanternGlass2",Vector3.new(3.5,3.5,0.2),Vector3.new(0,34.5,-2.1),"Glass",{180,220,240})
P("LanternGlass3",Vector3.new(0.2,3.5,3.5),Vector3.new(2.1,34.5,0),"Glass",{180,220,240})
P("LanternGlass4",Vector3.new(0.2,3.5,3.5),Vector3.new(-2.1,34.5,0),"Glass",{180,220,240})
-- The light itself (rotating beacon)
local beacon=P("Beacon",Vector3.new(2,1.5,2),Vector3.new(0,36.75,0),"Metal",{255,255,240})
L(beacon,20,80,{255,255,200})
P("BeaconLens",Vector3.new(1.5,1,1.5),Vector3.new(0,36.75,0),"Glass",{255,255,200})
-- Dome roof
P("LanternDome",Vector3.new(4.5,2.5,4.5),Vector3.new(0,37.5,0),"Metal",{170,165,160})
P("DomeTip",Vector3.new(0.6,1.5,0.6),Vector3.new(0,39,0),"Metal",{160,155,150})
-- Interior spiral stairs (decorative segments)
for step=0,11 do
  local ang=step*math.pi/6
  local sx=math.cos(ang)*1.8 sz=math.sin(ang)*1.8
  P("StairStep"..step,Vector3.new(1.5,0.3,0.8),Vector3.new(sx,step*2.8+1.5,sz),"Concrete",{170,160,150})
end
-- Rocks in water
P("SmallRock1",Vector3.new(5,2,4),Vector3.new(-12,-1,8),"Slate",{90,85,80})
P("SmallRock2",Vector3.new(4,1.5,3),Vector3.new(10,-0.5,12),"Slate",{95,90,85})
P("SmallRock3",Vector3.new(3,1,4),Vector3.new(−14,0,−5),"Slate",{100,95,90})
-- Navigation marker
P("RedBuoy",Vector3.new(1,1.5,1),Vector3.new(20,0.75,20),"Concrete",{200,40,40})
local bl=P("BuoyLight",Vector3.new(0.4,0.4,0.4),Vector3.new(20,1.75,20),"Metal",{255,60,60})
L(bl,3,10,{255,60,60})
` + LUAU_FOOTER;
  return code;
}

export function generatePrison(params: PrisonParams): string {
  const code = LUAU_HEADER('Prison') + `
-- Outer perimeter wall
local pw=36 pd=28
P("OuterWallN",Vector3.new(pw+4,8,1.5),Vector3.new(0,4,pd/2+2),"Concrete",{160,160,160})
P("OuterWallS",Vector3.new(pw+4,8,1.5),Vector3.new(0,4,-(pd/2+2)),"Concrete",{160,160,160})
P("OuterWallE",Vector3.new(1.5,8,pd+4),Vector3.new(pw/2+2,4,0),"Concrete",{160,160,160})
P("OuterWallW",Vector3.new(1.5,8,pd+4),Vector3.new(-(pw/2+2),4,0),"Concrete",{160,160,160})
-- Guard towers at corners
local corners={{pw/2+2,pd/2+2},{pw/2+2,-(pd/2+2)},{-(pw/2+2),pd/2+2},{-(pw/2+2),-(pd/2+2)}}
for i,c in ipairs(corners) do
  P("GuardTower"..i,Vector3.new(5,12,5),Vector3.new(c[1],6,c[2]),"Concrete",{150,150,150})
  P("GTRoof"..i,Vector3.new(6,0.8,6),Vector3.new(c[1],12.4,c[2]),"Metal",{130,130,135})
  P("GTLight"..i,Vector3.new(1,0.5,0.5),Vector3.new(c[1],12,c[2]+2.5),"Metal",{240,240,200})
  local gtl=P("GTPointLight"..i,Vector3.new(0.4,0.4,0.4),Vector3.new(c[1],11.5,c[2]),"Metal",{255,255,200})
  L(gtl,8,30,{255,255,200})
  -- Tower windows
  P("GTWin"..i,Vector3.new(1.5,2,0.3),Vector3.new(c[1],9,c[2]+2.6),"Glass",{160,200,225})
end
-- Barbed wire on outer walls
for bwi=0,6 do
  P("BarbedWire"..bwi,Vector3.new(0.1,0.4,pw),Vector3.new(-(pw/2-3)+bwi*(pw/7),8.5,pd/2+2),"Metal",{180,175,170})
end
-- Main building
P("MainBldgFloor",Vector3.new(pw,0.4,pd),Vector3.new(0,0.7,0),"Concrete",{190,185,180})
P("MainWallN",Vector3.new(pw,8,0.6),Vector3.new(0,4,pd/2),"Concrete",{180,175,170})
P("MainWallS",Vector3.new(pw,8,0.6),Vector3.new(0,4,-pd/2),"Concrete",{180,175,170})
P("MainWallE",Vector3.new(0.6,8,pd),Vector3.new(pw/2,4,0),"Concrete",{180,175,170})
P("MainWallW",Vector3.new(0.6,8,pd),Vector3.new(-pw/2,4,0),"Concrete",{180,175,170})
P("MainRoof",Vector3.new(pw+1,0.8,pd+1),Vector3.new(0,8.4,0),"Concrete",{170,165,160})
-- Central corridor
P("CorridorFloor",Vector3.new(4,0.3,pd),Vector3.new(0,1,0),"Concrete",{200,195,190})
P("CorridorWallL",Vector3.new(0.3,7.5,pd),Vector3.new(-2,4.25,0),"Concrete",{190,185,180})
P("CorridorWallR",Vector3.new(0.3,7.5,pd),Vector3.new(2,4.25,0),"Concrete",{190,185,180})
-- Cell blocks (left and right)
for cell=0,6 do
  local cz=-pd/2+2+cell*3.5
  for side=-1,1,2 do
    local cx=side*12
    -- Cell walls
    P("CellWallF"..cell..side,Vector3.new(6,7,0.3),Vector3.new(cx,3.5,cz+1.75),"Concrete",{195,190,185})
    P("CellWallB"..cell..side,Vector3.new(6,7,0.3),Vector3.new(cx,3.5,cz),"Concrete",{190,185,180})
    -- Cell bars
    for bar=0,3 do
      P("Bar"..cell..side..bar,Vector3.new(0.15,6.5,0.15),Vector3.new(cx-2.25+bar*1.5,3.5,cz+1.75),"Metal",{80,80,85})
    end
    -- Bunk bed
    P("BunkL"..cell..side,Vector3.new(1.8,0.3,4),Vector3.new(cx-1.5,1.5,cz+0.8),"Metal",{160,160,165})
    P("BunkU"..cell..side,Vector3.new(1.8,0.3,4),Vector3.new(cx-1.5,3.5,cz+0.8),"Metal",{160,160,165})
    P("MattL"..cell..side,Vector3.new(1.6,0.2,3.8),Vector3.new(cx-1.5,1.7,cz+0.8),"Fabric",{200,190,180})
    P("MattU"..cell..side,Vector3.new(1.6,0.2,3.8),Vector3.new(cx-1.5,3.7,cz+0.8),"Fabric",{200,190,180})
    -- Toilet
    P("Toilet"..cell..side,Vector3.new(0.8,1,0.8),Vector3.new(cx+1.8,0.7,cz+0.3),"Concrete",{230,228,225})
    -- Cell sink
    P("Sink"..cell..side,Vector3.new(0.8,0.6,0.5),Vector3.new(cx+1.8,1.8,cz+1.5),"Metal",{210,210,215})
  end
end
-- Guard station / control room
P("ControlRoom",Vector3.new(8,7,6),Vector3.new(0,3.5,-pd/2+3),"Concrete",{185,180,175})
P("ControlDesk",Vector3.new(6,1.2,2),Vector3.new(0,0.6,-pd/2+4),"Metal",{160,160,165})
P("ControlPanel",Vector3.new(5,1.5,0.5),Vector3.new(0,1.95,-pd/2+3.2),"Metal",{50,55,60})
-- Yard
P("Yard",Vector3.new(30,0.3,15),Vector3.new(0,0.15,pd/2+8),"Concrete",{180,178,175})
P("YardFenceN",Vector3.new(30,3,0.3),Vector3.new(0,1.5,pd/2+15.5),"Metal",{140,140,145})
P("YardFenceE",Vector3.new(0.3,3,15),Vector3.new(15,1.5,pd/2+8),"Metal",{140,140,145})
P("YardFenceW",Vector3.new(0.3,3,15),Vector3.new(-15,1.5,pd/2+8),"Metal",{140,140,145})
P("Basketball",Vector3.new(0.5,3,0.5),Vector3.new(8,1.5,pd/2+8),"Metal",{220,130,40})
P("BasketHoop",Vector3.new(2,0.2,2),Vector3.new(8,3,pd/2+8),"Metal",{200,120,35})
-- Corridor lights
for lz=0,6 do
  local lp=P("CorLight"..lz,Vector3.new(0.4,0.15,0.4),Vector3.new(0,7.8,-pd/2+3+lz*3.5),"Metal",{255,248,220})
  L(lp,4,16,{255,248,220})
end
` + LUAU_FOOTER;
  return code;
}

export function generateSpaceStation(params: SpaceStationParams): string {
  const code = LUAU_HEADER('SpaceStation') + `
-- Central hub (main ring)
P("CentralHub",Vector3.new(14,10,14),Vector3.new(0,0,0),"Metal",{180,185,190})
P("HubRing",Vector3.new(16,1,16),Vector3.new(0,5,0),"Metal",{160,165,170})
P("HubRingB",Vector3.new(16,1,16),Vector3.new(0,-5,0),"Metal",{160,165,170})
P("HubGlass",Vector3.new(12,8,0.3),Vector3.new(0,0,7.2),"Glass",{140,180,220})
P("HubGlass2",Vector3.new(12,8,0.3),Vector3.new(0,0,-7.2),"Glass",{140,180,220})
P("HubGlass3",Vector3.new(0.3,8,12),Vector3.new(7.2,0,0),"Glass",{140,180,220})
P("HubGlass4",Vector3.new(0.3,8,12),Vector3.new(-7.2,0,0),"Glass",{140,180,220})
-- Central command deck
P("CmdDeck",Vector3.new(8,1,8),Vector3.new(0,2,0),"Metal",{150,155,160})
P("CmdConsole",Vector3.new(6,1.5,1),Vector3.new(0,3,3),"Metal",{50,55,60})
P("CmdScreen",Vector3.new(5.5,2,0.2),Vector3.new(0,4.5,3),"Glass",{80,160,220})
local csl=P("ScreenLight",Vector3.new(0.3,0.3,0.3),Vector3.new(0,4.5,3.2),"Metal",{80,160,220})
L(csl,4,12,{80,160,220})
P("CaptainChair",Vector3.new(2,1.5,2),Vector3.new(0,3,-2),"Fabric",{40,50,70})
-- Habitat modules (arms extending out)
local arms={{20,0,0},{-20,0,0},{0,0,20},{0,0,-20}}
for i,arm in ipairs(arms) do
  P("Corridor"..i,Vector3.new(3,3,8),Vector3.new(arm[1]*0.6,0,arm[3]*0.6),"Metal",{170,175,180})
  P("Module"..i,Vector3.new(10,8,10),Vector3.new(arm[1],0,arm[3]),"Metal",{175,180,185})
  -- Module windows
  P("ModWin"..i.."a",Vector3.new(2.5,2.5,0.3),Vector3.new(arm[1]+3,1,arm[3]+5.2),"Glass",{140,180,220})
  P("ModWin"..i.."b",Vector3.new(2.5,2.5,0.3),Vector3.new(arm[1]-3,1,arm[3]+5.2),"Glass",{140,180,220})
  -- Airlock
  P("Airlock"..i,Vector3.new(4,4,2),Vector3.new(arm[1],0,arm[3]+7),"Metal",{155,160,165})
  P("AirlockDoor"..i,Vector3.new(2.5,3.5,0.3),Vector3.new(arm[1],0,arm[3]+8.2),"Metal",{130,135,140})
  -- Module interior
  P("Bunk"..i.."A",Vector3.new(2,0.4,5),Vector3.new(arm[1]+3,1,arm[3]-1),"Metal",{160,165,170})
  P("Bunk"..i.."B",Vector3.new(2,0.4,5),Vector3.new(arm[1]-3,1,arm[3]-1),"Metal",{160,165,170})
  P("LifeSupport"..i,Vector3.new(1.5,4,1.5),Vector3.new(arm[1]+4,0,arm[3]-4),"Metal",{80,160,120})
  -- Module lights
  local ml=P("ModLight"..i,Vector3.new(0.4,0.15,3),Vector3.new(arm[1],3.8,arm[3]),"Metal",{255,250,245})
  L(ml,4,16,{255,250,245})
end
-- Solar panels (large wing arrays)
local panels={{35,0,0},{-35,0,0}}
for i,pn in ipairs(panels) do
  P("SolarArm"..i,Vector3.new(3,1,50),Vector3.new(pn[1],8,0),"Metal",{170,175,180})
  P("SolarPanel"..i.."A",Vector3.new(2,0.4,20),Vector3.new(pn[1],9.2,12),"Metal",{30,50,100})
  P("SolarPanel"..i.."B",Vector3.new(2,0.4,20),Vector3.new(pn[1],9.2,-12),"Metal",{30,50,100})
  P("SolarCell"..i.."A",Vector3.new(1.8,0.2,19.5),Vector3.new(pn[1],9.5,12),"Glass",{40,80,180})
  P("SolarCell"..i.."B",Vector3.new(1.8,0.2,19.5),Vector3.new(pn[1],9.5,-12),"Glass",{40,80,180})
  -- Cell grid lines
  for grid=0,4 do
    P("Grid"..i..grid,Vector3.new(0.1,0.25,20),Vector3.new(pn[1]-0.8+grid*0.4,9.6,12),"Metal",{50,50,55})
  end
end
-- Science lab module (top)
P("LabSpire",Vector3.new(3,4,3),Vector3.new(0,12,0),"Metal",{180,185,190})
P("LabModule",Vector3.new(8,6,8),Vector3.new(0,17,0),"Metal",{175,180,185})
P("LabDome",Vector3.new(8,4,8),Vector3.new(0,22,0),"Glass",{140,180,220})
P("TelescopeTube",Vector3.new(1,8,1),Vector3.new(2,24,0),"Metal",{160,165,170})
P("TelescopeEnd",Vector3.new(2,1,2),Vector3.new(2,28.5,0),"Metal",{150,155,160})
-- Antenna array
for ant=0,4 do
  local aang=ant*math.pi*2/5
  local ax=math.cos(aang)*6 az=math.sin(aang)*6
  P("Antenna"..ant,Vector3.new(0.3,8,0.3),Vector3.new(ax,5,az),"Metal",{190,190,195})
  P("AntennaDish"..ant,Vector3.new(2,0.5,2),Vector3.new(ax,9.5,az),"Metal",{200,200,205})
  local al=P("AntennaLight"..ant,Vector3.new(0.3,0.3,0.3),Vector3.new(ax,9.8,az),"Metal",{255,0,0})
  L(al,2,8,{255,0,0})
end
-- Engine pods (bottom)
for ep=0,3 do
  local eang=ep*math.pi/2
  local ex=math.cos(eang)*10 ez=math.sin(eang)*10
  P("EngPod"..ep,Vector3.new(3,6,3),Vector3.new(ex,-9,ez),"Metal",{150,155,160})
  P("EngNozzle"..ep,Vector3.new(2.5,3,2.5),Vector3.new(ex,-13,ez),"Metal",{130,135,140})
  P("EngGlow"..ep,Vector3.new(2,1,2),Vector3.new(ex,-15,ez),"Neon",{80,180,255})
  local egl=P("EngLight"..ep,Vector3.new(0.3,0.3,0.3),Vector3.new(ex,-14.5,ez),"Metal",{80,180,255})
  L(egl,6,15,{80,180,255})
end
-- Docking clamps
for dc=0,1 do
  P("DockClamp"..dc,Vector3.new(8,2,8),Vector3.new(dc*14-7,-7,0),"Metal",{165,170,175})
  P("ClampArm"..dc.."A",Vector3.new(0.8,0.8,5),Vector3.new(dc*14-7,-6,-4),"Metal",{155,160,165})
  P("ClampArm"..dc.."B",Vector3.new(0.8,0.8,5),Vector3.new(dc*14-7,-6,4),"Metal",{155,160,165})
end
-- Observation cupola
P("Cupola",Vector3.new(6,3,6),Vector3.new(0,-8,0),"Glass",{140,180,220})
P("CupolaRing",Vector3.new(7,0.6,7),Vector3.new(0,-6.7,0),"Metal",{160,165,170})
P("CupolaFloor",Vector3.new(5,0.3,5),Vector3.new(0,-9.4,0),"Metal",{170,175,180})
local copLight=P("CupolaLight",Vector3.new(0.4,0.4,0.4),Vector3.new(0,-7,0),"Metal",{255,245,210})
L(copLight,3,15,{255,245,210})
-- Status lights around hull
for sl=0,11 do
  local sang=sl*math.pi/6
  local sx=math.cos(sang)*8 sz=math.sin(sang)*8
  local scolor=sl%3==0 and {255,0,0} or sl%3==1 and {0,255,0} or {255,200,0}
  local slp=P("StatusLight"..sl,Vector3.new(0.3,0.3,0.3),Vector3.new(sx,5.5,sz),"Metal",scolor)
  L(slp,1,5,scolor)
end
` + LUAU_FOOTER;
  return code;
}
