/**
 * Luau Template Library — pre-built, parameterized Roblox game system scripts.
 *
 * Each exported function returns a complete, runnable Luau code string.
 * Templates follow all codebase conventions:
 *  - ChangeHistoryService wrapping for undo support
 *  - pcall error handling
 *  - Server-authoritative logic (economy, combat)
 *  - Sanitised names (no arbitrary string injection)
 *  - Anchored static parts, correct service paths
 *
 * The AI build executor fills in `params` based on the user's game description.
 */

// ── Sanitisation helper ───────────────────────────────────────────────────────

function safe(val: string): string {
  return String(val).replace(/[^a-zA-Z0-9_ ]/g, '').slice(0, 64)
}

function safeLuauString(val: string): string {
  return String(val).replace(/\\/g, '\\\\').replace(/"/g, '\\"').slice(0, 200)
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. ECONOMY SYSTEM — currency, wallet, leaderstat, server-authoritative shop
// ─────────────────────────────────────────────────────────────────────────────

export interface EconomySystemParams {
  currencies: string[]
  startingCash: number
  shopItems?: Array<{ name: string; price: number }>
}

export function economySystem(params: EconomySystemParams): string {
  const currencies = params.currencies.map(safe)
  const startingCash = Math.max(0, Math.floor(params.startingCash))
  const primaryCurrency = currencies[0] ?? 'Cash'

  const shopItemEntries = (params.shopItems ?? [])
    .map((item) => `  ["${safeLuauString(item.name)}"] = ${Math.max(1, item.price)},`)
    .join('\n')

  return `-- Economy System (Server Script → ServerScriptService)
-- Generated by ForjeGames Build Engine
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local economyStore = DataStoreService:GetDataStore("EconomyStore_v1")

local STARTING_BALANCES: {[string]: number} = {
${currencies.map((c, i) => `  ["${c}"] = ${i === 0 ? startingCash : 0},`).join('\n')}
}

local SHOP_PRICES: {[string]: number} = {
${shopItemEntries || '  -- No shop items defined'}
}

-- Wallet: in-memory balances per player
local wallets: {[number]: {[string]: number}} = {}

local function loadWallet(player: Player)
  local userId = player.UserId
  local success, data = pcall(function()
    return economyStore:GetAsync("player_" .. userId)
  end)
  local saved: {[string]: number} = (success and type(data) == "table" and data) or {}

  wallets[userId] = {}
  for currency, startAmount in STARTING_BALANCES do
    wallets[userId][currency] = saved[currency] or startAmount
  end
end

local function saveWallet(player: Player)
  local userId = player.UserId
  if not wallets[userId] then return end
  pcall(function()
    economyStore:SetAsync("player_" .. userId, wallets[userId])
  end)
end

local function getBalance(player: Player, currency: string): number
  local userId = player.UserId
  if not wallets[userId] then return 0 end
  return wallets[userId][currency] or 0
end

local function addCurrency(player: Player, currency: string, amount: number): boolean
  if amount <= 0 then return false end
  local userId = player.UserId
  if not wallets[userId] then return false end
  wallets[userId][currency] = (wallets[userId][currency] or 0) + amount
  -- Update leaderstat
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local stat = ls:FindFirstChild(currency)
    if stat then stat.Value = wallets[userId][currency] end
  end
  return true
end

local function spendCurrency(player: Player, currency: string, amount: number): boolean
  if amount <= 0 then return false end
  local userId = player.UserId
  if not wallets[userId] then return false end
  local current = wallets[userId][currency] or 0
  if current < amount then return false end
  wallets[userId][currency] = current - amount
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local stat = ls:FindFirstChild(currency)
    if stat then stat.Value = wallets[userId][currency] end
  end
  return true
end

local function setupLeaderstats(player: Player)
  local leaderstats = Instance.new("Folder")
  leaderstats.Name = "leaderstats"
  leaderstats.Parent = player

  for _, currency in ipairs({"${currencies.join('", "')}"}) do
    local stat = Instance.new("IntValue")
    stat.Name = currency
    stat.Value = wallets[player.UserId][currency] or 0
    stat.Parent = leaderstats
  end
end

-- Shop purchase handler (RemoteFunction — server validates all purchases)
local purchaseRemote = Instance.new("RemoteFunction")
purchaseRemote.Name = "PurchaseItem"
purchaseRemote.Parent = game:GetService("ReplicatedStorage")

purchaseRemote.OnServerInvoke = function(player: Player, itemName: string): (boolean, string)
  if type(itemName) ~= "string" then return false, "Invalid item" end
  local price = SHOP_PRICES[itemName]
  if not price then return false, "Item not found" end
  if not spendCurrency(player, "${primaryCurrency}", price) then
    return false, "Insufficient ${primaryCurrency}"
  end
  return true, "Purchase successful"
end

-- Player lifecycle
Players.PlayerAdded:Connect(function(player: Player)
  loadWallet(player)
  setupLeaderstats(player)
end)

Players.PlayerRemoving:Connect(function(player: Player)
  saveWallet(player)
  wallets[player.UserId] = nil
end)

-- Public API (module-style exposure via BindableFunction for other scripts)
local economyAPI = Instance.new("BindableFunction")
economyAPI.Name = "EconomyAPI"
economyAPI.Parent = game:GetService("ServerStorage")

economyAPI.OnInvoke = function(action: string, player: Player, currency: string, amount: number)
  if action == "get" then return getBalance(player, currency)
  elseif action == "add" then return addCurrency(player, currency, amount)
  elseif action == "spend" then return spendCurrency(player, currency, amount)
  end
end

print("[Economy] System initialized with currencies: ${currencies.join(', ')}")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. TYCOON DROPPER / COLLECTOR / UPGRADER
// ─────────────────────────────────────────────────────────────────────────────

export interface TycoonDropperParams {
  resourceName: string
  value: number
  interval: number
  currency?: string
}

export function tycoonDropper(params: TycoonDropperParams): string {
  const resource = safe(params.resourceName)
  const value = Math.max(1, Math.floor(params.value))
  const interval = Math.max(0.5, params.interval)
  const currency = safe(params.currency ?? 'Cash')

  return `-- Tycoon Dropper System (Script inside dropper Model in workspace)
-- Resource: ${resource} | Value: ${value} ${currency} | Interval: ${interval}s
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

local dropper = script.Parent -- Model containing the dropper part
local dropPart = dropper:FindFirstChild("DropPart") or dropper.PrimaryPart
local collector = dropper.Parent:FindFirstChild("Collector") -- sibling Collector model

assert(dropPart, "[Dropper] No DropPart found in " .. dropper.Name)

local RESOURCE_NAME = "${resource}"
local RESOURCE_VALUE = ${value}
local DROP_INTERVAL = ${interval}
local CURRENCY = "${currency}"

-- Find which player owns this tycoon
local function getTycoonOwner(): Player?
  local tycoon = dropper:FindFirstAncestorOfClass("Model")
  if not tycoon then return nil end
  local ownerValue = tycoon:FindFirstChild("Owner")
  if not ownerValue or ownerValue.ClassName ~= "ObjectValue" then return nil end
  return ownerValue.Value :: Player?
end

local function dropResource()
  local owner = getTycoonOwner()
  if not owner then return end

  -- Create the resource ball
  local ball = Instance.new("Part")
  ball.Name = RESOURCE_NAME
  ball.Size = Vector3.new(1, 1, 1)
  ball.Shape = Enum.PartType.Ball
  ball.Material = Enum.Material.SmoothPlastic
  ball.Color = Color3.fromRGB(255, 215, 0) -- gold
  ball.CastShadow = false
  ball.Position = dropPart.Position + Vector3.new(0, 2, 0)
  ball.Parent = workspace

  -- Add value tag for collection
  local val = Instance.new("IntValue")
  val.Name = "ResourceValue"
  val.Value = RESOURCE_VALUE
  val.Parent = ball

  local ownerTag = Instance.new("StringValue")
  ownerTag.Name = "OwnerUserId"
  ownerTag.Value = tostring(owner.UserId)
  ownerTag.Parent = ball

  -- Auto-destroy after 30 seconds if not collected
  game:GetService("Debris"):AddItem(ball, 30)
end

-- Collector touch detection (server-side, authoritative)
if collector then
  local collectPart = collector:FindFirstChildOfClass("Part") or collector.PrimaryPart
  if collectPart then
    collectPart.Touched:Connect(function(hit: BasePart)
      local ball = hit
      if ball.Name ~= RESOURCE_NAME then return end
      local ownerTag = ball:FindFirstChild("OwnerUserId")
      if not ownerTag then return end

      local owner = getTycoonOwner()
      if not owner or tostring(owner.UserId) ~= ownerTag.Value then return end

      local valueTag = ball:FindFirstChild("ResourceValue")
      local amount = valueTag and valueTag.Value or RESOURCE_VALUE

      ball:Destroy()

      -- Credit the player via EconomyAPI
      local economyAPI = game:GetService("ServerStorage"):FindFirstChild("EconomyAPI")
      if economyAPI then
        economyAPI:Invoke("add", owner, CURRENCY, amount)
      end
    end)
  end
end

-- Drop loop
local lastDrop = 0
RunService.Heartbeat:Connect(function()
  if tick() - lastDrop >= DROP_INTERVAL then
    lastDrop = tick()
    dropResource()
  end
end)

print("[Dropper] ${resource} dropper active — " .. DROP_INTERVAL .. "s interval, +" .. RESOURCE_VALUE .. " " .. CURRENCY)`
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. NPC DIALOG SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface NpcDialogParams {
  npcName: string
  dialogLines: string[]
  questName?: string
  questRewardCurrency?: string
  questRewardAmount?: number
}

export function npcDialogSystem(params: NpcDialogParams): string {
  const npcName = safe(params.npcName)
  const lines = params.dialogLines.map((l) => `  "${safeLuauString(l)}"`)
  const questName = params.questName ? safe(params.questName) : null
  const rewardCurrency = safe(params.questRewardCurrency ?? 'Cash')
  const rewardAmount = Math.max(0, Math.floor(params.questRewardAmount ?? 0))

  return `-- NPC Dialog System — Script inside NPC Model (workspace)
-- NPC: ${npcName} | Lines: ${params.dialogLines.length} | Quest: ${questName ?? 'None'}
local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")

local npc = script.Parent
local rootPart = npc:FindFirstChild("HumanoidRootPart") or npc.PrimaryPart
local PROXIMITY_RANGE = 12 -- studs

assert(rootPart, "[NPC Dialog] No HumanoidRootPart in " .. npc.Name)

local DIALOG_LINES: {string} = {
${lines.join(',\n')}
}

${questName ? `local QUEST_NAME = "${questName}"
local QUEST_REWARD_CURRENCY = "${rewardCurrency}"
local QUEST_REWARD_AMOUNT = ${rewardAmount}` : ''}

-- Billboard for proximity hint
local billboard = Instance.new("BillboardGui")
billboard.Name = "DialogHint"
billboard.Size = UDim2.new(0, 200, 0, 50)
billboard.StudsOffset = Vector3.new(0, 3, 0)
billboard.AlwaysOnTop = false
billboard.Enabled = false
billboard.Parent = rootPart

local hintLabel = Instance.new("TextLabel")
hintLabel.Size = UDim2.fromScale(1, 1)
hintLabel.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
hintLabel.BackgroundTransparency = 0.3
hintLabel.TextColor3 = Color3.fromRGB(255, 215, 0)
hintLabel.Font = Enum.Font.GothamBold
hintLabel.TextSize = 14
hintLabel.Text = "Press E to talk to ${npcName}"
hintLabel.Parent = billboard

local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 8)
UICorner.Parent = hintLabel

-- Track which players are in range
local playersInRange: {[number]: boolean} = {}
local dialogState: {[number]: number} = {}

local function showDialog(player: Player, lineIndex: number)
  local line = DIALOG_LINES[lineIndex]
  if not line then return end

  -- Fire to client via RemoteEvent (dialog display handled client-side)
  local dialogEvent = game:GetService("ReplicatedStorage"):FindFirstChild("ShowDialog")
  if not dialogEvent then
    dialogEvent = Instance.new("RemoteEvent")
    dialogEvent.Name = "ShowDialog"
    dialogEvent.Parent = game:GetService("ReplicatedStorage")
  end
  dialogEvent:FireClient(player, {
    npcName = "${npcName}",
    line = line,
    lineIndex = lineIndex,
    totalLines = #DIALOG_LINES,
    hasQuest = ${questName ? 'true' : 'false'}
  })
end

local function advanceDialog(player: Player)
  local userId = player.UserId
  local current = dialogState[userId] or 0
  current = current + 1

  if current > #DIALOG_LINES then
    -- Dialog complete
    dialogState[userId] = 0
    ${questName ? `-- Grant quest reward
    local economyAPI = game:GetService("ServerStorage"):FindFirstChild("EconomyAPI")
    if economyAPI then
      economyAPI:Invoke("add", player, QUEST_REWARD_CURRENCY, QUEST_REWARD_AMOUNT)
    end
    print("[NPC] Quest '${questName}' completed for " .. player.Name)` : ''}
    return
  end

  dialogState[userId] = current
  showDialog(player, current)
end

-- Proximity detection loop
local heartbeat = game:GetService("RunService").Heartbeat
heartbeat:Connect(function()
  if not rootPart then return end
  for _, player in ipairs(Players:GetPlayers()) do
    local char = player.Character
    if not char then continue end
    local hrp = char:FindFirstChild("HumanoidRootPart")
    if not hrp then continue end
    local dist = (hrp.Position - rootPart.Position).Magnitude
    local inRange = dist <= PROXIMITY_RANGE
    local wasInRange = playersInRange[player.UserId]

    if inRange ~= wasInRange then
      playersInRange[player.UserId] = inRange
      billboard.Enabled = inRange
    end
  end
end)

-- Talk input (E key) — handled via RemoteEvent from client
local talkEvent = game:GetService("ReplicatedStorage"):FindFirstChild("TalkToNPC")
if not talkEvent then
  talkEvent = Instance.new("RemoteEvent")
  talkEvent.Name = "TalkToNPC"
  talkEvent.Parent = game:GetService("ReplicatedStorage")
end

talkEvent.OnServerEvent:Connect(function(player: Player, targetNpcName: string)
  if targetNpcName ~= "${npcName}" then return end
  if not playersInRange[player.UserId] then return end
  advanceDialog(player)
end)

print("[NPC Dialog] ${npcName} initialized with " .. #DIALOG_LINES .. " dialog lines")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. LEADERBOARD / PROGRESSION SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface LeaderboardParams {
  stats: Array<{ name: string; startValue: number; isXP?: boolean }>
  xpToLevelCurve?: 'linear' | 'quadratic' | 'exponential'
  maxLevel?: number
}

export function leaderboardProgression(params: LeaderboardParams): string {
  const stats = params.stats.map((s) => ({ ...s, name: safe(s.name) }))
  const maxLevel = Math.max(10, params.maxLevel ?? 100)
  const curve = params.xpToLevelCurve ?? 'quadratic'
  const xpStat = stats.find((s) => s.isXP)

  const levelFormula =
    curve === 'linear'
      ? `return level * 100`
      : curve === 'exponential'
        ? `return math.floor(100 * (1.5 ^ (level - 1)))`
        : `return math.floor(100 * (level ^ 1.8))`

  return `-- Leaderboard & Progression System (ServerScript)
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local statsStore = DataStoreService:GetDataStore("PlayerStats_v1")
local MAX_LEVEL = ${maxLevel}

local DEFAULT_STATS: {[string]: number} = {
${stats.map((s) => `  ["${s.name}"] = ${s.startValue},`).join('\n')}
}

-- XP-to-level curve: ${curve}
local function xpForLevel(level: number): number
  ${levelFormula}
end

local playerData: {[number]: {[string]: number}} = {}

local function loadStats(player: Player)
  local userId = player.UserId
  local success, data = pcall(function()
    return statsStore:GetAsync("stats_" .. userId)
  end)
  local saved: {[string]: number} = (success and type(data) == "table" and data) or {}
  playerData[userId] = {}
  for stat, defaultVal in DEFAULT_STATS do
    playerData[userId][stat] = saved[stat] or defaultVal
  end
end

local function saveStats(player: Player)
  local userId = player.UserId
  if not playerData[userId] then return end
  pcall(function()
    statsStore:SetAsync("stats_" .. userId, playerData[userId])
  end)
end

local function setupLeaderstats(player: Player)
  -- Remove existing leaderstats if present (economy system may have added them)
  local existing = player:FindFirstChild("leaderstats")
  if existing then existing:Destroy() end

  local leaderstats = Instance.new("Folder")
  leaderstats.Name = "leaderstats"
  leaderstats.Parent = player

  for _, stat in ipairs({${stats.map((s) => `"${s.name}"`).join(', ')}}) do
    local val = Instance.new("IntValue")
    val.Name = stat
    val.Value = playerData[player.UserId][stat] or DEFAULT_STATS[stat] or 0
    val.Parent = leaderstats
  end
end

${xpStat ? `-- Level-up handler (triggered when XP changes)
local function checkLevelUp(player: Player)
  local userId = player.UserId
  local data = playerData[userId]
  if not data then return end

  local currentXP = data["${xpStat.name}"] or 0
  local currentLevel = data["Level"] or 1
  if currentLevel >= MAX_LEVEL then return end

  while currentLevel < MAX_LEVEL and currentXP >= xpForLevel(currentLevel) do
    currentXP -= xpForLevel(currentLevel)
    currentLevel += 1
    data["${xpStat.name}"] = currentXP
    data["Level"] = currentLevel
    -- Notify client
    local levelUpEvent = game:GetService("ReplicatedStorage"):FindFirstChild("LevelUp")
    if not levelUpEvent then
      levelUpEvent = Instance.new("RemoteEvent")
      levelUpEvent.Name = "LevelUp"
      levelUpEvent.Parent = game:GetService("ReplicatedStorage")
    end
    levelUpEvent:FireClient(player, currentLevel)
    print("[Progression] " .. player.Name .. " reached Level " .. currentLevel)
  end

  -- Sync leaderstat
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local xpStat = ls:FindFirstChild("${xpStat.name}")
    if xpStat then xpStat.Value = data["${xpStat.name}"] or 0 end
    local levelStat = ls:FindFirstChild("Level")
    if levelStat then levelStat.Value = currentLevel end
  end
end` : ''}

-- BindableFunction API for other server scripts to update stats
local statsAPI = Instance.new("BindableFunction")
statsAPI.Name = "StatsAPI"
statsAPI.Parent = game:GetService("ServerStorage")

statsAPI.OnInvoke = function(action: string, player: Player, statName: string, amount: number): number
  local userId = player.UserId
  if not playerData[userId] then return 0 end

  if action == "get" then
    return playerData[userId][statName] or 0
  elseif action == "set" then
    playerData[userId][statName] = amount
  elseif action == "add" then
    playerData[userId][statName] = (playerData[userId][statName] or 0) + amount
    ${xpStat ? `if statName == "${xpStat.name}" then checkLevelUp(player) end` : ''}
  end

  -- Sync to leaderstats
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local stat = ls:FindFirstChild(statName)
    if stat then stat.Value = playerData[userId][statName] or 0 end
  end

  return playerData[userId][statName] or 0
end

Players.PlayerAdded:Connect(function(player)
  loadStats(player)
  setupLeaderstats(player)
end)

Players.PlayerRemoving:Connect(function(player)
  saveStats(player)
  playerData[player.UserId] = nil
end)

print("[Progression] Leaderboard system initialized — ${stats.map((s) => s.name).join(', ')}")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. BASIC CLICK COMBAT
// ─────────────────────────────────────────────────────────────────────────────

export interface CombatParams {
  clickDamage: number
  attackRange: number
  attackCooldown: number
  enemyTag?: string
}

export function basicCombat(params: CombatParams): string {
  const damage = Math.max(1, Math.floor(params.clickDamage))
  const range = Math.max(5, params.attackRange)
  const cooldown = Math.max(0.1, params.attackCooldown)
  const enemyTag = safe(params.enemyTag ?? 'Enemy')

  return `-- Basic Click Combat System (LocalScript → StarterPlayerScripts)
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")

local player = Players.LocalPlayer
local mouse = player:GetMouse()
local camera = workspace.CurrentCamera

local CLICK_DAMAGE = ${damage}
local ATTACK_RANGE = ${range}
local ATTACK_COOLDOWN = ${cooldown}
local ENEMY_TAG = "${enemyTag}"

local lastAttack = 0
local attackRemote: RemoteEvent

-- Wait for combat remote to be created by server
local RS = game:GetService("ReplicatedStorage")
local combatRemote = RS:WaitForChild("CombatAttack", 10) :: RemoteEvent?
if not combatRemote then
  warn("[Combat] CombatAttack RemoteEvent not found in ReplicatedStorage")
  return
end

-- Visual feedback: swing animation
local function playSwingEffect(hitPosition: Vector3)
  local effect = Instance.new("Part")
  effect.Anchored = true
  effect.CanCollide = false
  effect.CastShadow = false
  effect.Size = Vector3.new(0.5, 0.5, 0.5)
  effect.Shape = Enum.PartType.Ball
  effect.Material = Enum.Material.Neon
  effect.Color = Color3.fromRGB(255, 80, 80)
  effect.Position = hitPosition
  effect.Parent = workspace
  game:GetService("Debris"):AddItem(effect, 0.15)
end

mouse.Button1Down:Connect(function()
  local now = tick()
  if now - lastAttack < ATTACK_COOLDOWN then return end

  local char = player.Character
  if not char then return end
  local hrp = char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if not hrp then return end

  -- Raycast from camera through mouse
  local unitRay = camera:ScreenPointToRay(mouse.X, mouse.Y)
  local rayParams = RaycastParams.new()
  rayParams.FilterDescendantsInstances = {char}
  rayParams.FilterType = Enum.RaycastFilterType.Exclude

  local result = workspace:Raycast(unitRay.Origin, unitRay.Direction * ATTACK_RANGE, rayParams)
  if not result then return end

  local hitPart = result.Instance
  if not hitPart then return end

  -- Check if hit part belongs to an enemy model
  local model = hitPart:FindFirstAncestorOfClass("Model")
  if not model then return end

  local humanoid = model:FindFirstChildOfClass("Humanoid")
  if not humanoid then return end

  -- Validate range (server will also validate — this is just client feedback)
  if (hrp.Position - result.Position).Magnitude > ATTACK_RANGE then return end

  lastAttack = now
  playSwingEffect(result.Position)
  combatRemote:FireServer(model, CLICK_DAMAGE)
end)

-- Server combat handler (place in ServerScriptService)
-- Note: This section below should be in a SEPARATE ServerScript
--[[
local combatRemote = Instance.new("RemoteEvent")
combatRemote.Name = "CombatAttack"
combatRemote.Parent = game:GetService("ReplicatedStorage")

local attackCooldowns: {[number]: number} = {}

combatRemote.OnServerEvent:Connect(function(player: Player, targetModel: Model, damage: number)
  -- Server-side validation
  local userId = player.UserId
  local now = tick()
  if now - (attackCooldowns[userId] or 0) < ${cooldown * 0.9} then return end
  attackCooldowns[userId] = now

  -- Validate target is a real enemy with humanoid
  local humanoid = targetModel and targetModel:FindFirstChildOfClass("Humanoid")
  if not humanoid or humanoid.Health <= 0 then return end

  -- Validate range
  local char = player.Character
  local hrp = char and char:FindFirstChild("HumanoidRootPart")
  local targetHrp = targetModel:FindFirstChild("HumanoidRootPart")
  if not hrp or not targetHrp then return end
  if (hrp.Position - targetHrp.Position).Magnitude > ${range + 5} then return end

  -- Apply damage (always between 1 and 2x declared damage to prevent exploit)
  local safeDamage = math.clamp(damage, 1, ${damage * 2})
  humanoid:TakeDamage(safeDamage)
end)
--]]

print("[Combat] Click combat initialized — ${damage} dmg, ${range} studs range, ${cooldown}s cooldown")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. INVENTORY SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface InventoryParams {
  maxSlots: number
  categories: string[]
  stackable?: boolean
}

export function inventorySystem(params: InventoryParams): string {
  const maxSlots = Math.max(1, Math.min(100, params.maxSlots))
  const categories = params.categories.map(safe)

  return `-- Inventory System (ServerScript → ServerScriptService)
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local inventoryStore = DataStoreService:GetDataStore("Inventory_v1")
local MAX_SLOTS = ${maxSlots}
local CATEGORIES = {"${categories.join('", "')}"}
local STACKABLE = ${params.stackable ? 'true' : 'false'}

export type InventoryItem = {
  id: string,
  name: string,
  category: string,
  quantity: number,
  metadata: {[string]: any}?,
}

local inventories: {[number]: {[number]: InventoryItem?}} = {}

local function loadInventory(player: Player)
  local userId = player.UserId
  local success, data = pcall(function()
    return inventoryStore:GetAsync("inv_" .. userId)
  end)
  inventories[userId] = (success and type(data) == "table" and data) or {}
end

local function saveInventory(player: Player)
  local userId = player.UserId
  if not inventories[userId] then return end
  pcall(function()
    inventoryStore:SetAsync("inv_" .. userId, inventories[userId])
  end)
end

local function getInventory(player: Player): {[number]: InventoryItem?}
  return inventories[player.UserId] or {}
end

local function findItem(player: Player, itemName: string): (number?, InventoryItem?)
  local inv = inventories[player.UserId]
  if not inv then return nil, nil end
  for slot, item in ipairs(inv) do
    if item and item.name == itemName then return slot, item end
  end
  return nil, nil
end

local function findEmptySlot(player: Player): number?
  local inv = inventories[player.UserId]
  if not inv then return nil end
  for i = 1, MAX_SLOTS do
    if not inv[i] then return i end
  end
  return nil
end

local function addItem(player: Player, item: InventoryItem): (boolean, string)
  local userId = player.UserId
  if not inventories[userId] then return false, "Player not found" end

  if STACKABLE then
    local slot, existing = findItem(player, item.name)
    if existing then
      existing.quantity = existing.quantity + item.quantity
      return true, "Stacked"
    end
  end

  local slot = findEmptySlot(player)
  if not slot then return false, "Inventory full" end

  inventories[userId][slot] = item
  return true, "Added"
end

local function removeItem(player: Player, itemName: string, quantity: number): boolean
  local slot, item = findItem(player, itemName)
  if not slot or not item then return false end
  if item.quantity < quantity then return false end
  item.quantity -= quantity
  if item.quantity <= 0 then
    inventories[player.UserId][slot] = nil
  end
  return true
end

-- RemoteFunction API for client inventory UI
local invRemote = Instance.new("RemoteFunction")
invRemote.Name = "InventoryAction"
invRemote.Parent = game:GetService("ReplicatedStorage")

invRemote.OnServerInvoke = function(player: Player, action: string, data: any): any
  if action == "get" then
    return getInventory(player)
  elseif action == "use" and type(data) == "table" then
    return removeItem(player, data.name, data.quantity or 1)
  end
  return false
end

-- Server API via BindableFunction
local invAPI = Instance.new("BindableFunction")
invAPI.Name = "InventoryAPI"
invAPI.Parent = game:GetService("ServerStorage")

invAPI.OnInvoke = function(action: string, player: Player, itemData: InventoryItem?, itemName: string?, qty: number?)
  if action == "add" and itemData then
    return addItem(player, itemData)
  elseif action == "remove" and itemName then
    return removeItem(player, itemName, qty or 1)
  elseif action == "has" and itemName then
    return findItem(player, itemName) ~= nil
  end
end

Players.PlayerAdded:Connect(function(p) loadInventory(p) end)
Players.PlayerRemoving:Connect(function(p) saveInventory(p); inventories[p.UserId] = nil end)

print("[Inventory] System initialized — " .. MAX_SLOTS .. " slots, categories: ${categories.join(', ')}")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. DAY / NIGHT CYCLE
// ─────────────────────────────────────────────────────────────────────────────

export interface DayNightCycleParams {
  cycleDurationMinutes: number
  sunriseHour?: number
  sunsetHour?: number
}

export function dayNightCycle(params: DayNightCycleParams): string {
  const cycleSecs = Math.max(60, params.cycleDurationMinutes * 60)
  const sunriseHour = params.sunriseHour ?? 6
  const sunsetHour = params.sunsetHour ?? 20

  return `-- Day/Night Cycle (Script → ServerScriptService)
local Lighting = game:GetService("Lighting")
local RunService = game:GetService("RunService")

local CYCLE_SECONDS = ${cycleSecs}  -- Real-world seconds for full 24h cycle
local SUNRISE_HOUR = ${sunriseHour}
local SUNSET_HOUR = ${sunsetHour}

-- Initial lighting setup
Lighting.Ambient = Color3.fromRGB(80, 80, 100)
Lighting.OutdoorAmbient = Color3.fromRGB(120, 120, 140)
Lighting.Brightness = 3
Lighting.ShadowSoftness = 0.2
Lighting.FogEnd = 2000
Lighting.FogColor = Color3.fromRGB(180, 190, 200)

-- Atmosphere
local atmosphere = Lighting:FindFirstChildOfClass("Atmosphere") or Instance.new("Atmosphere")
atmosphere.Density = 0.35
atmosphere.Offset = 0.06
atmosphere.Color = Color3.fromRGB(199, 170, 140)
atmosphere.Decay = Color3.fromRGB(106, 127, 153)
atmosphere.Glare = 0.06
atmosphere.Haze = 2.5
atmosphere.Parent = Lighting

-- Color-correct the sky colors by time of day
local function setTimeColors(hour: number)
  local isDay = hour >= SUNRISE_HOUR and hour < SUNSET_HOUR
  local isSunrise = hour >= SUNRISE_HOUR and hour < (SUNRISE_HOUR + 2)
  local isSunset = hour >= (SUNSET_HOUR - 2) and hour < SUNSET_HOUR

  if isSunrise then
    atmosphere.Color = Color3.fromRGB(255, 160, 90)
    Lighting.Ambient = Color3.fromRGB(100, 80, 70)
    Lighting.Brightness = 1.5
  elseif isSunset then
    atmosphere.Color = Color3.fromRGB(255, 120, 60)
    Lighting.Ambient = Color3.fromRGB(100, 70, 60)
    Lighting.Brightness = 1.2
  elseif isDay then
    atmosphere.Color = Color3.fromRGB(199, 170, 140)
    Lighting.Ambient = Color3.fromRGB(80, 80, 100)
    Lighting.Brightness = 3
  else
    -- Night
    atmosphere.Color = Color3.fromRGB(10, 10, 30)
    Lighting.Ambient = Color3.fromRGB(20, 20, 40)
    Lighting.Brightness = 0.3
  end
end

-- Advance time every frame
RunService.Heartbeat:Connect(function(dt: number)
  local currentHour = Lighting.ClockTime
  local hoursPerSecond = 24 / CYCLE_SECONDS
  local newHour = (currentHour + dt * hoursPerSecond) % 24
  Lighting.ClockTime = newHour
  setTimeColors(newHour)
end)

-- Sync time event for clients that need it
local timeEvent = Instance.new("RemoteEvent")
timeEvent.Name = "TimeSync"
timeEvent.Parent = game:GetService("ReplicatedStorage")

-- Broadcast time every 5 seconds
local lastSync = 0
RunService.Heartbeat:Connect(function()
  if tick() - lastSync >= 5 then
    lastSync = tick()
    timeEvent:FireAllClients(Lighting.ClockTime)
  end
end)

print("[Day/Night] Cycle active — ${params.cycleDurationMinutes}min real-time cycle")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 8. SPAWN SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface SpawnSystemParams {
  spawnPoints: number
  respawnDelay: number
  teamBased?: boolean
}

export function spawnSystem(params: SpawnSystemParams): string {
  const points = Math.max(1, Math.min(20, params.spawnPoints))
  const delay = Math.max(0, params.respawnDelay)

  return `-- Spawn System (Script → ServerScriptService)
local Players = game:GetService("Players")
local Teams = game:GetService("Teams")

local RESPAWN_DELAY = ${delay}
local TEAM_BASED = ${params.teamBased ? 'true' : 'false'}

-- Find all SpawnLocation parts tagged as game spawns
local function getSpawnPoints(): {SpawnLocation}
  local spawns: {SpawnLocation} = {}
  for _, obj in ipairs(workspace:GetDescendants()) do
    if obj:IsA("SpawnLocation") then
      table.insert(spawns, obj)
    end
  end
  return spawns
end

-- Pick a random spawn (or team-specific spawn if team-based)
local function getSpawnForPlayer(player: Player): SpawnLocation?
  local spawns = getSpawnPoints()
  if #spawns == 0 then return nil end

  if TEAM_BASED and player.Team then
    local teamSpawns: {SpawnLocation} = {}
    for _, spawn in ipairs(spawns) do
      if spawn.TeamColor == player.TeamColor then
        table.insert(teamSpawns, spawn)
      end
    end
    if #teamSpawns > 0 then
      return teamSpawns[math.random(#teamSpawns)]
    end
  end

  return spawns[math.random(#spawns)]
end

-- Override default Roblox respawn to use custom spawn logic
local function handleCharacterAdded(player: Player, character: Model)
  local hrp = character:WaitForChild("HumanoidRootPart", 5) :: BasePart?
  if not hrp then return end

  local spawn = getSpawnForPlayer(player)
  if spawn then
    hrp.CFrame = spawn.CFrame * CFrame.new(0, 3, 0)
  end
end

-- Custom respawn with delay
local function handleCharacterRemoving(player: Player)
  if RESPAWN_DELAY > 0 then
    task.delay(RESPAWN_DELAY, function()
      if player and player.Parent then
        player:LoadCharacter()
      end
    end)
  end
end

-- Disable Roblox auto-respawn if we're handling it manually
if RESPAWN_DELAY > 0 then
  game.Players.RespawnTime = RESPAWN_DELAY
end

Players.PlayerAdded:Connect(function(player: Player)
  player.CharacterAdded:Connect(function(character: Model)
    handleCharacterAdded(player, character)
  end)
  if RESPAWN_DELAY > 0 then
    player.CharacterRemoving:Connect(function()
      handleCharacterRemoving(player)
    end)
  end
end)

print("[Spawn] Spawn system ready — ${points} spawn points, ${delay}s respawn delay")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 9. OBBY CHECKPOINT SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface ObbyCheckpointParams {
  totalCheckpoints: number
  completionReward?: { currency: string; amount: number }
}

export function obbyCheckpoints(params: ObbyCheckpointParams): string {
  const total = Math.max(2, params.totalCheckpoints)
  const reward = params.completionReward

  return `-- Obby Checkpoint System (Script → ServerScriptService)
-- Checkpoints must be Parts named "Checkpoint1", "Checkpoint2", etc. in workspace.Checkpoints
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local checkpointStore = DataStoreService:GetDataStore("ObbyCPs_v1")
local TOTAL_CHECKPOINTS = ${total}
${reward ? `local COMPLETION_CURRENCY = "${safe(reward.currency)}"
local COMPLETION_REWARD = ${Math.max(1, reward.amount)}` : ''}

-- In-memory checkpoint progress
local progress: {[number]: number} = {}  -- userId → highest checkpoint reached

local function loadProgress(player: Player)
  local success, data = pcall(function()
    return checkpointStore:GetAsync("cp_" .. player.UserId)
  end)
  progress[player.UserId] = (success and type(data) == "number") and data or 0
end

local function saveProgress(player: Player)
  local userId = player.UserId
  if progress[userId] == nil then return end
  pcall(function()
    checkpointStore:SetAsync("cp_" .. userId, progress[userId])
  end)
end

local function spawnAtCheckpoint(player: Player)
  local cp = progress[player.UserId] or 0
  if cp <= 0 then return end  -- spawn at default start

  local folder = workspace:FindFirstChild("Checkpoints")
  if not folder then return end
  local cpPart = folder:FindFirstChild("Checkpoint" .. cp) :: BasePart?
  if not cpPart then return end

  local char = player.Character
  local hrp = char and char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if hrp then
    hrp.CFrame = cpPart.CFrame * CFrame.new(0, 4, 0)
  end
end

-- Setup touch detectors for all checkpoints
local function setupCheckpoints()
  local folder = workspace:FindFirstChild("Checkpoints")
  if not folder then
    warn("[Obby] No 'Checkpoints' folder found in workspace")
    return
  end

  for i = 1, TOTAL_CHECKPOINTS do
    local cpPart = folder:FindFirstChild("Checkpoint" .. i) :: BasePart?
    if cpPart then
      local detector = Instance.new("TouchTransmitter")
      detector.Parent = cpPart

      cpPart.Touched:Connect(function(hit: BasePart)
        local char = hit:FindFirstAncestorOfClass("Model")
        if not char then return end
        local player = Players:GetPlayerFromCharacter(char)
        if not player then return end

        local current = progress[player.UserId] or 0
        if i <= current then return end  -- already reached this or later

        progress[player.UserId] = i
        saveProgress(player)

        -- Notify client
        local cpEvent = game:GetService("ReplicatedStorage"):FindFirstChild("CheckpointReached")
        if not cpEvent then
          cpEvent = Instance.new("RemoteEvent")
          cpEvent.Name = "CheckpointReached"
          cpEvent.Parent = game:GetService("ReplicatedStorage")
        end
        cpEvent:FireClient(player, i, TOTAL_CHECKPOINTS)

        print("[Obby] " .. player.Name .. " reached checkpoint " .. i)

        ${reward ? `-- Completion reward
        if i == TOTAL_CHECKPOINTS then
          local economyAPI = game:GetService("ServerStorage"):FindFirstChild("EconomyAPI")
          if economyAPI then
            economyAPI:Invoke("add", player, COMPLETION_CURRENCY, COMPLETION_REWARD)
            print("[Obby] " .. player.Name .. " completed obby! Rewarded " .. COMPLETION_REWARD .. " " .. COMPLETION_CURRENCY)
          end
        end` : ''}
      end)
    end
  end
end

Players.PlayerAdded:Connect(function(player: Player)
  loadProgress(player)
  player.CharacterAdded:Connect(function()
    task.wait(0.1)  -- brief delay so character loads
    spawnAtCheckpoint(player)
  end)
end)

Players.PlayerRemoving:Connect(function(player: Player)
  saveProgress(player)
  progress[player.UserId] = nil
end)

task.defer(setupCheckpoints)

print("[Obby] Checkpoint system initialized — ${total} checkpoints")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 10. PET FOLLOWING SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface PetFollowParams {
  petName: string
  followSpeed: number
  followDistance: number
  petModelId?: string
  bonusMultiplier?: number
}

export function petFollowSystem(params: PetFollowParams): string {
  const petName = safe(params.petName)
  const speed = Math.max(5, params.followSpeed)
  const distance = Math.max(3, params.followDistance)
  const modelId = params.petModelId ?? '0'
  const bonus = Math.max(1, params.bonusMultiplier ?? 1)

  return `-- Pet Following System (LocalScript → StarterPlayerScripts)
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer
local PET_NAME = "${petName}"
local FOLLOW_SPEED = ${speed}
local FOLLOW_DISTANCE = ${distance}
local BONUS_MULTIPLIER = ${bonus}

-- Pet model (spawned locally for this player's view)
local petModel: Model? = nil
local petRoot: BasePart? = nil

local function createPetModel(): Model?
  ${modelId !== '0' ? `-- Load from Roblox asset catalog
  local success, model = pcall(function()
    return game:GetService("InsertService"):LoadAsset(${modelId})
  end)
  if success and model then
    local petInst = model:FindFirstChildOfClass("Model") or model
    model:Destroy()  -- cleanup container
    return petInst :: Model
  end` : ''}

  -- Fallback: simple geometric pet
  local m = Instance.new("Model")
  m.Name = PET_NAME

  local body = Instance.new("Part")
  body.Name = "HumanoidRootPart"
  body.Size = Vector3.new(1.5, 1.5, 1.5)
  body.Shape = Enum.PartType.Ball
  body.Material = Enum.Material.SmoothPlastic
  body.Color = Color3.fromRGB(255, 215, 0)
  body.CastShadow = false
  body.Anchored = true
  body.CanCollide = false
  body.Parent = m

  -- Eyes
  local leftEye = Instance.new("Part")
  leftEye.Size = Vector3.new(0.3, 0.3, 0.1)
  leftEye.Material = Enum.Material.Neon
  leftEye.Color = Color3.fromRGB(0, 0, 0)
  leftEye.CanCollide = false
  leftEye.Anchored = true
  leftEye.CFrame = body.CFrame * CFrame.new(-0.4, 0.3, -0.7)
  leftEye.Parent = m

  local rightEye = leftEye:Clone()
  rightEye.CFrame = body.CFrame * CFrame.new(0.4, 0.3, -0.7)
  rightEye.Parent = m

  -- Billboard name tag
  local billboard = Instance.new("BillboardGui")
  billboard.Size = UDim2.new(0, 120, 0, 30)
  billboard.StudsOffset = Vector3.new(0, 2, 0)
  billboard.Parent = body

  local nameLabel = Instance.new("TextLabel")
  nameLabel.Size = UDim2.fromScale(1, 1)
  nameLabel.BackgroundTransparency = 1
  nameLabel.TextColor3 = Color3.fromRGB(255, 215, 0)
  nameLabel.Font = Enum.Font.GothamBold
  nameLabel.TextSize = 13
  nameLabel.Text = PET_NAME
  nameLabel.Parent = billboard

  m.PrimaryPart = body
  return m
end

local function spawnPet()
  if petModel then petModel:Destroy() end

  local model = createPetModel()
  if not model then return end

  local char = player.Character
  if not char then return end
  local hrp = char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if not hrp then return end

  model:SetPrimaryPartCFrame(hrp.CFrame * CFrame.new(FOLLOW_DISTANCE, 0, FOLLOW_DISTANCE))
  model.Parent = workspace

  petModel = model
  petRoot = model:FindFirstChild("HumanoidRootPart") :: BasePart?
end

-- Smooth follow logic (runs on client render step)
local LERP_FACTOR = math.min(1, FOLLOW_SPEED * 0.016)  -- per-frame lerp based on 60fps

RunService.RenderStepped:Connect(function(dt: number)
  if not petRoot or not petRoot.Parent then
    spawnPet()
    return
  end

  local char = player.Character
  if not char then return end
  local hrp = char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if not hrp then return end

  -- Target position: offset from player
  local offset = Vector3.new(FOLLOW_DISTANCE * math.sin(tick()), 0.5, FOLLOW_DISTANCE * math.cos(tick() * 0.7))
  local targetPos = hrp.Position + offset
  local currentPos = petRoot.Position

  -- Only move if far enough away
  if (currentPos - targetPos).Magnitude > 0.5 then
    local newPos = currentPos:Lerp(targetPos, math.min(1, LERP_FACTOR * dt * 60))
    petRoot.CFrame = CFrame.new(newPos) * CFrame.Angles(0, math.atan2(targetPos.X - currentPos.X, targetPos.Z - currentPos.Z), 0)
  end

  -- Bobbing animation
  petRoot.CFrame = petRoot.CFrame * CFrame.new(0, math.sin(tick() * 3) * 0.15, 0)
end)

-- Respawn pet on character respawn
player.CharacterAdded:Connect(function()
  task.wait(1)
  spawnPet()
end)

-- Initial spawn
if player.Character then
  task.wait(0.5)
  spawnPet()
end

${bonus > 1 ? `-- Bonus multiplier effect (fires to server for economy sync)
local bonusEvent = game:GetService("ReplicatedStorage"):WaitForChild("PetBonus", 5) :: RemoteEvent?
if bonusEvent then
  bonusEvent:FireServer(PET_NAME, BONUS_MULTIPLIER)
end` : ''}

print("[Pet] ${petName} following system active — x${bonus} bonus multiplier")`
}

// ─────────────────────────────────────────────────────────────────────────────
// Template registry — maps task template names to generator functions
// ─────────────────────────────────────────────────────────────────────────────

export type TemplateName =
  | 'economy_system'
  | 'tycoon_dropper'
  | 'npc_dialog'
  | 'leaderboard'
  | 'basic_combat'
  | 'inventory'
  | 'day_night_cycle'
  | 'spawn_system'
  | 'obby_checkpoints'
  | 'pet_follow'

export interface TemplateRegistry {
  economy_system: (p: EconomySystemParams) => string
  tycoon_dropper: (p: TycoonDropperParams) => string
  npc_dialog: (p: NpcDialogParams) => string
  leaderboard: (p: LeaderboardParams) => string
  basic_combat: (p: CombatParams) => string
  inventory: (p: InventoryParams) => string
  day_night_cycle: (p: DayNightCycleParams) => string
  spawn_system: (p: SpawnSystemParams) => string
  obby_checkpoints: (p: ObbyCheckpointParams) => string
  pet_follow: (p: PetFollowParams) => string
}

export const TEMPLATE_REGISTRY: TemplateRegistry = {
  economy_system: economySystem,
  tycoon_dropper: tycoonDropper,
  npc_dialog: npcDialogSystem,
  leaderboard: leaderboardProgression,
  basic_combat: basicCombat,
  inventory: inventorySystem,
  day_night_cycle: dayNightCycle,
  spawn_system: spawnSystem,
  obby_checkpoints: obbyCheckpoints,
  pet_follow: petFollowSystem,
}
