/**
 * Luau Template Library — pre-built, parameterized Roblox game system scripts.
 *
 * Each exported function returns a complete, runnable Luau code string.
 * Templates follow all codebase conventions:
 *  - ChangeHistoryService wrapping for undo support
 *  - pcall error handling
 *  - Server-authoritative logic (economy, combat)
 *  - Sanitised names (no arbitrary string injection)
 *  - Anchored static parts, correct service paths
 *
 * The AI build executor fills in `params` based on the user's game description.
 */

// ── Sanitisation helper ───────────────────────────────────────────────────────

function safe(val: string): string {
  return String(val).replace(/[^a-zA-Z0-9_ ]/g, '').slice(0, 64)
}

function safeLuauString(val: string): string {
  return String(val).replace(/\\/g, '\\\\').replace(/"/g, '\\"').slice(0, 200)
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. ECONOMY SYSTEM — currency, wallet, leaderstat, server-authoritative shop
// ─────────────────────────────────────────────────────────────────────────────

export interface EconomySystemParams {
  currencies: string[]
  startingCash: number
  shopItems?: Array<{ name: string; price: number }>
}

export function economySystem(params: EconomySystemParams): string {
  const currencies = params.currencies.map(safe)
  const startingCash = Math.max(0, Math.floor(params.startingCash))
  const primaryCurrency = currencies[0] ?? 'Cash'

  const shopItemEntries = (params.shopItems ?? [])
    .map((item) => `  ["${safeLuauString(item.name)}"] = ${Math.max(1, item.price)},`)
    .join('\n')

  return `-- Economy System (Server Script → ServerScriptService)
-- Generated by ForjeGames Build Engine
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local economyStore = DataStoreService:GetDataStore("EconomyStore_v1")

local STARTING_BALANCES: {[string]: number} = {
${currencies.map((c, i) => `  ["${c}"] = ${i === 0 ? startingCash : 0},`).join('\n')}
}

local SHOP_PRICES: {[string]: number} = {
${shopItemEntries || '  -- No shop items defined'}
}

-- Wallet: in-memory balances per player
local wallets: {[number]: {[string]: number}} = {}

local function loadWallet(player: Player)
  local userId = player.UserId
  local success, data = pcall(function()
    return economyStore:GetAsync("player_" .. userId)
  end)
  local saved: {[string]: number} = (success and type(data) == "table" and data) or {}

  wallets[userId] = {}
  for currency, startAmount in STARTING_BALANCES do
    wallets[userId][currency] = saved[currency] or startAmount
  end
end

local function saveWallet(player: Player)
  local userId = player.UserId
  if not wallets[userId] then return end
  pcall(function()
    economyStore:SetAsync("player_" .. userId, wallets[userId])
  end)
end

local function getBalance(player: Player, currency: string): number
  local userId = player.UserId
  if not wallets[userId] then return 0 end
  return wallets[userId][currency] or 0
end

local function addCurrency(player: Player, currency: string, amount: number): boolean
  if amount <= 0 then return false end
  local userId = player.UserId
  if not wallets[userId] then return false end
  wallets[userId][currency] = (wallets[userId][currency] or 0) + amount
  -- Update leaderstat
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local stat = ls:FindFirstChild(currency)
    if stat then stat.Value = wallets[userId][currency] end
  end
  return true
end

local function spendCurrency(player: Player, currency: string, amount: number): boolean
  if amount <= 0 then return false end
  local userId = player.UserId
  if not wallets[userId] then return false end
  local current = wallets[userId][currency] or 0
  if current < amount then return false end
  wallets[userId][currency] = current - amount
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local stat = ls:FindFirstChild(currency)
    if stat then stat.Value = wallets[userId][currency] end
  end
  return true
end

local function setupLeaderstats(player: Player)
  local leaderstats = Instance.new("Folder")
  leaderstats.Name = "leaderstats"
  leaderstats.Parent = player

  for _, currency in ipairs({"${currencies.join('", "')}"}) do
    local stat = Instance.new("IntValue")
    stat.Name = currency
    stat.Value = wallets[player.UserId][currency] or 0
    stat.Parent = leaderstats
  end
end

-- Shop purchase handler (RemoteFunction — server validates all purchases)
local purchaseRemote = Instance.new("RemoteFunction")
purchaseRemote.Name = "PurchaseItem"
purchaseRemote.Parent = game:GetService("ReplicatedStorage")

purchaseRemote.OnServerInvoke = function(player: Player, itemName: string): (boolean, string)
  if type(itemName) ~= "string" then return false, "Invalid item" end
  local price = SHOP_PRICES[itemName]
  if not price then return false, "Item not found" end
  if not spendCurrency(player, "${primaryCurrency}", price) then
    return false, "Insufficient ${primaryCurrency}"
  end
  return true, "Purchase successful"
end

-- Player lifecycle
Players.PlayerAdded:Connect(function(player: Player)
  loadWallet(player)
  setupLeaderstats(player)
end)

Players.PlayerRemoving:Connect(function(player: Player)
  saveWallet(player)
  wallets[player.UserId] = nil
end)

-- Public API (module-style exposure via BindableFunction for other scripts)
local economyAPI = Instance.new("BindableFunction")
economyAPI.Name = "EconomyAPI"
economyAPI.Parent = game:GetService("ServerStorage")

economyAPI.OnInvoke = function(action: string, player: Player, currency: string, amount: number)
  if action == "get" then return getBalance(player, currency)
  elseif action == "add" then return addCurrency(player, currency, amount)
  elseif action == "spend" then return spendCurrency(player, currency, amount)
  end
end

print("[Economy] System initialized with currencies: ${currencies.join(', ')}")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. TYCOON DROPPER / COLLECTOR / UPGRADER
// ─────────────────────────────────────────────────────────────────────────────

export interface TycoonDropperParams {
  resourceName: string
  value: number
  interval: number
  currency?: string
}

export function tycoonDropper(params: TycoonDropperParams): string {
  const resource = safe(params.resourceName)
  const value = Math.max(1, Math.floor(params.value))
  const interval = Math.max(0.5, params.interval)
  const currency = safe(params.currency ?? 'Cash')

  return `-- Tycoon Dropper System (Script inside dropper Model in workspace)
-- Resource: ${resource} | Value: ${value} ${currency} | Interval: ${interval}s
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

local dropper = script.Parent -- Model containing the dropper part
local dropPart = dropper:FindFirstChild("DropPart") or dropper.PrimaryPart
local collector = dropper.Parent:FindFirstChild("Collector") -- sibling Collector model

assert(dropPart, "[Dropper] No DropPart found in " .. dropper.Name)

local RESOURCE_NAME = "${resource}"
local RESOURCE_VALUE = ${value}
local DROP_INTERVAL = ${interval}
local CURRENCY = "${currency}"

-- Find which player owns this tycoon
local function getTycoonOwner(): Player?
  local tycoon = dropper:FindFirstAncestorOfClass("Model")
  if not tycoon then return nil end
  local ownerValue = tycoon:FindFirstChild("Owner")
  if not ownerValue or ownerValue.ClassName ~= "ObjectValue" then return nil end
  return ownerValue.Value :: Player?
end

local function dropResource()
  local owner = getTycoonOwner()
  if not owner then return end

  -- Create the resource ball
  local ball = Instance.new("Part")
  ball.Name = RESOURCE_NAME
  ball.Size = Vector3.new(1, 1, 1)
  ball.Shape = Enum.PartType.Ball
  ball.Material = Enum.Material.SmoothPlastic
  ball.Color = Color3.fromRGB(255, 215, 0) -- gold
  ball.CastShadow = false
  ball.Position = dropPart.Position + Vector3.new(0, 2, 0)
  ball.Parent = workspace

  -- Add value tag for collection
  local val = Instance.new("IntValue")
  val.Name = "ResourceValue"
  val.Value = RESOURCE_VALUE
  val.Parent = ball

  local ownerTag = Instance.new("StringValue")
  ownerTag.Name = "OwnerUserId"
  ownerTag.Value = tostring(owner.UserId)
  ownerTag.Parent = ball

  -- Auto-destroy after 30 seconds if not collected
  game:GetService("Debris"):AddItem(ball, 30)
end

-- Collector touch detection (server-side, authoritative)
if collector then
  local collectPart = collector:FindFirstChildOfClass("Part") or collector.PrimaryPart
  if collectPart then
    collectPart.Touched:Connect(function(hit: BasePart)
      local ball = hit
      if ball.Name ~= RESOURCE_NAME then return end
      local ownerTag = ball:FindFirstChild("OwnerUserId")
      if not ownerTag then return end

      local owner = getTycoonOwner()
      if not owner or tostring(owner.UserId) ~= ownerTag.Value then return end

      local valueTag = ball:FindFirstChild("ResourceValue")
      local amount = valueTag and valueTag.Value or RESOURCE_VALUE

      ball:Destroy()

      -- Credit the player via EconomyAPI
      local economyAPI = game:GetService("ServerStorage"):FindFirstChild("EconomyAPI")
      if economyAPI then
        economyAPI:Invoke("add", owner, CURRENCY, amount)
      end
    end)
  end
end

-- Drop loop
local lastDrop = 0
RunService.Heartbeat:Connect(function()
  if tick() - lastDrop >= DROP_INTERVAL then
    lastDrop = tick()
    dropResource()
  end
end)

print("[Dropper] ${resource} dropper active — " .. DROP_INTERVAL .. "s interval, +" .. RESOURCE_VALUE .. " " .. CURRENCY)`
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. NPC DIALOG SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface NpcDialogParams {
  npcName: string
  dialogLines: string[]
  questName?: string
  questRewardCurrency?: string
  questRewardAmount?: number
}

export function npcDialogSystem(params: NpcDialogParams): string {
  const npcName = safe(params.npcName)
  const lines = params.dialogLines.map((l) => `  "${safeLuauString(l)}"`)
  const questName = params.questName ? safe(params.questName) : null
  const rewardCurrency = safe(params.questRewardCurrency ?? 'Cash')
  const rewardAmount = Math.max(0, Math.floor(params.questRewardAmount ?? 0))

  return `-- NPC Dialog System — Script inside NPC Model (workspace)
-- NPC: ${npcName} | Lines: ${params.dialogLines.length} | Quest: ${questName ?? 'None'}
local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")

local npc = script.Parent
local rootPart = npc:FindFirstChild("HumanoidRootPart") or npc.PrimaryPart
local PROXIMITY_RANGE = 12 -- studs

assert(rootPart, "[NPC Dialog] No HumanoidRootPart in " .. npc.Name)

local DIALOG_LINES: {string} = {
${lines.join(',\n')}
}

${questName ? `local QUEST_NAME = "${questName}"
local QUEST_REWARD_CURRENCY = "${rewardCurrency}"
local QUEST_REWARD_AMOUNT = ${rewardAmount}` : ''}

-- Billboard for proximity hint
local billboard = Instance.new("BillboardGui")
billboard.Name = "DialogHint"
billboard.Size = UDim2.new(0, 200, 0, 50)
billboard.StudsOffset = Vector3.new(0, 3, 0)
billboard.AlwaysOnTop = false
billboard.Enabled = false
billboard.Parent = rootPart

local hintLabel = Instance.new("TextLabel")
hintLabel.Size = UDim2.fromScale(1, 1)
hintLabel.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
hintLabel.BackgroundTransparency = 0.3
hintLabel.TextColor3 = Color3.fromRGB(255, 215, 0)
hintLabel.Font = Enum.Font.GothamBold
hintLabel.TextSize = 14
hintLabel.Text = "Press E to talk to ${npcName}"
hintLabel.Parent = billboard

local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 8)
UICorner.Parent = hintLabel

-- Track which players are in range
local playersInRange: {[number]: boolean} = {}
local dialogState: {[number]: number} = {}

local function showDialog(player: Player, lineIndex: number)
  local line = DIALOG_LINES[lineIndex]
  if not line then return end

  -- Fire to client via RemoteEvent (dialog display handled client-side)
  local dialogEvent = game:GetService("ReplicatedStorage"):FindFirstChild("ShowDialog")
  if not dialogEvent then
    dialogEvent = Instance.new("RemoteEvent")
    dialogEvent.Name = "ShowDialog"
    dialogEvent.Parent = game:GetService("ReplicatedStorage")
  end
  dialogEvent:FireClient(player, {
    npcName = "${npcName}",
    line = line,
    lineIndex = lineIndex,
    totalLines = #DIALOG_LINES,
    hasQuest = ${questName ? 'true' : 'false'}
  })
end

local function advanceDialog(player: Player)
  local userId = player.UserId
  local current = dialogState[userId] or 0
  current = current + 1

  if current > #DIALOG_LINES then
    -- Dialog complete
    dialogState[userId] = 0
    ${questName ? `-- Grant quest reward
    local economyAPI = game:GetService("ServerStorage"):FindFirstChild("EconomyAPI")
    if economyAPI then
      economyAPI:Invoke("add", player, QUEST_REWARD_CURRENCY, QUEST_REWARD_AMOUNT)
    end
    print("[NPC] Quest '${questName}' completed for " .. player.Name)` : ''}
    return
  end

  dialogState[userId] = current
  showDialog(player, current)
end

-- Proximity detection loop
local heartbeat = game:GetService("RunService").Heartbeat
heartbeat:Connect(function()
  if not rootPart then return end
  for _, player in ipairs(Players:GetPlayers()) do
    local char = player.Character
    if not char then continue end
    local hrp = char:FindFirstChild("HumanoidRootPart")
    if not hrp then continue end
    local dist = (hrp.Position - rootPart.Position).Magnitude
    local inRange = dist <= PROXIMITY_RANGE
    local wasInRange = playersInRange[player.UserId]

    if inRange ~= wasInRange then
      playersInRange[player.UserId] = inRange
      billboard.Enabled = inRange
    end
  end
end)

-- Talk input (E key) — handled via RemoteEvent from client
local talkEvent = game:GetService("ReplicatedStorage"):FindFirstChild("TalkToNPC")
if not talkEvent then
  talkEvent = Instance.new("RemoteEvent")
  talkEvent.Name = "TalkToNPC"
  talkEvent.Parent = game:GetService("ReplicatedStorage")
end

talkEvent.OnServerEvent:Connect(function(player: Player, targetNpcName: string)
  if targetNpcName ~= "${npcName}" then return end
  if not playersInRange[player.UserId] then return end
  advanceDialog(player)
end)

print("[NPC Dialog] ${npcName} initialized with " .. #DIALOG_LINES .. " dialog lines")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. LEADERBOARD / PROGRESSION SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface LeaderboardParams {
  stats: Array<{ name: string; startValue: number; isXP?: boolean }>
  xpToLevelCurve?: 'linear' | 'quadratic' | 'exponential'
  maxLevel?: number
}

export function leaderboardProgression(params: LeaderboardParams): string {
  const stats = params.stats.map((s) => ({ ...s, name: safe(s.name) }))
  const maxLevel = Math.max(10, params.maxLevel ?? 100)
  const curve = params.xpToLevelCurve ?? 'quadratic'
  const xpStat = stats.find((s) => s.isXP)

  const levelFormula =
    curve === 'linear'
      ? `return level * 100`
      : curve === 'exponential'
        ? `return math.floor(100 * (1.5 ^ (level - 1)))`
        : `return math.floor(100 * (level ^ 1.8))`

  return `-- Leaderboard & Progression System (ServerScript)
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local statsStore = DataStoreService:GetDataStore("PlayerStats_v1")
local MAX_LEVEL = ${maxLevel}

local DEFAULT_STATS: {[string]: number} = {
${stats.map((s) => `  ["${s.name}"] = ${s.startValue},`).join('\n')}
}

-- XP-to-level curve: ${curve}
local function xpForLevel(level: number): number
  ${levelFormula}
end

local playerData: {[number]: {[string]: number}} = {}

local function loadStats(player: Player)
  local userId = player.UserId
  local success, data = pcall(function()
    return statsStore:GetAsync("stats_" .. userId)
  end)
  local saved: {[string]: number} = (success and type(data) == "table" and data) or {}
  playerData[userId] = {}
  for stat, defaultVal in DEFAULT_STATS do
    playerData[userId][stat] = saved[stat] or defaultVal
  end
end

local function saveStats(player: Player)
  local userId = player.UserId
  if not playerData[userId] then return end
  pcall(function()
    statsStore:SetAsync("stats_" .. userId, playerData[userId])
  end)
end

local function setupLeaderstats(player: Player)
  -- Remove existing leaderstats if present (economy system may have added them)
  local existing = player:FindFirstChild("leaderstats")
  if existing then existing:Destroy() end

  local leaderstats = Instance.new("Folder")
  leaderstats.Name = "leaderstats"
  leaderstats.Parent = player

  for _, stat in ipairs({${stats.map((s) => `"${s.name}"`).join(', ')}}) do
    local val = Instance.new("IntValue")
    val.Name = stat
    val.Value = playerData[player.UserId][stat] or DEFAULT_STATS[stat] or 0
    val.Parent = leaderstats
  end
end

${xpStat ? `-- Level-up handler (triggered when XP changes)
local function checkLevelUp(player: Player)
  local userId = player.UserId
  local data = playerData[userId]
  if not data then return end

  local currentXP = data["${xpStat.name}"] or 0
  local currentLevel = data["Level"] or 1
  if currentLevel >= MAX_LEVEL then return end

  while currentLevel < MAX_LEVEL and currentXP >= xpForLevel(currentLevel) do
    currentXP -= xpForLevel(currentLevel)
    currentLevel += 1
    data["${xpStat.name}"] = currentXP
    data["Level"] = currentLevel
    -- Notify client
    local levelUpEvent = game:GetService("ReplicatedStorage"):FindFirstChild("LevelUp")
    if not levelUpEvent then
      levelUpEvent = Instance.new("RemoteEvent")
      levelUpEvent.Name = "LevelUp"
      levelUpEvent.Parent = game:GetService("ReplicatedStorage")
    end
    levelUpEvent:FireClient(player, currentLevel)
    print("[Progression] " .. player.Name .. " reached Level " .. currentLevel)
  end

  -- Sync leaderstat
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local xpStat = ls:FindFirstChild("${xpStat.name}")
    if xpStat then xpStat.Value = data["${xpStat.name}"] or 0 end
    local levelStat = ls:FindFirstChild("Level")
    if levelStat then levelStat.Value = currentLevel end
  end
end` : ''}

-- BindableFunction API for other server scripts to update stats
local statsAPI = Instance.new("BindableFunction")
statsAPI.Name = "StatsAPI"
statsAPI.Parent = game:GetService("ServerStorage")

statsAPI.OnInvoke = function(action: string, player: Player, statName: string, amount: number): number
  local userId = player.UserId
  if not playerData[userId] then return 0 end

  if action == "get" then
    return playerData[userId][statName] or 0
  elseif action == "set" then
    playerData[userId][statName] = amount
  elseif action == "add" then
    playerData[userId][statName] = (playerData[userId][statName] or 0) + amount
    ${xpStat ? `if statName == "${xpStat.name}" then checkLevelUp(player) end` : ''}
  end

  -- Sync to leaderstats
  local ls = player:FindFirstChild("leaderstats")
  if ls then
    local stat = ls:FindFirstChild(statName)
    if stat then stat.Value = playerData[userId][statName] or 0 end
  end

  return playerData[userId][statName] or 0
end

Players.PlayerAdded:Connect(function(player)
  loadStats(player)
  setupLeaderstats(player)
end)

Players.PlayerRemoving:Connect(function(player)
  saveStats(player)
  playerData[player.UserId] = nil
end)

print("[Progression] Leaderboard system initialized — ${stats.map((s) => s.name).join(', ')}")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. BASIC CLICK COMBAT
// ─────────────────────────────────────────────────────────────────────────────

export interface CombatParams {
  clickDamage: number
  attackRange: number
  attackCooldown: number
  enemyTag?: string
}

export function basicCombat(params: CombatParams): string {
  const damage = Math.max(1, Math.floor(params.clickDamage))
  const range = Math.max(5, params.attackRange)
  const cooldown = Math.max(0.1, params.attackCooldown)
  const enemyTag = safe(params.enemyTag ?? 'Enemy')

  return `-- Basic Click Combat System (LocalScript → StarterPlayerScripts)
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")

local player = Players.LocalPlayer
local mouse = player:GetMouse()
local camera = workspace.CurrentCamera

local CLICK_DAMAGE = ${damage}
local ATTACK_RANGE = ${range}
local ATTACK_COOLDOWN = ${cooldown}
local ENEMY_TAG = "${enemyTag}"

local lastAttack = 0
local attackRemote: RemoteEvent

-- Wait for combat remote to be created by server
local RS = game:GetService("ReplicatedStorage")
local combatRemote = RS:WaitForChild("CombatAttack", 10) :: RemoteEvent?
if not combatRemote then
  warn("[Combat] CombatAttack RemoteEvent not found in ReplicatedStorage")
  return
end

-- Visual feedback: swing animation
local function playSwingEffect(hitPosition: Vector3)
  local effect = Instance.new("Part")
  effect.Anchored = true
  effect.CanCollide = false
  effect.CastShadow = false
  effect.Size = Vector3.new(0.5, 0.5, 0.5)
  effect.Shape = Enum.PartType.Ball
  effect.Material = Enum.Material.Neon
  effect.Color = Color3.fromRGB(255, 80, 80)
  effect.Position = hitPosition
  effect.Parent = workspace
  game:GetService("Debris"):AddItem(effect, 0.15)
end

mouse.Button1Down:Connect(function()
  local now = tick()
  if now - lastAttack < ATTACK_COOLDOWN then return end

  local char = player.Character
  if not char then return end
  local hrp = char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if not hrp then return end

  -- Raycast from camera through mouse
  local unitRay = camera:ScreenPointToRay(mouse.X, mouse.Y)
  local rayParams = RaycastParams.new()
  rayParams.FilterDescendantsInstances = {char}
  rayParams.FilterType = Enum.RaycastFilterType.Exclude

  local result = workspace:Raycast(unitRay.Origin, unitRay.Direction * ATTACK_RANGE, rayParams)
  if not result then return end

  local hitPart = result.Instance
  if not hitPart then return end

  -- Check if hit part belongs to an enemy model
  local model = hitPart:FindFirstAncestorOfClass("Model")
  if not model then return end

  local humanoid = model:FindFirstChildOfClass("Humanoid")
  if not humanoid then return end

  -- Validate range (server will also validate — this is just client feedback)
  if (hrp.Position - result.Position).Magnitude > ATTACK_RANGE then return end

  lastAttack = now
  playSwingEffect(result.Position)
  combatRemote:FireServer(model, CLICK_DAMAGE)
end)

-- Server combat handler (place in ServerScriptService)
-- Note: This section below should be in a SEPARATE ServerScript
--[[
local combatRemote = Instance.new("RemoteEvent")
combatRemote.Name = "CombatAttack"
combatRemote.Parent = game:GetService("ReplicatedStorage")

local attackCooldowns: {[number]: number} = {}

combatRemote.OnServerEvent:Connect(function(player: Player, targetModel: Model, damage: number)
  -- Server-side validation
  local userId = player.UserId
  local now = tick()
  if now - (attackCooldowns[userId] or 0) < ${cooldown * 0.9} then return end
  attackCooldowns[userId] = now

  -- Validate target is a real enemy with humanoid
  local humanoid = targetModel and targetModel:FindFirstChildOfClass("Humanoid")
  if not humanoid or humanoid.Health <= 0 then return end

  -- Validate range
  local char = player.Character
  local hrp = char and char:FindFirstChild("HumanoidRootPart")
  local targetHrp = targetModel:FindFirstChild("HumanoidRootPart")
  if not hrp or not targetHrp then return end
  if (hrp.Position - targetHrp.Position).Magnitude > ${range + 5} then return end

  -- Apply damage (always between 1 and 2x declared damage to prevent exploit)
  local safeDamage = math.clamp(damage, 1, ${damage * 2})
  humanoid:TakeDamage(safeDamage)
end)
--]]

print("[Combat] Click combat initialized — ${damage} dmg, ${range} studs range, ${cooldown}s cooldown")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. INVENTORY SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface InventoryParams {
  maxSlots: number
  categories: string[]
  stackable?: boolean
}

export function inventorySystem(params: InventoryParams): string {
  const maxSlots = Math.max(1, Math.min(100, params.maxSlots))
  const categories = params.categories.map(safe)

  return `-- Inventory System (ServerScript → ServerScriptService)
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local inventoryStore = DataStoreService:GetDataStore("Inventory_v1")
local MAX_SLOTS = ${maxSlots}
local CATEGORIES = {"${categories.join('", "')}"}
local STACKABLE = ${params.stackable ? 'true' : 'false'}

export type InventoryItem = {
  id: string,
  name: string,
  category: string,
  quantity: number,
  metadata: {[string]: any}?,
}

local inventories: {[number]: {[number]: InventoryItem?}} = {}

local function loadInventory(player: Player)
  local userId = player.UserId
  local success, data = pcall(function()
    return inventoryStore:GetAsync("inv_" .. userId)
  end)
  inventories[userId] = (success and type(data) == "table" and data) or {}
end

local function saveInventory(player: Player)
  local userId = player.UserId
  if not inventories[userId] then return end
  pcall(function()
    inventoryStore:SetAsync("inv_" .. userId, inventories[userId])
  end)
end

local function getInventory(player: Player): {[number]: InventoryItem?}
  return inventories[player.UserId] or {}
end

local function findItem(player: Player, itemName: string): (number?, InventoryItem?)
  local inv = inventories[player.UserId]
  if not inv then return nil, nil end
  for slot, item in ipairs(inv) do
    if item and item.name == itemName then return slot, item end
  end
  return nil, nil
end

local function findEmptySlot(player: Player): number?
  local inv = inventories[player.UserId]
  if not inv then return nil end
  for i = 1, MAX_SLOTS do
    if not inv[i] then return i end
  end
  return nil
end

local function addItem(player: Player, item: InventoryItem): (boolean, string)
  local userId = player.UserId
  if not inventories[userId] then return false, "Player not found" end

  if STACKABLE then
    local slot, existing = findItem(player, item.name)
    if existing then
      existing.quantity = existing.quantity + item.quantity
      return true, "Stacked"
    end
  end

  local slot = findEmptySlot(player)
  if not slot then return false, "Inventory full" end

  inventories[userId][slot] = item
  return true, "Added"
end

local function removeItem(player: Player, itemName: string, quantity: number): boolean
  local slot, item = findItem(player, itemName)
  if not slot or not item then return false end
  if item.quantity < quantity then return false end
  item.quantity -= quantity
  if item.quantity <= 0 then
    inventories[player.UserId][slot] = nil
  end
  return true
end

-- RemoteFunction API for client inventory UI
local invRemote = Instance.new("RemoteFunction")
invRemote.Name = "InventoryAction"
invRemote.Parent = game:GetService("ReplicatedStorage")

invRemote.OnServerInvoke = function(player: Player, action: string, data: any): any
  if action == "get" then
    return getInventory(player)
  elseif action == "use" and type(data) == "table" then
    return removeItem(player, data.name, data.quantity or 1)
  end
  return false
end

-- Server API via BindableFunction
local invAPI = Instance.new("BindableFunction")
invAPI.Name = "InventoryAPI"
invAPI.Parent = game:GetService("ServerStorage")

invAPI.OnInvoke = function(action: string, player: Player, itemData: InventoryItem?, itemName: string?, qty: number?)
  if action == "add" and itemData then
    return addItem(player, itemData)
  elseif action == "remove" and itemName then
    return removeItem(player, itemName, qty or 1)
  elseif action == "has" and itemName then
    return findItem(player, itemName) ~= nil
  end
end

Players.PlayerAdded:Connect(function(p) loadInventory(p) end)
Players.PlayerRemoving:Connect(function(p) saveInventory(p); inventories[p.UserId] = nil end)

print("[Inventory] System initialized — " .. MAX_SLOTS .. " slots, categories: ${categories.join(', ')}")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. DAY / NIGHT CYCLE
// ─────────────────────────────────────────────────────────────────────────────

export interface DayNightCycleParams {
  cycleDurationMinutes: number
  sunriseHour?: number
  sunsetHour?: number
}

export function dayNightCycle(params: DayNightCycleParams): string {
  const cycleSecs = Math.max(60, params.cycleDurationMinutes * 60)
  const sunriseHour = params.sunriseHour ?? 6
  const sunsetHour = params.sunsetHour ?? 20

  return `-- Day/Night Cycle (Script → ServerScriptService)
local Lighting = game:GetService("Lighting")
local RunService = game:GetService("RunService")

local CYCLE_SECONDS = ${cycleSecs}  -- Real-world seconds for full 24h cycle
local SUNRISE_HOUR = ${sunriseHour}
local SUNSET_HOUR = ${sunsetHour}

-- Initial lighting setup
Lighting.Ambient = Color3.fromRGB(80, 80, 100)
Lighting.OutdoorAmbient = Color3.fromRGB(120, 120, 140)
Lighting.Brightness = 3
Lighting.ShadowSoftness = 0.2
Lighting.FogEnd = 2000
Lighting.FogColor = Color3.fromRGB(180, 190, 200)

-- Atmosphere
local atmosphere = Lighting:FindFirstChildOfClass("Atmosphere") or Instance.new("Atmosphere")
atmosphere.Density = 0.35
atmosphere.Offset = 0.06
atmosphere.Color = Color3.fromRGB(199, 170, 140)
atmosphere.Decay = Color3.fromRGB(106, 127, 153)
atmosphere.Glare = 0.06
atmosphere.Haze = 2.5
atmosphere.Parent = Lighting

-- Color-correct the sky colors by time of day
local function setTimeColors(hour: number)
  local isDay = hour >= SUNRISE_HOUR and hour < SUNSET_HOUR
  local isSunrise = hour >= SUNRISE_HOUR and hour < (SUNRISE_HOUR + 2)
  local isSunset = hour >= (SUNSET_HOUR - 2) and hour < SUNSET_HOUR

  if isSunrise then
    atmosphere.Color = Color3.fromRGB(255, 160, 90)
    Lighting.Ambient = Color3.fromRGB(100, 80, 70)
    Lighting.Brightness = 1.5
  elseif isSunset then
    atmosphere.Color = Color3.fromRGB(255, 120, 60)
    Lighting.Ambient = Color3.fromRGB(100, 70, 60)
    Lighting.Brightness = 1.2
  elseif isDay then
    atmosphere.Color = Color3.fromRGB(199, 170, 140)
    Lighting.Ambient = Color3.fromRGB(80, 80, 100)
    Lighting.Brightness = 3
  else
    -- Night
    atmosphere.Color = Color3.fromRGB(10, 10, 30)
    Lighting.Ambient = Color3.fromRGB(20, 20, 40)
    Lighting.Brightness = 0.3
  end
end

-- Advance time every frame
RunService.Heartbeat:Connect(function(dt: number)
  local currentHour = Lighting.ClockTime
  local hoursPerSecond = 24 / CYCLE_SECONDS
  local newHour = (currentHour + dt * hoursPerSecond) % 24
  Lighting.ClockTime = newHour
  setTimeColors(newHour)
end)

-- Sync time event for clients that need it
local timeEvent = Instance.new("RemoteEvent")
timeEvent.Name = "TimeSync"
timeEvent.Parent = game:GetService("ReplicatedStorage")

-- Broadcast time every 5 seconds
local lastSync = 0
RunService.Heartbeat:Connect(function()
  if tick() - lastSync >= 5 then
    lastSync = tick()
    timeEvent:FireAllClients(Lighting.ClockTime)
  end
end)

print("[Day/Night] Cycle active — ${params.cycleDurationMinutes}min real-time cycle")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 8. SPAWN SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface SpawnSystemParams {
  spawnPoints: number
  respawnDelay: number
  teamBased?: boolean
}

export function spawnSystem(params: SpawnSystemParams): string {
  const points = Math.max(1, Math.min(20, params.spawnPoints))
  const delay = Math.max(0, params.respawnDelay)

  return `-- Spawn System (Script → ServerScriptService)
local Players = game:GetService("Players")
local Teams = game:GetService("Teams")

local RESPAWN_DELAY = ${delay}
local TEAM_BASED = ${params.teamBased ? 'true' : 'false'}

-- Find all SpawnLocation parts tagged as game spawns
local function getSpawnPoints(): {SpawnLocation}
  local spawns: {SpawnLocation} = {}
  for _, obj in ipairs(workspace:GetDescendants()) do
    if obj:IsA("SpawnLocation") then
      table.insert(spawns, obj)
    end
  end
  return spawns
end

-- Pick a random spawn (or team-specific spawn if team-based)
local function getSpawnForPlayer(player: Player): SpawnLocation?
  local spawns = getSpawnPoints()
  if #spawns == 0 then return nil end

  if TEAM_BASED and player.Team then
    local teamSpawns: {SpawnLocation} = {}
    for _, spawn in ipairs(spawns) do
      if spawn.TeamColor == player.TeamColor then
        table.insert(teamSpawns, spawn)
      end
    end
    if #teamSpawns > 0 then
      return teamSpawns[math.random(#teamSpawns)]
    end
  end

  return spawns[math.random(#spawns)]
end

-- Override default Roblox respawn to use custom spawn logic
local function handleCharacterAdded(player: Player, character: Model)
  local hrp = character:WaitForChild("HumanoidRootPart", 5) :: BasePart?
  if not hrp then return end

  local spawn = getSpawnForPlayer(player)
  if spawn then
    hrp.CFrame = spawn.CFrame * CFrame.new(0, 3, 0)
  end
end

-- Custom respawn with delay
local function handleCharacterRemoving(player: Player)
  if RESPAWN_DELAY > 0 then
    task.delay(RESPAWN_DELAY, function()
      if player and player.Parent then
        player:LoadCharacter()
      end
    end)
  end
end

-- Disable Roblox auto-respawn if we're handling it manually
if RESPAWN_DELAY > 0 then
  game.Players.RespawnTime = RESPAWN_DELAY
end

Players.PlayerAdded:Connect(function(player: Player)
  player.CharacterAdded:Connect(function(character: Model)
    handleCharacterAdded(player, character)
  end)
  if RESPAWN_DELAY > 0 then
    player.CharacterRemoving:Connect(function()
      handleCharacterRemoving(player)
    end)
  end
end)

print("[Spawn] Spawn system ready — ${points} spawn points, ${delay}s respawn delay")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 9. OBBY CHECKPOINT SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface ObbyCheckpointParams {
  totalCheckpoints: number
  completionReward?: { currency: string; amount: number }
}

export function obbyCheckpoints(params: ObbyCheckpointParams): string {
  const total = Math.max(2, params.totalCheckpoints)
  const reward = params.completionReward

  return `-- Obby Checkpoint System (Script → ServerScriptService)
-- Checkpoints must be Parts named "Checkpoint1", "Checkpoint2", etc. in workspace.Checkpoints
local Players = game:GetService("Players")
local DataStoreService = game:GetService("DataStoreService")

local checkpointStore = DataStoreService:GetDataStore("ObbyCPs_v1")
local TOTAL_CHECKPOINTS = ${total}
${reward ? `local COMPLETION_CURRENCY = "${safe(reward.currency)}"
local COMPLETION_REWARD = ${Math.max(1, reward.amount)}` : ''}

-- In-memory checkpoint progress
local progress: {[number]: number} = {}  -- userId → highest checkpoint reached

local function loadProgress(player: Player)
  local success, data = pcall(function()
    return checkpointStore:GetAsync("cp_" .. player.UserId)
  end)
  progress[player.UserId] = (success and type(data) == "number") and data or 0
end

local function saveProgress(player: Player)
  local userId = player.UserId
  if progress[userId] == nil then return end
  pcall(function()
    checkpointStore:SetAsync("cp_" .. userId, progress[userId])
  end)
end

local function spawnAtCheckpoint(player: Player)
  local cp = progress[player.UserId] or 0
  if cp <= 0 then return end  -- spawn at default start

  local folder = workspace:FindFirstChild("Checkpoints")
  if not folder then return end
  local cpPart = folder:FindFirstChild("Checkpoint" .. cp) :: BasePart?
  if not cpPart then return end

  local char = player.Character
  local hrp = char and char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if hrp then
    hrp.CFrame = cpPart.CFrame * CFrame.new(0, 4, 0)
  end
end

-- Setup touch detectors for all checkpoints
local function setupCheckpoints()
  local folder = workspace:FindFirstChild("Checkpoints")
  if not folder then
    warn("[Obby] No 'Checkpoints' folder found in workspace")
    return
  end

  for i = 1, TOTAL_CHECKPOINTS do
    local cpPart = folder:FindFirstChild("Checkpoint" .. i) :: BasePart?
    if cpPart then
      local detector = Instance.new("TouchTransmitter")
      detector.Parent = cpPart

      cpPart.Touched:Connect(function(hit: BasePart)
        local char = hit:FindFirstAncestorOfClass("Model")
        if not char then return end
        local player = Players:GetPlayerFromCharacter(char)
        if not player then return end

        local current = progress[player.UserId] or 0
        if i <= current then return end  -- already reached this or later

        progress[player.UserId] = i
        saveProgress(player)

        -- Notify client
        local cpEvent = game:GetService("ReplicatedStorage"):FindFirstChild("CheckpointReached")
        if not cpEvent then
          cpEvent = Instance.new("RemoteEvent")
          cpEvent.Name = "CheckpointReached"
          cpEvent.Parent = game:GetService("ReplicatedStorage")
        end
        cpEvent:FireClient(player, i, TOTAL_CHECKPOINTS)

        print("[Obby] " .. player.Name .. " reached checkpoint " .. i)

        ${reward ? `-- Completion reward
        if i == TOTAL_CHECKPOINTS then
          local economyAPI = game:GetService("ServerStorage"):FindFirstChild("EconomyAPI")
          if economyAPI then
            economyAPI:Invoke("add", player, COMPLETION_CURRENCY, COMPLETION_REWARD)
            print("[Obby] " .. player.Name .. " completed obby! Rewarded " .. COMPLETION_REWARD .. " " .. COMPLETION_CURRENCY)
          end
        end` : ''}
      end)
    end
  end
end

Players.PlayerAdded:Connect(function(player: Player)
  loadProgress(player)
  player.CharacterAdded:Connect(function()
    task.wait(0.1)  -- brief delay so character loads
    spawnAtCheckpoint(player)
  end)
end)

Players.PlayerRemoving:Connect(function(player: Player)
  saveProgress(player)
  progress[player.UserId] = nil
end)

task.defer(setupCheckpoints)

print("[Obby] Checkpoint system initialized — ${total} checkpoints")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 10. PET FOLLOWING SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface PetFollowParams {
  petName: string
  followSpeed: number
  followDistance: number
  petModelId?: string
  bonusMultiplier?: number
}

export function petFollowSystem(params: PetFollowParams): string {
  const petName = safe(params.petName)
  const speed = Math.max(5, params.followSpeed)
  const distance = Math.max(3, params.followDistance)
  const modelId = params.petModelId ?? '0'
  const bonus = Math.max(1, params.bonusMultiplier ?? 1)

  return `-- Pet Following System (LocalScript → StarterPlayerScripts)
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer
local PET_NAME = "${petName}"
local FOLLOW_SPEED = ${speed}
local FOLLOW_DISTANCE = ${distance}
local BONUS_MULTIPLIER = ${bonus}

-- Pet model (spawned locally for this player's view)
local petModel: Model? = nil
local petRoot: BasePart? = nil

local function createPetModel(): Model?
  ${modelId !== '0' ? `-- Load from Roblox asset catalog
  local success, model = pcall(function()
    return game:GetService("InsertService"):LoadAsset(${modelId})
  end)
  if success and model then
    local petInst = model:FindFirstChildOfClass("Model") or model
    model:Destroy()  -- cleanup container
    return petInst :: Model
  end` : ''}

  -- Fallback: simple geometric pet
  local m = Instance.new("Model")
  m.Name = PET_NAME

  local body = Instance.new("Part")
  body.Name = "HumanoidRootPart"
  body.Size = Vector3.new(1.5, 1.5, 1.5)
  body.Shape = Enum.PartType.Ball
  body.Material = Enum.Material.SmoothPlastic
  body.Color = Color3.fromRGB(255, 215, 0)
  body.CastShadow = false
  body.Anchored = true
  body.CanCollide = false
  body.Parent = m

  -- Eyes
  local leftEye = Instance.new("Part")
  leftEye.Size = Vector3.new(0.3, 0.3, 0.1)
  leftEye.Material = Enum.Material.Neon
  leftEye.Color = Color3.fromRGB(0, 0, 0)
  leftEye.CanCollide = false
  leftEye.Anchored = true
  leftEye.CFrame = body.CFrame * CFrame.new(-0.4, 0.3, -0.7)
  leftEye.Parent = m

  local rightEye = leftEye:Clone()
  rightEye.CFrame = body.CFrame * CFrame.new(0.4, 0.3, -0.7)
  rightEye.Parent = m

  -- Billboard name tag
  local billboard = Instance.new("BillboardGui")
  billboard.Size = UDim2.new(0, 120, 0, 30)
  billboard.StudsOffset = Vector3.new(0, 2, 0)
  billboard.Parent = body

  local nameLabel = Instance.new("TextLabel")
  nameLabel.Size = UDim2.fromScale(1, 1)
  nameLabel.BackgroundTransparency = 1
  nameLabel.TextColor3 = Color3.fromRGB(255, 215, 0)
  nameLabel.Font = Enum.Font.GothamBold
  nameLabel.TextSize = 13
  nameLabel.Text = PET_NAME
  nameLabel.Parent = billboard

  m.PrimaryPart = body
  return m
end

local function spawnPet()
  if petModel then petModel:Destroy() end

  local model = createPetModel()
  if not model then return end

  local char = player.Character
  if not char then return end
  local hrp = char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if not hrp then return end

  model:SetPrimaryPartCFrame(hrp.CFrame * CFrame.new(FOLLOW_DISTANCE, 0, FOLLOW_DISTANCE))
  model.Parent = workspace

  petModel = model
  petRoot = model:FindFirstChild("HumanoidRootPart") :: BasePart?
end

-- Smooth follow logic (runs on client render step)
local LERP_FACTOR = math.min(1, FOLLOW_SPEED * 0.016)  -- per-frame lerp based on 60fps

RunService.RenderStepped:Connect(function(dt: number)
  if not petRoot or not petRoot.Parent then
    spawnPet()
    return
  end

  local char = player.Character
  if not char then return end
  local hrp = char:FindFirstChild("HumanoidRootPart") :: BasePart?
  if not hrp then return end

  -- Target position: offset from player
  local offset = Vector3.new(FOLLOW_DISTANCE * math.sin(tick()), 0.5, FOLLOW_DISTANCE * math.cos(tick() * 0.7))
  local targetPos = hrp.Position + offset
  local currentPos = petRoot.Position

  -- Only move if far enough away
  if (currentPos - targetPos).Magnitude > 0.5 then
    local newPos = currentPos:Lerp(targetPos, math.min(1, LERP_FACTOR * dt * 60))
    petRoot.CFrame = CFrame.new(newPos) * CFrame.Angles(0, math.atan2(targetPos.X - currentPos.X, targetPos.Z - currentPos.Z), 0)
  end

  -- Bobbing animation
  petRoot.CFrame = petRoot.CFrame * CFrame.new(0, math.sin(tick() * 3) * 0.15, 0)
end)

-- Respawn pet on character respawn
player.CharacterAdded:Connect(function()
  task.wait(1)
  spawnPet()
end)

-- Initial spawn
if player.Character then
  task.wait(0.5)
  spawnPet()
end

${bonus > 1 ? `-- Bonus multiplier effect (fires to server for economy sync)
local bonusEvent = game:GetService("ReplicatedStorage"):WaitForChild("PetBonus", 5) :: RemoteEvent?
if bonusEvent then
  bonusEvent:FireServer(PET_NAME, BONUS_MULTIPLIER)
end` : ''}

print("[Pet] ${petName} following system active — x${bonus} bonus multiplier")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 11. PROFESSIONAL BUILDING
// ─────────────────────────────────────────────────────────────────────────────

export interface ProBuildingParams {
  name: string
  type: 'shop' | 'house' | 'office' | 'warehouse' | 'apartment' | 'restaurant' | 'bank'
  floors: number
  width: number
  depth: number
  style: 'modern' | 'victorian' | 'industrial' | 'medieval' | 'futuristic'
  withInterior: boolean
  withLighting: boolean
  withVegetation: boolean
}

export function professionalBuilding(params: ProBuildingParams): string {
  const name = safe(params.name)
  const floors = Math.max(1, Math.min(5, Math.floor(params.floors)))
  const width = Math.max(8, Math.min(80, params.width))
  const depth = Math.max(8, Math.min(80, params.depth))
  const style = params.style
  const btype = params.type

  // Material per style
  const wallMat =
    style === 'victorian'  ? 'Enum.Material.Brick' :
    style === 'modern'     ? 'Enum.Material.SmoothPlastic' :
    style === 'industrial' ? 'Enum.Material.Metal' :
    style === 'medieval'   ? 'Enum.Material.Cobblestone' :
    style === 'futuristic' ? 'Enum.Material.Neon' :
    'Enum.Material.SmoothPlastic'

  const wallColorR =
    style === 'victorian'  ? '180, 150, 110' :
    style === 'modern'     ? '230, 230, 230' :
    style === 'industrial' ? '90, 85, 80' :
    style === 'medieval'   ? '140, 130, 120' :
    style === 'futuristic' ? '30, 40, 60' :
    '220, 220, 220'

  const trimColorR =
    style === 'victorian'  ? '100, 75, 50' :
    style === 'modern'     ? '50, 50, 50' :
    style === 'industrial' ? '60, 55, 50' :
    style === 'medieval'   ? '90, 85, 80' :
    style === 'futuristic' ? '0, 180, 255' :
    '60, 60, 60'

  const roofColorR =
    style === 'victorian'  ? '60, 40, 30' :
    style === 'modern'     ? '40, 40, 40' :
    style === 'industrial' ? '55, 50, 45' :
    style === 'medieval'   ? '80, 70, 60' :
    style === 'futuristic' ? '20, 30, 50' :
    '50, 50, 50'

  const floorHeight = 4
  const totalHeight = floors * floorHeight
  const wallThickness = 0.5
  const foundationHeight = 1.5
  const roofOverhang = 1.5
  const windowW = 2.2
  const windowH = 2.0

  return `-- Professional Building: ${name}
-- Style: ${style} | Type: ${btype} | ${floors} floors | ${width}x${depth} studs
-- Generated by ForjeGames Build Engine — place in workspace and anchor all parts
local ChangeHistoryService = game:GetService("ChangeHistoryService")

ChangeHistoryService:SetWaypoint("Before_Build_${name}")

local function makePart(parent, partName, size, position, color, material, anchored)
  anchored = anchored == nil and true or anchored
  local p = Instance.new("Part")
  p.Name = partName
  p.Size = size
  p.CFrame = CFrame.new(position)
  p.Color = Color3.fromRGB(table.unpack(color))
  p.Material = material
  p.Anchored = anchored
  p.TopSurface = Enum.SurfaceType.Smooth
  p.BottomSurface = Enum.SurfaceType.Smooth
  p.Parent = parent
  return p
end

-- ── Root model & folders ────────────────────────────────────────────────────
local building = Instance.new("Model")
building.Name = "${name}"
building.Parent = workspace

local fWalls   = Instance.new("Folder"); fWalls.Name   = "Walls";   fWalls.Parent   = building
local fRoof    = Instance.new("Folder"); fRoof.Name    = "Roof";    fRoof.Parent    = building
local fDetails = Instance.new("Folder"); fDetails.Name = "Details"; fDetails.Parent = building
local fLights  = Instance.new("Folder"); fLights.Name  = "Lights";  fLights.Parent  = building
local fPlants  = Instance.new("Folder"); fPlants.Name  = "Plants";  fPlants.Parent  = building

local W  = ${width}
local D  = ${depth}
local FH = ${floorHeight}    -- floor height in studs
local WT = ${wallThickness}  -- wall thickness
local FLOORS = ${floors}
local originX, originY, originZ = 0, 0, 0  -- change this to reposition the building

-- ── Foundation ──────────────────────────────────────────────────────────────
local foundationY = originY + ${foundationHeight / 2}
makePart(fDetails, "Foundation",
  Vector3.new(W + 1.5, ${foundationHeight}, D + 1.5),
  Vector3.new(originX, foundationY, originZ),
  {130, 125, 120}, Enum.Material.Concrete)

-- ── Walls per floor ─────────────────────────────────────────────────────────
for floor = 1, FLOORS do
  local floorBase = originY + ${foundationHeight} + (floor - 1) * FH

  -- Four walls: front(+Z), back(-Z), left(-X), right(+X)
  local walls = {
    {name="WallFront_F"..floor,  size=Vector3.new(W, FH, WT),        pos=Vector3.new(originX, floorBase + FH/2, originZ + D/2)},
    {name="WallBack_F"..floor,   size=Vector3.new(W, FH, WT),        pos=Vector3.new(originX, floorBase + FH/2, originZ - D/2)},
    {name="WallLeft_F"..floor,   size=Vector3.new(WT, FH, D - WT*2), pos=Vector3.new(originX - W/2, floorBase + FH/2, originZ)},
    {name="WallRight_F"..floor,  size=Vector3.new(WT, FH, D - WT*2), pos=Vector3.new(originX + W/2, floorBase + FH/2, originZ)},
  }

  for _, w in ipairs(walls) do
    makePart(fWalls, w.name, w.size, w.pos,
      {${wallColorR}}, ${wallMat})
  end

  -- Floor ledge / trim between floors (skip top of last floor — that's the roof)
  if floor < FLOORS then
    local ledgeY = floorBase + FH
    makePart(fDetails, "FloorLedge_"..floor,
      Vector3.new(W + 0.6, 0.35, D + 0.6),
      Vector3.new(originX, ledgeY + 0.175, originZ),
      {${trimColorR}}, Enum.Material.SmoothPlastic)
  end

  -- Corner pillar details
  local corners = {
    Vector3.new(originX - W/2, floorBase + FH/2, originZ + D/2),
    Vector3.new(originX + W/2, floorBase + FH/2, originZ + D/2),
    Vector3.new(originX - W/2, floorBase + FH/2, originZ - D/2),
    Vector3.new(originX + W/2, floorBase + FH/2, originZ - D/2),
  }
  for ci, cp in ipairs(corners) do
    makePart(fDetails, "Corner_F"..floor.."_"..ci,
      Vector3.new(0.8, FH + 0.1, 0.8),
      cp,
      {${trimColorR}}, Enum.Material.SmoothPlastic)
  end

  -- Recessed windows — front wall (one window per 4 studs of width, leaving room for corners)
  local numWindows = math.max(1, math.floor((W - 4) / 4))
  local windowSpacing = (W - 4) / numWindows
  for wi = 1, numWindows do
    local wx = originX - (W/2 - 2) + (wi - 1) * windowSpacing + windowSpacing / 2
    local wz = originZ + D/2 + 0.1
    local windowY = floorBase + FH * 0.55

    -- Window recess (slightly inset box)
    local recess = makePart(fDetails, "WindowRecess_F"..floor.."_"..wi,
      Vector3.new(${windowW + 0.2}, ${windowH + 0.2}, 0.3),
      Vector3.new(wx, windowY, wz),
      {${trimColorR}}, Enum.Material.SmoothPlastic)

    -- Window glass pane
    local glass = makePart(fDetails, "WindowGlass_F"..floor.."_"..wi,
      Vector3.new(${windowW}, ${windowH}, 0.1),
      Vector3.new(wx, windowY, wz + 0.15),
      {180, 210, 240}, Enum.Material.Glass)
    glass.Transparency = 0.5

    -- Window frame (top header bar)
    makePart(fDetails, "WindowHeader_F"..floor.."_"..wi,
      Vector3.new(${windowW + 0.4}, 0.25, 0.35),
      Vector3.new(wx, windowY + ${windowH / 2 + 0.12}, wz),
      {${trimColorR}}, Enum.Material.SmoothPlastic)

    -- Window sill (bottom ledge)
    makePart(fDetails, "WindowSill_F"..floor.."_"..wi,
      Vector3.new(${windowW + 0.6}, 0.2, 0.5),
      Vector3.new(wx, windowY - ${windowH / 2 + 0.1}, wz + 0.1),
      {${trimColorR}}, Enum.Material.SmoothPlastic)
  end
end

-- ── Door frame (ground floor, front wall center) ─────────────────────────────
local doorW, doorH = 3.5, 4.0
local doorBase = originY + ${foundationHeight}
-- Door opening (slightly darker inset)
makePart(fDetails, "DoorRecess",
  Vector3.new(doorW + 0.4, doorH + 0.2, 0.4),
  Vector3.new(originX, doorBase + doorH/2, originZ + D/2 + 0.05),
  {${trimColorR}}, Enum.Material.SmoothPlastic)
-- Door panels (left + right half)
makePart(fDetails, "DoorLeft",
  Vector3.new(doorW/2 - 0.1, doorH - 0.2, 0.15),
  Vector3.new(originX - doorW/4, doorBase + doorH/2, originZ + D/2 + 0.25),
  {${wallColorR}}, Enum.Material.WoodPlanks)
makePart(fDetails, "DoorRight",
  Vector3.new(doorW/2 - 0.1, doorH - 0.2, 0.15),
  Vector3.new(originX + doorW/4, doorBase + doorH/2, originZ + D/2 + 0.25),
  {${wallColorR}}, Enum.Material.WoodPlanks)
-- Door header
makePart(fDetails, "DoorHeader",
  Vector3.new(doorW + 0.8, 0.4, 0.5),
  Vector3.new(originX, doorBase + doorH + 0.2, originZ + D/2 + 0.05),
  {${trimColorR}}, Enum.Material.SmoothPlastic)

-- ── Roof overhang ────────────────────────────────────────────────────────────
local roofY = originY + ${foundationHeight} + floors * floorHeight
local overhang = ${roofOverhang}
makePart(fRoof, "RoofSlab",
  Vector3.new(W + overhang*2, 0.5, D + overhang*2),
  Vector3.new(originX, roofY + 0.25, originZ),
  {${roofColorR}}, Enum.Material.SmoothPlastic)
-- Fascia (front/back)
makePart(fRoof, "FasciaFront",
  Vector3.new(W + overhang*2 + 0.2, 0.8, 0.4),
  Vector3.new(originX, roofY - 0.15, originZ + D/2 + overhang),
  {${trimColorR}}, Enum.Material.SmoothPlastic)
makePart(fRoof, "FasciaBack",
  Vector3.new(W + overhang*2 + 0.2, 0.8, 0.4),
  Vector3.new(originX, roofY - 0.15, originZ - D/2 - overhang),
  {${trimColorR}}, Enum.Material.SmoothPlastic)
makePart(fRoof, "FasciaLeft",
  Vector3.new(0.4, 0.8, D + overhang*2),
  Vector3.new(originX - W/2 - overhang, roofY - 0.15, originZ),
  {${trimColorR}}, Enum.Material.SmoothPlastic)
makePart(fRoof, "FasciaRight",
  Vector3.new(0.4, 0.8, D + overhang*2),
  Vector3.new(originX + W/2 + overhang, roofY - 0.15, originZ),
  {${trimColorR}}, Enum.Material.SmoothPlastic)

${params.withLighting ? `
-- ── Lighting ─────────────────────────────────────────────────────────────────
-- Interior ceiling lights per floor
for floor = 1, FLOORS do
  local lightY = originY + ${foundationHeight} + (floor - 1) * FH + FH * 0.9
  local interior = Instance.new("Part")
  interior.Name = "CeilingLight_F"..floor
  interior.Size = Vector3.new(0.6, 0.2, 0.6)
  interior.Anchored = true
  interior.Material = Enum.Material.Neon
  interior.Color = Color3.fromRGB(255, 245, 220)
  interior.CFrame = CFrame.new(originX, lightY, originZ)
  interior.Parent = fLights

  local pl = Instance.new("PointLight")
  pl.Brightness = 3
  pl.Range = math.max(W, D) * 0.9
  pl.Color = Color3.fromRGB(255, 245, 220)
  pl.Parent = interior
end

-- Exterior wall sconces (flanking the door)
for _, xOff in ipairs({-doorW/2 - 1, doorW/2 + 1}) do
  local sconce = Instance.new("Part")
  sconce.Name = "Sconce"
  sconce.Size = Vector3.new(0.4, 0.4, 0.4)
  sconce.Shape = Enum.PartType.Ball
  sconce.Material = Enum.Material.Neon
  sconce.Color = Color3.fromRGB(255, 230, 160)
  sconce.Anchored = true
  sconce.CFrame = CFrame.new(originX + xOff, originY + ${foundationHeight} + 2.8, originZ + D/2 + 0.5)
  sconce.Parent = fLights

  local sl = Instance.new("SpotLight")
  sl.Brightness = 4
  sl.Range = 20
  sl.Angle = 90
  sl.Face = Enum.NormalId.Front
  sl.Color = Color3.fromRGB(255, 230, 160)
  sl.Parent = sconce
end
` : '-- withLighting = false: no lights added'}

${params.withVegetation ? `
-- ── Vegetation ───────────────────────────────────────────────────────────────
-- Window planters (front wall, ground floor only)
local numPlanters = math.max(1, math.floor((W - 4) / 4))
local planterSpacing = (W - 4) / numPlanters
for pi = 1, numPlanters do
  local px = originX - (W/2 - 2) + (pi - 1) * planterSpacing + planterSpacing / 2
  local pz = originZ + D/2 + 0.4
  local planterY = originY + ${foundationHeight} + FH * 0.25

  -- Planter box
  local box = makePart(fPlants, "Planter_"..pi,
    Vector3.new(2, 0.5, 0.4),
    Vector3.new(px, planterY, pz),
    {80, 60, 45}, Enum.Material.WoodPlanks)

  -- Plant foliage (small sphere of leaves)
  local foliage = makePart(fPlants, "Foliage_"..pi,
    Vector3.new(1.8, 1.2, 1.0),
    Vector3.new(px, planterY + 0.85, pz),
    {55 + math.random(0,20), 130 + math.random(0,25), 55 + math.random(0,20)},
    Enum.Material.LeafyGrass)
  foliage.Shape = Enum.PartType.Ball
end

-- Base shrubs along building front
local shrubCount = math.max(2, math.floor(W / 5))
for si = 1, shrubCount do
  local sx = originX - W/2 + 2 + (si - 1) * (W - 4) / math.max(1, shrubCount - 1)
  local shrubY = originY + ${foundationHeight} + 0.8
  local shrub = makePart(fPlants, "Shrub_"..si,
    Vector3.new(1.8, 1.6, 1.6),
    Vector3.new(sx, shrubY, originZ + D/2 + 1.2),
    {45 + math.random(0,20), 110 + math.random(0,20), 50 + math.random(0,15)},
    Enum.Material.LeafyGrass)
  shrub.Shape = Enum.PartType.Ball
end
` : '-- withVegetation = false: no plants added'}

${params.withInterior ? `
-- ── Interior floor ───────────────────────────────────────────────────────────
for floor = 1, FLOORS do
  local floorY = originY + ${foundationHeight} + (floor - 1) * FH
  local floorMat = ("${btype}" == "restaurant" or "${btype}" == "bank")
    and Enum.Material.Marble
    or ("${btype}" == "warehouse") and Enum.Material.Concrete
    or Enum.Material.WoodPlanks
  local floorCol = ("${btype}" == "restaurant" or "${btype}" == "bank")
    and {200, 195, 190}
    or ("${btype}" == "warehouse") and {100, 95, 90}
    or {180, 150, 110}

  makePart(fDetails, "InteriorFloor_F"..floor,
    Vector3.new(W - WT*2, 0.2, D - WT*2),
    Vector3.new(originX, floorY + 0.1, originZ),
    floorCol, floorMat)

  -- Baseboard trim
  local baseboards = {
    {size=Vector3.new(W - WT*2, 0.3, 0.15), pos=Vector3.new(originX, floorY + 0.25, originZ + D/2 - WT - 0.07)},
    {size=Vector3.new(W - WT*2, 0.3, 0.15), pos=Vector3.new(originX, floorY + 0.25, originZ - D/2 + WT + 0.07)},
    {size=Vector3.new(0.15, 0.3, D - WT*2), pos=Vector3.new(originX - W/2 + WT + 0.07, floorY + 0.25, originZ)},
    {size=Vector3.new(0.15, 0.3, D - WT*2), pos=Vector3.new(originX + W/2 - WT - 0.07, floorY + 0.25, originZ)},
  }
  for bi, bb in ipairs(baseboards) do
    makePart(fDetails, "Baseboard_F"..floor.."_"..bi, bb.size, bb.pos,
      {${trimColorR}}, Enum.Material.SmoothPlastic)
  end
end
` : '-- withInterior = false: no interior details added'}

building.PrimaryPart = building:FindFirstChildOfClass("Part")
ChangeHistoryService:SetWaypoint("Built_${name}")
print("[Building] ${name} (${style} ${btype}, ${floors} floors) built successfully.")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 12. DETAILED STREET LAMP
// ─────────────────────────────────────────────────────────────────────────────

export interface StreetLampParams {
  style: 'modern' | 'victorian' | 'industrial'
  height: number
  lightColor: [number, number, number]
  withBanner: boolean
}

export function detailedStreetLamp(params: StreetLampParams): string {
  const style = params.style
  const height = Math.max(8, Math.min(30, params.height))
  const [lr, lg, lb] = params.lightColor.map((v) => Math.max(0, Math.min(255, Math.floor(v))))

  const shaftMat =
    style === 'victorian'  ? 'Enum.Material.Metal' :
    style === 'modern'     ? 'Enum.Material.SmoothPlastic' :
    'Enum.Material.Metal'

  const shaftColorR =
    style === 'victorian'  ? '40, 35, 30' :
    style === 'modern'     ? '60, 60, 65' :
    '55, 50, 45'

  const fixtureColorR =
    style === 'victorian'  ? '50, 45, 35' :
    style === 'modern'     ? '40, 40, 45' :
    '65, 60, 55'

  const baseDiam = style === 'victorian' ? 1.8 : 1.2

  return `-- Detailed Street Lamp (${style}) — run in Command Bar or Script to place at origin
-- Move the "StreetLamp" model to your desired position after generation.
local ChangeHistoryService = game:GetService("ChangeHistoryService")
ChangeHistoryService:SetWaypoint("Before_StreetLamp")

local function part(parent, nm, sz, cf, color, mat, shape)
  local p = Instance.new("Part")
  p.Name = nm
  p.Size = sz
  p.CFrame = cf
  p.Color = Color3.fromRGB(table.unpack(color))
  p.Material = mat
  p.Anchored = true
  p.TopSurface = Enum.SurfaceType.Smooth
  p.BottomSurface = Enum.SurfaceType.Smooth
  if shape then p.Shape = shape end
  p.Parent = parent
  return p
end

local lamp = Instance.new("Model")
lamp.Name = "StreetLamp"
lamp.Parent = workspace

local HEIGHT = ${height}
local originX, originY, originZ = 0, 0, 0

-- ── Base plate ───────────────────────────────────────────────────────────────
part(lamp, "BasePlate",
  Vector3.new(${baseDiam + 0.4}, 0.4, ${baseDiam + 0.4}),
  CFrame.new(originX, originY + 0.2, originZ),
  {${shaftColorR}}, ${shaftMat})

${style === 'victorian' ? `
-- Victorian decorative base collar
part(lamp, "BaseCollar",
  Vector3.new(${baseDiam}, 0.6, ${baseDiam}),
  CFrame.new(originX, originY + 0.7, originZ),
  {${shaftColorR}}, ${shaftMat}, Enum.PartType.Cylinder)
-- Ornamental fluting rings (3 stacked)
for ri = 1, 3 do
  part(lamp, "Ring_"..ri,
    Vector3.new(${baseDiam - 0.2}, 0.25, ${baseDiam - 0.2}),
    CFrame.new(originX, originY + 1.0 + ri * 1.1, originZ),
    {${fixtureColorR}}, ${shaftMat}, Enum.PartType.Cylinder)
end
` : ''}

-- ── Shaft (3 stacked cylinders for subtle taper) ─────────────────────────────
local shaftSegments = 3
local segH = (HEIGHT - 2) / shaftSegments
for si = 1, shaftSegments do
  local diam = ${baseDiam} - (si - 1) * 0.15
  local cy = originY + 1.0 + (si - 1) * segH + segH / 2
  part(lamp, "Shaft_"..si,
    Vector3.new(diam, segH, diam),
    CFrame.new(originX, cy, originZ),
    {${shaftColorR}}, ${shaftMat}, Enum.PartType.Cylinder)
end

-- ── Arm bracket ──────────────────────────────────────────────────────────────
local armY = originY + HEIGHT - 1.5
-- Vertical neck
part(lamp, "ArmNeck",
  Vector3.new(0.35, 1.4, 0.35),
  CFrame.new(originX, armY, originZ),
  {${shaftColorR}}, ${shaftMat}, Enum.PartType.Cylinder)
-- Horizontal arm (extends forward/+Z)
local armLen = ${style === 'victorian' ? 2.5 : 1.8}
part(lamp, "Arm",
  Vector3.new(0.3, 0.3, armLen),
  CFrame.new(originX, armY + 0.7, originZ + armLen / 2),
  {${shaftColorR}}, ${shaftMat})

-- ── Fixture housing ──────────────────────────────────────────────────────────
local fixtureX = originX
local fixtureZ = originZ + armLen
local fixtureY = armY + 0.4

part(lamp, "FixtureTop",
  Vector3.new(1.0, 0.3, 1.0),
  CFrame.new(fixtureX, fixtureY + 0.15, fixtureZ),
  {${fixtureColorR}}, ${shaftMat})
part(lamp, "FixtureBody",
  Vector3.new(0.8, 0.5, 0.8),
  CFrame.new(fixtureX, fixtureY - 0.15, fixtureZ),
  {${fixtureColorR}}, ${shaftMat})

-- Bulb (neon sphere for glow effect)
local bulb = part(lamp, "Bulb",
  Vector3.new(0.5, 0.5, 0.5),
  CFrame.new(fixtureX, fixtureY - 0.4, fixtureZ),
  {${lr}, ${lg}, ${lb}}, Enum.Material.Neon, Enum.PartType.Ball)

-- ── Lights ───────────────────────────────────────────────────────────────────
-- SpotLight angled downward for ground illumination
local spot = Instance.new("SpotLight")
spot.Brightness = 5
spot.Range = 30
spot.Angle = 75
spot.Face = Enum.NormalId.Bottom
spot.Color = Color3.fromRGB(${lr}, ${lg}, ${lb})
spot.Parent = bulb

-- PointLight for ambient halo glow
local glow = Instance.new("PointLight")
glow.Brightness = 1.5
glow.Range = 18
glow.Color = Color3.fromRGB(${lr}, ${lg}, ${lb})
glow.Parent = bulb

${params.withBanner ? `
-- ── Banner attachment ─────────────────────────────────────────────────────────
local bannerY = armY - 1.5
-- Pole clips (top and bottom)
part(lamp, "BannerClipTop",
  Vector3.new(0.5, 0.25, 0.5),
  CFrame.new(originX, bannerY + 1.5, originZ),
  {${shaftColorR}}, ${shaftMat})
part(lamp, "BannerClipBottom",
  Vector3.new(0.5, 0.25, 0.5),
  CFrame.new(originX, bannerY - 1.5, originZ),
  {${shaftColorR}}, ${shaftMat})
-- Banner face (SurfaceGui target)
local banner = part(lamp, "BannerFace",
  Vector3.new(1.8, 3.0, 0.08),
  CFrame.new(originX + 0.9 + 0.04, bannerY, originZ),
  {220, 30, 30}, Enum.Material.SmoothPlastic)
-- Attach a SurfaceGui for custom text
local gui = Instance.new("SurfaceGui")
gui.Face = Enum.NormalId.Front
gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
gui.PixelsPerStud = 50
gui.Parent = banner
local label = Instance.new("TextLabel")
label.Size = UDim2.fromScale(1, 1)
label.BackgroundTransparency = 1
label.TextColor3 = Color3.fromRGB(255, 255, 255)
label.Font = Enum.Font.GothamBold
label.TextScaled = true
label.Text = "BANNER"
label.Parent = gui
` : '-- withBanner = false'}

lamp.PrimaryPart = lamp:FindFirstChildOfClass("Part")
ChangeHistoryService:SetWaypoint("Built_StreetLamp")
print("[StreetLamp] ${style} lamp built — height ${height}, RGB(${lr},${lg},${lb})")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 13. DETAILED TREE
// ─────────────────────────────────────────────────────────────────────────────

export interface TreeParams {
  type: 'oak' | 'pine' | 'cherry' | 'palm' | 'birch'
  size: 'small' | 'medium' | 'large'
  withRoots: boolean
  withFallenLeaves: boolean
  season: 'spring' | 'summer' | 'autumn' | 'winter'
}

export function detailedTree(params: TreeParams): string {
  const ttype = params.type
  const tsize = params.size
  const season = params.season

  const scale = tsize === 'small' ? 0.65 : tsize === 'large' ? 1.55 : 1.0

  // Trunk color per tree type
  const trunkColorR =
    ttype === 'birch'  ? '220, 215, 205' :
    ttype === 'palm'   ? '150, 120, 80' :
    '100, 75, 50'

  // Leaf color per season
  const leafColorR =
    season === 'spring'  ? '120, 190, 90' :
    season === 'summer'  ? '55, 140, 55' :
    season === 'autumn'  ? '200, 90, 30' :
    '60, 60, 70'  // winter — bare/grey

  const leafColorVariantR =
    season === 'spring'  ? '140, 200, 100' :
    season === 'summer'  ? '70, 160, 60' :
    season === 'autumn'  ? '180, 60, 20' :
    '70, 70, 80'

  const hasLeaves = season !== 'winter'
  const trunkH = 6 * scale
  const trunkBaseW = 1.0 * scale
  const branchCount = ttype === 'pine' ? 0 : (ttype === 'palm' ? 0 : 4)

  return `-- Detailed Tree: ${ttype} (${season}) — ${tsize} size
local ChangeHistoryService = game:GetService("ChangeHistoryService")
ChangeHistoryService:SetWaypoint("Before_Tree")

local SCALE = ${scale.toFixed(2)}
local originX, originY, originZ = 0, 0, 0

local tree = Instance.new("Model")
tree.Name = "${ttype}_${season}"
tree.Parent = workspace

local function cyl(parent, nm, diam, h, cf, color)
  local p = Instance.new("Part")
  p.Name = nm
  p.Shape = Enum.PartType.Cylinder
  p.Size = Vector3.new(h, diam, diam)
  p.CFrame = cf * CFrame.Angles(0, 0, math.pi/2)
  p.Color = Color3.fromRGB(table.unpack(color))
  p.Material = Enum.Material.Wood
  p.Anchored = true
  p.TopSurface = Enum.SurfaceType.Smooth
  p.BottomSurface = Enum.SurfaceType.Smooth
  p.Parent = parent
  return p
end

local function sphere(parent, nm, size, pos, color, mat)
  local p = Instance.new("Part")
  p.Name = nm
  p.Shape = Enum.PartType.Ball
  p.Size = Vector3.new(size, size, size)
  p.CFrame = CFrame.new(pos)
  p.Color = Color3.fromRGB(table.unpack(color))
  p.Material = mat or Enum.Material.LeafyGrass
  p.Anchored = true
  p.CastShadow = true
  p.Parent = parent
  return p
end

-- ── Trunk (3 stacked cylinders, tapering) ───────────────────────────────────
local trunkH = ${trunkH.toFixed(2)}
local trunkBaseW = ${trunkBaseW.toFixed(2)}
local trunkSections = 3
for ti = 1, trunkSections do
  local segH = trunkH / trunkSections
  local segDiam = trunkBaseW * (1 - (ti - 1) * 0.22)
  local segY = originY + (ti - 1) * segH + segH / 2
  cyl(tree, "Trunk_"..ti, segDiam, segH,
    CFrame.new(originX, segY, originZ),
    {${trunkColorR}})
end

${params.withRoots ? `
-- ── Surface roots (radiating planks) ─────────────────────────────────────────
local rootAngles = {0, math.pi*0.4, math.pi*0.8, math.pi*1.2, math.pi*1.6}
for ri, angle in ipairs(rootAngles) do
  local rootLen = SCALE * (1.8 + math.random() * 0.8)
  local rootX = originX + math.cos(angle) * rootLen * 0.5
  local rootZ = originZ + math.sin(angle) * rootLen * 0.5
  local p = Instance.new("Part")
  p.Name = "Root_"..ri
  p.Size = Vector3.new(rootLen, 0.4 * SCALE, 0.35 * SCALE)
  p.CFrame = CFrame.new(rootX, originY + 0.15, rootZ)
    * CFrame.Angles(0, angle + math.pi/2, 0)
    * CFrame.Angles(-0.15, 0, 0)
  p.Color = Color3.fromRGB(${trunkColorR})
  p.Material = Enum.Material.Wood
  p.Anchored = true
  p.Parent = tree
end
` : ''}

${ttype === 'pine' ? `
-- ── Pine cone layers ─────────────────────────────────────────────────────────
local layers = {
  {y = trunkH * 0.35, r = SCALE * 3.5, h = SCALE * 2.2},
  {y = trunkH * 0.55, r = SCALE * 2.8, h = SCALE * 1.8},
  {y = trunkH * 0.73, r = SCALE * 2.0, h = SCALE * 1.4},
  {y = trunkH * 0.88, r = SCALE * 1.2, h = SCALE * 1.0},
}
for li, layer in ipairs(layers) do
  if ${hasLeaves} then
    local cone = Instance.new("SpecialMesh")
    local part = Instance.new("Part")
    part.Name = "PineLayer_"..li
    part.Size = Vector3.new(layer.r * 2, layer.h, layer.r * 2)
    part.CFrame = CFrame.new(originX, originY + layer.y, originZ)
    part.Color = Color3.fromRGB(${leafColorR})
    part.Material = Enum.Material.LeafyGrass
    part.Anchored = true
    part.Parent = tree
    cone.MeshType = Enum.MeshType.FileMesh
    cone.MeshId = "rbxasset://fonts/rightarm.mesh"
    cone.Parent = part
  end
end
` : ttype === 'palm' ? `
-- ── Palm fronds ───────────────────────────────────────────────────────────────
local palmTopY = originY + trunkH
local frondCount = 7
for fi = 1, frondCount do
  local angle = (fi / frondCount) * math.pi * 2
  local frondLen = SCALE * 4.5
  local frondX = originX + math.cos(angle) * frondLen * 0.5
  local frondZ = originZ + math.sin(angle) * frondLen * 0.5
  local frondY = palmTopY + frondLen * 0.1
  local p = Instance.new("Part")
  p.Name = "PalmFrond_"..fi
  p.Size = Vector3.new(frondLen, 0.25 * SCALE, 0.8 * SCALE)
  p.CFrame = CFrame.new(frondX, frondY, frondZ)
    * CFrame.Angles(0, angle + math.pi/2, 0)
    * CFrame.Angles(-0.35, 0, 0)
  p.Color = Color3.fromRGB(${leafColorR})
  p.Material = Enum.Material.LeafyGrass
  p.Anchored = true
  p.Parent = tree
end
` : `
-- ── Branches + leaf clumps (oak/cherry/birch) ────────────────────────────────
local branchStartY = originY + trunkH * 0.55
local numBranches = ${branchCount}
for bi = 1, numBranches do
  local angle = (bi / numBranches) * math.pi * 2
  local bLen = SCALE * (2.0 + math.random() * 1.2)
  local bX = originX + math.cos(angle) * bLen * 0.55
  local bZ = originZ + math.sin(angle) * bLen * 0.55
  local bY = branchStartY + bLen * 0.4

  -- Branch part
  local bp = Instance.new("Part")
  bp.Name = "Branch_"..bi
  bp.Size = Vector3.new(bLen, 0.5 * SCALE, 0.5 * SCALE)
  bp.CFrame = CFrame.new(
    originX + math.cos(angle) * bLen * 0.28,
    branchStartY + bLen * 0.2,
    originZ + math.sin(angle) * bLen * 0.28
  ) * CFrame.Angles(0, angle + math.pi/2, 0) * CFrame.Angles(-0.4, 0, 0)
  bp.Color = Color3.fromRGB(${trunkColorR})
  bp.Material = Enum.Material.Wood
  bp.Anchored = true
  bp.Parent = tree

  -- Leaf clumps at branch tip (3 overlapping spheres for density)
  if ${hasLeaves} then
    for ci = 1, 3 do
      local offX = (math.random() - 0.5) * SCALE * 1.2
      local offY = (math.random() - 0.5) * SCALE * 0.8
      local offZ = (math.random() - 0.5) * SCALE * 1.2
      local clumpSize = SCALE * (2.2 + math.random() * 0.8)
      local useVariant = ci == 2
      sphere(tree, "Leaves_B"..bi.."_C"..ci,
        clumpSize,
        Vector3.new(bX + offX, bY + offY + SCALE, bZ + offZ),
        useVariant and {${leafColorVariantR}} or {${leafColorR}})
    end
  end
end

-- Central canopy mass (main body)
if ${hasLeaves} then
  sphere(tree, "CanopyCenter",
    SCALE * (${ttype === 'oak' ? 5.5 : 4.0}),
    Vector3.new(originX, originY + trunkH * 0.9, originZ),
    {${leafColorR}})
  sphere(tree, "CanopyLeft",
    SCALE * 3.8,
    Vector3.new(originX - SCALE * 1.8, originY + trunkH * 0.85, originZ),
    {${leafColorVariantR}})
  sphere(tree, "CanopyRight",
    SCALE * 3.8,
    Vector3.new(originX + SCALE * 1.8, originY + trunkH * 0.85, originZ),
    {${leafColorR}})
  sphere(tree, "CanopyTop",
    SCALE * 3.0,
    Vector3.new(originX, originY + trunkH * 1.1, originZ),
    {${leafColorVariantR}})
end
`}

${params.withFallenLeaves && season === 'autumn' ? `
-- ── Fallen leaves (scattered around base) ────────────────────────────────────
local fallenColors = {
  {200, 80, 20}, {180, 60, 10}, {210, 110, 30}, {170, 50, 15}, {195, 90, 25}
}
for li = 1, 18 do
  local angle = math.random() * math.pi * 2
  local dist = SCALE * (0.8 + math.random() * 2.5)
  local lx = originX + math.cos(angle) * dist
  local lz = originZ + math.sin(angle) * dist
  local col = fallenColors[(li % #fallenColors) + 1]
  local leaf = Instance.new("Part")
  leaf.Name = "FallenLeaf_"..li
  leaf.Size = Vector3.new(SCALE * 0.6, 0.05, SCALE * 0.5)
  leaf.CFrame = CFrame.new(lx, originY + 0.03, lz)
    * CFrame.Angles(0, math.random() * math.pi * 2, 0)
  leaf.Color = Color3.fromRGB(table.unpack(col))
  leaf.Material = Enum.Material.LeafyGrass
  leaf.Anchored = true
  leaf.CastShadow = false
  leaf.CanCollide = false
  leaf.Parent = tree
end
` : ''}

tree.PrimaryPart = tree:FindFirstChildOfClass("Part")
ChangeHistoryService:SetWaypoint("Built_Tree")
print("[Tree] ${ttype} (${season}, ${tsize}) built.")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 14. PROFESSIONAL INTERIOR
// ─────────────────────────────────────────────────────────────────────────────

export interface InteriorParams {
  type: 'living_room' | 'kitchen' | 'bedroom' | 'office' | 'shop_floor' | 'restaurant'
  width: number
  depth: number
  withFurniture: boolean
  withLighting: boolean
}

export function professionalInterior(params: InteriorParams): string {
  const itype = params.type
  const width = Math.max(10, Math.min(60, params.width))
  const depth = Math.max(10, Math.min(60, params.depth))

  const floorMat =
    itype === 'restaurant' ? 'Enum.Material.Marble' :
    itype === 'shop_floor' ? 'Enum.Material.SmoothPlastic' :
    itype === 'office'     ? 'Enum.Material.SmoothPlastic' :
    'Enum.Material.WoodPlanks'

  const floorColorR =
    itype === 'restaurant' ? '205, 200, 195' :
    itype === 'shop_floor' ? '235, 235, 235' :
    itype === 'office'     ? '220, 215, 210' :
    '175, 148, 108'

  const wallColorR = '240, 238, 232'
  const trimColorR = '80, 70, 60'
  const ceilColorR = '248, 248, 248'

  const wallHeight = 5.0
  const wallThick = 0.4

  return `-- Professional Interior: ${itype} (${width}x${depth} studs)
-- Place this Model at the correct position. All parts are anchored.
local ChangeHistoryService = game:GetService("ChangeHistoryService")
ChangeHistoryService:SetWaypoint("Before_Interior")

local room = Instance.new("Model")
room.Name = "Interior_${itype}"
room.Parent = workspace

local W = ${width}
local D = ${depth}
local WH = ${wallHeight}
local WT = ${wallThick}
local ox, oy, oz = 0, 0, 0  -- set origin to match your building floor Y

local function part(parent, nm, size, pos, color, mat)
  local p = Instance.new("Part")
  p.Name = nm
  p.Size = size
  p.CFrame = CFrame.new(pos)
  p.Color = Color3.fromRGB(table.unpack(color))
  p.Material = mat
  p.Anchored = true
  p.TopSurface = Enum.SurfaceType.Smooth
  p.BottomSurface = Enum.SurfaceType.Smooth
  p.Parent = parent
  return p
end

-- ── Floor ────────────────────────────────────────────────────────────────────
part(room, "Floor",
  Vector3.new(W, 0.2, D),
  Vector3.new(ox, oy + 0.1, oz),
  {${floorColorR}}, ${floorMat})

-- ── Ceiling ───────────────────────────────────────────────────────────────────
part(room, "Ceiling",
  Vector3.new(W, 0.2, D),
  Vector3.new(ox, oy + WH + 0.1, oz),
  {${ceilColorR}}, Enum.Material.SmoothPlastic)

-- ── Walls ─────────────────────────────────────────────────────────────────────
part(room, "WallFront", Vector3.new(W, WH, WT), Vector3.new(ox, oy + WH/2, oz + D/2), {${wallColorR}}, Enum.Material.SmoothPlastic)
part(room, "WallBack",  Vector3.new(W, WH, WT), Vector3.new(ox, oy + WH/2, oz - D/2), {${wallColorR}}, Enum.Material.SmoothPlastic)
part(room, "WallLeft",  Vector3.new(WT, WH, D), Vector3.new(ox - W/2, oy + WH/2, oz), {${wallColorR}}, Enum.Material.SmoothPlastic)
part(room, "WallRight", Vector3.new(WT, WH, D), Vector3.new(ox + W/2, oy + WH/2, oz), {${wallColorR}}, Enum.Material.SmoothPlastic)

-- ── Baseboard trim ────────────────────────────────────────────────────────────
local baseboards = {
  {Vector3.new(W, 0.3, 0.12), Vector3.new(ox, oy + 0.25, oz + D/2 - WT/2 - 0.06)},
  {Vector3.new(W, 0.3, 0.12), Vector3.new(ox, oy + 0.25, oz - D/2 + WT/2 + 0.06)},
  {Vector3.new(0.12, 0.3, D), Vector3.new(ox - W/2 + WT/2 + 0.06, oy + 0.25, oz)},
  {Vector3.new(0.12, 0.3, D), Vector3.new(ox + W/2 - WT/2 - 0.06, oy + 0.25, oz)},
}
for bi, bb in ipairs(baseboards) do
  part(room, "Baseboard_"..bi, bb[1], bb[2], {${trimColorR}}, Enum.Material.SmoothPlastic)
end

-- ── Crown molding ─────────────────────────────────────────────────────────────
local moldings = {
  {Vector3.new(W + WT*2, 0.25, 0.14), Vector3.new(ox, oy + WH - 0.12, oz + D/2)},
  {Vector3.new(W + WT*2, 0.25, 0.14), Vector3.new(ox, oy + WH - 0.12, oz - D/2)},
  {Vector3.new(0.14, 0.25, D), Vector3.new(ox - W/2, oy + WH - 0.12, oz)},
  {Vector3.new(0.14, 0.25, D), Vector3.new(ox + W/2, oy + WH - 0.12, oz)},
}
for mi, mm in ipairs(moldings) do
  part(room, "CrownMolding_"..mi, mm[1], mm[2], {${trimColorR}}, Enum.Material.SmoothPlastic)
end

${params.withLighting ? `
-- ── Ceiling lights ────────────────────────────────────────────────────────────
local lightType = "${itype}"
local isRestaurant = lightType == "restaurant"
local isOffice = lightType == "office"
local lightRows = isOffice and 2 or 1
local lightCols = math.max(1, math.floor(W / 6))
local lSpacingX = (W - 4) / math.max(1, lightCols - 1)
local lSpacingZ = isOffice and (D - 4) / (lightRows - 1 + 0.001) or 0

for row = 1, lightRows do
  for col = 1, lightCols do
    local lx = ox - (W/2 - 2) + (col - 1) * lSpacingX
    local lz = isOffice and (oz - (D/2 - 2) + (row - 1) * lSpacingZ) or oz
    local ly = oy + WH - 0.2

    if isRestaurant then
      -- Hanging pendant lamp
      local cord = part(room, "Cord_"..row.."_"..col,
        Vector3.new(0.08, 1.2, 0.08),
        Vector3.new(lx, ly - 0.6, lz),
        {50, 50, 50}, Enum.Material.SmoothPlastic)
      local shade = part(room, "Shade_"..row.."_"..col,
        Vector3.new(0.9, 0.5, 0.9),
        Vector3.new(lx, ly - 1.45, lz),
        {30, 30, 30}, Enum.Material.Metal)
      local bulb = part(room, "PendantBulb_"..row.."_"..col,
        Vector3.new(0.35, 0.35, 0.35),
        Vector3.new(lx, ly - 1.6, lz),
        {255, 240, 200}, Enum.Material.Neon)
      bulb.Shape = Enum.PartType.Ball
      local pl = Instance.new("PointLight")
      pl.Brightness = 3; pl.Range = math.max(W, D) * 0.6
      pl.Color = Color3.fromRGB(255, 235, 190)
      pl.Parent = bulb
    else
      -- Recessed flush light
      local fixture = part(room, "CeilingFixture_"..row.."_"..col,
        Vector3.new(0.8, 0.12, 0.8),
        Vector3.new(lx, ly, lz),
        {255, 248, 230}, Enum.Material.Neon)
      local pl = Instance.new("PointLight")
      pl.Brightness = isOffice and 4 or 3
      pl.Range = math.max(W, D) * 0.7
      pl.Color = Color3.fromRGB(255, 248, 230)
      pl.Parent = fixture
    end
  end
end
` : '-- withLighting = false'}

${params.withFurniture ? `
-- ── Furniture ─────────────────────────────────────────────────────────────────
local roomType = "${itype}"

if roomType == "living_room" then
  -- Sofa (3-seater)
  part(room, "SofaBase",    Vector3.new(6, 1.0, 2.2), Vector3.new(ox, oy + 0.5, oz + D/2 - 3), {80, 70, 65}, Enum.Material.Fabric)
  part(room, "SofaBack",    Vector3.new(6, 1.5, 0.5), Vector3.new(ox, oy + 1.25, oz + D/2 - 1.85), {75, 65, 60}, Enum.Material.Fabric)
  part(room, "SofaArmLeft", Vector3.new(0.5, 1.2, 2.2), Vector3.new(ox - 3.25, oy + 0.8, oz + D/2 - 3), {75, 65, 60}, Enum.Material.Fabric)
  part(room, "SofaArmRight",Vector3.new(0.5, 1.2, 2.2), Vector3.new(ox + 3.25, oy + 0.8, oz + D/2 - 3), {75, 65, 60}, Enum.Material.Fabric)
  -- Coffee table
  part(room, "CoffeeTable", Vector3.new(3, 0.15, 1.6), Vector3.new(ox, oy + 1.0, oz + D/2 - 5.5), {120, 90, 60}, Enum.Material.WoodPlanks)
  part(room, "CoffeeTableLeg1", Vector3.new(0.2, 1.0, 0.2), Vector3.new(ox - 1.3, oy + 0.5, oz + D/2 - 6.2), {100, 75, 50}, Enum.Material.Wood)
  part(room, "CoffeeTableLeg2", Vector3.new(0.2, 1.0, 0.2), Vector3.new(ox + 1.3, oy + 0.5, oz + D/2 - 6.2), {100, 75, 50}, Enum.Material.Wood)
  part(room, "CoffeeTableLeg3", Vector3.new(0.2, 1.0, 0.2), Vector3.new(ox - 1.3, oy + 0.5, oz + D/2 - 4.8), {100, 75, 50}, Enum.Material.Wood)
  part(room, "CoffeeTableLeg4", Vector3.new(0.2, 1.0, 0.2), Vector3.new(ox + 1.3, oy + 0.5, oz + D/2 - 4.8), {100, 75, 50}, Enum.Material.Wood)

elseif roomType == "office" then
  -- Desk cluster (2 desks)
  for di = 0, 1 do
    local dx = ox - 2.5 + di * 5
    part(room, "Desk_"..di, Vector3.new(4, 0.15, 2), Vector3.new(dx, oy + 2.0, oz), {200, 195, 185}, Enum.Material.SmoothPlastic)
    part(room, "DeskLeg1_"..di, Vector3.new(0.2, 2.0, 0.2), Vector3.new(dx - 1.8, oy + 1.0, oz - 0.8), {80, 80, 85}, Enum.Material.Metal)
    part(room, "DeskLeg2_"..di, Vector3.new(0.2, 2.0, 0.2), Vector3.new(dx + 1.8, oy + 1.0, oz - 0.8), {80, 80, 85}, Enum.Material.Metal)
    part(room, "DeskLeg3_"..di, Vector3.new(0.2, 2.0, 0.2), Vector3.new(dx - 1.8, oy + 1.0, oz + 0.8), {80, 80, 85}, Enum.Material.Metal)
    part(room, "DeskLeg4_"..di, Vector3.new(0.2, 2.0, 0.2), Vector3.new(dx + 1.8, oy + 1.0, oz + 0.8), {80, 80, 85}, Enum.Material.Metal)
    -- Monitor
    part(room, "MonitorScreen_"..di, Vector3.new(2.2, 1.4, 0.12), Vector3.new(dx, oy + 3.0, oz - 0.5), {20, 20, 22}, Enum.Material.SmoothPlastic)
    part(room, "MonitorStand_"..di, Vector3.new(0.25, 0.6, 0.3), Vector3.new(dx, oy + 2.45, oz - 0.5), {50, 50, 55}, Enum.Material.Metal)
  end

elseif roomType == "restaurant" then
  -- 4-top dining tables
  local tableCount = math.floor(W / 6) * math.floor(D / 6)
  local tPerRow = math.max(1, math.floor(W / 6))
  local rows = math.max(1, math.floor(D / 6))
  for ri = 1, rows do
    for ci = 1, tPerRow do
      local tx = ox - W/2 + 3 + (ci - 1) * 6
      local tz = oz - D/2 + 3 + (ri - 1) * 6
      -- Table top
      part(room, "Table_R"..ri.."C"..ci, Vector3.new(2.4, 0.15, 2.4), Vector3.new(tx, oy + 2.0, tz), {210, 205, 195}, Enum.Material.Marble)
      -- Table pedestal
      part(room, "Pedestal_R"..ri.."C"..ci, Vector3.new(0.4, 2.0, 0.4), Vector3.new(tx, oy + 1.0, tz), {80, 80, 85}, Enum.Material.Metal)
      -- 4 chairs
      local chairOffsets = {{1.5,0},{-1.5,0},{0,1.5},{0,-1.5}}
      for chi, co in ipairs(chairOffsets) do
        part(room, "ChairSeat_R"..ri.."C"..ci.."_"..chi,
          Vector3.new(1.0, 0.12, 1.0), Vector3.new(tx + co[1], oy + 1.3, tz + co[2]),
          {90, 75, 60}, Enum.Material.Fabric)
        part(room, "ChairBack_R"..ri.."C"..ci.."_"..chi,
          Vector3.new(1.0, 1.0, 0.12),
          Vector3.new(tx + co[1] * 1.0, oy + 1.85, tz + co[2] * 1.0),
          {90, 75, 60}, Enum.Material.Fabric)
      end
    end
  end

elseif roomType == "bedroom" then
  -- Bed frame
  part(room, "BedFrame",   Vector3.new(5, 0.5, 7),   Vector3.new(ox, oy + 0.45, oz), {120, 95, 70}, Enum.Material.WoodPlanks)
  part(room, "Mattress",   Vector3.new(4.6, 0.5, 6.4), Vector3.new(ox, oy + 0.95, oz), {240, 235, 230}, Enum.Material.Fabric)
  part(room, "Pillow1",    Vector3.new(1.8, 0.25, 1.0), Vector3.new(ox - 1.1, oy + 1.2, oz + 2.6), {255, 252, 245}, Enum.Material.Fabric)
  part(room, "Pillow2",    Vector3.new(1.8, 0.25, 1.0), Vector3.new(ox + 1.1, oy + 1.2, oz + 2.6), {255, 252, 245}, Enum.Material.Fabric)
  part(room, "Headboard",  Vector3.new(5.2, 2.0, 0.4), Vector3.new(ox, oy + 1.4, oz + 3.7), {110, 85, 60}, Enum.Material.WoodPlanks)
  -- Bedside tables
  part(room, "Nightstand1", Vector3.new(1.4, 1.8, 1.4), Vector3.new(ox - 3.3, oy + 0.9, oz + 2.5), {120, 95, 70}, Enum.Material.WoodPlanks)
  part(room, "Nightstand2", Vector3.new(1.4, 1.8, 1.4), Vector3.new(ox + 3.3, oy + 0.9, oz + 2.5), {120, 95, 70}, Enum.Material.WoodPlanks)

elseif roomType == "shop_floor" then
  -- Display shelving units along walls
  local shelfCount = math.max(2, math.floor(W / 5))
  for si = 1, shelfCount do
    local sx = ox - W/2 + 2 + (si - 1) * ((W - 4) / math.max(1, shelfCount - 1))
    -- Shelf unit back panel
    part(room, "ShelfBack_"..si, Vector3.new(3, 4.5, 0.3), Vector3.new(sx, oy + 2.5, oz - D/2 + 0.5), {210, 208, 205}, Enum.Material.SmoothPlastic)
    -- 3 shelves
    for shi = 1, 3 do
      part(room, "Shelf_"..si.."_"..shi, Vector3.new(3, 0.15, 1.0), Vector3.new(sx, oy + shi * 1.4, oz - D/2 + 0.9), {200, 198, 192}, Enum.Material.SmoothPlastic)
    end
  end
  -- Central display island
  part(room, "DisplayIsland",    Vector3.new(4, 1.2, 2), Vector3.new(ox, oy + 0.6, oz), {215, 210, 205}, Enum.Material.SmoothPlastic)
  part(room, "IslandGlassTop",   Vector3.new(4, 0.12, 2), Vector3.new(ox, oy + 1.3, oz), {200, 220, 240}, Enum.Material.Glass)
  local glassPart = room:FindFirstChild("IslandGlassTop")
  if glassPart then glassPart.Transparency = 0.3 end
end
` : '-- withFurniture = false'}

room.PrimaryPart = room:FindFirstChildOfClass("Part")
ChangeHistoryService:SetWaypoint("Built_Interior")
print("[Interior] ${itype} (${width}x${depth}) built.")`
}

// ─────────────────────────────────────────────────────────────────────────────
// 15. WEATHERING EFFECT
// ─────────────────────────────────────────────────────────────────────────────

export interface WeatheringParams {
  targetModelName: string
  type: 'water_staining' | 'rust' | 'moss' | 'age_darkening' | 'dust'
}

export function weatheringEffect(params: WeatheringParams): string {
  const modelName = safe(params.targetModelName)
  const wtype = params.type

  // Per-type color tweak logic as inline Luau
  const colorLogic =
    wtype === 'water_staining' ?
`  -- Water staining: darken toward base, add grey-blue tint
  local t = 1 - math.clamp((p.Position.Y - baseY) / totalHeight, 0, 1)
  local stainStrength = t * 0.45
  local r = math.clamp(c.R - stainStrength * 0.25, 0, 1)
  local g = math.clamp(c.G - stainStrength * 0.15, 0, 1)
  local b = math.clamp(c.B - stainStrength * 0.05 + stainStrength * 0.08, 0, 1)
  p.Color = Color3.new(r, g, b)` :
    wtype === 'rust' ?
`  -- Rust: shift toward brown/orange, stronger on metal parts
  local isMetal = p.Material == Enum.Material.Metal or p.Material == Enum.Material.CorrodedMetal
  local strength = isMetal and 0.6 or 0.25
  local r = math.clamp(c.R * (1 - strength) + 0.72 * strength, 0, 1)
  local g = math.clamp(c.G * (1 - strength) + 0.28 * strength, 0, 1)
  local b = math.clamp(c.B * (1 - strength) + 0.08 * strength, 0, 1)
  p.Color = Color3.new(r, g, b)
  if isMetal then p.Material = Enum.Material.CorrodedMetal end` :
    wtype === 'moss' ?
`  -- Moss: green tint, stronger on top surfaces and lower sections
  local t = 1 - math.clamp((p.Position.Y - baseY) / totalHeight, 0, 1)
  local mossStrength = math.clamp(t * 0.5, 0, 0.55)
  local r = math.clamp(c.R * (1 - mossStrength) + 0.25 * mossStrength, 0, 1)
  local g = math.clamp(c.G * (1 - mossStrength) + 0.45 * mossStrength, 0, 1)
  local b = math.clamp(c.B * (1 - mossStrength) + 0.18 * mossStrength, 0, 1)
  p.Color = Color3.new(r, g, b)` :
    wtype === 'age_darkening' ?
`  -- Age darkening: uniformly darken + desaturate
  local factor = 0.72
  local grey = (c.R + c.G + c.B) / 3
  local r = math.clamp(c.R * factor + grey * 0.05, 0, 1)
  local g = math.clamp(c.G * factor + grey * 0.05, 0, 1)
  local b = math.clamp(c.B * factor + grey * 0.05, 0, 1)
  p.Color = Color3.new(r, g, b)` :
`  -- Dust: shift color toward warm grey, lighter on top
  local t = math.clamp((p.Position.Y - baseY) / totalHeight, 0, 1)
  local dustStrength = t * 0.35 + 0.1
  local dustR, dustG, dustB = 0.82, 0.78, 0.72
  local r = math.clamp(c.R * (1 - dustStrength) + dustR * dustStrength, 0, 1)
  local g = math.clamp(c.G * (1 - dustStrength) + dustG * dustStrength, 0, 1)
  local b = math.clamp(c.B * (1 - dustStrength) + dustB * dustStrength, 0, 1)
  p.Color = Color3.new(r, g, b)`

  return `-- Weathering Effect: ${wtype} → applied to model "${modelName}"
-- Run this in the Command Bar. It modifies part Colors in-place.
-- TIP: Run on a duplicate of your model to preserve the original.
local ChangeHistoryService = game:GetService("ChangeHistoryService")
ChangeHistoryService:SetWaypoint("Before_Weathering_${modelName}")

local model = workspace:FindFirstChild("${modelName}", true)
if not model then
  warn("[Weathering] Model '${modelName}' not found in workspace.")
  return
end

-- Compute vertical bounds for gradient-based effects
local minY, maxY = math.huge, -math.huge
for _, p in ipairs(model:GetDescendants()) do
  if p:IsA("BasePart") then
    minY = math.min(minY, p.Position.Y)
    maxY = math.max(maxY, p.Position.Y)
  end
end
local baseY = minY
local totalHeight = math.max(1, maxY - minY)

local partsModified = 0

for _, p in ipairs(model:GetDescendants()) do
  if p:IsA("BasePart") then
    -- Skip Neon, Glass, and very small detail parts (avoid ruining lights/windows)
    if p.Material == Enum.Material.Neon then continue end
    if p.Material == Enum.Material.Glass then continue end
    if p.Size.Magnitude < 0.4 then continue end

    local c = p.Color
${colorLogic}
    partsModified += 1
  end
end

ChangeHistoryService:SetWaypoint("Applied_Weathering_${modelName}")
print("[Weathering] ${wtype} applied to '" .. model.Name .. "' — " .. partsModified .. " parts modified.")`
}

// ─────────────────────────────────────────────────────────────────────────────
// Template registry — maps task template names to generator functions
// ─────────────────────────────────────────────────────────────────────────────

export type TemplateName =
  | 'economy_system'
  | 'tycoon_dropper'
  | 'npc_dialog'
  | 'leaderboard'
  | 'basic_combat'
  | 'inventory'
  | 'day_night_cycle'
  | 'spawn_system'
  | 'obby_checkpoints'
  | 'pet_follow'
  | 'professional_building'
  | 'street_lamp'
  | 'detailed_tree'
  | 'professional_interior'
  | 'weathering_effect'

export interface TemplateRegistry {
  economy_system: (p: EconomySystemParams) => string
  tycoon_dropper: (p: TycoonDropperParams) => string
  npc_dialog: (p: NpcDialogParams) => string
  leaderboard: (p: LeaderboardParams) => string
  basic_combat: (p: CombatParams) => string
  inventory: (p: InventoryParams) => string
  day_night_cycle: (p: DayNightCycleParams) => string
  spawn_system: (p: SpawnSystemParams) => string
  obby_checkpoints: (p: ObbyCheckpointParams) => string
  pet_follow: (p: PetFollowParams) => string
  professional_building: (p: ProBuildingParams) => string
  street_lamp: (p: StreetLampParams) => string
  detailed_tree: (p: TreeParams) => string
  professional_interior: (p: InteriorParams) => string
  weathering_effect: (p: WeatheringParams) => string
}

export const TEMPLATE_REGISTRY: TemplateRegistry = {
  economy_system: economySystem,
  tycoon_dropper: tycoonDropper,
  npc_dialog: npcDialogSystem,
  leaderboard: leaderboardProgression,
  basic_combat: basicCombat,
  inventory: inventorySystem,
  day_night_cycle: dayNightCycle,
  spawn_system: spawnSystem,
  obby_checkpoints: obbyCheckpoints,
  pet_follow: petFollowSystem,
  professional_building: professionalBuilding,
  street_lamp: detailedStreetLamp,
  detailed_tree: detailedTree,
  professional_interior: professionalInterior,
  weathering_effect: weatheringEffect,
}
