// AUTO-GENERATED by Knowledge Crawler — 2026-04-29
// Source: Roblox Creator Hub (parts, models, CFrames, materials, meshes, textures, constraints)

export const BUILDING_PARTS_CFRAME = `
=== ROBLOX PARTS & CFRAME MASTER REFERENCE ===

--- PART TYPES ---
Block          — default rectangular prism
Sphere         — perfect sphere
Cylinder       — round cylinder
Wedge          — right-angle wedge
CornerWedge    — corner wedge piece
TrussPart      — truss/scaffolding piece
UnionOperation — CSG union of multiple parts
IntersectOperation — CSG intersection
NegateOperation — CSG negation (subtract)
MeshPart       — imported 3D mesh from Blender/Maya

--- PART PROPERTIES (BasePart) ---
Size              Vector3    — dimensions in studs (X, Y, Z)
Position          Vector3    — world position center
CFrame            CFrame     — position + orientation combined
Rotation          Vector3    — Euler angles in degrees (read/write shortcut)
Material          Enum.Material — surface material (see full list below)
Color             Color3     — RGB color (use Color3.fromRGB or Color3.fromHSV)
BrickColor        BrickColor — legacy color system (prefer Color3)
Transparency      number     — 0 = opaque, 1 = invisible
Reflectance       number     — 0 to 1, mirror-like sheen
Anchored          bool       — if true, not moved by physics
CanCollide        bool       — if false, other parts pass through
CanTouch          bool       — enables Touched/TouchEnded events
CanQuery          bool       — included in spatial queries
Massless          bool       — zero mass when welded to assembly
CastShadow        bool       — whether part casts shadows
Shape             Enum.PartType — Block/Ball/Cylinder
TopSurface        Enum.SurfaceType — surface joint type
BottomSurface     Enum.SurfaceType — surface joint type

--- CREATING PARTS IN LUAU ---
-- Basic part creation
local part = Instance.new("Part")
part.Size = Vector3.new(4, 1, 4)
part.Position = Vector3.new(0, 5, 0)
part.Anchored = true
part.Material = Enum.Material.Concrete
part.Color = Color3.fromRGB(120, 100, 80)
part.Parent = workspace

-- Sphere
local sphere = Instance.new("Part")
sphere.Shape = Enum.PartType.Ball
sphere.Size = Vector3.new(4, 4, 4)
sphere.Material = Enum.Material.SmoothPlastic
sphere.Parent = workspace

-- Cylinder
local cyl = Instance.new("Part")
cyl.Shape = Enum.PartType.Cylinder
cyl.Size = Vector3.new(8, 2, 2)  -- X = length, Y&Z = diameter
cyl.Parent = workspace

-- Wedge
local wedge = Instance.new("WedgePart")
wedge.Size = Vector3.new(4, 4, 4)
wedge.Parent = workspace

-- CornerWedge
local corner = Instance.new("CornerWedgePart")
corner.Size = Vector3.new(4, 4, 4)
corner.Parent = workspace

--- ALL MATERIAL ENUM VALUES (Enum.Material.*) ---

-- Metals & Industrial
Metal              -- shiny metallic
DiamondPlate       -- diamond-pattern metal
CorrodedMetal      -- rusty weathered metal
Foil               -- reflective foil

-- Stone & Rock
Brick              -- brick pattern
Concrete           -- smooth concrete
Basalt             -- dark volcanic rock
Granite            -- speckled granite
Slate              -- flat dark stone
Marble             -- veined marble
Limestone          -- light beige stone
Sandstone          -- warm sandy stone
Pavement           -- flat urban pavement
Cobblestone        -- rounded cobble
Rock               -- generic rough rock
Pebble             -- small rounded pebbles
CrackedLava        -- volcanic cracked lava

-- Natural
Grass              -- standard grass (green)
LeafyGrass         -- detailed leaf-textured grass
Ground             -- bare dirt ground
Mud                -- wet mud
Sand               -- sandy surface
Snow               -- white snow surface
Ice                -- slick blue-white ice
Glacier            -- blue glacier ice
Salt               -- white mineral salt flat
Asphalt            -- dark road surface

-- Organic & Textiles
Wood               -- rough wood grain
WoodPlanks         -- plank-style wood boards
Leather            -- leather texture
Fabric             -- soft fabric/cloth
Carpet             -- carpet texture

-- Specialty
Plastic            -- matte plastic
SmoothPlastic      -- smooth matte plastic (AVOID — prefer others)
Glass              -- transparent glass (set Transparency 0.3-0.6)
Neon               -- glowing emissive (ignores lighting)
ForceField         -- sci-fi forcefield shimmer

-- Newer Additions
Cardboard          -- corrugated cardboard
Plaster            -- white wall plaster
CeramicTiles       -- glossy tile
ClayRoofTiles      -- terracotta roof tiles
Rubber             -- matte rubber
RoofShingles       -- dark roof shingles

-- Apply material
part.Material = Enum.Material.WoodPlanks
part.Material = Enum.Material.Neon  -- makes part glow

--- CFRAME MATH PATTERNS ---

-- 1. Absolute position
part.CFrame = CFrame.new(10, 5, -20)
part.CFrame = CFrame.new(Vector3.new(10, 5, -20))

-- 2. Position + Euler rotation (radians)
part.CFrame = CFrame.new(0, 10, 0) * CFrame.Angles(0, math.rad(45), 0)

-- 3. fromEulerAnglesXYZ (same as Angles)
part.CFrame = CFrame.new(0, 5, 0) * CFrame.fromEulerAnglesXYZ(math.rad(30), 0, 0)

-- 4. lookAt — point object toward a target
part.CFrame = CFrame.lookAt(part.Position, targetPosition)
part.CFrame = CFrame.lookAt(Vector3.new(0,5,0), Vector3.new(10,5,0))

-- 5. Offset by world Vector3
part.CFrame = CFrame.new(basePart.Position) + Vector3.new(0, 5, 0)

-- 6. Offset relative to another object's CFrame (preserves orientation)
local offsetCF = CFrame.new(0, 2, -3)  -- 2 up, 3 behind
part.CFrame = basePart.CFrame:ToWorldSpace(offsetCF)

-- 7. Rotate relative to self
local rotateCF = CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
part.CFrame = part.CFrame:ToWorldSpace(rotateCF)

-- 8. Lerp between two positions (t=0 to 1)
part.CFrame = startCF:Lerp(endCF, 0.5)  -- halfway between

-- 9. Build a grid of parts
local COLS, ROWS = 5, 5
local SIZE = Vector3.new(4, 1, 4)
local GAP = 0.1
for row = 0, ROWS - 1 do
  for col = 0, COLS - 1 do
    local p = Instance.new("Part")
    p.Size = SIZE
    p.Anchored = true
    p.CFrame = CFrame.new(
      col * (SIZE.X + GAP),
      0,
      row * (SIZE.Z + GAP)
    )
    p.Parent = workspace
  end
end

-- 10. Stack parts vertically
local parts = {}
local BASE_Y = 0
local heights = {2, 1.5, 3, 1}
local currentY = BASE_Y
for i, h in ipairs(heights) do
  local p = Instance.new("Part")
  p.Size = Vector3.new(4, h, 4)
  p.Anchored = true
  currentY = currentY + h / 2
  p.CFrame = CFrame.new(0, currentY, 0)
  currentY = currentY + h / 2
  p.Parent = workspace
  parts[i] = p
end

-- 11. Circle/ring arrangement
local COUNT = 8
local RADIUS = 10
for i = 1, COUNT do
  local angle = (i - 1) / COUNT * math.pi * 2
  local p = Instance.new("Part")
  p.Anchored = true
  p.CFrame = CFrame.new(
    math.cos(angle) * RADIUS,
    0,
    math.sin(angle) * RADIUS
  ) * CFrame.Angles(0, -angle, 0)
  p.Parent = workspace
end

-- 12. Relative offset helper function
local function placeRelative(anchor: BasePart, offsetX: number, offsetY: number, offsetZ: number): CFrame
  return anchor.CFrame:ToWorldSpace(CFrame.new(offsetX, offsetY, offsetZ))
end

-- 13. Get CFrame components
local pos: Vector3 = part.CFrame.Position
local lookVec: Vector3 = part.CFrame.LookVector     -- forward (-Z)
local rightVec: Vector3 = part.CFrame.RightVector    -- right (+X)
local upVec: Vector3 = part.CFrame.UpVector          -- up (+Y)

-- 14. CFrame arithmetic
local cf1 = CFrame.new(0, 5, 0)
local cf2 = CFrame.Angles(0, math.rad(45), 0)
local combined = cf1 * cf2  -- position then rotate

--- MODELS & GROUPING ---

-- Create a model programmatically
local model = Instance.new("Model")
model.Name = "MyHouse"
model.Parent = workspace

local primaryPart = Instance.new("Part")
primaryPart.Name = "Root"
primaryPart.Size = Vector3.new(0.1, 0.1, 0.1)
primaryPart.Transparency = 1
primaryPart.Anchored = true
primaryPart.CanCollide = false
primaryPart.Parent = model
model.PrimaryPart = primaryPart

-- Move entire model
model:PivotTo(CFrame.new(50, 0, 50))

-- Move model preserving orientation
model:MoveTo(Vector3.new(100, 0, 100))

-- Shift model by offset
model:TranslateBy(Vector3.new(5, 0, 0))

-- Get bounding box
local cf, size = model:GetBoundingBox()

-- Destroy model
model:Destroy()

--- MESHPART & SPECIAL MESHES ---

-- MeshPart (imported asset)
local mesh = Instance.new("MeshPart")
mesh.MeshId = "rbxassetid://12345678"
mesh.TextureID = "rbxassetid://87654321"
mesh.Size = Vector3.new(5, 5, 5)
mesh.Anchored = true
mesh.Material = Enum.Material.SmoothPlastic

-- RenderFidelity (detail level)
mesh.RenderFidelity = Enum.RenderFidelity.Automatic  -- default
mesh.RenderFidelity = Enum.RenderFidelity.Precise    -- always full detail
mesh.RenderFidelity = Enum.RenderFidelity.Performance -- always low LOD

-- CollisionFidelity
mesh.CollisionFidelity = Enum.CollisionFidelity.Box   -- cheapest
mesh.CollisionFidelity = Enum.CollisionFidelity.Hull  -- convex hull
mesh.CollisionFidelity = Enum.CollisionFidelity.Default
mesh.CollisionFidelity = Enum.CollisionFidelity.PreciseConvexDecomposition

mesh.Parent = workspace

-- SpecialMesh (legacy, still used)
local specialMesh = Instance.new("SpecialMesh")
specialMesh.MeshType = Enum.MeshType.FileMesh
specialMesh.MeshId = "rbxassetid://12345678"
specialMesh.TextureId = "rbxassetid://87654321"
specialMesh.Scale = Vector3.new(1, 1, 1)
specialMesh.Offset = Vector3.new(0, 0, 0)
specialMesh.Parent = part

-- SpecialMesh types
-- Enum.MeshType.FileMesh      — custom uploaded mesh
-- Enum.MeshType.Sphere        — perfect sphere
-- Enum.MeshType.Cylinder      — cylinder
-- Enum.MeshType.Wedge         — wedge
-- Enum.MeshType.Brick         — brick (same as Block Part)
-- Enum.MeshType.Head          — Roblox avatar head shape
-- Enum.MeshType.Torso         — torso shape

--- SurfaceAppearance (PBR Textures) ---
local sa = Instance.new("SurfaceAppearance")
sa.ColorMapContent = "rbxassetid://COLOR_ID"
sa.MetalnessMapContent = "rbxassetid://METAL_ID"
sa.RoughnessMapContent = "rbxassetid://ROUGH_ID"
sa.NormalMapContent = "rbxassetid://NORMAL_ID"
sa.Parent = mesh

--- TEXTURES & DECALS ---

-- Texture (tiles/repeats)
local texture = Instance.new("Texture")
texture.Texture = "rbxassetid://12345678"
texture.Face = Enum.NormalId.Top      -- Top/Bottom/Front/Back/Left/Right
texture.StudsPerTileU = 4             -- horizontal tile size in studs
texture.StudsPerTileV = 4             -- vertical tile size in studs
texture.Color3 = Color3.new(1, 1, 1)  -- tint
texture.Transparency = 0
texture.Parent = part

-- Decal (stretches to fit face)
local decal = Instance.new("Decal")
decal.Texture = "rbxassetid://12345678"
decal.Face = Enum.NormalId.Front
decal.Color3 = Color3.fromRGB(255, 255, 255)
decal.Transparency = 0
decal.Parent = part

-- Animated texture (sliding)
local TweenService = game:GetService("TweenService")
local tw = TweenService:Create(texture, TweenInfo.new(8, Enum.EasingStyle.Sine,
  Enum.EasingDirection.InOut, -1), {OffsetStudsV = 50})
tw:Play()

--- CONSTRAINTS ---

-- WeldConstraint (most common — locks two parts together)
local weld = Instance.new("WeldConstraint")
weld.Part0 = partA
weld.Part1 = partB
weld.Parent = partA

-- HingeConstraint (door hinge, wheel)
local att0 = Instance.new("Attachment", partA)
local att1 = Instance.new("Attachment", partB)
local hinge = Instance.new("HingeConstraint")
hinge.Attachment0 = att0
hinge.Attachment1 = att1
hinge.Parent = partA

-- Motor (powered hinge)
hinge.ActuatorType = Enum.ActuatorType.Motor
hinge.AngularVelocity = 5   -- radians/s
hinge.MotorMaxTorque = 1000

-- Servo (target angle)
hinge.ActuatorType = Enum.ActuatorType.Servo
hinge.TargetAngle = 90
hinge.ServoMaxTorque = 1000

-- BallSocketConstraint (shoulder joint)
local ball = Instance.new("BallSocketConstraint")
ball.Attachment0 = att0
ball.Attachment1 = att1
ball.Parent = partA

-- PrismaticConstraint (sliding door)
local prism = Instance.new("PrismaticConstraint")
prism.Attachment0 = att0
prism.Attachment1 = att1
prism.ActuatorType = Enum.ActuatorType.Motor
prism.Velocity = 5         -- studs/s
prism.MotorMaxForce = 10000
prism.Parent = partA

-- SpringConstraint
local spring = Instance.new("SpringConstraint")
spring.Attachment0 = att0
spring.Attachment1 = att1
spring.Stiffness = 500
spring.Damping = 50
spring.Parent = partA

-- RopeConstraint (chain)
local rope = Instance.new("RopeConstraint")
rope.Attachment0 = att0
rope.Attachment1 = att1
rope.Length = 10
rope.Parent = partA

-- RodConstraint (fixed-length rod)
local rod = Instance.new("RodConstraint")
rod.Attachment0 = att0
rod.Attachment1 = att1
rod.Length = 5
rod.Parent = partA

-- NoCollisionConstraint (ghost parts)
local noCol = Instance.new("NoCollisionConstraint")
noCol.Part0 = partA
noCol.Part1 = partB
noCol.Parent = partA

--- MOVER CONSTRAINTS ---

-- AlignPosition (float object to goal)
local alignPos = Instance.new("AlignPosition")
alignPos.Attachment0 = att0
alignPos.Attachment1 = att1
alignPos.MaxForce = 10000
alignPos.MaxVelocity = 20
alignPos.Parent = partA

-- AlignOrientation
local alignOri = Instance.new("AlignOrientation")
alignOri.Attachment0 = att0
alignOri.Attachment1 = att1
alignOri.MaxTorque = 10000
alignOri.Parent = partA

-- LinearVelocity (constant movement)
local linVel = Instance.new("LinearVelocity")
linVel.Attachment0 = att0
linVel.VelocityConstraintMode = Enum.VelocityConstraintMode.Vector
linVel.MaxForce = 5000
linVel.PlaneVelocity = Vector2.new(0, 10)
linVel.Parent = partA

-- VectorForce (constant push)
local vecForce = Instance.new("VectorForce")
vecForce.Attachment0 = att0
vecForce.Force = Vector3.new(0, 200, 0)
vecForce.RelativeTo = Enum.ActuatorRelativeTo.World
vecForce.Parent = partA

--- USEFUL HELPER PATTERNS ---

-- Clone a part N times in a row
local function cloneRow(template: BasePart, count: number, spacing: number): {BasePart}
  local parts = {}
  for i = 0, count - 1 do
    local clone = template:Clone()
    clone.CFrame = template.CFrame + Vector3.new(i * spacing, 0, 0)
    clone.Parent = workspace
    parts[i + 1] = clone
  end
  return parts
end

-- Build a wall from bricks
local function buildWall(startPos: Vector3, width: number, height: number, brickSize: Vector3)
  local model = Instance.new("Model")
  model.Name = "Wall"
  model.Parent = workspace
  for row = 0, height - 1 do
    local offsetX = (row % 2 == 0) and 0 or brickSize.X / 2
    local colCount = math.floor(width / brickSize.X)
    for col = 0, colCount - 1 do
      local brick = Instance.new("Part")
      brick.Size = brickSize
      brick.Anchored = true
      brick.Material = Enum.Material.Brick
      brick.Color = Color3.fromRGB(180, 100, 60)
      brick.CFrame = CFrame.new(
        startPos.X + col * brickSize.X + offsetX,
        startPos.Y + row * brickSize.Y + brickSize.Y / 2,
        startPos.Z
      )
      brick.Parent = model
    end
  end
  return model
end

-- Color3 helpers
Color3.fromRGB(255, 255, 255)       -- white
Color3.fromRGB(0, 0, 0)             -- black
Color3.fromHSV(0.6, 0.8, 0.9)      -- blue-ish
Color3.new(1, 1, 1)                 -- normalized 0-1 range

-- BrickColor legacy
part.BrickColor = BrickColor.new("Bright Red")
part.BrickColor = BrickColor.new("Medium stone grey")
part.BrickColor = BrickColor.new("Reddish brown")

=== END BUILDING PARTS CFRAME REFERENCE ===
`;
