// AUTO-GENERATED by Knowledge Crawler — 2026-04-29
// Source: Roblox Creator Hub (parts, models, CFrames, materials, meshes, textures, constraints)

export const BUILDING_PARTS_CFRAME = `
=== ROBLOX PARTS & CFRAME MASTER REFERENCE ===

--- PART TYPES ---
Block          — default rectangular prism
Sphere         — perfect sphere
Cylinder       — round cylinder
Wedge          — right-angle wedge
CornerWedge    — corner wedge piece
TrussPart      — truss/scaffolding piece
UnionOperation — CSG union of multiple parts
IntersectOperation — CSG intersection
NegateOperation — CSG negation (subtract)
MeshPart       — imported 3D mesh from Blender/Maya

--- PART PROPERTIES (BasePart) ---
Size              Vector3    — dimensions in studs (X, Y, Z)
Position          Vector3    — world position center
CFrame            CFrame     — position + orientation combined
Rotation          Vector3    — Euler angles in degrees (read/write shortcut)
Material          Enum.Material — surface material (see full list below)
Color             Color3     — RGB color (use Color3.fromRGB or Color3.fromHSV)
BrickColor        BrickColor — legacy color system (prefer Color3)
Transparency      number     — 0 = opaque, 1 = invisible
Reflectance       number     — 0 to 1, mirror-like sheen
Anchored          bool       — if true, not moved by physics
CanCollide        bool       — if false, other parts pass through
CanTouch          bool       — enables Touched/TouchEnded events
CanQuery          bool       — included in spatial queries
Massless          bool       — zero mass when welded to assembly
CastShadow        bool       — whether part casts shadows
Shape             Enum.PartType — Block/Ball/Cylinder
TopSurface        Enum.SurfaceType — surface joint type
BottomSurface     Enum.SurfaceType — surface joint type

--- CREATING PARTS IN LUAU ---
-- Basic part creation
local part = Instance.new("Part")
part.Size = Vector3.new(4, 1, 4)
part.Position = Vector3.new(0, 5, 0)
part.Anchored = true
part.Material = Enum.Material.Concrete
part.Color = Color3.fromRGB(120, 100, 80)
part.Parent = workspace

-- Sphere
local sphere = Instance.new("Part")
sphere.Shape = Enum.PartType.Ball
sphere.Size = Vector3.new(4, 4, 4)
sphere.Material = Enum.Material.SmoothPlastic
sphere.Parent = workspace

-- Cylinder
local cyl = Instance.new("Part")
cyl.Shape = Enum.PartType.Cylinder
cyl.Size = Vector3.new(8, 2, 2)  -- X = length, Y&Z = diameter
cyl.Parent = workspace

-- Wedge
local wedge = Instance.new("WedgePart")
wedge.Size = Vector3.new(4, 4, 4)
wedge.Parent = workspace

-- CornerWedge
local corner = Instance.new("CornerWedgePart")
corner.Size = Vector3.new(4, 4, 4)
corner.Parent = workspace

--- ALL MATERIAL ENUM VALUES (Enum.Material.*) ---

-- Metals & Industrial
Metal              -- shiny metallic
DiamondPlate       -- diamond-pattern metal
CorrodedMetal      -- rusty weathered metal
Foil               -- reflective foil

-- Stone & Rock
Brick              -- brick pattern
Concrete           -- smooth concrete
Basalt             -- dark volcanic rock
Granite            -- speckled granite
Slate              -- flat dark stone
Marble             -- veined marble
Limestone          -- light beige stone
Sandstone          -- warm sandy stone
Pavement           -- flat urban pavement
Cobblestone        -- rounded cobble
Rock               -- generic rough rock
Pebble             -- small rounded pebbles
CrackedLava        -- volcanic cracked lava

-- Natural
Grass              -- standard grass (green)
LeafyGrass         -- detailed leaf-textured grass
Ground             -- bare dirt ground
Mud                -- wet mud
Sand               -- sandy surface
Snow               -- white snow surface
Ice                -- slick blue-white ice
Glacier            -- blue glacier ice
Salt               -- white mineral salt flat
Asphalt            -- dark road surface

-- Organic & Textiles
Wood               -- rough wood grain
WoodPlanks         -- plank-style wood boards
Leather            -- leather texture
Fabric             -- soft fabric/cloth
Carpet             -- carpet texture

-- Specialty
Plastic            -- matte plastic
SmoothPlastic      -- smooth matte plastic (AVOID — prefer others)
Glass              -- transparent glass (set Transparency 0.3-0.6)
Neon               -- glowing emissive (ignores lighting)
ForceField         -- sci-fi forcefield shimmer

-- Newer Additions
Cardboard          -- corrugated cardboard
Plaster            -- white wall plaster
CeramicTiles       -- glossy tile
ClayRoofTiles      -- terracotta roof tiles
Rubber             -- matte rubber
RoofShingles       -- dark roof shingles

-- Apply material
part.Material = Enum.Material.WoodPlanks
part.Material = Enum.Material.Neon  -- makes part glow

--- CFRAME MATH PATTERNS ---

-- 1. Absolute position
part.CFrame = CFrame.new(10, 5, -20)
part.CFrame = CFrame.new(Vector3.new(10, 5, -20))

-- 2. Position + Euler rotation (radians)
part.CFrame = CFrame.new(0, 10, 0) * CFrame.Angles(0, math.rad(45), 0)

-- 3. fromEulerAnglesXYZ (same as Angles)
part.CFrame = CFrame.new(0, 5, 0) * CFrame.fromEulerAnglesXYZ(math.rad(30), 0, 0)

-- 4. lookAt — point object toward a target
part.CFrame = CFrame.lookAt(part.Position, targetPosition)
part.CFrame = CFrame.lookAt(Vector3.new(0,5,0), Vector3.new(10,5,0))

-- 5. Offset by world Vector3
part.CFrame = CFrame.new(basePart.Position) + Vector3.new(0, 5, 0)

-- 6. Offset relative to another object's CFrame (preserves orientation)
local offsetCF = CFrame.new(0, 2, -3)  -- 2 up, 3 behind
part.CFrame = basePart.CFrame:ToWorldSpace(offsetCF)

-- 7. Rotate relative to self
local rotateCF = CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
part.CFrame = part.CFrame:ToWorldSpace(rotateCF)

-- 8. Lerp between two positions (t=0 to 1)
part.CFrame = startCF:Lerp(endCF, 0.5)  -- halfway between

-- 9. Build a grid of parts
local COLS, ROWS = 5, 5
local SIZE = Vector3.new(4, 1, 4)
local GAP = 0.1
for row = 0, ROWS - 1 do
  for col = 0, COLS - 1 do
    local p = Instance.new("Part")
    p.Size = SIZE
    p.Anchored = true
    p.CFrame = CFrame.new(
      col * (SIZE.X + GAP),
      0,
      row * (SIZE.Z + GAP)
    )
    p.Parent = workspace
  end
end

-- 10. Stack parts vertically
local parts = {}
local BASE_Y = 0
local heights = {2, 1.5, 3, 1}
local currentY = BASE_Y
for i, h in ipairs(heights) do
  local p = Instance.new("Part")
  p.Size = Vector3.new(4, h, 4)
  p.Anchored = true
  currentY = currentY + h / 2
  p.CFrame = CFrame.new(0, currentY, 0)
  currentY = currentY + h / 2
  p.Parent = workspace
  parts[i] = p
end

-- 11. Circle/ring arrangement
local COUNT = 8
local RADIUS = 10
for i = 1, COUNT do
  local angle = (i - 1) / COUNT * math.pi * 2
  local p = Instance.new("Part")
  p.Anchored = true
  p.CFrame = CFrame.new(
    math.cos(angle) * RADIUS,
    0,
    math.sin(angle) * RADIUS
  ) * CFrame.Angles(0, -angle, 0)
  p.Parent = workspace
end

-- 12. Relative offset helper function
local function placeRelative(anchor: BasePart, offsetX: number, offsetY: number, offsetZ: number): CFrame
  return anchor.CFrame:ToWorldSpace(CFrame.new(offsetX, offsetY, offsetZ))
end

-- 13. Get CFrame components
local pos: Vector3 = part.CFrame.Position
local lookVec: Vector3 = part.CFrame.LookVector     -- forward (-Z)
local rightVec: Vector3 = part.CFrame.RightVector    -- right (+X)
local upVec: Vector3 = part.CFrame.UpVector          -- up (+Y)

-- 14. CFrame arithmetic
local cf1 = CFrame.new(0, 5, 0)
local cf2 = CFrame.Angles(0, math.rad(45), 0)
local combined = cf1 * cf2  -- position then rotate

--- MODELS & GROUPING ---

-- Create a model programmatically
local model = Instance.new("Model")
model.Name = "MyHouse"
model.Parent = workspace

local primaryPart = Instance.new("Part")
primaryPart.Name = "Root"
primaryPart.Size = Vector3.new(0.1, 0.1, 0.1)
primaryPart.Transparency = 1
primaryPart.Anchored = true
primaryPart.CanCollide = false
primaryPart.Parent = model
model.PrimaryPart = primaryPart

-- Move entire model
model:PivotTo(CFrame.new(50, 0, 50))

-- Move model preserving orientation
model:MoveTo(Vector3.new(100, 0, 100))

-- Shift model by offset
model:TranslateBy(Vector3.new(5, 0, 0))

-- Get bounding box
local cf, size = model:GetBoundingBox()

-- Destroy model
model:Destroy()

--- MESHPART & SPECIAL MESHES ---

-- MeshPart (imported asset)
local mesh = Instance.new("MeshPart")
mesh.MeshId = "rbxassetid://12345678"
mesh.TextureID = "rbxassetid://87654321"
mesh.Size = Vector3.new(5, 5, 5)
mesh.Anchored = true
mesh.Material = Enum.Material.SmoothPlastic

-- RenderFidelity (detail level)
mesh.RenderFidelity = Enum.RenderFidelity.Automatic  -- default
mesh.RenderFidelity = Enum.RenderFidelity.Precise    -- always full detail
mesh.RenderFidelity = Enum.RenderFidelity.Performance -- always low LOD

-- CollisionFidelity
mesh.CollisionFidelity = Enum.CollisionFidelity.Box   -- cheapest
mesh.CollisionFidelity = Enum.CollisionFidelity.Hull  -- convex hull
mesh.CollisionFidelity = Enum.CollisionFidelity.Default
mesh.CollisionFidelity = Enum.CollisionFidelity.PreciseConvexDecomposition

mesh.Parent = workspace

-- SpecialMesh (legacy, still used)
local specialMesh = Instance.new("SpecialMesh")
specialMesh.MeshType = Enum.MeshType.FileMesh
specialMesh.MeshId = "rbxassetid://12345678"
specialMesh.TextureId = "rbxassetid://87654321"
specialMesh.Scale = Vector3.new(1, 1, 1)
specialMesh.Offset = Vector3.new(0, 0, 0)
specialMesh.Parent = part

-- SpecialMesh types
-- Enum.MeshType.FileMesh      — custom uploaded mesh
-- Enum.MeshType.Sphere        — perfect sphere
-- Enum.MeshType.Cylinder      — cylinder
-- Enum.MeshType.Wedge         — wedge
-- Enum.MeshType.Brick         — brick (same as Block Part)
-- Enum.MeshType.Head          — Roblox avatar head shape
-- Enum.MeshType.Torso         — torso shape

--- SurfaceAppearance (PBR Textures) ---
local sa = Instance.new("SurfaceAppearance")
sa.ColorMapContent = "rbxassetid://COLOR_ID"
sa.MetalnessMapContent = "rbxassetid://METAL_ID"
sa.RoughnessMapContent = "rbxassetid://ROUGH_ID"
sa.NormalMapContent = "rbxassetid://NORMAL_ID"
sa.Parent = mesh

--- TEXTURES & DECALS ---

-- Texture (tiles/repeats)
local texture = Instance.new("Texture")
texture.Texture = "rbxassetid://12345678"
texture.Face = Enum.NormalId.Top      -- Top/Bottom/Front/Back/Left/Right
texture.StudsPerTileU = 4             -- horizontal tile size in studs
texture.StudsPerTileV = 4             -- vertical tile size in studs
texture.Color3 = Color3.new(1, 1, 1)  -- tint
texture.Transparency = 0
texture.Parent = part

-- Decal (stretches to fit face)
local decal = Instance.new("Decal")
decal.Texture = "rbxassetid://12345678"
decal.Face = Enum.NormalId.Front
decal.Color3 = Color3.fromRGB(255, 255, 255)
decal.Transparency = 0
decal.Parent = part

-- Animated texture (sliding)
local TweenService = game:GetService("TweenService")
local tw = TweenService:Create(texture, TweenInfo.new(8, Enum.EasingStyle.Sine,
  Enum.EasingDirection.InOut, -1), {OffsetStudsV = 50})
tw:Play()

--- CONSTRAINTS ---

-- WeldConstraint (most common — locks two parts together)
local weld = Instance.new("WeldConstraint")
weld.Part0 = partA
weld.Part1 = partB
weld.Parent = partA

-- HingeConstraint (door hinge, wheel)
local att0 = Instance.new("Attachment", partA)
local att1 = Instance.new("Attachment", partB)
local hinge = Instance.new("HingeConstraint")
hinge.Attachment0 = att0
hinge.Attachment1 = att1
hinge.Parent = partA

-- Motor (powered hinge)
hinge.ActuatorType = Enum.ActuatorType.Motor
hinge.AngularVelocity = 5   -- radians/s
hinge.MotorMaxTorque = 1000

-- Servo (target angle)
hinge.ActuatorType = Enum.ActuatorType.Servo
hinge.TargetAngle = 90
hinge.ServoMaxTorque = 1000

-- BallSocketConstraint (shoulder joint)
local ball = Instance.new("BallSocketConstraint")
ball.Attachment0 = att0
ball.Attachment1 = att1
ball.Parent = partA

-- PrismaticConstraint (sliding door)
local prism = Instance.new("PrismaticConstraint")
prism.Attachment0 = att0
prism.Attachment1 = att1
prism.ActuatorType = Enum.ActuatorType.Motor
prism.Velocity = 5         -- studs/s
prism.MotorMaxForce = 10000
prism.Parent = partA

-- SpringConstraint
local spring = Instance.new("SpringConstraint")
spring.Attachment0 = att0
spring.Attachment1 = att1
spring.Stiffness = 500
spring.Damping = 50
spring.Parent = partA

-- RopeConstraint (chain)
local rope = Instance.new("RopeConstraint")
rope.Attachment0 = att0
rope.Attachment1 = att1
rope.Length = 10
rope.Parent = partA

-- RodConstraint (fixed-length rod)
local rod = Instance.new("RodConstraint")
rod.Attachment0 = att0
rod.Attachment1 = att1
rod.Length = 5
rod.Parent = partA

-- NoCollisionConstraint (ghost parts)
local noCol = Instance.new("NoCollisionConstraint")
noCol.Part0 = partA
noCol.Part1 = partB
noCol.Parent = partA

--- MOVER CONSTRAINTS ---

-- AlignPosition (float object to goal)
local alignPos = Instance.new("AlignPosition")
alignPos.Attachment0 = att0
alignPos.Attachment1 = att1
alignPos.MaxForce = 10000
alignPos.MaxVelocity = 20
alignPos.Parent = partA

-- AlignOrientation
local alignOri = Instance.new("AlignOrientation")
alignOri.Attachment0 = att0
alignOri.Attachment1 = att1
alignOri.MaxTorque = 10000
alignOri.Parent = partA

-- LinearVelocity (constant movement)
local linVel = Instance.new("LinearVelocity")
linVel.Attachment0 = att0
linVel.VelocityConstraintMode = Enum.VelocityConstraintMode.Vector
linVel.MaxForce = 5000
linVel.PlaneVelocity = Vector2.new(0, 10)
linVel.Parent = partA

-- VectorForce (constant push)
local vecForce = Instance.new("VectorForce")
vecForce.Attachment0 = att0
vecForce.Force = Vector3.new(0, 200, 0)
vecForce.RelativeTo = Enum.ActuatorRelativeTo.World
vecForce.Parent = partA

--- USEFUL HELPER PATTERNS ---

-- Clone a part N times in a row
local function cloneRow(template: BasePart, count: number, spacing: number): {BasePart}
  local parts = {}
  for i = 0, count - 1 do
    local clone = template:Clone()
    clone.CFrame = template.CFrame + Vector3.new(i * spacing, 0, 0)
    clone.Parent = workspace
    parts[i + 1] = clone
  end
  return parts
end

-- Build a wall from bricks
local function buildWall(startPos: Vector3, width: number, height: number, brickSize: Vector3)
  local model = Instance.new("Model")
  model.Name = "Wall"
  model.Parent = workspace
  for row = 0, height - 1 do
    local offsetX = (row % 2 == 0) and 0 or brickSize.X / 2
    local colCount = math.floor(width / brickSize.X)
    for col = 0, colCount - 1 do
      local brick = Instance.new("Part")
      brick.Size = brickSize
      brick.Anchored = true
      brick.Material = Enum.Material.Brick
      brick.Color = Color3.fromRGB(180, 100, 60)
      brick.CFrame = CFrame.new(
        startPos.X + col * brickSize.X + offsetX,
        startPos.Y + row * brickSize.Y + brickSize.Y / 2,
        startPos.Z
      )
      brick.Parent = model
    end
  end
  return model
end

-- Color3 helpers
Color3.fromRGB(255, 255, 255)       -- white
Color3.fromRGB(0, 0, 0)             -- black
Color3.fromHSV(0.6, 0.8, 0.9)      -- blue-ish
Color3.new(1, 1, 1)                 -- normalized 0-1 range

-- BrickColor legacy
part.BrickColor = BrickColor.new("Bright Red")
part.BrickColor = BrickColor.new("Medium stone grey")
part.BrickColor = BrickColor.new("Reddish brown")

--- UNION OPERATIONS / CSG ---
-- When to use CSG vs multi-part:
--   USE unions for: curved cutouts, arch holes, complex silhouettes that can't be made from basic parts
--   AVOID unions when: you need many instances (unions are expensive), physics precision matters,
--                      or the part count would be <= 3 (just use WedgeParts/Cylinders instead)
--   PREFER multi-part for: performance-critical builds, anything animated, large repeating elements

-- CreateUnion: merge multiple parts into one solid
local mainBlock = Instance.new("Part")
mainBlock.Size = Vector3.new(10, 6, 2)
mainBlock.Anchored = true
mainBlock.Parent = workspace

local cutter = Instance.new("Part")
cutter.Size = Vector3.new(4, 4, 4)   -- will be subtracted
cutter.CFrame = mainBlock.CFrame     -- overlapping
cutter.Parent = workspace

-- NegateAsync: mark a part as the "hole" cutter
local negated = cutter:NegateAsync()   -- returns NegateOperation
negated.Parent = workspace
cutter:Destroy()

-- SubtractAsync: cut negated parts from a base part
local union = mainBlock:SubtractAsync({negated})  -- returns UnionOperation
union.Parent = workspace
mainBlock:Destroy()
negated:Destroy()

-- UnionAsync: combine parts into a solid union
local partA = Instance.new("Part")
partA.Size = Vector3.new(4, 4, 4)
partA.Anchored = true
partA.Parent = workspace

local partB = Instance.new("Part")
partB.Size = Vector3.new(4, 4, 4)
partB.CFrame = partA.CFrame + Vector3.new(2, 0, 0)  -- overlapping
partB.Anchored = true
partB.Parent = workspace

local unionResult = partA:UnionAsync({partB})
unionResult.Anchored = true
unionResult.Parent = workspace
partA:Destroy()
partB:Destroy()

-- CSG performance notes:
--   RenderFidelity.Performance on unions = LOD saves GPU cost
--   CollisionFidelity.Box on unions = cheapest physics
--   Never union more than 10 parts at once — diminishing returns + lag spike
--   SplitApart() on a union gives back the original parts

--- SURFACEAPPEARANCE (PBR TEXTURES) ---
-- SurfaceAppearance applies realistic PBR maps to any BasePart or MeshPart.
-- Much higher quality than Material alone. Maps are Roblox asset IDs.

local sa = Instance.new("SurfaceAppearance")

-- ColorMap (Albedo / Diffuse): base color texture
sa.ColorMap = "rbxassetid://COLOR_ASSET_ID"

-- NormalMap: surface detail / bump. R=X G=Y B=Z normals. Makes flat parts look detailed.
sa.NormalMap = "rbxassetid://NORMAL_ASSET_ID"

-- RoughnessMap: grayscale. Black = mirror-smooth. White = fully rough/matte.
sa.RoughnessMap = "rbxassetid://ROUGHNESS_ASSET_ID"

-- MetalnessMap: grayscale. Black = dielectric. White = full metal (reflective, tinted).
sa.MetalnessMap = "rbxassetid://METALNESS_ASSET_ID"

-- AlphaMode: how ColorMap alpha is used
sa.AlphaMode = Enum.AlphaMode.Overlay       -- alpha blends with part color (default)
sa.AlphaMode = Enum.AlphaMode.Transparency  -- alpha drives part transparency

-- TextureTransparency: 0 = fully opaque, 1 = invisible
sa.TextureTransparency = 0

-- Parent to the target part (works on Part, MeshPart, UnionOperation)
sa.Parent = mesh   -- or any BasePart

-- Practical example: rusted metal plate
local rustSA = Instance.new("SurfaceAppearance")
rustSA.ColorMap    = "rbxassetid://7547304948"   -- rust color
rustSA.NormalMap   = "rbxassetid://7547305897"   -- surface dents
rustSA.RoughnessMap = "rbxassetid://7547306045"  -- rough except shiny spots
rustSA.MetalnessMap = "rbxassetid://7547306200"  -- mostly metal
rustSA.Parent = steelPart

-- Note: SurfaceAppearance overrides Material textures.
--       Set Material = Enum.Material.SmoothPlastic for cleanest PBR base (no competing texture).
--       For Neon emission, use Material = Enum.Material.Neon — SurfaceAppearance still applies color.

--- COLLISIONFIDELITY VS RENDERFIDELITY ---
-- Only applies to MeshPart and UnionOperation (not regular Parts).

-- RenderFidelity — controls visual LOD (Level of Detail)
--   Automatic    — engine decides based on distance (best default)
--   Precise      — always full detail, never simplifies (use for hero props)
--   Performance  — always lowest LOD (use for background filler, vegetation)
mesh.RenderFidelity = Enum.RenderFidelity.Automatic   -- recommended default
mesh.RenderFidelity = Enum.RenderFidelity.Precise     -- never degrades
mesh.RenderFidelity = Enum.RenderFidelity.Performance -- always low poly

-- CollisionFidelity — controls physics collision mesh complexity
--   Default                    — Roblox picks (usually Hull for MeshPart)
--   Box                        — CHEAPEST: axis-aligned bounding box. Use for boxes, floors, walls.
--   Hull                       — convex hull wrapping. Good for most props.
--   PreciseConvexDecomposition — most accurate, MOST EXPENSIVE. Use only for hero interactive props.
mesh.CollisionFidelity = Enum.CollisionFidelity.Box                        -- cheapest, flat surfaces
mesh.CollisionFidelity = Enum.CollisionFidelity.Hull                       -- good general-purpose
mesh.CollisionFidelity = Enum.CollisionFidelity.Default                    -- engine decides
mesh.CollisionFidelity = Enum.CollisionFidelity.PreciseConvexDecomposition -- exact shape, use sparingly

-- Performance guide:
--   Background / decoration (trees, rubble, fences): CollisionFidelity.Box + RenderFidelity.Performance
--   General props (crates, barrels, furniture):      CollisionFidelity.Hull + RenderFidelity.Automatic
--   Hero / interactive (weapons, vehicles, stairs):  CollisionFidelity.PreciseConvexDecomposition + RenderFidelity.Precise
--   If a MeshPart is Anchored and CanCollide=false: any CollisionFidelity is fine (no physics cost)

--- CONSTRAINT EXAMPLES: DOOR, DRAWBRIDGE, SLIDING SHELF ---

-- 1. Door hinge that opens (Servo mode — snaps to target angle)
local doorFrame = Instance.new("Part")
doorFrame.Size = Vector3.new(1, 8, 0.5)
doorFrame.Anchored = true
doorFrame.Parent = workspace

local door = Instance.new("Part")
door.Size = Vector3.new(4, 8, 0.3)
door.Anchored = false
door.Parent = workspace

-- Hinge attachment on door frame edge
local hingeAttFrame = Instance.new("Attachment", doorFrame)
hingeAttFrame.Position = Vector3.new(0, 0, 0)

-- Hinge attachment on door edge
local hingeAttDoor = Instance.new("Attachment", door)
hingeAttDoor.Position = Vector3.new(-2, 0, 0)   -- left edge of door

local doorHinge = Instance.new("HingeConstraint")
doorHinge.Attachment0 = hingeAttFrame
doorHinge.Attachment1 = hingeAttDoor
doorHinge.ActuatorType = Enum.ActuatorType.Servo
doorHinge.TargetAngle = 0        -- 0 = closed
doorHinge.ServoMaxTorque = 5000
doorHinge.AngularSpeed = 2       -- rad/s
doorHinge.Parent = doorFrame

-- Open door: set TargetAngle = 90 (or -90)
-- doorHinge.TargetAngle = 90

-- 2. Drawbridge (Motor mode — spins until LimitsEnabled stops it)
local bridgeBase = Instance.new("Part")
bridgeBase.Size = Vector3.new(8, 1, 1)
bridgeBase.Anchored = true
bridgeBase.Parent = workspace

local bridge = Instance.new("Part")
bridge.Size = Vector3.new(8, 0.5, 10)
bridge.Anchored = false
bridge.Parent = workspace

local bridgeAttBase = Instance.new("Attachment", bridgeBase)
local bridgeAttBridge = Instance.new("Attachment", bridge)
bridgeAttBridge.Position = Vector3.new(0, 0, -5)  -- pivot at back edge

local drawHinge = Instance.new("HingeConstraint")
drawHinge.Attachment0 = bridgeAttBase
drawHinge.Attachment1 = bridgeAttBridge
drawHinge.ActuatorType = Enum.ActuatorType.Servo
drawHinge.TargetAngle = 0        -- flat (down)
drawHinge.ServoMaxTorque = 20000
drawHinge.AngularSpeed = 1
drawHinge.LimitsEnabled = true
drawHinge.LowerAngle = -90       -- max raised position
drawHinge.UpperAngle = 0         -- flat position
drawHinge.Parent = bridgeBase
-- Raise: drawHinge.TargetAngle = -90

-- 3. Sliding shelf (PrismaticConstraint — linear motor)
local shelfTrack = Instance.new("Part")
shelfTrack.Size = Vector3.new(0.5, 0.5, 20)
shelfTrack.Anchored = true
shelfTrack.Parent = workspace

local shelf = Instance.new("Part")
shelf.Size = Vector3.new(6, 0.5, 4)
shelf.Anchored = false
shelf.Parent = workspace

local slideAttTrack = Instance.new("Attachment", shelfTrack)
local slideAttShelf = Instance.new("Attachment", shelf)

local slider = Instance.new("PrismaticConstraint")
slider.Attachment0 = slideAttTrack
slider.Attachment1 = slideAttShelf
slider.ActuatorType = Enum.ActuatorType.Servo
slider.TargetPosition = 0        -- starting position (studs along axis)
slider.ServoMaxForce = 10000
slider.Speed = 5                 -- studs/s
slider.LimitsEnabled = true
slider.LowerLimit = -8
slider.UpperLimit = 8
slider.Parent = shelfTrack
-- Slide out: slider.TargetPosition = 8
-- Slide in:  slider.TargetPosition = -8

--- ADVANCED CFRAME PATTERNS ---

-- 1. Spiral staircase
local function buildSpiralStaircase(center: Vector3, steps: number, stepHeight: number,
    stepWidth: number, radius: number, turnsPerStaircase: number): Model
  local model = Instance.new("Model")
  model.Name = "SpiralStaircase"
  model.Parent = workspace
  local anglePerStep = (turnsPerStaircase * math.pi * 2) / steps
  for i = 0, steps - 1 do
    local angle = i * anglePerStep
    local x = center.X + math.cos(angle) * radius
    local z = center.Z + math.sin(angle) * radius
    local y = center.Y + i * stepHeight + stepHeight / 2
    local step = Instance.new("WedgePart")
    step.Size = Vector3.new(stepWidth, stepHeight, 2)
    step.Anchored = true
    step.Material = Enum.Material.Concrete
    step.Color = Color3.fromRGB(140, 130, 120)
    step.CFrame = CFrame.new(x, y, z) * CFrame.Angles(0, angle + math.pi / 2, 0)
    step.Parent = model
  end
  -- Central pillar
  local pillar = Instance.new("Part")
  pillar.Shape = Enum.PartType.Cylinder
  pillar.Size = Vector3.new(steps * stepHeight, radius * 0.4, radius * 0.4)
  pillar.Anchored = true
  pillar.Material = Enum.Material.Concrete
  pillar.CFrame = CFrame.new(center.X, center.Y + (steps * stepHeight) / 2, center.Z)
              * CFrame.Angles(0, 0, math.rad(90))
  pillar.Parent = model
  return model
end

-- Usage: buildSpiralStaircase(Vector3.new(0,0,0), 24, 1, 4, 5, 1.5)

-- 2. Dome generation (hemisphere from wedge/block parts)
local function buildDome(center: Vector3, radius: number, rings: number, segments: number): Model
  local model = Instance.new("Model")
  model.Name = "Dome"
  model.Parent = workspace
  for ring = 0, rings - 1 do
    local phi = (ring / rings) * (math.pi / 2)          -- 0 = equator, pi/2 = top
    local nextPhi = ((ring + 1) / rings) * (math.pi / 2)
    local ringRadius = math.cos(phi) * radius
    local ringY = center.Y + math.sin(phi) * radius
    local ringHeight = (math.sin(nextPhi) - math.sin(phi)) * radius
    for seg = 0, segments - 1 do
      local theta = (seg / segments) * math.pi * 2
      local x = center.X + math.cos(theta) * ringRadius
      local z = center.Z + math.sin(theta) * ringRadius
      local panel = Instance.new("Part")
      panel.Size = Vector3.new(
        (2 * math.pi * ringRadius) / segments - 0.1,
        math.max(ringHeight, 0.3),
        radius * 0.12
      )
      panel.Anchored = true
      panel.Material = Enum.Material.Concrete
      panel.Color = Color3.fromRGB(220, 200, 170)
      -- Face inward + tilt to follow sphere surface
      local midPhi = (phi + nextPhi) / 2
      panel.CFrame = CFrame.new(x, ringY, z)
                   * CFrame.Angles(0, -theta, 0)
                   * CFrame.Angles(midPhi, 0, 0)
      panel.Parent = model
    end
  end
  -- Cap at top
  local cap = Instance.new("Part")
  cap.Shape = Enum.PartType.Ball
  cap.Size = Vector3.new(radius * 0.2, radius * 0.2, radius * 0.2)
  cap.Anchored = true
  cap.CFrame = CFrame.new(center.X, center.Y + radius, center.Z)
  cap.Parent = model
  return model
end

-- Usage: buildDome(Vector3.new(0,0,0), 20, 6, 12)

-- 3. Arch generation (Roman/Gothic arch over a doorway)
local function buildArch(baseLeft: Vector3, baseRight: Vector3,
    thickness: number, depth: number, segments: number): Model
  local model = Instance.new("Model")
  model.Name = "Arch"
  model.Parent = workspace
  local midX = (baseLeft.X + baseRight.X) / 2
  local midY = baseLeft.Y
  local midZ = (baseLeft.Z + baseRight.Z) / 2
  local radius = (baseRight - baseLeft).Magnitude / 2
  for i = 0, segments - 1 do
    local t0 = i / segments
    local t1 = (i + 1) / segments
    local a0 = math.pi + t0 * math.pi   -- pi to 2pi = bottom-left to bottom-right (semicircle)
    local a1 = math.pi + t1 * math.pi
    local aMid = (a0 + a1) / 2
    local x = midX + math.cos(aMid) * radius
    local y = midY + math.sin(aMid) * radius  -- sin goes 0→1→0 across the arch
    local segLen = radius * (a1 - a0)
    local stone = Instance.new("Part")
    stone.Size = Vector3.new(thickness, segLen, depth)
    stone.Anchored = true
    stone.Material = Enum.Material.Limestone
    stone.Color = Color3.fromRGB(200, 185, 155)
    stone.CFrame = CFrame.new(x, y, midZ) * CFrame.Angles(0, 0, -(aMid - math.pi / 2))
    stone.Parent = model
  end
  return model
end

-- Usage: buildArch(Vector3.new(-5,0,0), Vector3.new(5,0,0), 1.5, 2, 10)

-- 4. Procedural corridor (repeating room segment with walls/ceiling/floor)
local function buildCorridor(startPos: Vector3, length: number, width: number,
    height: number, segmentSize: number): Model
  local model = Instance.new("Model")
  model.Name = "Corridor"
  model.Parent = workspace
  local numSegs = math.floor(length / segmentSize)
  local wallMat = Enum.Material.Concrete
  local floorMat = Enum.Material.WoodPlanks
  for i = 0, numSegs - 1 do
    local segZ = startPos.Z + i * segmentSize + segmentSize / 2
    -- Floor slab
    local floor = Instance.new("Part")
    floor.Size = Vector3.new(width, 0.5, segmentSize)
    floor.Anchored = true
    floor.Material = floorMat
    floor.Color = Color3.fromRGB(140, 100, 60)
    floor.CFrame = CFrame.new(startPos.X, startPos.Y, segZ)
    floor.Parent = model
    -- Ceiling slab
    local ceiling = Instance.new("Part")
    ceiling.Size = Vector3.new(width, 0.5, segmentSize)
    ceiling.Anchored = true
    ceiling.Material = wallMat
    ceiling.Color = Color3.fromRGB(180, 170, 160)
    ceiling.CFrame = CFrame.new(startPos.X, startPos.Y + height, segZ)
    ceiling.Parent = model
    -- Left wall
    local leftWall = Instance.new("Part")
    leftWall.Size = Vector3.new(0.5, height, segmentSize)
    leftWall.Anchored = true
    leftWall.Material = wallMat
    leftWall.Color = Color3.fromRGB(160, 150, 140)
    leftWall.CFrame = CFrame.new(startPos.X - width / 2, startPos.Y + height / 2, segZ)
    leftWall.Parent = model
    -- Right wall
    local rightWall = leftWall:Clone()
    rightWall.CFrame = CFrame.new(startPos.X + width / 2, startPos.Y + height / 2, segZ)
    rightWall.Parent = model
  end
  return model
end

-- Usage: buildCorridor(Vector3.new(0,0,0), 60, 8, 5, 6)

--- WELDCONSTRAINT AUTO-WELD FUNCTION ---
-- Loops through a model and welds all BaseParts to the PrimaryPart (or first part found).
-- Call after building a multi-part structure to make it behave as one rigid body.

local function autoWeldModel(model: Model)
  local primary = model.PrimaryPart
  if not primary then
    -- Use first BasePart found as anchor
    for _, v in ipairs(model:GetDescendants()) do
      if v:IsA("BasePart") then
        primary = v
        model.PrimaryPart = v
        break
      end
    end
  end
  if not primary then return end
  for _, part in ipairs(model:GetDescendants()) do
    if part:IsA("BasePart") and part ~= primary then
      local weld = Instance.new("WeldConstraint")
      weld.Part0 = primary
      weld.Part1 = part
      weld.Parent = primary
    end
  end
end

-- Usage after building a structure:
-- autoWeldModel(myHouseModel)

-- Advanced: weld every part to its nearest neighbor (better for long chains)
local function chainWeldModel(model: Model)
  local parts = {}
  for _, v in ipairs(model:GetDescendants()) do
    if v:IsA("BasePart") then
      table.insert(parts, v)
    end
  end
  -- Weld each part to part[1] as root
  local root = parts[1]
  if not root then return end
  root.Anchored = true
  for i = 2, #parts do
    local weld = Instance.new("WeldConstraint")
    weld.Part0 = root
    weld.Part1 = parts[i]
    weld.Parent = root
    parts[i].Anchored = false  -- physics handled by weld
  end
end

--- MODEL:GETBOUNDINGBOX() USAGE ---
-- Returns (CFrame, Vector3) — the orientation + size of the model's full bounding box.
-- Use for: measuring builds, centering on plot, scaling to fit, collision footprints.

local model = workspace.MyBuild
local boundCF: CFrame, boundSize: Vector3 = model:GetBoundingBox()

-- Get world-space center position
local centerPos: Vector3 = boundCF.Position

-- Get total extents
local width: number  = boundSize.X
local height: number = boundSize.Y
local depth: number  = boundSize.Z

-- Center model on a plot
local function centerOnPlot(model: Model, plotCenter: Vector3)
  local cf, size = model:GetBoundingBox()
  -- Calculate offset so model base sits on ground at plotCenter
  local offsetY = -cf.Position.Y + size.Y / 2
  model:PivotTo(CFrame.new(plotCenter.X, plotCenter.Y + offsetY, plotCenter.Z))
end

-- Scale model to fit within maxSize studs
local function scaleModelToFit(model: Model, maxSize: number)
  local cf, size = model:GetBoundingBox()
  local currentMax = math.max(size.X, size.Y, size.Z)
  if currentMax <= maxSize then return end
  local scaleFactor = maxSize / currentMax
  for _, part in ipairs(model:GetDescendants()) do
    if part:IsA("BasePart") then
      part.Size = part.Size * scaleFactor
      local relCF = cf:ToObjectSpace(part.CFrame)
      part.CFrame = cf:ToWorldSpace(CFrame.new(relCF.Position * scaleFactor)
                  * CFrame.fromMatrix(Vector3.new(), relCF.XVector, relCF.YVector, relCF.ZVector))
    end
  end
end

-- Check if build fits inside a plot region
local function buildFitsInPlot(model: Model, plotSize: Vector3): boolean
  local _, size = model:GetBoundingBox()
  return size.X <= plotSize.X and size.Z <= plotSize.Z
end

--- ASSEMBLY VELOCITY (PHYSICS-BASED MOVEMENT) ---
-- AssemblyLinearVelocity / AssemblyAngularVelocity apply to the entire physics assembly
-- (all parts welded together). More reliable than setting individual part velocities.
-- Part must NOT be Anchored for these to have effect.

local part = workspace.Projectile

-- Launch in a direction (studs/s)
part.AssemblyLinearVelocity = Vector3.new(0, 50, -100)    -- up + forward

-- Spin (radians/s, relative to world axes)
part.AssemblyAngularVelocity = Vector3.new(0, math.pi * 2, 0)  -- 1 full rotation/s around Y

-- Combine: thrown ball with spin
local ball = Instance.new("Part")
ball.Shape = Enum.PartType.Ball
ball.Size = Vector3.new(2, 2, 2)
ball.Material = Enum.Material.Rubber
ball.Anchored = false
ball.CFrame = CFrame.new(0, 10, 0)
ball.Parent = workspace
ball.AssemblyLinearVelocity = Vector3.new(20, 30, 0)        -- throw right + up
ball.AssemblyAngularVelocity = Vector3.new(5, 0, 0)         -- topspin

-- Platform moving left/right (use LinearVelocity constraint for sustained movement,
-- AssemblyLinearVelocity for a one-shot impulse-style set)
local platform = workspace.MovingPlatform
platform.Anchored = false
-- Move platform right at 10 studs/s (one-shot, physics will take over)
platform.AssemblyLinearVelocity = Vector3.new(10, 0, 0)

-- Stop a moving assembly
platform.AssemblyLinearVelocity = Vector3.zero
platform.AssemblyAngularVelocity = Vector3.zero

-- Note: For sustained / controlled movement, prefer LinearVelocity or AlignPosition constraints.
--       AssemblyLinearVelocity is best for: launching projectiles, knockback, one-time boosts.

--- TERRAIN:FILLREGION() VS TERRAIN:FILLBLOCK() ---
-- Both fill terrain voxels with a material. Choose based on what you have: a Region3 or a CFrame.

local Terrain = workspace.Terrain

-- FillBlock(cframe, size, material) — fill a rotatable box
-- USE WHEN: you need to place terrain at an angle, or you already have a CFrame to work with
Terrain:FillBlock(
  CFrame.new(0, 0, 0),                  -- center CFrame (can be rotated)
  Vector3.new(100, 10, 100),            -- size in studs
  Enum.Material.Ground
)

-- Rotated terrain fill (diagonal cliff)
Terrain:FillBlock(
  CFrame.new(50, 20, 50) * CFrame.Angles(0, 0, math.rad(30)),  -- tilted 30 degrees
  Vector3.new(80, 8, 40),
  Enum.Material.Rock
)

-- FillRegion(region3, resolution, material) — fill an axis-aligned Region3
-- USE WHEN: you have a Region3 (e.g. from workspace:FindPartsInRegion3 or a fixed AABB zone)
-- Resolution must be power of 2 between 2 and 2048 (4 is standard)
local region = Region3.new(
  Vector3.new(-50, -5, -50),   -- min corner
  Vector3.new(50, 5, 50)       -- max corner
)
Terrain:FillRegion(region, 4, Enum.Material.Grass)

-- Decision guide:
--   FillBlock  → rotated terrain, angled hills, CFrame-driven placement (more flexible)
--   FillRegion → flat AABB fills, map zones, clearing large areas, grid-aligned terrain

-- Common terrain generation pattern: layered biome fill
local function fillTerrain(cx: number, cz: number, radius: number)
  local base = Region3.new(
    Vector3.new(cx - radius, -20, cz - radius),
    Vector3.new(cx + radius, 0, cz + radius)
  )
  Terrain:FillRegion(base, 4, Enum.Material.Rock)           -- bedrock layer
  local soil = Region3.new(
    Vector3.new(cx - radius, 0, cz - radius),
    Vector3.new(cx + radius, 2, cz + radius)
  )
  Terrain:FillRegion(soil, 4, Enum.Material.Ground)         -- soil layer
  local surface = Region3.new(
    Vector3.new(cx - radius, 2, cz - radius),
    Vector3.new(cx + radius, 4, cz + radius)
  )
  Terrain:FillRegion(surface, 4, Enum.Material.Grass)       -- grass top
end

-- FillWater: fill with water material (same signature as FillBlock)
Terrain:FillBlock(CFrame.new(0, -2, 0), Vector3.new(200, 4, 200), Enum.Material.Water)

-- ReplaceMaterial: swap one terrain material for another in a region
Terrain:ReplaceMaterial(region, 4, Enum.Material.Grass, Enum.Material.Snow)

=== END BUILDING PARTS CFRAME REFERENCE ===
`;
