// AUTO-GENERATED by Knowledge Crawler — 2026-04-29
// Source: Roblox Creator Hub (terrain, lighting, atmosphere, skybox, post-processing, wind)

export const ENVIRONMENT_TERRAIN_LIGHTING = `
=== ROBLOX ENVIRONMENT, TERRAIN & LIGHTING MASTER REFERENCE ===

--- TERRAIN API ---
-- Terrain is a singleton at workspace.Terrain
-- Voxel resolution: always 4 studs per voxel

-- FillBlock — fill a box of terrain
-- workspace.Terrain:FillBlock(cframe, size, material)
workspace.Terrain:FillBlock(
  CFrame.new(0, 0, 0),            -- center position + orientation
  Vector3.new(100, 4, 100),        -- size in studs
  Enum.Material.Grass              -- terrain material
)

-- FillBall — fill a sphere
-- workspace.Terrain:FillBall(center, radius, material)
workspace.Terrain:FillBall(
  Vector3.new(0, 0, -10),
  10,                              -- radius in studs
  Enum.Material.Grass
)

-- FillCylinder — fill a cylinder
-- workspace.Terrain:FillCylinder(cframe, height, radius, material)
workspace.Terrain:FillCylinder(
  CFrame.new(0, 50, 0),
  5,                               -- height
  30,                              -- radius
  Enum.Material.Asphalt
)

-- FillWedge — fill a wedge-shaped volume
-- workspace.Terrain:FillWedge(cframe, size, material)
workspace.Terrain:FillWedge(
  CFrame.new(0, 0, 0),
  Vector3.new(20, 10, 20),
  Enum.Material.Rock
)

-- ReadVoxels — read terrain voxel data (returns materials 3D array + occupancies 3D array)
-- resolution MUST be 4
local region = Region3.new(Vector3.new(-50, -10, -50), Vector3.new(50, 10, 50))
local materials, occupancies = workspace.Terrain:ReadVoxels(region, 4)
local size = materials.Size
for x = 1, size.X do
  for y = 1, size.Y do
    for z = 1, size.Z do
      local mat = materials[x][y][z]
      local occ = occupancies[x][y][z]   -- 0 to 1
      print(mat.Name, occ)
    end
  end
end

-- WriteVoxels — write terrain voxel data
-- Dimensions of materials/occupancy arrays must exactly match region voxel count
local region2 = Region3.new(Vector3.new(0, 0, 0), Vector3.new(8, 8, 8))
local mat3D = {}  -- 3D array of Enum.Material values
local occ3D = {}  -- 3D array of 0-1 values
workspace.Terrain:WriteVoxels(region2, 4, mat3D, occ3D)

-- ReplaceMaterial — swap one terrain material for another in a region
local region3 = Region3.new(Vector3.new(-20, -20, -20), Vector3.new(20, 20, 20))
workspace.Terrain:ReplaceMaterial(region3, 4, Enum.Material.Grass, Enum.Material.Asphalt)

-- Clear all terrain
workspace.Terrain:Clear()

-- Common terrain generation pattern — flat island
local function generateFlatIsland(size: number, height: number)
  workspace.Terrain:FillBlock(
    CFrame.new(0, -height / 2, 0),
    Vector3.new(size, height, size),
    Enum.Material.Ground
  )
  workspace.Terrain:FillBlock(
    CFrame.new(0, 0.5, 0),
    Vector3.new(size, 1, size),
    Enum.Material.Grass
  )
end

-- Terrain material enum values (Enum.Material.* — subset valid for Terrain)
-- Grass, LeafyGrass, Ground, Mud, Sand, Snow, Ice, Glacier, Salt
-- Rock, Basalt, Granite, Slate, Marble, Limestone, Sandstone, Pavement, Cobblestone, Pebble, CrackedLava
-- Asphalt, Brick, Concrete, Plastic, SmoothPlastic, Metal, Wood, WoodPlanks
-- Water, Air (special — clears/empties voxels)

-- Generate mountainous terrain with noise
local function generateTerrain(mapSize: number, maxHeight: number)
  local resolution = 4
  local xSize = mapSize / resolution
  local zSize = mapSize / resolution
  for x = 0, xSize - 1 do
    for z = 0, zSize - 1 do
      local worldX = x * resolution - mapSize / 2
      local worldZ = z * resolution - mapSize / 2
      local height = math.noise(worldX / 60, worldZ / 60) * maxHeight
      local mat = height > 20 and Enum.Material.Rock
        or height > 5  and Enum.Material.Grass
        or Enum.Material.Sand
      workspace.Terrain:FillBlock(
        CFrame.new(worldX, height / 2, worldZ),
        Vector3.new(resolution, math.abs(height), resolution),
        mat
      )
    end
  end
end

--- LIGHTING SERVICE ---
-- Access: game:GetService("Lighting")
local Lighting = game:GetService("Lighting")

-- Core properties
Lighting.Ambient = Color3.fromRGB(70, 70, 70)         -- indoor/overall ambient hue
Lighting.OutdoorAmbient = Color3.fromRGB(100, 100, 140) -- outdoor sky ambient
Lighting.Brightness = 2                                -- sun intensity (0-10)
Lighting.ColorShift_Top = Color3.fromRGB(255, 250, 230)  -- hue from top (sun side)
Lighting.ColorShift_Bottom = Color3.fromRGB(50, 50, 80)  -- hue from bottom (shadow side)
Lighting.ExposureCompensation = 0                      -- -5 to 5, camera exposure
Lighting.GlobalShadows = true                          -- enable shadows
Lighting.ShadowSoftness = 0.5                          -- 0=hard, 1=very soft
Lighting.FogStart = 0                                  -- fog begins at this distance
Lighting.FogEnd = 500                                  -- fog fully opaque at this distance
Lighting.FogColor = Color3.fromRGB(192, 192, 192)      -- fog tint color

-- Time of day
Lighting.ClockTime = 14                                -- 0-24 float (14 = 2PM)
Lighting.TimeOfDay = "14:00:00"                        -- string format alternative
Lighting.GeographicLatitude = 41.7                     -- latitude for sun angle (degrees)

-- Technology (lighting model)
Lighting.Technology = Enum.Technology.Future           -- best quality (PBR, shadows)
Lighting.Technology = Enum.Technology.ShadowMap        -- good quality
Lighting.Technology = Enum.Technology.Compatibility    -- legacy

-- EnvironmentDiffuseScale / EnvironmentSpecularScale
Lighting.EnvironmentDiffuseScale = 1.0   -- how much sky contributes to ambient
Lighting.EnvironmentSpecularScale = 1.0  -- how much sky contributes to specular

-- Environment presets
-- DAY
Lighting.ClockTime = 14
Lighting.Brightness = 2
Lighting.Ambient = Color3.fromRGB(70, 70, 70)
Lighting.OutdoorAmbient = Color3.fromRGB(127, 127, 127)
Lighting.ShadowSoftness = 0.2
Lighting.FogEnd = 1000

-- SUNSET / GOLDEN HOUR
Lighting.ClockTime = 18.5
Lighting.Brightness = 1.5
Lighting.Ambient = Color3.fromRGB(80, 60, 40)
Lighting.OutdoorAmbient = Color3.fromRGB(180, 130, 80)
Lighting.ColorShift_Top = Color3.fromRGB(255, 200, 120)
Lighting.FogColor = Color3.fromRGB(220, 160, 100)
Lighting.FogEnd = 400

-- NIGHT
Lighting.ClockTime = 23
Lighting.Brightness = 0.2
Lighting.Ambient = Color3.fromRGB(20, 20, 40)
Lighting.OutdoorAmbient = Color3.fromRGB(30, 30, 60)
Lighting.ShadowSoftness = 0.8
Lighting.FogEnd = 300

-- OVERCAST
Lighting.ClockTime = 12
Lighting.Brightness = 0.8
Lighting.Ambient = Color3.fromRGB(90, 90, 90)
Lighting.OutdoorAmbient = Color3.fromRGB(110, 110, 120)
Lighting.FogColor = Color3.fromRGB(180, 180, 190)
Lighting.FogEnd = 600

-- EERIE / HORROR
Lighting.ClockTime = 2
Lighting.Brightness = 0.1
Lighting.Ambient = Color3.fromRGB(10, 20, 10)
Lighting.OutdoorAmbient = Color3.fromRGB(5, 15, 5)
Lighting.FogColor = Color3.fromRGB(20, 40, 20)
Lighting.FogEnd = 80

-- SCI-FI / FUTURISTIC
Lighting.ClockTime = 0
Lighting.Brightness = 0.5
Lighting.Ambient = Color3.fromRGB(0, 20, 40)
Lighting.OutdoorAmbient = Color3.fromRGB(0, 30, 60)
Lighting.FogColor = Color3.fromRGB(0, 80, 140)
Lighting.FogEnd = 300

--- LIGHT OBJECTS ---
-- PointLight (omnidirectional — lamps, torches)
local pointLight = Instance.new("PointLight")
pointLight.Brightness = 3
pointLight.Range = 20
pointLight.Color = Color3.fromRGB(255, 200, 100)  -- warm orange
pointLight.Parent = lampPart

-- SpotLight (directional cone — flashlights, headlights)
local spotLight = Instance.new("SpotLight")
spotLight.Brightness = 5
spotLight.Range = 40
spotLight.Angle = 45       -- cone angle degrees
spotLight.Face = Enum.NormalId.Front
spotLight.Color = Color3.fromRGB(255, 255, 200)
spotLight.Parent = flashlightPart

-- SurfaceLight (area light — screens, glowing panels)
local surfLight = Instance.new("SurfaceLight")
surfLight.Brightness = 2
surfLight.Range = 15
surfLight.Angle = 90
surfLight.Face = Enum.NormalId.Front
surfLight.Color = Color3.fromRGB(100, 200, 255)
surfLight.Parent = screenPart

--- POST-PROCESSING EFFECTS ---
-- Add to Lighting (affects all) or Camera (affects specific player)
local lighting = game:GetService("Lighting")

-- BloomEffect — glow around bright areas
local bloom = Instance.new("BloomEffect")
bloom.Intensity = 0.5     -- glow strength (0 to 1+)
bloom.Size = 24           -- glow spread size
bloom.Threshold = 0.95    -- brightness threshold to start glowing
bloom.Parent = lighting

-- BlurEffect — Gaussian blur (menus, transitions)
local blur = Instance.new("BlurEffect")
blur.Size = 0             -- 0 = off, 24 = heavy blur
blur.Parent = lighting

-- ColorCorrectionEffect — color grade the scene
local cc = Instance.new("ColorCorrectionEffect")
cc.Brightness = 0         -- -1 to 1 (darker/brighter)
cc.Contrast = 0           -- -1 to 1
cc.Saturation = 0         -- -1 = grayscale, 1 = vivid
cc.TintColor = Color3.new(1, 1, 1)  -- color tint multiplier
cc.Parent = lighting

-- Common color grades
-- Warm / Golden Hour
cc.TintColor = Color3.fromRGB(255, 220, 180)
cc.Saturation = 0.2

-- Cool / Sci-Fi
cc.TintColor = Color3.fromRGB(180, 220, 255)
cc.Saturation = 0.3

-- Horror / Desaturated
cc.Saturation = -0.5
cc.TintColor = Color3.fromRGB(200, 220, 200)

-- Sepia / Retro
cc.TintColor = Color3.fromRGB(240, 210, 160)
cc.Saturation = -0.3

-- SunRaysEffect — god rays from sun
local sunRays = Instance.new("SunRaysEffect")
sunRays.Intensity = 0.25  -- 0 to 1
sunRays.Spread = 0.5      -- 0 to 1
sunRays.Parent = lighting

-- DepthOfFieldEffect — cinematic bokeh focus
local dof = Instance.new("DepthOfFieldEffect")
dof.FocusDistance = 50    -- distance from camera in focus
dof.InFocusRadius = 15    -- range around FocusDistance that is sharp
dof.NearIntensity = 0     -- foreground blur strength
dof.FarIntensity = 1      -- background blur strength
dof.Parent = lighting

-- ColorGradingEffect — tonemapper
local cg = Instance.new("ColorGradingEffect")
cg.TonemapperPreset = Enum.TonemapperPreset.Default  -- modern vivid colors
-- cg.TonemapperPreset = Enum.TonemapperPreset.Retro -- pre-2019 look
cg.Parent = lighting

--- ATMOSPHERE ---
-- Add Atmosphere inside Lighting
local atmo = Instance.new("Atmosphere")
atmo.Parent = lighting

-- Properties
atmo.Density = 0.3         -- 0 = clear sky, higher = foggy/thick
atmo.Offset = 0.25         -- 0 = blend horizon, 1 = crisp horizon silhouette
atmo.Color = Color3.fromRGB(199, 199, 199)  -- atmosphere hue
atmo.Decay = Color3.fromRGB(106, 112, 125)  -- hue away from sun
atmo.Glare = 0             -- sun glare (needs Haze > 0)
atmo.Haze = 0              -- atmospheric haze strength

-- Atmosphere presets

-- CLEAR DAY
atmo.Density = 0.17
atmo.Offset = 0.25
atmo.Color = Color3.fromRGB(199, 199, 199)
atmo.Decay = Color3.fromRGB(106, 112, 125)
atmo.Glare = 0
atmo.Haze = 0

-- HAZY / MISTY
atmo.Density = 0.35
atmo.Offset = 0.1
atmo.Haze = 2.5
atmo.Color = Color3.fromRGB(210, 200, 195)
atmo.Glare = 0.3

-- DUSTY / DESERT
atmo.Density = 0.25
atmo.Haze = 1.8
atmo.Color = Color3.fromRGB(220, 190, 150)
atmo.Decay = Color3.fromRGB(180, 140, 100)
atmo.Glare = 0.4

-- DEEP SPACE (minimal atmosphere)
atmo.Density = 0
atmo.Haze = 0
atmo.Glare = 0

-- ALIEN WORLD
atmo.Density = 0.3
atmo.Haze = 2.0
atmo.Color = Color3.fromRGB(120, 180, 255)  -- blue-purple sky
atmo.Decay = Color3.fromRGB(60, 100, 180)
atmo.Glare = 0.5

--- SKY / SKYBOX ---
-- Add Sky inside Lighting
local sky = Instance.new("Sky")
sky.Parent = lighting

-- Skybox face textures (asset IDs for each face)
sky.SkyboxBk = "rbxassetid://BACK_ID"
sky.SkyboxDn = "rbxassetid://DOWN_ID"
sky.SkyboxFt = "rbxassetid://FRONT_ID"
sky.SkyboxLf = "rbxassetid://LEFT_ID"
sky.SkyboxRt = "rbxassetid://RIGHT_ID"
sky.SkyboxUp = "rbxassetid://UP_ID"

-- Celestial bodies
sky.CelestialBodiesShown = true          -- show sun/moon
sky.StarCount = 3000                     -- number of stars (night)
sky.SunTextureId = "rbxassetid://SUN_ID" -- custom sun texture
sky.MoonTextureId = "rbxassetid://MOON_ID"
sky.SunAngularSize = 21                  -- apparent size of sun
sky.MoonAngularSize = 11                 -- apparent size of moon

-- Remove sky (pure color or Atmosphere-only look)
sky:Destroy()

--- GLOBAL WIND ---
-- workspace.GlobalWind is a Vector3
-- Affects: terrain grass, dynamic clouds, particles with WindAffectsDrag

-- Set wind direction and strength
workspace.GlobalWind = Vector3.new(5, 0, 0)   -- blowing east, medium strength
workspace.GlobalWind = Vector3.new(0, 0, 0)   -- no wind
workspace.GlobalWind = Vector3.new(20, 2, 10) -- strong diagonal wind

-- Cyclical wind gusts with sin wave
local baseWind = Vector3.new(5, 0, 0)
local gustIntensity = 8
local gustPeriod = 4  -- seconds per full cycle
game:GetService("RunService").Heartbeat:Connect(function()
  local t = tick()
  local gust = math.sin(t * math.pi * 2 / gustPeriod)
  local ramped = 0.5 + 0.5 * gust  -- 0 to 1
  workspace.GlobalWind = baseWind + Vector3.new(ramped * gustIntensity, 0, 0)
end)

-- Particle wind interaction (on ParticleEmitter)
-- particle.WindAffectsDrag = true
-- particle.Drag = 1  (must be > 0 for wind to work)

--- COMPLETE ENVIRONMENT SETUPS ---

-- FOREST / NATURE
local function setupForest()
  local L = game:GetService("Lighting")
  L.ClockTime = 13
  L.Brightness = 1.5
  L.Ambient = Color3.fromRGB(60, 70, 50)
  L.OutdoorAmbient = Color3.fromRGB(100, 120, 80)
  L.FogColor = Color3.fromRGB(150, 170, 130)
  L.FogEnd = 600

  local atm = Instance.new("Atmosphere", L)
  atm.Density = 0.2
  atm.Haze = 0.5
  atm.Color = Color3.fromRGB(180, 210, 160)

  workspace.GlobalWind = Vector3.new(3, 0, 1)

  local cc2 = Instance.new("ColorCorrectionEffect", L)
  cc2.Saturation = 0.15
  cc2.TintColor = Color3.fromRGB(220, 240, 200)
end

-- SPACE STATION / SCI-FI
local function setupSciFi()
  local L = game:GetService("Lighting")
  L.ClockTime = 0
  L.Brightness = 0.3
  L.Ambient = Color3.fromRGB(0, 15, 35)
  L.OutdoorAmbient = Color3.fromRGB(0, 20, 50)
  L.FogEnd = 500
  L.FogColor = Color3.fromRGB(0, 40, 80)

  local atm = Instance.new("Atmosphere", L)
  atm.Density = 0.05
  atm.Haze = 0
  atm.Color = Color3.fromRGB(0, 100, 200)

  local bloom2 = Instance.new("BloomEffect", L)
  bloom2.Intensity = 0.8
  bloom2.Size = 30
  bloom2.Threshold = 0.8

  local cc2 = Instance.new("ColorCorrectionEffect", L)
  cc2.TintColor = Color3.fromRGB(180, 220, 255)
  cc2.Saturation = 0.25
  cc2.Contrast = 0.1

  workspace.GlobalWind = Vector3.new(0, 0, 0)
end

-- UNDERWATER VIBE
local function setupUnderwater()
  local L = game:GetService("Lighting")
  L.ClockTime = 14
  L.Brightness = 0.7
  L.Ambient = Color3.fromRGB(0, 50, 80)
  L.OutdoorAmbient = Color3.fromRGB(0, 80, 120)
  L.FogColor = Color3.fromRGB(0, 100, 150)
  L.FogEnd = 150
  L.FogStart = 10

  local cc2 = Instance.new("ColorCorrectionEffect", L)
  cc2.TintColor = Color3.fromRGB(100, 200, 255)
  cc2.Saturation = 0.3

  local blur2 = Instance.new("BlurEffect", L)
  blur2.Size = 3
end

-- HORROR / HAUNTED
local function setupHorror()
  local L = game:GetService("Lighting")
  L.ClockTime = 0.5
  L.Brightness = 0.05
  L.Ambient = Color3.fromRGB(10, 10, 15)
  L.OutdoorAmbient = Color3.fromRGB(5, 8, 10)
  L.FogColor = Color3.fromRGB(15, 20, 15)
  L.FogEnd = 60
  L.FogStart = 5

  local atm = Instance.new("Atmosphere", L)
  atm.Density = 0.4
  atm.Haze = 2.8
  atm.Color = Color3.fromRGB(80, 100, 80)

  local cc2 = Instance.new("ColorCorrectionEffect", L)
  cc2.Saturation = -0.4
  cc2.TintColor = Color3.fromRGB(190, 210, 190)
  cc2.Contrast = 0.2
end

--- TERRAIN MATERIAL QUICK REFERENCE ---
-- For terrain fills — use these Enum.Material values:
-- NATURE:    Grass, LeafyGrass, Ground, Mud, Sand, Snow, Ice, Glacier, Salt
-- STONE:     Rock, Basalt, Granite, Slate, Marble, Limestone, Sandstone, Pebble, CrackedLava
-- URBAN:     Asphalt, Pavement, Cobblestone, Brick, Concrete
-- MISC:      Plastic, SmoothPlastic, Metal, Wood, WoodPlanks
-- SPECIAL:   Water (fills voxel with water), Air (empties/clears voxel)

=== END ENVIRONMENT TERRAIN LIGHTING REFERENCE ===
`;
