/**
 * Daily Rewards Template — 7-day login calendar.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function dailyRewardsTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Daily Rewards UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- LocalScript in StarterPlayerScripts. Server-side script should fire
-- ReplicatedStorage.ClaimDaily to update claimed status.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    bg        = Color3.fromRGB(22, 22, 30),
    panel     = Color3.fromRGB(36, 36, 46),
    claimed   = Color3.fromRGB(70, 160, 80),
    locked    = Color3.fromRGB(60, 60, 72),
    text      = Color3.fromRGB(240, 240, 248),
}

local REWARDS = {
    { day = 1, icon = "\u{1F4B0}", name = "100 Coins",      value = 100  },
    { day = 2, icon = "\u{1F48E}", name = "5 Gems",          value = 5    },
    { day = 3, icon = "\u{1F4B0}", name = "250 Coins",      value = 250  },
    { day = 4, icon = "\u{1F9EA}", name = "3 Potions",      value = 3    },
    { day = 5, icon = "\u{1F48E}", name = "15 Gems",        value = 15   },
    { day = 6, icon = "\u{2B50}",  name = "XP Booster",     value = 1    },
    { day = 7, icon = "\u{1F451}", name = "Legendary Crate",value = 1    },
}

local gui = Instance.new("ScreenGui")
gui.Name = "ForjeDailyRewards"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.Enabled = false
gui.Parent = playerGui

local dim = Instance.new("Frame")
dim.Size = UDim2.fromScale(1, 1)
dim.BackgroundColor3 = Color3.new(0, 0, 0)
dim.BackgroundTransparency = 0.5
dim.BorderSizePixel = 0
dim.Parent = gui

local window = Instance.new("Frame")
window.Size = UDim2.new(0, 760, 0, 340)
window.AnchorPoint = Vector2.new(0.5, 0.5)
window.Position = UDim2.fromScale(0.5, 0.5)
window.BackgroundColor3 = COLORS.bg
window.BorderSizePixel = 0
window.Parent = gui

local winCorner = Instance.new("UICorner")
winCorner.CornerRadius = UDim.new(0, 18)
winCorner.Parent = window

local winStroke = Instance.new("UIStroke")
winStroke.Thickness = 3
winStroke.Color = COLORS.accent
winStroke.Parent = window

local winGrad = Instance.new("UIGradient")
winGrad.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, COLORS.bg),
    ColorSequenceKeypoint.new(1, COLORS.secondary),
})
winGrad.Rotation = 135
winGrad.Parent = window

local header = Instance.new("Frame")
header.Size = UDim2.new(1, 0, 0, 56)
header.BackgroundColor3 = COLORS.primary
header.BorderSizePixel = 0
header.Parent = window

local headerCorner = Instance.new("UICorner")
headerCorner.CornerRadius = UDim.new(0, 18)
headerCorner.Parent = header

local headerMask = Instance.new("Frame")
headerMask.Size = UDim2.new(1, 0, 0, 18)
headerMask.Position = UDim2.new(0, 0, 1, -18)
headerMask.BackgroundColor3 = COLORS.primary
headerMask.BorderSizePixel = 0
headerMask.Parent = header

local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, -60, 1, 0)
title.Position = UDim2.new(0, 20, 0, 0)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "\u{1F381}  DAILY REWARDS"
title.TextColor3 = COLORS.highlight
title.TextXAlignment = Enum.TextXAlignment.Left
title.Parent = header

local closeBtn = Instance.new("TextButton")
closeBtn.Size = UDim2.new(0, 36, 0, 36)
closeBtn.Position = UDim2.new(1, -48, 0.5, -18)
closeBtn.BackgroundColor3 = Color3.fromRGB(200, 60, 60)
closeBtn.BorderSizePixel = 0
closeBtn.Font = Enum.Font.GothamBlack
closeBtn.Text = "X"
closeBtn.TextColor3 = Color3.new(1, 1, 1)
closeBtn.TextScaled = true
closeBtn.Parent = header

local closeCorner = Instance.new("UICorner")
closeCorner.CornerRadius = UDim.new(1, 0)
closeCorner.Parent = closeBtn

-- Grid of 7 day cards
local grid = Instance.new("Frame")
grid.Size = UDim2.new(1, -40, 1, -80)
grid.Position = UDim2.new(0, 20, 0, 70)
grid.BackgroundTransparency = 1
grid.Parent = window

local gridLayout = Instance.new("UIListLayout")
gridLayout.FillDirection = Enum.FillDirection.Horizontal
gridLayout.Padding = UDim.new(0, 8)
gridLayout.VerticalAlignment = Enum.VerticalAlignment.Center
gridLayout.SortOrder = Enum.SortOrder.LayoutOrder
gridLayout.Parent = grid

local cards = {}

for i, reward in ipairs(REWARDS) do
    local card = Instance.new("Frame")
    card.Name = "Day" .. reward.day
    card.Size = UDim2.new(0, 96, 0, 200)
    card.LayoutOrder = i
    card.BackgroundColor3 = COLORS.panel
    card.BorderSizePixel = 0
    card.Parent = grid

    local cc = Instance.new("UICorner")
    cc.CornerRadius = UDim.new(0, 12)
    cc.Parent = card

    local cs = Instance.new("UIStroke")
    cs.Thickness = 2
    cs.Color = COLORS.accent
    cs.Transparency = 0.5
    cs.Parent = card

    local dayLabel = Instance.new("TextLabel")
    dayLabel.Size = UDim2.new(1, 0, 0, 22)
    dayLabel.Position = UDim2.new(0, 0, 0, 8)
    dayLabel.BackgroundTransparency = 1
    dayLabel.Font = Enum.Font.GothamBold
    dayLabel.TextScaled = true
    dayLabel.Text = "DAY " .. reward.day
    dayLabel.TextColor3 = COLORS.highlight
    dayLabel.Parent = card

    local iconLabel = Instance.new("TextLabel")
    iconLabel.Size = UDim2.new(1, 0, 0, 70)
    iconLabel.Position = UDim2.new(0, 0, 0, 40)
    iconLabel.BackgroundTransparency = 1
    iconLabel.Font = Enum.Font.GothamBlack
    iconLabel.TextScaled = true
    iconLabel.Text = reward.icon
    iconLabel.Parent = card

    local nameLabel = Instance.new("TextLabel")
    nameLabel.Size = UDim2.new(1, -10, 0, 28)
    nameLabel.Position = UDim2.new(0, 5, 0, 112)
    nameLabel.BackgroundTransparency = 1
    nameLabel.Font = Enum.Font.Gotham
    nameLabel.TextScaled = true
    nameLabel.Text = reward.name
    nameLabel.TextColor3 = COLORS.text
    nameLabel.TextWrapped = true
    nameLabel.Parent = card

    local claimBtn = Instance.new("TextButton")
    claimBtn.Name = "Claim"
    claimBtn.Size = UDim2.new(1, -12, 0, 34)
    claimBtn.Position = UDim2.new(0, 6, 1, -42)
    claimBtn.BackgroundColor3 = COLORS.accent
    claimBtn.BorderSizePixel = 0
    claimBtn.Font = Enum.Font.GothamBold
    claimBtn.Text = "CLAIM"
    claimBtn.TextColor3 = COLORS.bg
    claimBtn.TextScaled = true
    claimBtn.AutoButtonColor = false
    claimBtn.Parent = card

    local bc = Instance.new("UICorner")
    bc.CornerRadius = UDim.new(0, 8)
    bc.Parent = claimBtn

    cards[reward.day] = { card = card, button = claimBtn }

    claimBtn.MouseButton1Click:Connect(function()
        local ev = ReplicatedStorage:FindFirstChild("ClaimDaily")
        if ev and ev:IsA("RemoteEvent") then
            ev:FireServer(reward.day)
        end
    end)
end

-- Paint the state of each day: locked / available / claimed
local function setState(day, state)
    local entry = cards[day]
    if not entry then return end
    local card = entry.card
    local btn = entry.button
    if state == "claimed" then
        card.BackgroundColor3 = COLORS.claimed
        btn.Text = "CLAIMED"
        btn.BackgroundColor3 = COLORS.claimed
        btn.AutoButtonColor = false
        btn.Active = false
    elseif state == "locked" then
        card.BackgroundColor3 = COLORS.locked
        btn.Text = "LOCKED"
        btn.BackgroundColor3 = COLORS.locked
        btn.TextColor3 = COLORS.text
        btn.Active = false
    else
        card.BackgroundColor3 = COLORS.panel
        btn.Text = "CLAIM"
        btn.BackgroundColor3 = COLORS.accent
        btn.TextColor3 = COLORS.bg
        btn.Active = true
    end
end

closeBtn.MouseButton1Click:Connect(function() gui.Enabled = false end)

-- External control
local toggle = Instance.new("BindableEvent")
toggle.Name = "ToggleDaily"
toggle.Parent = gui
toggle.Event:Connect(function(state) gui.Enabled = state end)

local updateEvt = Instance.new("BindableEvent")
updateEvt.Name = "UpdateStates"
updateEvt.Parent = gui
updateEvt.Event:Connect(function(states)
    for day, state in pairs(states) do setState(day, state) end
end)

-- Demo default: day 1 claimed, day 2 available, rest locked
setState(1, "claimed")
setState(2, "available")
for d = 3, 7 do setState(d, "locked") end

print("[ForjeDailyRewards] ready")
`
}
