/**
 * Dialogue Template — NPC dialogue box with portrait, name, text, choices.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function dialogueTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Dialogue UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- LocalScript in StarterPlayerScripts.
-- Fire ReplicatedStorage.ShowDialogue with:
--   { speaker = "Elder", text = "Hello!", choices = { "Hi", "Goodbye" } }

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    bg        = Color3.fromRGB(20, 20, 26),
    text      = Color3.fromRGB(245, 245, 250),
    muted     = Color3.fromRGB(160, 160, 175),
}

local gui = Instance.new("ScreenGui")
gui.Name = "ForjeDialogue"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.Enabled = false
gui.Parent = playerGui

local box = Instance.new("Frame")
box.Size = UDim2.new(0.8, 0, 0, 200)
box.AnchorPoint = Vector2.new(0.5, 1)
box.Position = UDim2.new(0.5, 0, 1, -40)
box.BackgroundColor3 = COLORS.bg
box.BorderSizePixel = 0
box.Parent = gui

local boxCorner = Instance.new("UICorner")
boxCorner.CornerRadius = UDim.new(0, 16)
boxCorner.Parent = box

local boxStroke = Instance.new("UIStroke")
boxStroke.Thickness = 3
boxStroke.Color = COLORS.accent
boxStroke.Parent = box

local boxGrad = Instance.new("UIGradient")
boxGrad.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, COLORS.bg),
    ColorSequenceKeypoint.new(1, COLORS.secondary),
})
boxGrad.Rotation = 90
boxGrad.Parent = box

-- Portrait (left)
local portrait = Instance.new("Frame")
portrait.Size = UDim2.new(0, 140, 0, 140)
portrait.Position = UDim2.new(0, 20, 0, 30)
portrait.BackgroundColor3 = COLORS.primary
portrait.BorderSizePixel = 0
portrait.Parent = box

local portraitCorner = Instance.new("UICorner")
portraitCorner.CornerRadius = UDim.new(0, 12)
portraitCorner.Parent = portrait

local portraitStroke = Instance.new("UIStroke")
portraitStroke.Thickness = 3
portraitStroke.Color = COLORS.highlight
portraitStroke.Parent = portrait

local portraitFace = Instance.new("TextLabel")
portraitFace.Size = UDim2.fromScale(1, 1)
portraitFace.BackgroundTransparency = 1
portraitFace.Font = Enum.Font.GothamBlack
portraitFace.TextScaled = true
portraitFace.Text = "\u{1F9D9}"
portraitFace.TextColor3 = COLORS.highlight
portraitFace.Parent = portrait

-- Speaker name plate
local namePlate = Instance.new("Frame")
namePlate.Size = UDim2.new(0, 160, 0, 28)
namePlate.Position = UDim2.new(0, 180, 0, 10)
namePlate.BackgroundColor3 = COLORS.accent
namePlate.BorderSizePixel = 0
namePlate.Parent = box

local nameCorner = Instance.new("UICorner")
nameCorner.CornerRadius = UDim.new(0, 6)
nameCorner.Parent = namePlate

local nameLabel = Instance.new("TextLabel")
nameLabel.Name = "Speaker"
nameLabel.Size = UDim2.new(1, -12, 1, 0)
nameLabel.Position = UDim2.new(0, 6, 0, 0)
nameLabel.BackgroundTransparency = 1
nameLabel.Font = Enum.Font.GothamBold
nameLabel.TextScaled = true
nameLabel.Text = "NPC"
nameLabel.TextColor3 = COLORS.bg
nameLabel.TextXAlignment = Enum.TextXAlignment.Left
nameLabel.Parent = namePlate

-- Dialogue text
local textLabel = Instance.new("TextLabel")
textLabel.Name = "Body"
textLabel.Size = UDim2.new(1, -200, 0, 80)
textLabel.Position = UDim2.new(0, 180, 0, 46)
textLabel.BackgroundTransparency = 1
textLabel.Font = Enum.Font.Gotham
textLabel.TextSize = 20
textLabel.TextWrapped = true
textLabel.TextColor3 = COLORS.text
textLabel.TextXAlignment = Enum.TextXAlignment.Left
textLabel.TextYAlignment = Enum.TextYAlignment.Top
textLabel.Text = ""
textLabel.Parent = box

-- Choice bar
local choices = Instance.new("Frame")
choices.Name = "Choices"
choices.Size = UDim2.new(1, -200, 0, 40)
choices.Position = UDim2.new(0, 180, 1, -56)
choices.BackgroundTransparency = 1
choices.Parent = box

local choiceLayout = Instance.new("UIListLayout")
choiceLayout.FillDirection = Enum.FillDirection.Horizontal
choiceLayout.Padding = UDim.new(0, 10)
choiceLayout.Parent = choices

-- Prompt event
local showEvent = ReplicatedStorage:FindFirstChild("ShowDialogue")
if not showEvent then
    showEvent = Instance.new("RemoteEvent")
    showEvent.Name = "ShowDialogue"
    showEvent.Parent = ReplicatedStorage
end

local function clearChoices()
    for _, c in ipairs(choices:GetChildren()) do
        if c:IsA("TextButton") then c:Destroy() end
    end
end

local function typeOut(text)
    textLabel.Text = ""
    for i = 1, #text do
        textLabel.Text = string.sub(text, 1, i)
        task.wait(0.02)
    end
end

local function makeChoiceBtn(label, order, onClick)
    local btn = Instance.new("TextButton")
    btn.Size = UDim2.new(0, 160, 1, 0)
    btn.LayoutOrder = order
    btn.BackgroundColor3 = COLORS.secondary
    btn.BorderSizePixel = 0
    btn.Font = Enum.Font.GothamBold
    btn.Text = label
    btn.TextColor3 = COLORS.highlight
    btn.TextScaled = true
    btn.Parent = choices

    local c = Instance.new("UICorner")
    c.CornerRadius = UDim.new(0, 8)
    c.Parent = btn

    local s = Instance.new("UIStroke")
    s.Thickness = 2
    s.Color = COLORS.accent
    s.Parent = btn

    btn.MouseButton1Click:Connect(onClick)
    return btn
end

showEvent.OnClientEvent:Connect(function(payload)
    payload = payload or {}
    gui.Enabled = true
    nameLabel.Text = payload.speaker or "NPC"
    portraitFace.Text = payload.face or "\u{1F9D9}"
    clearChoices()
    task.spawn(function() typeOut(payload.text or "...") end)
    local list = payload.choices or { "Continue" }
    for i, c in ipairs(list) do
        makeChoiceBtn(c, i, function()
            showEvent:FireServer({ choice = i, label = c })
            gui.Enabled = false
        end)
    end
end)

print("[ForjeDialogue] ready")
`
}
