/**
 * Leaderboard Template — tabbed leaderboard (daily/weekly/all-time).
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function leaderboardTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Leaderboard UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- LocalScript in StarterPlayerScripts.

local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    bg        = Color3.fromRGB(22, 22, 28),
    row       = Color3.fromRGB(34, 34, 42),
    rowAlt    = Color3.fromRGB(28, 28, 36),
    text      = Color3.fromRGB(240, 240, 245),
    muted     = Color3.fromRGB(150, 150, 165),
    gold      = Color3.fromRGB(255, 200, 80),
    silver    = Color3.fromRGB(200, 200, 215),
    bronze    = Color3.fromRGB(205, 130, 80),
}

local DEMO_DATA = {
    daily  = {
        { rank=1, name="FrostKnight_42",  score=12840 },
        { rank=2, name="VoidRunner",      score=11200 },
        { rank=3, name="LunaBlade",       score=9875  },
        { rank=4, name="TacoBandit",      score=8420  },
        { rank=5, name="StoneMason",      score=7910  },
        { rank=6, name="PixelPirate",     score=6250  },
        { rank=7, name="NinjaCat",        score=5800  },
        { rank=8, name="DragonLord",      score=5120  },
    },
    weekly = {
        { rank=1, name="EmeraldHawk",     score=84210 },
        { rank=2, name="FrostKnight_42",  score=78240 },
        { rank=3, name="ShadowWisp",      score=66100 },
        { rank=4, name="IronHeart",       score=58920 },
        { rank=5, name="MagicMushroom",   score=52000 },
    },
    alltime = {
        { rank=1, name="GodOfObbys",      score=1242400 },
        { rank=2, name="TycoonTitan",     score=982100  },
        { rank=3, name="SpeedDemon",      score=804200  },
        { rank=4, name="EmeraldHawk",     score=712540  },
        { rank=5, name="FrostKnight_42",  score=698320  },
    },
}

local currentTab = "daily"

local gui = Instance.new("ScreenGui")
gui.Name = "ForjeLeaderboard"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.Enabled = false
gui.Parent = playerGui

local dim = Instance.new("Frame")
dim.Size = UDim2.fromScale(1, 1)
dim.BackgroundColor3 = Color3.new(0, 0, 0)
dim.BackgroundTransparency = 0.55
dim.BorderSizePixel = 0
dim.Parent = gui

local window = Instance.new("Frame")
window.Size = UDim2.new(0, 560, 0, 580)
window.AnchorPoint = Vector2.new(0.5, 0.5)
window.Position = UDim2.fromScale(0.5, 0.5)
window.BackgroundColor3 = COLORS.bg
window.BorderSizePixel = 0
window.Parent = gui

local winCorner = Instance.new("UICorner")
winCorner.CornerRadius = UDim.new(0, 18)
winCorner.Parent = window

local winStroke = Instance.new("UIStroke")
winStroke.Thickness = 3
winStroke.Color = COLORS.accent
winStroke.Parent = window

local header = Instance.new("Frame")
header.Size = UDim2.new(1, 0, 0, 72)
header.BackgroundColor3 = COLORS.primary
header.BorderSizePixel = 0
header.Parent = window

local headerCorner = Instance.new("UICorner")
headerCorner.CornerRadius = UDim.new(0, 18)
headerCorner.Parent = header

local headerMask = Instance.new("Frame")
headerMask.Size = UDim2.new(1, 0, 0, 18)
headerMask.Position = UDim2.new(0, 0, 1, -18)
headerMask.BackgroundColor3 = COLORS.primary
headerMask.BorderSizePixel = 0
headerMask.Parent = header

local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, -60, 0, 34)
title.Position = UDim2.new(0, 20, 0, 6)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "\u{1F3C6}  LEADERBOARD"
title.TextColor3 = COLORS.highlight
title.TextXAlignment = Enum.TextXAlignment.Left
title.Parent = header

-- Tab bar
local tabs = Instance.new("Frame")
tabs.Size = UDim2.new(1, -40, 0, 28)
tabs.Position = UDim2.new(0, 20, 0, 40)
tabs.BackgroundTransparency = 1
tabs.Parent = header

local tabLayout = Instance.new("UIListLayout")
tabLayout.FillDirection = Enum.FillDirection.Horizontal
tabLayout.Padding = UDim.new(0, 6)
tabLayout.Parent = tabs

local tabButtons = {}

local function makeTab(id, label)
    local btn = Instance.new("TextButton")
    btn.Size = UDim2.new(0, 110, 1, 0)
    btn.BackgroundColor3 = COLORS.secondary
    btn.BorderSizePixel = 0
    btn.Font = Enum.Font.GothamBold
    btn.Text = label
    btn.TextColor3 = COLORS.text
    btn.TextScaled = true
    btn.AutoButtonColor = false
    btn.Parent = tabs

    local c = Instance.new("UICorner")
    c.CornerRadius = UDim.new(0, 6)
    c.Parent = btn

    tabButtons[id] = btn
    return btn
end

local closeBtn = Instance.new("TextButton")
closeBtn.Size = UDim2.new(0, 32, 0, 32)
closeBtn.Position = UDim2.new(1, -44, 0, 8)
closeBtn.BackgroundColor3 = Color3.fromRGB(200, 60, 60)
closeBtn.BorderSizePixel = 0
closeBtn.Font = Enum.Font.GothamBlack
closeBtn.Text = "X"
closeBtn.TextColor3 = Color3.new(1, 1, 1)
closeBtn.TextScaled = true
closeBtn.Parent = header

local closeCorner = Instance.new("UICorner")
closeCorner.CornerRadius = UDim.new(1, 0)
closeCorner.Parent = closeBtn

-- Content scroll
local scroll = Instance.new("ScrollingFrame")
scroll.Size = UDim2.new(1, -32, 1, -96)
scroll.Position = UDim2.new(0, 16, 0, 84)
scroll.BackgroundTransparency = 1
scroll.BorderSizePixel = 0
scroll.ScrollBarThickness = 6
scroll.ScrollBarImageColor3 = COLORS.accent
scroll.CanvasSize = UDim2.new(0, 0, 0, 0)
scroll.AutomaticCanvasSize = Enum.AutomaticSize.Y
scroll.Parent = window

local rowLayout = Instance.new("UIListLayout")
rowLayout.Padding = UDim.new(0, 4)
rowLayout.Parent = scroll

local function renderRows(list)
    for _, child in ipairs(scroll:GetChildren()) do
        if child:IsA("Frame") then child:Destroy() end
    end
    for i, entry in ipairs(list) do
        local row = Instance.new("Frame")
        row.Size = UDim2.new(1, 0, 0, 42)
        row.BackgroundColor3 = (i % 2 == 0) and COLORS.rowAlt or COLORS.row
        row.BorderSizePixel = 0
        row.LayoutOrder = i
        row.Parent = scroll

        local rc = Instance.new("UICorner")
        rc.CornerRadius = UDim.new(0, 8)
        rc.Parent = row

        local rankLabel = Instance.new("TextLabel")
        rankLabel.Size = UDim2.new(0, 60, 1, 0)
        rankLabel.BackgroundTransparency = 1
        rankLabel.Font = Enum.Font.GothamBlack
        rankLabel.TextScaled = true
        rankLabel.Text = "#" .. entry.rank
        rankLabel.TextColor3 = entry.rank == 1 and COLORS.gold
            or entry.rank == 2 and COLORS.silver
            or entry.rank == 3 and COLORS.bronze
            or COLORS.muted
        rankLabel.Parent = row

        local nameLabel = Instance.new("TextLabel")
        nameLabel.Size = UDim2.new(1, -200, 1, 0)
        nameLabel.Position = UDim2.new(0, 68, 0, 0)
        nameLabel.BackgroundTransparency = 1
        nameLabel.Font = Enum.Font.GothamBold
        nameLabel.TextScaled = true
        nameLabel.Text = entry.name
        nameLabel.TextColor3 = COLORS.text
        nameLabel.TextXAlignment = Enum.TextXAlignment.Left
        nameLabel.Parent = row

        local scoreLabel = Instance.new("TextLabel")
        scoreLabel.Size = UDim2.new(0, 120, 1, 0)
        scoreLabel.Position = UDim2.new(1, -128, 0, 0)
        scoreLabel.BackgroundTransparency = 1
        scoreLabel.Font = Enum.Font.GothamBold
        scoreLabel.TextScaled = true
        scoreLabel.Text = tostring(entry.score)
        scoreLabel.TextColor3 = COLORS.highlight
        scoreLabel.TextXAlignment = Enum.TextXAlignment.Right
        scoreLabel.Parent = row
    end
end

local function switchTab(id)
    currentTab = id
    for tid, btn in pairs(tabButtons) do
        btn.BackgroundColor3 = (tid == id) and COLORS.accent or COLORS.secondary
        btn.TextColor3 = (tid == id) and COLORS.bg or COLORS.text
    end
    renderRows(DEMO_DATA[id])
end

local dailyBtn = makeTab("daily", "Daily")
local weeklyBtn = makeTab("weekly", "Weekly")
local allBtn = makeTab("alltime", "All-Time")

dailyBtn.MouseButton1Click:Connect(function() switchTab("daily") end)
weeklyBtn.MouseButton1Click:Connect(function() switchTab("weekly") end)
allBtn.MouseButton1Click:Connect(function() switchTab("alltime") end)

switchTab("daily")

closeBtn.MouseButton1Click:Connect(function() gui.Enabled = false end)

local toggle = Instance.new("BindableEvent")
toggle.Name = "ToggleLeaderboard"
toggle.Parent = gui
toggle.Event:Connect(function(state) gui.Enabled = state end)

print("[ForjeLeaderboard] ready")
`
}
