/**
 * Loading Screen Template — fullscreen loader with progress bar + tip rotator.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function loadingScreenTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Loading Screen UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- LocalScript in ReplicatedFirst (must be under ReplicatedFirst to show
-- before the game fully loads). Replace the print loop with actual load work.

local Players = game:GetService("Players")
local ReplicatedFirst = game:GetService("ReplicatedFirst")
local TweenService = game:GetService("TweenService")

ReplicatedFirst:RemoveDefaultLoadingScreen()

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    bg        = Color3.fromRGB(12, 12, 18),
    text      = Color3.fromRGB(240, 240, 250),
    muted     = Color3.fromRGB(160, 160, 180),
}

local TIPS = {
    "Tip: Press B to open the shop.",
    "Tip: Complete daily rewards for bonus coins.",
    "Tip: Hold shift to sprint.",
    "Tip: Drag items in the inventory to reorder.",
    "Tip: You can pause the game with P or Escape.",
    "Tip: Join our Discord for events and giveaways.",
    "Tip: Defeating bosses drops rare loot.",
    "Tip: Your progress auto-saves every 60 seconds.",
}

local gui = Instance.new("ScreenGui")
gui.Name = "ForjeLoadingScreen"
gui.IgnoreGuiInset = true
gui.DisplayOrder = 200
gui.Parent = playerGui

local backdrop = Instance.new("Frame")
backdrop.Size = UDim2.fromScale(1, 1)
backdrop.BackgroundColor3 = COLORS.bg
backdrop.BorderSizePixel = 0
backdrop.Parent = gui

local bgGradient = Instance.new("UIGradient")
bgGradient.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, COLORS.bg),
    ColorSequenceKeypoint.new(0.5, COLORS.primary),
    ColorSequenceKeypoint.new(1, COLORS.secondary),
})
bgGradient.Rotation = 120
bgGradient.Parent = backdrop

-- Centered logo / title
local title = Instance.new("TextLabel")
title.Size = UDim2.new(0.7, 0, 0, 120)
title.Position = UDim2.new(0.5, 0, 0.35, 0)
title.AnchorPoint = Vector2.new(0.5, 0.5)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "LOADING..."
title.TextColor3 = COLORS.highlight
title.TextStrokeTransparency = 0.3
title.TextStrokeColor3 = COLORS.secondary
title.Parent = gui

local subtitle = Instance.new("TextLabel")
subtitle.Size = UDim2.new(0.5, 0, 0, 30)
subtitle.Position = UDim2.new(0.5, 0, 0.47, 0)
subtitle.AnchorPoint = Vector2.new(0.5, 0.5)
subtitle.BackgroundTransparency = 1
subtitle.Font = Enum.Font.Gotham
subtitle.TextScaled = true
subtitle.Text = "Preparing adventure..."
subtitle.TextColor3 = COLORS.muted
subtitle.Parent = gui

-- Progress bar
local barBg = Instance.new("Frame")
barBg.Size = UDim2.new(0.5, 0, 0, 18)
barBg.Position = UDim2.new(0.5, 0, 0.58, 0)
barBg.AnchorPoint = Vector2.new(0.5, 0.5)
barBg.BackgroundColor3 = Color3.fromRGB(40, 40, 50)
barBg.BorderSizePixel = 0
barBg.Parent = gui

local barCorner = Instance.new("UICorner")
barCorner.CornerRadius = UDim.new(1, 0)
barCorner.Parent = barBg

local barStroke = Instance.new("UIStroke")
barStroke.Thickness = 2
barStroke.Color = COLORS.accent
barStroke.Parent = barBg

local barFill = Instance.new("Frame")
barFill.Size = UDim2.new(0, 0, 1, 0)
barFill.BackgroundColor3 = COLORS.accent
barFill.BorderSizePixel = 0
barFill.Parent = barBg

local fillCorner = Instance.new("UICorner")
fillCorner.CornerRadius = UDim.new(1, 0)
fillCorner.Parent = barFill

local fillGradient = Instance.new("UIGradient")
fillGradient.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, COLORS.accent),
    ColorSequenceKeypoint.new(1, COLORS.highlight),
})
fillGradient.Parent = barFill

local pctLabel = Instance.new("TextLabel")
pctLabel.Size = UDim2.new(1, 0, 1, 0)
pctLabel.BackgroundTransparency = 1
pctLabel.Font = Enum.Font.GothamBold
pctLabel.TextScaled = true
pctLabel.Text = "0%"
pctLabel.TextColor3 = COLORS.highlight
pctLabel.TextStrokeTransparency = 0.3
pctLabel.Parent = barBg

-- Tip rotator
local tip = Instance.new("TextLabel")
tip.Size = UDim2.new(0.7, 0, 0, 30)
tip.Position = UDim2.new(0.5, 0, 0.72, 0)
tip.AnchorPoint = Vector2.new(0.5, 0.5)
tip.BackgroundTransparency = 1
tip.Font = Enum.Font.GothamMedium
tip.TextScaled = true
tip.Text = TIPS[1]
tip.TextColor3 = COLORS.accent
tip.Parent = gui

task.spawn(function()
    local i = 1
    while gui.Parent do
        task.wait(4)
        i = i + 1
        if not tip.Parent then break end
        TweenService:Create(tip, TweenInfo.new(0.25), { TextTransparency = 1 }):Play()
        task.wait(0.25)
        tip.Text = TIPS[((i - 1) % #TIPS) + 1]
        TweenService:Create(tip, TweenInfo.new(0.25), { TextTransparency = 0 }):Play()
    end
end)

-- Progress driver — waits for game.Loaded or custom signal
local function setProgress(pct)
    pct = math.clamp(pct, 0, 1)
    TweenService:Create(barFill, TweenInfo.new(0.3), {
        Size = UDim2.new(pct, 0, 1, 0),
    }):Play()
    pctLabel.Text = string.format("%d%%", math.floor(pct * 100))
end

task.spawn(function()
    for i = 1, 10 do
        setProgress(i / 10)
        task.wait(0.15)
    end
    if not game:IsLoaded() then game.Loaded:Wait() end
    setProgress(1)
    task.wait(0.6)
    TweenService:Create(backdrop, TweenInfo.new(0.6), { BackgroundTransparency = 1 }):Play()
    for _, v in ipairs(gui:GetDescendants()) do
        if v:IsA("TextLabel") then
            TweenService:Create(v, TweenInfo.new(0.6), { TextTransparency = 1 }):Play()
        end
    end
    task.wait(0.8)
    gui:Destroy()
end)

print("[ForjeLoadingScreen] active")
`
}
