/**
 * Main Menu Template — Play / Settings / Credits / Quit.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function mainMenuTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Main Menu UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- Place as LocalScript under StarterPlayerScripts.
-- When the player joins, the menu is shown. Clicking "Play" hides it.

local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    text      = Color3.fromRGB(240, 240, 245),
    muted     = Color3.fromRGB(160, 160, 175),
}

local gui = Instance.new("ScreenGui")
gui.Name = "ForjeMainMenu"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.DisplayOrder = 50
gui.Parent = playerGui

-- Fullscreen background with gradient
local backdrop = Instance.new("Frame")
backdrop.Size = UDim2.fromScale(1, 1)
backdrop.BackgroundColor3 = COLORS.primary
backdrop.BorderSizePixel = 0
backdrop.Parent = gui

local bgGradient = Instance.new("UIGradient")
bgGradient.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, COLORS.primary),
    ColorSequenceKeypoint.new(1, COLORS.secondary),
})
bgGradient.Rotation = 135
bgGradient.Parent = backdrop

-- Decorative glow orbs
for i = 1, 6 do
    local orb = Instance.new("Frame")
    orb.Size = UDim2.new(0, 240, 0, 240)
    orb.Position = UDim2.fromScale(math.random(), math.random())
    orb.BackgroundColor3 = COLORS.accent
    orb.BackgroundTransparency = 0.85
    orb.BorderSizePixel = 0
    orb.ZIndex = 2
    orb.Parent = backdrop

    local oc = Instance.new("UICorner")
    oc.CornerRadius = UDim.new(1, 0)
    oc.Parent = orb
end

-- Game title
local title = Instance.new("TextLabel")
title.Size = UDim2.new(0.8, 0, 0, 120)
title.Position = UDim2.new(0.5, 0, 0.18, 0)
title.AnchorPoint = Vector2.new(0.5, 0)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "MY AWESOME GAME"
title.TextColor3 = COLORS.highlight
title.TextStrokeTransparency = 0.2
title.TextStrokeColor3 = COLORS.secondary
title.ZIndex = 5
title.Parent = gui

local tagline = Instance.new("TextLabel")
tagline.Size = UDim2.new(0.6, 0, 0, 34)
tagline.Position = UDim2.new(0.5, 0, 0.34, 0)
tagline.AnchorPoint = Vector2.new(0.5, 0)
tagline.BackgroundTransparency = 1
tagline.Font = Enum.Font.Gotham
tagline.TextScaled = true
tagline.Text = "— A ForjeGames production —"
tagline.TextColor3 = COLORS.muted
tagline.ZIndex = 5
tagline.Parent = gui

-- Button panel
local panel = Instance.new("Frame")
panel.Size = UDim2.new(0, 320, 0, 320)
panel.AnchorPoint = Vector2.new(0.5, 0.5)
panel.Position = UDim2.new(0.5, 0, 0.62, 0)
panel.BackgroundTransparency = 1
panel.ZIndex = 5
panel.Parent = gui

local panelLayout = Instance.new("UIListLayout")
panelLayout.Padding = UDim.new(0, 14)
panelLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
panelLayout.SortOrder = Enum.SortOrder.LayoutOrder
panelLayout.Parent = panel

local function menuButton(label, icon, order, onClick, isPrimary)
    local btn = Instance.new("TextButton")
    btn.Size = UDim2.new(1, 0, 0, 60)
    btn.LayoutOrder = order
    btn.BackgroundColor3 = isPrimary and COLORS.accent or COLORS.secondary
    btn.BorderSizePixel = 0
    btn.Font = Enum.Font.GothamBold
    btn.Text = icon .. "  " .. label
    btn.TextColor3 = isPrimary and COLORS.secondary or COLORS.text
    btn.TextScaled = true
    btn.AutoButtonColor = false
    btn.ZIndex = 6
    btn.Parent = panel

    local c = Instance.new("UICorner")
    c.CornerRadius = UDim.new(0, 12)
    c.Parent = btn

    local s = Instance.new("UIStroke")
    s.Thickness = 2
    s.Color = isPrimary and COLORS.highlight or COLORS.accent
    s.Transparency = 0.4
    s.Parent = btn

    local pad = Instance.new("UIPadding")
    pad.PaddingLeft = UDim.new(0, 24)
    pad.PaddingRight = UDim.new(0, 24)
    pad.Parent = btn

    btn.MouseEnter:Connect(function()
        TweenService:Create(btn, TweenInfo.new(0.15), {
            Size = UDim2.new(1, 12, 0, 64),
        }):Play()
    end)
    btn.MouseLeave:Connect(function()
        TweenService:Create(btn, TweenInfo.new(0.15), {
            Size = UDim2.new(1, 0, 0, 60),
        }):Play()
    end)
    btn.MouseButton1Click:Connect(onClick)

    return btn
end

menuButton("PLAY", "\u{25B6}", 1, function()
    TweenService:Create(gui:FindFirstChildOfClass("Frame"), TweenInfo.new(0.4), {
        BackgroundTransparency = 1,
    }):Play()
    TweenService:Create(title, TweenInfo.new(0.4), { TextTransparency = 1 }):Play()
    TweenService:Create(tagline, TweenInfo.new(0.4), { TextTransparency = 1 }):Play()
    task.delay(0.45, function() gui.Enabled = false end)
end, true)

menuButton("SETTINGS", "\u{2699}", 2, function()
    local settings = playerGui:FindFirstChild("ForjeSettings")
    if settings then settings.Enabled = true end
end, false)

menuButton("CREDITS", "\u{1F4DC}", 3, function()
    local credits = gui:FindFirstChild("CreditsOverlay")
    if credits then credits.Visible = not credits.Visible end
end, false)

menuButton("QUIT", "\u{274C}", 4, function()
    player:Kick("Thanks for playing!")
end, false)

-- Credits overlay
local creditsOverlay = Instance.new("Frame")
creditsOverlay.Name = "CreditsOverlay"
creditsOverlay.Size = UDim2.new(0, 420, 0, 260)
creditsOverlay.AnchorPoint = Vector2.new(0.5, 0.5)
creditsOverlay.Position = UDim2.fromScale(0.5, 0.5)
creditsOverlay.BackgroundColor3 = COLORS.secondary
creditsOverlay.BorderSizePixel = 0
creditsOverlay.Visible = false
creditsOverlay.ZIndex = 15
creditsOverlay.Parent = gui

local cc = Instance.new("UICorner")
cc.CornerRadius = UDim.new(0, 14)
cc.Parent = creditsOverlay

local cs = Instance.new("UIStroke")
cs.Thickness = 3
cs.Color = COLORS.accent
cs.Parent = creditsOverlay

local creditsText = Instance.new("TextLabel")
creditsText.Size = UDim2.new(1, -32, 1, -32)
creditsText.Position = UDim2.new(0, 16, 0, 16)
creditsText.BackgroundTransparency = 1
creditsText.Font = Enum.Font.Gotham
creditsText.TextScaled = false
creditsText.TextSize = 16
creditsText.TextWrapped = true
creditsText.Text = "MY AWESOME GAME\\n\\nDesign: You\\nProgramming: ForjeGames AI\\nArt: ForjeGames AI\\nMusic: ForjeGames AI\\n\\nBuilt with Forje — the AI game studio for Roblox.\\n\\nClick anywhere to close."
creditsText.TextColor3 = COLORS.highlight
creditsText.TextXAlignment = Enum.TextXAlignment.Center
creditsText.TextYAlignment = Enum.TextYAlignment.Center
creditsText.ZIndex = 16
creditsText.Parent = creditsOverlay

creditsOverlay.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        creditsOverlay.Visible = false
    end
end)

print("[ForjeMainMenu] shown for " .. player.Name)
`
}
