/**
 * Pause Menu Template — overlay with Resume / Settings / Exit.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function pauseMenuTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Pause Menu UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- LocalScript under StarterPlayerScripts. Press P or Esc to toggle.

local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    text      = Color3.fromRGB(245, 245, 250),
}

local gui = Instance.new("ScreenGui")
gui.Name = "ForjePauseMenu"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.Enabled = false
gui.DisplayOrder = 40
gui.Parent = playerGui

local blur = Instance.new("BlurEffect")
blur.Size = 0
blur.Parent = game.Lighting

local backdrop = Instance.new("Frame")
backdrop.Size = UDim2.fromScale(1, 1)
backdrop.BackgroundColor3 = Color3.new(0, 0, 0)
backdrop.BackgroundTransparency = 0.5
backdrop.BorderSizePixel = 0
backdrop.Parent = gui

local panel = Instance.new("Frame")
panel.Size = UDim2.new(0, 360, 0, 420)
panel.AnchorPoint = Vector2.new(0.5, 0.5)
panel.Position = UDim2.fromScale(0.5, 0.5)
panel.BackgroundColor3 = COLORS.primary
panel.BorderSizePixel = 0
panel.Parent = gui

local panelCorner = Instance.new("UICorner")
panelCorner.CornerRadius = UDim.new(0, 16)
panelCorner.Parent = panel

local panelStroke = Instance.new("UIStroke")
panelStroke.Thickness = 3
panelStroke.Color = COLORS.accent
panelStroke.Parent = panel

local grad = Instance.new("UIGradient")
grad.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, COLORS.primary),
    ColorSequenceKeypoint.new(1, COLORS.secondary),
})
grad.Rotation = 135
grad.Parent = panel

local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, -40, 0, 64)
title.Position = UDim2.new(0, 20, 0, 20)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "\u{23F8}  PAUSED"
title.TextColor3 = COLORS.highlight
title.Parent = panel

local list = Instance.new("Frame")
list.Size = UDim2.new(1, -40, 1, -120)
list.Position = UDim2.new(0, 20, 0, 100)
list.BackgroundTransparency = 1
list.Parent = panel

local listLayout = Instance.new("UIListLayout")
listLayout.Padding = UDim.new(0, 14)
listLayout.SortOrder = Enum.SortOrder.LayoutOrder
listLayout.Parent = list

local function menuBtn(label, order, onClick)
    local btn = Instance.new("TextButton")
    btn.Size = UDim2.new(1, 0, 0, 54)
    btn.LayoutOrder = order
    btn.BackgroundColor3 = COLORS.secondary
    btn.BorderSizePixel = 0
    btn.Font = Enum.Font.GothamBold
    btn.Text = label
    btn.TextColor3 = COLORS.text
    btn.TextScaled = true
    btn.AutoButtonColor = false
    btn.Parent = list

    local c = Instance.new("UICorner")
    c.CornerRadius = UDim.new(0, 10)
    c.Parent = btn

    local s = Instance.new("UIStroke")
    s.Thickness = 2
    s.Color = COLORS.accent
    s.Transparency = 0.5
    s.Parent = btn

    btn.MouseEnter:Connect(function()
        TweenService:Create(btn, TweenInfo.new(0.15), {
            BackgroundColor3 = COLORS.accent,
        }):Play()
    end)
    btn.MouseLeave:Connect(function()
        TweenService:Create(btn, TweenInfo.new(0.15), {
            BackgroundColor3 = COLORS.secondary,
        }):Play()
    end)
    btn.MouseButton1Click:Connect(onClick)
    return btn
end

local function setPaused(state)
    gui.Enabled = state
    TweenService:Create(blur, TweenInfo.new(0.25), {
        Size = state and 16 or 0,
    }):Play()
end

menuBtn("\u{25B6}  Resume",   1, function() setPaused(false) end)
menuBtn("\u{2699}  Settings", 2, function()
    local settings = playerGui:FindFirstChild("ForjeSettings")
    if settings then settings.Enabled = true end
end)
menuBtn("\u{1F3E0}  Main Menu", 3, function()
    local mm = playerGui:FindFirstChild("ForjeMainMenu")
    if mm then mm.Enabled = true end
    setPaused(false)
end)
menuBtn("\u{1F6AA}  Exit Game", 4, function()
    player:Kick("Thanks for playing!")
end)

UserInputService.InputBegan:Connect(function(input, gp)
    if gp then return end
    if input.KeyCode == Enum.KeyCode.P or input.KeyCode == Enum.KeyCode.Escape then
        setPaused(not gui.Enabled)
    end
end)

print("[ForjePauseMenu] ready")
`
}
