/**
 * Quest Tracker Template — pinned panel with checkboxes + objectives.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function questTrackerTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Quest Tracker UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- LocalScript in StarterPlayerScripts.

local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    bg        = Color3.fromRGB(20, 20, 26),
    text      = Color3.fromRGB(240, 240, 245),
    muted     = Color3.fromRGB(150, 150, 165),
    done      = Color3.fromRGB(100, 220, 120),
}

local gui = Instance.new("ScreenGui")
gui.Name = "ForjeQuestTracker"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.Parent = playerGui

local panel = Instance.new("Frame")
panel.Size = UDim2.new(0, 280, 0, 220)
panel.Position = UDim2.new(1, -300, 0, 120)
panel.BackgroundColor3 = COLORS.bg
panel.BackgroundTransparency = 0.15
panel.BorderSizePixel = 0
panel.Parent = gui

local panelCorner = Instance.new("UICorner")
panelCorner.CornerRadius = UDim.new(0, 12)
panelCorner.Parent = panel

local panelStroke = Instance.new("UIStroke")
panelStroke.Thickness = 2
panelStroke.Color = COLORS.accent
panelStroke.Transparency = 0.3
panelStroke.Parent = panel

local panelPad = Instance.new("UIPadding")
panelPad.PaddingTop = UDim.new(0, 10)
panelPad.PaddingBottom = UDim.new(0, 10)
panelPad.PaddingLeft = UDim.new(0, 12)
panelPad.PaddingRight = UDim.new(0, 12)
panelPad.Parent = panel

-- Header
local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, 0, 0, 24)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "\u{1F4DC}  ACTIVE QUEST"
title.TextColor3 = COLORS.highlight
title.TextXAlignment = Enum.TextXAlignment.Left
title.Parent = panel

local questName = Instance.new("TextLabel")
questName.Name = "QuestName"
questName.Size = UDim2.new(1, 0, 0, 22)
questName.Position = UDim2.new(0, 0, 0, 28)
questName.BackgroundTransparency = 1
questName.Font = Enum.Font.GothamBold
questName.TextScaled = true
questName.Text = "The Lost Relic"
questName.TextColor3 = COLORS.text
questName.TextXAlignment = Enum.TextXAlignment.Left
questName.Parent = panel

local divider = Instance.new("Frame")
divider.Size = UDim2.new(1, 0, 0, 2)
divider.Position = UDim2.new(0, 0, 0, 54)
divider.BackgroundColor3 = COLORS.accent
divider.BackgroundTransparency = 0.5
divider.BorderSizePixel = 0
divider.Parent = panel

local objectiveList = Instance.new("Frame")
objectiveList.Name = "Objectives"
objectiveList.Size = UDim2.new(1, 0, 1, -68)
objectiveList.Position = UDim2.new(0, 0, 0, 64)
objectiveList.BackgroundTransparency = 1
objectiveList.Parent = panel

local objLayout = Instance.new("UIListLayout")
objLayout.Padding = UDim.new(0, 6)
objLayout.SortOrder = Enum.SortOrder.LayoutOrder
objLayout.Parent = objectiveList

local function makeObjective(text, done, order)
    local row = Instance.new("Frame")
    row.Size = UDim2.new(1, 0, 0, 22)
    row.BackgroundTransparency = 1
    row.LayoutOrder = order
    row.Parent = objectiveList

    local checkbox = Instance.new("Frame")
    checkbox.Size = UDim2.new(0, 16, 0, 16)
    checkbox.Position = UDim2.new(0, 0, 0.5, -8)
    checkbox.BackgroundColor3 = done and COLORS.done or Color3.fromRGB(60, 60, 72)
    checkbox.BorderSizePixel = 0
    checkbox.Parent = row

    local cc = Instance.new("UICorner")
    cc.CornerRadius = UDim.new(0, 4)
    cc.Parent = checkbox

    local cs = Instance.new("UIStroke")
    cs.Thickness = 1.5
    cs.Color = done and COLORS.done or COLORS.muted
    cs.Parent = checkbox

    if done then
        local tick = Instance.new("TextLabel")
        tick.Size = UDim2.fromScale(1, 1)
        tick.BackgroundTransparency = 1
        tick.Font = Enum.Font.GothamBlack
        tick.TextScaled = true
        tick.Text = "\u{2714}"
        tick.TextColor3 = COLORS.bg
        tick.Parent = checkbox
    end

    local label = Instance.new("TextLabel")
    label.Size = UDim2.new(1, -24, 1, 0)
    label.Position = UDim2.new(0, 22, 0, 0)
    label.BackgroundTransparency = 1
    label.Font = Enum.Font.Gotham
    label.TextScaled = true
    label.Text = text
    label.TextColor3 = done and COLORS.muted or COLORS.text
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.Parent = row

    if done then
        label.Font = Enum.Font.GothamMedium
    end
end

-- Demo objectives
makeObjective("Speak to the Elder",      true,  1)
makeObjective("Find the Ancient Map",    true,  2)
makeObjective("Enter the Forgotten Cave", false, 3)
makeObjective("Retrieve the Relic",      false, 4)
makeObjective("Return to the Elder",     false, 5)

-- Public API: fired from a server Script with RemoteEvent
local updateEvent = Instance.new("BindableEvent")
updateEvent.Name = "UpdateQuest"
updateEvent.Parent = gui
updateEvent.Event:Connect(function(data)
    questName.Text = data.title or "Quest"
    for _, child in ipairs(objectiveList:GetChildren()) do
        if child:IsA("Frame") then child:Destroy() end
    end
    for i, obj in ipairs(data.objectives or {}) do
        makeObjective(obj.text, obj.done, i)
    end
end)

print("[ForjeQuestTracker] ready")
`
}
