/**
 * Settings Template — sliders for sound/music/quality.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function settingsTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Settings UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- Place as LocalScript under StarterPlayerScripts.

local Players = game:GetService("Players")
local SoundService = game:GetService("SoundService")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    bg        = Color3.fromRGB(22, 22, 28),
    panel     = Color3.fromRGB(36, 36, 44),
    text      = Color3.fromRGB(240, 240, 245),
    track     = Color3.fromRGB(60, 60, 72),
}

local gui = Instance.new("ScreenGui")
gui.Name = "ForjeSettings"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.Enabled = false
gui.Parent = playerGui

local dim = Instance.new("Frame")
dim.Size = UDim2.fromScale(1, 1)
dim.BackgroundColor3 = Color3.new(0, 0, 0)
dim.BackgroundTransparency = 0.5
dim.BorderSizePixel = 0
dim.Parent = gui

local window = Instance.new("Frame")
window.Size = UDim2.new(0, 520, 0, 520)
window.AnchorPoint = Vector2.new(0.5, 0.5)
window.Position = UDim2.fromScale(0.5, 0.5)
window.BackgroundColor3 = COLORS.bg
window.BorderSizePixel = 0
window.Parent = gui

local winCorner = Instance.new("UICorner")
winCorner.CornerRadius = UDim.new(0, 18)
winCorner.Parent = window

local winStroke = Instance.new("UIStroke")
winStroke.Thickness = 3
winStroke.Color = COLORS.accent
winStroke.Parent = window

local header = Instance.new("Frame")
header.Size = UDim2.new(1, 0, 0, 56)
header.BackgroundColor3 = COLORS.primary
header.BorderSizePixel = 0
header.Parent = window

local headerCorner = Instance.new("UICorner")
headerCorner.CornerRadius = UDim.new(0, 18)
headerCorner.Parent = header

local headerMask = Instance.new("Frame")
headerMask.Size = UDim2.new(1, 0, 0, 18)
headerMask.Position = UDim2.new(0, 0, 1, -18)
headerMask.BackgroundColor3 = COLORS.primary
headerMask.BorderSizePixel = 0
headerMask.Parent = header

local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, -80, 1, 0)
title.Position = UDim2.new(0, 20, 0, 0)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "\u{2699}  SETTINGS"
title.TextColor3 = COLORS.highlight
title.TextXAlignment = Enum.TextXAlignment.Left
title.Parent = header

local closeBtn = Instance.new("TextButton")
closeBtn.Size = UDim2.new(0, 36, 0, 36)
closeBtn.Position = UDim2.new(1, -48, 0.5, -18)
closeBtn.BackgroundColor3 = Color3.fromRGB(200, 60, 60)
closeBtn.Font = Enum.Font.GothamBlack
closeBtn.Text = "X"
closeBtn.TextColor3 = Color3.new(1, 1, 1)
closeBtn.TextScaled = true
closeBtn.BorderSizePixel = 0
closeBtn.Parent = header

local closeCorner = Instance.new("UICorner")
closeCorner.CornerRadius = UDim.new(1, 0)
closeCorner.Parent = closeBtn

-- Settings list
local list = Instance.new("Frame")
list.Size = UDim2.new(1, -40, 1, -80)
list.Position = UDim2.new(0, 20, 0, 68)
list.BackgroundTransparency = 1
list.Parent = window

local layout = Instance.new("UIListLayout")
layout.Padding = UDim.new(0, 16)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = list

-- Slider factory
local function makeSlider(labelText, initial, onChange, order)
    local row = Instance.new("Frame")
    row.Size = UDim2.new(1, 0, 0, 64)
    row.BackgroundColor3 = COLORS.panel
    row.BorderSizePixel = 0
    row.LayoutOrder = order
    row.Parent = list

    local rowCorner = Instance.new("UICorner")
    rowCorner.CornerRadius = UDim.new(0, 10)
    rowCorner.Parent = row

    local rowPad = Instance.new("UIPadding")
    rowPad.PaddingLeft = UDim.new(0, 16)
    rowPad.PaddingRight = UDim.new(0, 16)
    rowPad.PaddingTop = UDim.new(0, 8)
    rowPad.PaddingBottom = UDim.new(0, 8)
    rowPad.Parent = row

    local label = Instance.new("TextLabel")
    label.Size = UDim2.new(0.5, 0, 0, 20)
    label.BackgroundTransparency = 1
    label.Font = Enum.Font.GothamBold
    label.TextScaled = true
    label.Text = labelText
    label.TextColor3 = COLORS.text
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.Parent = row

    local value = Instance.new("TextLabel")
    value.Size = UDim2.new(0.5, 0, 0, 20)
    value.Position = UDim2.new(0.5, 0, 0, 0)
    value.BackgroundTransparency = 1
    value.Font = Enum.Font.GothamBold
    value.TextScaled = true
    value.Text = tostring(math.floor(initial * 100)) .. "%"
    value.TextColor3 = COLORS.highlight
    value.TextXAlignment = Enum.TextXAlignment.Right
    value.Parent = row

    local track = Instance.new("Frame")
    track.Size = UDim2.new(1, 0, 0, 12)
    track.Position = UDim2.new(0, 0, 0, 32)
    track.BackgroundColor3 = COLORS.track
    track.BorderSizePixel = 0
    track.Parent = row

    local trackCorner = Instance.new("UICorner")
    trackCorner.CornerRadius = UDim.new(1, 0)
    trackCorner.Parent = track

    local fill = Instance.new("Frame")
    fill.Size = UDim2.new(initial, 0, 1, 0)
    fill.BackgroundColor3 = COLORS.accent
    fill.BorderSizePixel = 0
    fill.Parent = track

    local fillCorner = Instance.new("UICorner")
    fillCorner.CornerRadius = UDim.new(1, 0)
    fillCorner.Parent = fill

    local knob = Instance.new("TextButton")
    knob.Size = UDim2.new(0, 20, 0, 20)
    knob.Position = UDim2.new(initial, -10, 0.5, -10)
    knob.AnchorPoint = Vector2.new(0, 0)
    knob.BackgroundColor3 = COLORS.highlight
    knob.BorderSizePixel = 0
    knob.Text = ""
    knob.AutoButtonColor = false
    knob.Parent = track

    local knobCorner = Instance.new("UICorner")
    knobCorner.CornerRadius = UDim.new(1, 0)
    knobCorner.Parent = knob

    local dragging = false
    knob.MouseButton1Down:Connect(function() dragging = true end)
    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = false
        end
    end)

    UserInputService.InputChanged:Connect(function(input)
        if not dragging then return end
        if input.UserInputType ~= Enum.UserInputType.MouseMovement
           and input.UserInputType ~= Enum.UserInputType.Touch then return end
        local rel = (input.Position.X - track.AbsolutePosition.X) / track.AbsoluteSize.X
        rel = math.clamp(rel, 0, 1)
        fill.Size = UDim2.new(rel, 0, 1, 0)
        knob.Position = UDim2.new(rel, -10, 0.5, -10)
        value.Text = tostring(math.floor(rel * 100)) .. "%"
        onChange(rel)
    end)
end

makeSlider("Master Volume",  SoundService.MasterVolume or 0.7, function(v) SoundService.MasterVolume = v end, 1)
makeSlider("Music Volume",   0.5, function(v) end, 2)
makeSlider("SFX Volume",     0.8, function(v) end, 3)
makeSlider("Graphics Quality", 0.6, function(v)
    local q = math.floor(v * 10)
    settings():GetService("UserGameSettings").SavedQualityLevel = Enum.SavedQualitySetting["QualityLevel" .. math.clamp(q, 1, 10)]
end, 4)

local function setOpen(state)
    gui.Enabled = state
    if state then
        window.Size = UDim2.new(0, 520, 0, 520)
    end
end

closeBtn.MouseButton1Click:Connect(function() setOpen(false) end)

UserInputService.InputBegan:Connect(function(input, gp)
    if gp then return end
    if input.KeyCode == Enum.KeyCode.Escape then setOpen(false) end
end)

print("[ForjeSettings] ready")
`
}
