/**
 * Shop Template — themed in-game shop with item grid, buy button, currency.
 * Returns Luau source for a LocalScript that builds the ScreenGui.
 */

import type { ThemePreset } from '@/lib/theme/theme-presets'

export function shopTemplate(theme: ThemePreset): string {
  const { primary, secondary, accent, highlight } = theme.colorPalette

  return `-- Shop UI (auto-generated by ForjeGames UI Kit)
-- Theme: ${theme.name}
-- Place as LocalScript under StarterPlayerScripts.

local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local COLORS = {
    primary   = Color3.fromHex("${primary}"),
    secondary = Color3.fromHex("${secondary}"),
    accent    = Color3.fromHex("${accent}"),
    highlight = Color3.fromHex("${highlight}"),
    bg        = Color3.fromRGB(22, 22, 28),
    panel     = Color3.fromRGB(32, 32, 40),
    text      = Color3.fromRGB(240, 240, 245),
    muted     = Color3.fromRGB(150, 150, 165),
    success   = Color3.fromRGB(90, 200, 110),
}

-- Example catalog — replace with a ModuleScript lookup for production.
local CATALOG = {
    { id = "sword_iron",   name = "Iron Sword",   price = 250,   icon = "\u{2694}",  rarity = "Common"    },
    { id = "shield_oak",   name = "Oak Shield",   price = 180,   icon = "\u{1F6E1}", rarity = "Common"    },
    { id = "potion_heal",  name = "Health Potion",price = 50,    icon = "\u{1F9EA}", rarity = "Common"    },
    { id = "bow_elven",    name = "Elven Bow",    price = 750,   icon = "\u{1F3F9}", rarity = "Rare"      },
    { id = "ring_mana",    name = "Mana Ring",    price = 1200,  icon = "\u{1F48D}", rarity = "Rare"      },
    { id = "armor_plate",  name = "Plate Armor",  price = 2500,  icon = "\u{1F97A}", rarity = "Epic"      },
    { id = "crown_king",   name = "King's Crown", price = 5000,  icon = "\u{1F451}", rarity = "Legendary" },
    { id = "pet_dragon",   name = "Baby Dragon",  price = 9999,  icon = "\u{1F409}", rarity = "Legendary" },
}

local RARITY_COLORS = {
    Common    = Color3.fromRGB(180, 180, 195),
    Rare      = Color3.fromRGB(90, 160, 255),
    Epic      = Color3.fromRGB(200, 110, 255),
    Legendary = Color3.fromRGB(255, 180, 60),
}

-- Root ScreenGui
local gui = Instance.new("ScreenGui")
gui.Name = "ForjeShop"
gui.ResetOnSpawn = false
gui.IgnoreGuiInset = true
gui.Enabled = false
gui.Parent = playerGui

-- Backdrop dim
local backdrop = Instance.new("Frame")
backdrop.Size = UDim2.fromScale(1, 1)
backdrop.BackgroundColor3 = Color3.new(0, 0, 0)
backdrop.BackgroundTransparency = 0.45
backdrop.BorderSizePixel = 0
backdrop.Parent = gui

-- Shop window
local window = Instance.new("Frame")
window.Name = "Window"
window.Size = UDim2.new(0, 720, 0, 520)
window.AnchorPoint = Vector2.new(0.5, 0.5)
window.Position = UDim2.fromScale(0.5, 0.5)
window.BackgroundColor3 = COLORS.bg
window.BorderSizePixel = 0
window.Parent = gui

local winCorner = Instance.new("UICorner")
winCorner.CornerRadius = UDim.new(0, 18)
winCorner.Parent = window

local winStroke = Instance.new("UIStroke")
winStroke.Thickness = 3
winStroke.Color = COLORS.accent
winStroke.Transparency = 0.2
winStroke.Parent = window

local winGradient = Instance.new("UIGradient")
winGradient.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, COLORS.bg),
    ColorSequenceKeypoint.new(1, COLORS.secondary),
})
winGradient.Rotation = 135
winGradient.Parent = window

-- Header bar
local header = Instance.new("Frame")
header.Name = "Header"
header.Size = UDim2.new(1, 0, 0, 64)
header.BackgroundColor3 = COLORS.primary
header.BorderSizePixel = 0
header.Parent = window

local headerCorner = Instance.new("UICorner")
headerCorner.CornerRadius = UDim.new(0, 18)
headerCorner.Parent = header

local headerMask = Instance.new("Frame")
headerMask.Size = UDim2.new(1, 0, 0, 18)
headerMask.Position = UDim2.new(0, 0, 1, -18)
headerMask.BackgroundColor3 = COLORS.primary
headerMask.BorderSizePixel = 0
headerMask.Parent = header

local title = Instance.new("TextLabel")
title.Name = "Title"
title.Size = UDim2.new(1, -120, 1, 0)
title.Position = UDim2.new(0, 20, 0, 0)
title.BackgroundTransparency = 1
title.Font = Enum.Font.GothamBlack
title.TextScaled = true
title.Text = "\u{1F3EA}  SHOP"
title.TextColor3 = COLORS.highlight
title.TextXAlignment = Enum.TextXAlignment.Left
title.Parent = header

local currencyFrame = Instance.new("Frame")
currencyFrame.Name = "Currency"
currencyFrame.Size = UDim2.new(0, 160, 0, 40)
currencyFrame.Position = UDim2.new(1, -220, 0.5, -20)
currencyFrame.BackgroundColor3 = COLORS.secondary
currencyFrame.BorderSizePixel = 0
currencyFrame.Parent = header

local currencyCorner = Instance.new("UICorner")
currencyCorner.CornerRadius = UDim.new(1, 0)
currencyCorner.Parent = currencyFrame

local currencyLabel = Instance.new("TextLabel")
currencyLabel.Size = UDim2.new(1, -16, 1, 0)
currencyLabel.Position = UDim2.new(0, 8, 0, 0)
currencyLabel.BackgroundTransparency = 1
currencyLabel.Font = Enum.Font.GothamBold
currencyLabel.TextScaled = true
currencyLabel.Text = "\u{1F4B0} 0"
currencyLabel.TextColor3 = COLORS.highlight
currencyLabel.Parent = currencyFrame

local closeBtn = Instance.new("TextButton")
closeBtn.Size = UDim2.new(0, 40, 0, 40)
closeBtn.Position = UDim2.new(1, -50, 0.5, -20)
closeBtn.BackgroundColor3 = Color3.fromRGB(200, 60, 60)
closeBtn.BorderSizePixel = 0
closeBtn.Font = Enum.Font.GothamBlack
closeBtn.Text = "X"
closeBtn.TextColor3 = Color3.new(1, 1, 1)
closeBtn.TextScaled = true
closeBtn.AutoButtonColor = true
closeBtn.Parent = header

local closeCorner = Instance.new("UICorner")
closeCorner.CornerRadius = UDim.new(1, 0)
closeCorner.Parent = closeBtn

-- Scrollable item grid
local scroll = Instance.new("ScrollingFrame")
scroll.Name = "Grid"
scroll.Size = UDim2.new(1, -32, 1, -96)
scroll.Position = UDim2.new(0, 16, 0, 80)
scroll.BackgroundTransparency = 1
scroll.BorderSizePixel = 0
scroll.ScrollBarThickness = 6
scroll.ScrollBarImageColor3 = COLORS.accent
scroll.CanvasSize = UDim2.new(0, 0, 0, 0)
scroll.AutomaticCanvasSize = Enum.AutomaticSize.Y
scroll.Parent = window

local gridLayout = Instance.new("UIGridLayout")
gridLayout.CellSize = UDim2.new(0, 156, 0, 200)
gridLayout.CellPadding = UDim2.new(0, 12, 0, 12)
gridLayout.SortOrder = Enum.SortOrder.LayoutOrder
gridLayout.Parent = scroll

local gridPad = Instance.new("UIPadding")
gridPad.PaddingTop = UDim.new(0, 8)
gridPad.PaddingBottom = UDim.new(0, 8)
gridPad.PaddingLeft = UDim.new(0, 8)
gridPad.PaddingRight = UDim.new(0, 8)
gridPad.Parent = scroll

-- Build cards
local function makeCard(item, index)
    local card = Instance.new("Frame")
    card.Name = item.id
    card.LayoutOrder = index
    card.BackgroundColor3 = COLORS.panel
    card.BorderSizePixel = 0

    local c = Instance.new("UICorner")
    c.CornerRadius = UDim.new(0, 12)
    c.Parent = card

    local s = Instance.new("UIStroke")
    s.Thickness = 2
    s.Color = RARITY_COLORS[item.rarity] or COLORS.muted
    s.Parent = card

    local icon = Instance.new("TextLabel")
    icon.Size = UDim2.new(1, 0, 0, 80)
    icon.Position = UDim2.new(0, 0, 0, 12)
    icon.BackgroundTransparency = 1
    icon.Font = Enum.Font.GothamBlack
    icon.TextScaled = true
    icon.Text = item.icon
    icon.TextColor3 = COLORS.highlight
    icon.Parent = card

    local name = Instance.new("TextLabel")
    name.Size = UDim2.new(1, -16, 0, 20)
    name.Position = UDim2.new(0, 8, 0, 96)
    name.BackgroundTransparency = 1
    name.Font = Enum.Font.GothamBold
    name.TextScaled = true
    name.Text = item.name
    name.TextColor3 = COLORS.text
    name.Parent = card

    local rarity = Instance.new("TextLabel")
    rarity.Size = UDim2.new(1, -16, 0, 16)
    rarity.Position = UDim2.new(0, 8, 0, 120)
    rarity.BackgroundTransparency = 1
    rarity.Font = Enum.Font.Gotham
    rarity.TextScaled = true
    rarity.Text = item.rarity
    rarity.TextColor3 = RARITY_COLORS[item.rarity] or COLORS.muted
    rarity.Parent = card

    local buyBtn = Instance.new("TextButton")
    buyBtn.Size = UDim2.new(1, -16, 0, 36)
    buyBtn.Position = UDim2.new(0, 8, 1, -44)
    buyBtn.BackgroundColor3 = COLORS.accent
    buyBtn.BorderSizePixel = 0
    buyBtn.Font = Enum.Font.GothamBold
    buyBtn.Text = "Buy " .. tostring(item.price)
    buyBtn.TextColor3 = COLORS.bg
    buyBtn.TextScaled = true
    buyBtn.Parent = card

    local btnCorner = Instance.new("UICorner")
    btnCorner.CornerRadius = UDim.new(0, 8)
    btnCorner.Parent = buyBtn

    buyBtn.MouseButton1Click:Connect(function()
        local evt = game.ReplicatedStorage:FindFirstChild("ShopPurchase")
        if evt and evt:IsA("RemoteEvent") then
            evt:FireServer(item.id)
        end
        TweenService:Create(buyBtn, TweenInfo.new(0.15), {
            BackgroundColor3 = COLORS.success,
        }):Play()
        task.delay(0.25, function()
            buyBtn.BackgroundColor3 = COLORS.accent
        end)
    end)

    card.Parent = scroll
    return card
end

for i, item in ipairs(CATALOG) do
    makeCard(item, i)
end

-- Open / close behavior
local function setOpen(open)
    gui.Enabled = open
    local goal = open and UDim2.fromScale(0.5, 0.5) or UDim2.fromScale(0.5, 0.7)
    window.Position = open and UDim2.fromScale(0.5, 0.7) or UDim2.fromScale(0.5, 0.5)
    TweenService:Create(window, TweenInfo.new(0.25, Enum.EasingStyle.Back), {
        Position = goal,
    }):Play()
end

closeBtn.MouseButton1Click:Connect(function() setOpen(false) end)

UserInputService.InputBegan:Connect(function(input, gp)
    if gp then return end
    if input.KeyCode == Enum.KeyCode.B then
        setOpen(not gui.Enabled)
    end
end)

-- External toggle (server can fire this via a RemoteEvent clone)
local toggle = Instance.new("BindableEvent")
toggle.Name = "ToggleShop"
toggle.Parent = gui
toggle.Event:Connect(function(state) setOpen(state) end)

-- Update currency
local setCurrency = Instance.new("BindableEvent")
setCurrency.Name = "SetCurrency"
setCurrency.Parent = gui
setCurrency.Event:Connect(function(n)
    currencyLabel.Text = string.format("\u{1F4B0} %d", n)
end)

print("[ForjeShop] loaded " .. #CATALOG .. " items")
`
}
