/**
 * script-templates.ts
 *
 * Luau code generation templates per script kind.
 *
 * Each template is a system-prompt prefix that tells the LLM:
 *   - what Roblox APIs it MUST prefer (task.wait, WaitForChild, DataStoreService)
 *   - what patterns are FORBIDDEN (loadstring, require(id), wait(), HttpService in client)
 *   - what the expected file layout looks like (ServerScriptService, ReplicatedStorage)
 *   - security best practices (server-authoritative state, validate remotes)
 *
 * These prefixes are concatenated with the user's script prompt by the chat
 * route / build executor before the final `callAI` call.
 */

export type ScriptKind =
  | 'server'
  | 'localscript'
  | 'module'
  | 'remote-event'
  | 'datastore'
  | 'leaderboard'
  | 'gamepass-handler'
  | 'humanoid-combat'
  | 'tween-animation'
  | 'proximity-prompt'
  | 'generic'

const SECURITY_PREAMBLE = `Security rules (HARD):
- NEVER use loadstring, require(assetId), or HttpService in client code.
- NEVER trust the client: all coin/XP/inventory mutations happen on the SERVER.
- Always validate RemoteEvent/RemoteFunction arguments: typeof, tostring, math.clamp.
- Wrap DataStore calls in pcall and retry up to 3 times with task.wait(2).
- Use task.wait instead of wait(). Use task.spawn instead of spawn().
- Use WaitForChild(name, 10) with a timeout, never the infinite form.
- Prefer Attribute and CollectionService tags over string-keyed state.
- Add a top-line watermark comment: -- Generated by Forje AI`

const STYLE_PREAMBLE = `Style rules:
- Use local for every variable; no globals.
- Use 4-space indentation.
- Use type annotations on function params where obvious: local function foo(n: number): boolean
- Use descriptive names; no single-letter vars except loop indices.
- Guard every service lookup: local Players = game:GetService("Players")
- Wrap the main logic in a function and call it at the end.`

export const SCRIPT_TEMPLATES: Record<ScriptKind, string> = {
  server: `You are writing a Roblox server Script for ServerScriptService.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

Expected structure:
  1. Services block (game:GetService) at the top.
  2. Constants block.
  3. Helper functions.
  4. Main logic (attached to events or run once).
  5. No top-level loops without task.wait inside.`,

  localscript: `You are writing a Roblox LocalScript for StarterPlayerScripts or StarterGui.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

Client-specific rules:
- Use game.Players.LocalPlayer, NEVER game.Players:GetPlayers() on the client.
- Use ReplicatedStorage.RemoteEvent:FireServer(...) for any state change.
- Use UserInputService, NOT the deprecated ContextActionService for simple inputs.
- Guard UI lookups: local gui = player:WaitForChild("PlayerGui"):WaitForChild("MyGui", 10)
- NEVER run DataStore or HttpService calls from a LocalScript.`,

  module: `You are writing a Roblox ModuleScript for ReplicatedStorage or ServerScriptService.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

ModuleScript rules:
- Return a table at the end: local M = {}; ... return M
- Expose functions as M.doSomething = function(...)
- Document each public function with a -- comment above it.
- NEVER use module-level side effects that run on require.
- Use type exports where possible: export type Config = { ... }`,

  'remote-event': `You are writing a RemoteEvent handler pair (client + server) for Roblox.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

RemoteEvent rules:
- Server script ALWAYS validates: typeof the args, clamp numbers, reject strings > 200 chars.
- Server script ALWAYS checks Player:IsA("Player") before processing.
- Use :Connect(function(player, arg1, arg2) — player is automatically first on server.
- Rate-limit per-player via a dictionary: lastFire[player] = os.clock().
- If validation fails, silently ignore (do not fire back an error — clients can exploit error paths).
- Return a 2-part code block: one for the server Script, one for the client LocalScript, each clearly labeled.`,

  datastore: `You are writing a DataStoreService save/load module for Roblox.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

DataStore rules:
- Always use pcall: local ok, err = pcall(function() return ds:GetAsync(key) end)
- Retry up to 3 times on failure with task.wait(2) between attempts.
- Use UpdateAsync instead of SetAsync where possible for optimistic concurrency.
- Save on PlayerRemoving AND BindToClose (for server shutdown).
- Key format: "Player_" .. player.UserId (never use Name — it can change).
- Schema is a Lua table; version it with a "version" field for future migrations.
- Wrap the save in a repeat task.wait() until success loop inside BindToClose.`,

  leaderboard: `You are writing a Roblox leaderstats script for ServerScriptService.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

Leaderstats rules:
- Listen to Players.PlayerAdded.
- Create a Folder named "leaderstats" inside the player.
- Each stat is an IntValue or NumberValue child of that folder.
- Load saved values via pcall(DataStoreService:GetDataStore("Name"):GetAsync).
- Save on PlayerRemoving AND BindToClose.
- NEVER let the client modify leaderstats directly.`,

  'gamepass-handler': `You are writing a GamePass / DevProduct purchase handler for Roblox.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

GamePass rules:
- Use MarketplaceService:UserOwnsGamePassAsync(player.UserId, gamepassId) — wrap in pcall.
- For DevProducts, set MarketplaceService.ProcessReceipt = function(info) ... return Enum.ProductPurchaseDecision.PurchaseGranted end.
- ALWAYS track "already processed" purchases in a DataStore to prevent double-credit on retries.
- Use ProductPurchaseDecision.NotProcessedYet if DataStore save fails.
- Grant the item BEFORE returning PurchaseGranted.`,

  'humanoid-combat': `You are writing a Roblox Humanoid combat script.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

Combat rules:
- Damage is calculated and applied on the SERVER only.
- Hit detection is via Region3 or :GetPartsInPart on the server.
- Use humanoid:TakeDamage(n) — NEVER direct Health subtraction (bypasses ForceField).
- Cooldowns are tracked per-player in a server-side dictionary with os.clock().
- Use RemoteEvent for client-initiated attacks; server does the authoritative hit check.
- Clamp damage: damage = math.clamp(damage, 0, 100).`,

  'tween-animation': `You are writing a TweenService animation script.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

Tween rules:
- Use TweenService:Create(instance, TweenInfo.new(duration, Easing, Direction, reps, reverses, delay), goal)
- Easing styles: Sine, Quad, Quart are smooth; Elastic, Bounce are "juicy".
- Always :Play() after creating.
- Use :GetPropertyChangedSignal for dependent animations, NOT polling.
- Clean up tweens on destruction: tween.Completed:Once(function() tween:Cancel() end)`,

  'proximity-prompt': `You are writing a ProximityPrompt handler.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

ProximityPrompt rules:
- Create on the server: local prompt = Instance.new("ProximityPrompt", part).
- Set ActionText, ObjectText, HoldDuration (0 for instant, 1+ for "hold to interact").
- Listen with prompt.Triggered:Connect(function(player) — runs on SERVER, trusted.
- Validate the player is alive and within range server-side even though prompt does it client-side.
- Set MaxActivationDistance to the actual gameplay distance (default 10 studs).`,

  generic: `You are writing Roblox Luau code.
${SECURITY_PREAMBLE}
${STYLE_PREAMBLE}

General rules:
- Choose the right script type (Script vs LocalScript vs ModuleScript) and EXPLAIN which at the top.
- Match the user's intent precisely. Do not pad with unnecessary features.
- Wrap any asset lookup in a guard clause.
- End with a clear code block tagged as \`\`\`lua.`,
}

export function resolveScriptTemplate(kind: string | undefined): string {
  if (!kind) return SCRIPT_TEMPLATES.generic
  const key = kind.toLowerCase().trim() as ScriptKind
  return SCRIPT_TEMPLATES[key] ?? SCRIPT_TEMPLATES.generic
}
